{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.5.jar",
          "url": "vectorx-data-redis-24.1.5.jar",
          "size": 9718,
          "sha512": "9f4f9902aadcd7a266501bb5775a546378dba9366b089d45e1b5cffa123844440ce9c1734e5eb28d040f80e32b0aecd19f71cf1af287454ddf36e504ddb9fad0",
          "sha256": "4ca989cebc1f2a6e3b6214905abccb05d0a7c9c564e9519a431158c6fc7f2f91",
          "sha1": "487e3aa6777d37f4608b767c99df17178ccb5a0b",
          "md5": "8c0b303c6faeffa73ae624eb238cd060"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.5.jar",
          "url": "vectorx-data-redis-24.1.5.jar",
          "size": 9718,
          "sha512": "9f4f9902aadcd7a266501bb5775a546378dba9366b089d45e1b5cffa123844440ce9c1734e5eb28d040f80e32b0aecd19f71cf1af287454ddf36e504ddb9fad0",
          "sha256": "4ca989cebc1f2a6e3b6214905abccb05d0a7c9c564e9519a431158c6fc7f2f91",
          "sha1": "487e3aa6777d37f4608b767c99df17178ccb5a0b",
          "md5": "8c0b303c6faeffa73ae624eb238cd060"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.5-javadoc.jar",
          "url": "vectorx-data-redis-24.1.5-javadoc.jar",
          "size": 93499,
          "sha512": "fc1c9a4c348ec7225cd8eee803336623923e3f9f81c9dbdc104d823b659a28de444e6053b99430c972c1a90e4b51d2a3f94b0ddb3448bd7696a7fe1af608f437",
          "sha256": "016cfcc9cc6c1999aa73c7cda81fcb765e4664a0eb38c797f790d71bb23ac492",
          "sha1": "9e5ae389b7a3439da073e423bd6a6b0acf4a6012",
          "md5": "8627b421d53e672c7327baffa31af8b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.5-sources.jar",
          "url": "vectorx-data-redis-24.1.5-sources.jar",
          "size": 3360,
          "sha512": "71e307cae75066177093453ee6503f4d27f5b125aafe85d69b0b5e08d8b5d01f9741356ea7a87bb69ffafdf729366135d63d124d4343ca5ff4f3cd48f0c423c4",
          "sha256": "2ea8f46c759ca4f4f938af2eb33891dd40bb4f6c35e2fa6b6f07bfc4a601d71a",
          "sha1": "077aa3380e66dae38a3f735e7252584dd9d5f474",
          "md5": "9473d82e813d4145669e953827ced7eb"
        }
      ]
    }
  ]
}
