{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.9.jar",
          "size": 23002,
          "sha512": "d5572011c6d4f76e3ad62f21ca587762a35f68d5e79c567a6aa5942228df3bdc5139547c91d9bab279f5a459ac2e9f8d576ee44c96702b264446dfcfc368b055",
          "sha256": "b9a6b17096b9acd730f5e20cbd8359160897cab6be86743a6cdef602f495e789",
          "sha1": "90829e24f9f17f9c5edac7d7f860429ba9fe8f22",
          "md5": "ce47922a79b1451efc6867e83f1f25e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.9.jar",
          "size": 23002,
          "sha512": "d5572011c6d4f76e3ad62f21ca587762a35f68d5e79c567a6aa5942228df3bdc5139547c91d9bab279f5a459ac2e9f8d576ee44c96702b264446dfcfc368b055",
          "sha256": "b9a6b17096b9acd730f5e20cbd8359160897cab6be86743a6cdef602f495e789",
          "sha1": "90829e24f9f17f9c5edac7d7f860429ba9fe8f22",
          "md5": "ce47922a79b1451efc6867e83f1f25e3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 128575,
          "sha512": "0729fcc70419bd3b2ccafd1195fa5050a10660e6303c72d236315d3739878deb5c2193e4d9b18cd2cab5cfeefa7122a7e4e3628da71bf2a3275dd457c0fbc4d2",
          "sha256": "4999d038249d668319a189c8c3de7379a74d92108bb4f3195308ba6d7864cad0",
          "sha1": "1c75595ab0cef84a6b1a10bb41cfc706f128c36c",
          "md5": "5ab80291fb62af2c9d4aad5e32a84e90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 11416,
          "sha512": "77d279f22bb4a99cea4d7868752e255fae028a0ae1f385bf77ab8dc1904b5480df6c6375208425b96ce323c2009f586f268e38020460b5d640303e3fbbfa31df",
          "sha256": "69b19515b4cbf8b80cde371d8760097b376f4a4779df94a7b0e290895982c3d8",
          "sha1": "3b487390b7adcf7951fff89f72c3fd30c024f20b",
          "md5": "6d6651fed256d6cd190fcc0cd4087c81"
        }
      ]
    }
  ]
}
