{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.5.jar",
          "url": "vectorx-autoconfigure-24.1.5.jar",
          "size": 181378,
          "sha512": "58e1b2eb5cdee1ff3e00e4f2e1e7aff56d8a392386c490e7f7ffda5b393bcb3af0c03590cfd48d791f6736d418d0642ff77856a404d696c159f52d3f8b3eab90",
          "sha256": "c7b0eb1b7301a6c5ebb008546cbf2780a3c072b5fee1149a2f4fe5fdbf18fb89",
          "sha1": "487927290384e635083cad8ee39c6b5edfd6c407",
          "md5": "9a295d7b795dc90931b940cfe1e330d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.5.jar",
          "url": "vectorx-autoconfigure-24.1.5.jar",
          "size": 181378,
          "sha512": "58e1b2eb5cdee1ff3e00e4f2e1e7aff56d8a392386c490e7f7ffda5b393bcb3af0c03590cfd48d791f6736d418d0642ff77856a404d696c159f52d3f8b3eab90",
          "sha256": "c7b0eb1b7301a6c5ebb008546cbf2780a3c072b5fee1149a2f4fe5fdbf18fb89",
          "sha1": "487927290384e635083cad8ee39c6b5edfd6c407",
          "md5": "9a295d7b795dc90931b940cfe1e330d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.5-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.5-javadoc.jar",
          "size": 273522,
          "sha512": "1d26e16f087a2526b65e815797f3782af13cbc7255c3517b1190044e21c8021556ae3f00c3b6f936fcb1fd2b4fc1c0bb3eaaa7694e0e1cbdeee6006c439a63fd",
          "sha256": "35476304ba312d5b5b266645a8aa24f796d925fd0890aa55345fb4ff632a1f51",
          "sha1": "70ab49193244e449a52974e3765ea5aa2aee962c",
          "md5": "0c2c0bbd10b8d6bb1014ab643108b367"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.5-sources.jar",
          "url": "vectorx-autoconfigure-24.1.5-sources.jar",
          "size": 68162,
          "sha512": "e4816d4290dcfa65401b627b4c2f4b1dfeffb53982edf30ad2c6e93ca2f94c7010550ddb62b363545a5e6d02e4d57147edb82afc63a5101ddf4ecbb124b13200",
          "sha256": "d4387ae74757b83657a92439699645b801ebdf66c4b2f2ddef7e54597a353d6e",
          "sha1": "217ed8c3099b1de88e13993f7ae8f112f6768203",
          "md5": "8da7cbe4645f92686e655049d52ab3cb"
        }
      ]
    }
  ]
}
