{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.1.jar",
          "url": "vectorx-data-jpa-24.1.1.jar",
          "size": 2690,
          "sha512": "1efcd5cc598b38e6df00a4ef3d48ab6e048ea25035402482dbf9958f30b8ef28ee9362dadf8380004e95ebc92cb58f03a8079f5911fe4e2961d8a0f4bf5c6c8b",
          "sha256": "45bbadf2c376bbfcce258990a5e154ca24e60b52638f759282794ddb8f5b7f87",
          "sha1": "dd63d30990e59aaca5e15825d325b428a624b64e",
          "md5": "3e4087927e5f723998fff98c2eea3784"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.1.jar",
          "url": "vectorx-data-jpa-24.1.1.jar",
          "size": 2690,
          "sha512": "1efcd5cc598b38e6df00a4ef3d48ab6e048ea25035402482dbf9958f30b8ef28ee9362dadf8380004e95ebc92cb58f03a8079f5911fe4e2961d8a0f4bf5c6c8b",
          "sha256": "45bbadf2c376bbfcce258990a5e154ca24e60b52638f759282794ddb8f5b7f87",
          "sha1": "dd63d30990e59aaca5e15825d325b428a624b64e",
          "md5": "3e4087927e5f723998fff98c2eea3784"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.1-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.1-javadoc.jar",
          "size": 70339,
          "sha512": "0500d1d4e20e9c187ecf6004440438a93439ad02877005fb31e00b2be56c99c8bc3f013bae1f5317fd7acffdd6fcb929351c7f8dda619e83668b7e38a69e8728",
          "sha256": "f5a804a8a9c45d091682ed4abcbf5477faf9363ea6dd4a880947778e6c3daaae",
          "sha1": "63b87410e6e272e45c7a2fdadae6a0de9a9805bc",
          "md5": "876acac7502efb452fb70284084a815b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.1-sources.jar",
          "url": "vectorx-data-jpa-24.1.1-sources.jar",
          "size": 1184,
          "sha512": "9c8cf32edc544f97612191bbf3bdc74109bb5aabd1180200f5bd3fa7a2ee39d69423d31478a458cf5891706229164a6bc046b9c9d58fa0380b35c54311f897b7",
          "sha256": "cf3d0ad2eefdfb31572d12bc596ef795e0ea1f3b10986914f9f3407e64201d56",
          "sha1": "2cec95aae7b2d8a1ffdbe9e272a36c290250212d",
          "md5": "cb09b4c2435686c85e34e866883f8352"
        }
      ]
    }
  ]
}
