{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-web-servlet-tobe-24.1.8-SNAPSHOT.2.jar",
          "size": 811849,
          "sha512": "eb1f22773f1f73d07ff3e20a60aa852fb5ad9a068acd5bddd040f3116d67c39be57e8923329947c613b753ce155968d5d436a1326193a4ed677e7805af67bb2b",
          "sha256": "882499ef7d66e4dfce23bdd0025b153ddf1cc2c9c22ae6974ac0cb280fb56330",
          "sha1": "21a06976d67f862f8d65f83a414b8fdea7ecc88e",
          "md5": "b808a1c6a420c1f88b7873cadd2ef3d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-web-servlet-tobe-24.1.8-SNAPSHOT.2.jar",
          "size": 811849,
          "sha512": "eb1f22773f1f73d07ff3e20a60aa852fb5ad9a068acd5bddd040f3116d67c39be57e8923329947c613b753ce155968d5d436a1326193a4ed677e7805af67bb2b",
          "sha256": "882499ef7d66e4dfce23bdd0025b153ddf1cc2c9c22ae6974ac0cb280fb56330",
          "sha1": "21a06976d67f862f8d65f83a414b8fdea7ecc88e",
          "md5": "b808a1c6a420c1f88b7873cadd2ef3d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 1068176,
          "sha512": "8b14dc554a3a69809bced3bbc936ffc50c74ee7ec16d6bc0bfcffb9e62b919a50af114a8768b73b72ab933e3c4d0eb5ffba5a4a0cb71cf27596293a7c84f03b0",
          "sha256": "87f2331a2ba1bef150cc0a5d0410e4841b35148a418d3804b8c9fe340474f6e3",
          "sha1": "970b0b50beefbdba9222c2ce9e7b92028df266c1",
          "md5": "c7431c60d589dc98cb2928432a10d3d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-web-servlet-tobe-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 413021,
          "sha512": "944e49f65e15cb01efef9c380fcff8f86b3c15e12c94be34b3e0164467111e25c0e8bccace4d2bc6fb855b13f080d999223dd80cacb080d00a3f1079c1220fc3",
          "sha256": "10092275071fdfd314e9a6fb98d49e642a44a32503accd1aa001f6c5a54f3cd0",
          "sha1": "f5bdf9e7c4524b5a198ce7281d8594a68a909368",
          "md5": "bba132a495c5262b59d37d64a4c44f71"
        }
      ]
    }
  ]
}
