{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security-jwt",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.devskiller.friendly-id",
          "module": "friendly-id-spring-boot",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.1.jar",
          "url": "vectorx-security-jwt-24.1.1.jar",
          "size": 87344,
          "sha512": "756091388d1e3bd75429671a3be4c48e8c17f3b89610b6ce00de9fd42884441e63af720319dd0525ab7c287e9d4f40911ea2a15d673696af3d7e9a4f35ebc52a",
          "sha256": "838053ac98c78bcba0c83fc6609a66ac5a89bdc112e55cba3361125d2122c5db",
          "sha1": "4b50d104d7879412d02bf026692b0a3a836cf186",
          "md5": "4cc3515b52e549974538bb51f10890e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.devskiller.friendly-id",
          "module": "friendly-id-spring-boot",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.1.jar",
          "url": "vectorx-security-jwt-24.1.1.jar",
          "size": 87344,
          "sha512": "756091388d1e3bd75429671a3be4c48e8c17f3b89610b6ce00de9fd42884441e63af720319dd0525ab7c287e9d4f40911ea2a15d673696af3d7e9a4f35ebc52a",
          "sha256": "838053ac98c78bcba0c83fc6609a66ac5a89bdc112e55cba3361125d2122c5db",
          "sha1": "4b50d104d7879412d02bf026692b0a3a836cf186",
          "md5": "4cc3515b52e549974538bb51f10890e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.1-javadoc.jar",
          "url": "vectorx-security-jwt-24.1.1-javadoc.jar",
          "size": 251658,
          "sha512": "b84f3d30333e68e5f2a882a36fa59ac2dc641c9f1e849532f79a7927609e9a8dc7e44bae9d273f400d4782df2d435dbcd0907273caf3a2318a32803e1db8bbdf",
          "sha256": "c4b53f3c892180ace113a0e08e8f0767c1022b2eb277776d5e8d821c58a15870",
          "sha1": "04aa2dcaaa31050bf5b91c5f3aed2f8a53592e98",
          "md5": "3d6121fa5e35b867812ca869ee98b3db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.1-sources.jar",
          "url": "vectorx-security-jwt-24.1.1-sources.jar",
          "size": 42985,
          "sha512": "2bba130efe3baea0d13ff072dec59e2089b7a8ad84805c541cc6bb6123198c88cd0f4ac6c1f64f8e7303620e6d4363300a873e14ee542c9d105dd81f85b50e28",
          "sha256": "df846eb240768ed9869b313fb9a7242f3f695cea42c8b86cd8af7a7ff300f569",
          "sha1": "b908f62250a4e5e3e1a6eab0a4ae4b3057c7d5b6",
          "md5": "b75dcce561da51d9646682b14cc629ee"
        }
      ]
    }
  ]
}
