{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.1.jar",
          "size": 2773,
          "sha512": "98404ef9e36de85068bb288b8fa3b251c610fcbdcd75f36bf7954ea4bd2fa5d4217d60f9f326377d24a92c423119e5f3ead9abf4949b26d5ac004e68930f38d1",
          "sha256": "7617ffd2893cacec00ee979435a083c544fb5fe6ab38ac34acbe2d64c4685d28",
          "sha1": "5cf29c81c078a7238aec3ee2f70533c3af48330b",
          "md5": "b012b021f6dd234d87ea237931a4c957"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.1.jar",
          "size": 2773,
          "sha512": "98404ef9e36de85068bb288b8fa3b251c610fcbdcd75f36bf7954ea4bd2fa5d4217d60f9f326377d24a92c423119e5f3ead9abf4949b26d5ac004e68930f38d1",
          "sha256": "7617ffd2893cacec00ee979435a083c544fb5fe6ab38ac34acbe2d64c4685d28",
          "sha1": "5cf29c81c078a7238aec3ee2f70533c3af48330b",
          "md5": "b012b021f6dd234d87ea237931a4c957"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 70459,
          "sha512": "36ec8811adcac141bffff205ccc93828a3ec2b2654378acabf7972b172e6ee64f81b1504674f5ea81a2f780478691331535ea51cfc88742ee6d20229a8c588a3",
          "sha256": "ab55274dafd140ba838cf49cd58545ef8c2c500ede088a685eb69a21ae392eab",
          "sha1": "e90e4316ff0957e9c2f66fa2e42b320718af33c2",
          "md5": "f36f2e7d00f55b723b2bad2fbd8d1544"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 1228,
          "sha512": "56ba59cc975b959ee47dd8abf0830ee2decd7f2f08e4ec9da2fcd6c4557604115534b7d617bf5c9903475682b55c3b63e70ed39452c340322cda4dbe4a299fd8",
          "sha256": "f6983a2fff8c1364a633187c9d2076699d3578384e7d0c0727504e0e0c085bca",
          "sha1": "a62bb0d1d19e7d27c02b509ae5eafe0693301cd4",
          "md5": "0377de89f5c382fc80b15b38c1b1c172"
        }
      ]
    }
  ]
}
