{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.4.jar",
          "url": "vectorx-cloud-core-24.1.4.jar",
          "size": 2695,
          "sha512": "b30933b7844976df88f071f13656e0cc826dfa5e488ba08b856ee678b1b7ae83f10dda4ff5c1cbac0721f1a43a8c5bc06174e66cb3224d265a0444d91fa83f27",
          "sha256": "cd0658a97b54c438d0042b137a722e93c2fc6d4fdb1e6c1881b85907e59e91c3",
          "sha1": "426cd7dd07f1afa415142080a9bfeecb347a50ee",
          "md5": "785b3e9cfee28f98770a922bb9bcd641"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.4.jar",
          "url": "vectorx-cloud-core-24.1.4.jar",
          "size": 2695,
          "sha512": "b30933b7844976df88f071f13656e0cc826dfa5e488ba08b856ee678b1b7ae83f10dda4ff5c1cbac0721f1a43a8c5bc06174e66cb3224d265a0444d91fa83f27",
          "sha256": "cd0658a97b54c438d0042b137a722e93c2fc6d4fdb1e6c1881b85907e59e91c3",
          "sha1": "426cd7dd07f1afa415142080a9bfeecb347a50ee",
          "md5": "785b3e9cfee28f98770a922bb9bcd641"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.4-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.4-javadoc.jar",
          "size": 70383,
          "sha512": "963d36d1409b612e693d22ab90a8822500bd3e75f7302bd589435dfbd00699553d294d4d5d322493ce9fd92ff3bf8826c6b2697a8bf5e47cc6c4382a839b732d",
          "sha256": "d8a5b47b249f9960daa643352f780401483ac3e56be7e624a666774beb82a080",
          "sha1": "120c13d957c982a1416ed6659ffa21d5cd331533",
          "md5": "fc27f37e8580ecf81693b7c317e730da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.4-sources.jar",
          "url": "vectorx-cloud-core-24.1.4-sources.jar",
          "size": 1186,
          "sha512": "fd8cf3f649facdc7021da0e99841f955bf54d0bdb0dea7478e86730afa4baba6a309752a818a59d8e3b184dec5db28b216e8880a86a9be7a6fab416e5b7be260",
          "sha256": "f7a3b1012c3445e92698ebf339787c84839486cdfcaff98711ea646047d2c416",
          "sha1": "73ff9250cb747e98989b62341e0985a3458fd6ab",
          "md5": "40a513a2897af921344210bbb975d236"
        }
      ]
    }
  ]
}
