{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.4.jar",
          "url": "vectorx-cloud-core-24.1.4.jar",
          "size": 2695,
          "sha512": "7ac79dde0894179d5879c5142626ff2d1680c4fb4de934741c43a746b7b145dc8499ed9f325661c213cb6828376897d7a586f1124ac423adc27cc6468e20abca",
          "sha256": "02eddbbe2c73b6d421fbfed272921a3f710719ef23d7524d8b3a7a27bea588a5",
          "sha1": "688c4fe90656ee766c48ac1bf7fbdc56acc2652d",
          "md5": "11bfaa7bb7d40478474e0f5c6918231e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.4.jar",
          "url": "vectorx-cloud-core-24.1.4.jar",
          "size": 2695,
          "sha512": "7ac79dde0894179d5879c5142626ff2d1680c4fb4de934741c43a746b7b145dc8499ed9f325661c213cb6828376897d7a586f1124ac423adc27cc6468e20abca",
          "sha256": "02eddbbe2c73b6d421fbfed272921a3f710719ef23d7524d8b3a7a27bea588a5",
          "sha1": "688c4fe90656ee766c48ac1bf7fbdc56acc2652d",
          "md5": "11bfaa7bb7d40478474e0f5c6918231e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.4-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.4-javadoc.jar",
          "size": 70383,
          "sha512": "3a85a508b846dd18333e1bb0bcb511b2149135641ddb1022bf246ae9a48e70f53df401669e5861410d80bd82a6882713a794c2b0440ede0e0f985f7d4265f150",
          "sha256": "00387b30e7d698b91d8bc097a8d79c2bfa285493150a646ae7ad3057c66bc918",
          "sha1": "cca64f345835d831110079f5b5e489e7b34364ac",
          "md5": "2ca85dd6fad7ff0039915595f5b5a247"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.4-sources.jar",
          "url": "vectorx-cloud-core-24.1.4-sources.jar",
          "size": 1186,
          "sha512": "270994c7f6719a6e6a97ac107355b1deb1541e4bb848ffacf7fa68ac3cafc3663487e569156394aeb6d63cf5635624dd952562e284136b9caab391300542acf7",
          "sha256": "a56f3ce197e85f78672342cd52a6ca80f32781d2bf140042705ce25597733bd0",
          "sha1": "bb2f47445844553868f6b19cb3ae97eb5fd73ee2",
          "md5": "a7bd090fad46171b652d33c9d26513b1"
        }
      ]
    }
  ]
}
