{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-view-bo",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-bo",
          "version": {
            "requires": "24.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-view-bo-24.1.6.jar",
          "url": "vectorx-starter-view-bo-24.1.6.jar",
          "size": 261,
          "sha512": "d98dc723889a07b79ec9d68eb7db388ffd527a531c6ad564de524616eca7baf1a20b832df6f93b9521a9cecd7faff38405d93845a3e5d4d93ad9259a1dd5df94",
          "sha256": "73ea3ccea30fcc3c31b005238ffcf7237525a14eea5c1cbfa22566b61863600b",
          "sha1": "c7a89f77bcff0fa2682159546cea78dbee46621a",
          "md5": "3ce3c51bd023cfc6e280eae712e2f0a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-bo",
          "version": {
            "requires": "24.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-view-bo-24.1.6.jar",
          "url": "vectorx-starter-view-bo-24.1.6.jar",
          "size": 261,
          "sha512": "d98dc723889a07b79ec9d68eb7db388ffd527a531c6ad564de524616eca7baf1a20b832df6f93b9521a9cecd7faff38405d93845a3e5d4d93ad9259a1dd5df94",
          "sha256": "73ea3ccea30fcc3c31b005238ffcf7237525a14eea5c1cbfa22566b61863600b",
          "sha1": "c7a89f77bcff0fa2682159546cea78dbee46621a",
          "md5": "3ce3c51bd023cfc6e280eae712e2f0a0"
        }
      ]
    }
  ]
}
