{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.4.jar",
          "url": "vectorx-management-core-24.1.4.jar",
          "size": 922235,
          "sha512": "2b3a6c84714ad7fb30e602cffe6c271cfdf34ef07fee0e4a5719236a94241ec79fdd7e9a2ccd8f60df1aafdde5dec2cd67e9879857278ab256385fdfaa868020",
          "sha256": "e736c9fc6bf1dfe2ba9afc2303d4d673449a89574a5f464b5cc3b82e118b43ba",
          "sha1": "3a9ffa1ff7c830546f034efe2d2253773f24bb90",
          "md5": "592eb66c192725fdb1775008fc36b3d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.4.jar",
          "url": "vectorx-management-core-24.1.4.jar",
          "size": 922235,
          "sha512": "2b3a6c84714ad7fb30e602cffe6c271cfdf34ef07fee0e4a5719236a94241ec79fdd7e9a2ccd8f60df1aafdde5dec2cd67e9879857278ab256385fdfaa868020",
          "sha256": "e736c9fc6bf1dfe2ba9afc2303d4d673449a89574a5f464b5cc3b82e118b43ba",
          "sha1": "3a9ffa1ff7c830546f034efe2d2253773f24bb90",
          "md5": "592eb66c192725fdb1775008fc36b3d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.4-javadoc.jar",
          "url": "vectorx-management-core-24.1.4-javadoc.jar",
          "size": 1332099,
          "sha512": "86a43d0b291a00673566a3a3c7be144acc2ece48688f084f68d55aaa0c4aed3ffe86e6390279a3f50fca3821c3c9dbf92b6d67932ba1b1c66217e8562f34f96f",
          "sha256": "2d4c60364c2f96efd61b720a8e3ec5c28486f692a3a04fe4cd6ae628a33a008b",
          "sha1": "28726bfb54df91eb2dca415dc8c04eaf666bf843",
          "md5": "6705662abbd98a1987e6a9f0e141ac0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.4-sources.jar",
          "url": "vectorx-management-core-24.1.4-sources.jar",
          "size": 328242,
          "sha512": "a968c8c6712769c2f15281ca24bd16cb72e624f9f94ca2278d1b1d78740ed9a61d142bbd1daa0b97d31422ba219f17758857057cbdc9927435fb2abda968597e",
          "sha256": "517b0b5bd3fa8c6fbcb5f209fbc737fc3d9b8eecfb8433e3b7aa9412e704b396",
          "sha1": "2a0d4aeeed7653a90c112a83d389c1aff7b0f174",
          "md5": "b03b2c0d237080c741b5551f5a5be31d"
        }
      ]
    }
  ]
}
