{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.4.jar",
          "size": 22655,
          "sha512": "30deda264205195605fcd771c22c04e1ea37969553f2ca5f5fa773ac687258bd615f493fddf73f02a8590b69f1396af25fb69b52fd085de8dc2b167ba41dfddd",
          "sha256": "07ed868a838ff6d371cfc75d6d18cfb8ce1fca3b5f493b915a04b89c7e0137b5",
          "sha1": "9250a555239155d23e8be7a492c6f7f5400d479c",
          "md5": "b86b0d2c81f414984231042eb7a4bdd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.4.jar",
          "size": 22655,
          "sha512": "30deda264205195605fcd771c22c04e1ea37969553f2ca5f5fa773ac687258bd615f493fddf73f02a8590b69f1396af25fb69b52fd085de8dc2b167ba41dfddd",
          "sha256": "07ed868a838ff6d371cfc75d6d18cfb8ce1fca3b5f493b915a04b89c7e0137b5",
          "sha1": "9250a555239155d23e8be7a492c6f7f5400d479c",
          "md5": "b86b0d2c81f414984231042eb7a4bdd1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 141571,
          "sha512": "52082ab43642a56459d44340c4c33d38202b49d0b2d34b47477c012d949deab90024ca22726f91a4ac0a42be777bf847052ac59b55c69dc332914da2c4b00440",
          "sha256": "fa18b7d2b3ecf2d700dea0658e78d04b39c8d822b8c8a57775e4423f4d496c9c",
          "sha1": "15f6072396d49b8aaba12f6b2cac897289666924",
          "md5": "4756c995f0666d4311ac0980a03b2556"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 12222,
          "sha512": "f8848e154017f95c3f0a95d0de6107a96db01ee848b52d4ff5221cdafa1deba828ce8883764ec4dcbf5024e6a3c386d7fc0eccf9859381714d05411222102e2c",
          "sha256": "ed4653ad3d8ebd2a2552be2c8e0e4e5069ffae5592a90a176d0d81569e67c2a4",
          "sha1": "ee65323ae3461ffc55e828995589fc7453b55cbe",
          "md5": "e03c1d6d8183cb15248edaf1f029df64"
        }
      ]
    }
  ]
}
