{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.5.jar",
          "size": 107373,
          "sha512": "cb981fe0edc7187e9e40a07d3f2a79a430706f0edef9c1c1ce7ef20b095215cfe6068b3bcc55caa80f6f3c6d06fbb05fc993f9c182f2df86e777e6a0b0a40538",
          "sha256": "d10e97f8ff122978e5f73cf85effd00f6af68436640cb8746c052c1efa1d57b0",
          "sha1": "ad681449bdd8c2523b300d38940630309f4cfd8f",
          "md5": "f5a8327f6c6b7beea2aefcd58c1a83d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.5.jar",
          "size": 107373,
          "sha512": "cb981fe0edc7187e9e40a07d3f2a79a430706f0edef9c1c1ce7ef20b095215cfe6068b3bcc55caa80f6f3c6d06fbb05fc993f9c182f2df86e777e6a0b0a40538",
          "sha256": "d10e97f8ff122978e5f73cf85effd00f6af68436640cb8746c052c1efa1d57b0",
          "sha1": "ad681449bdd8c2523b300d38940630309f4cfd8f",
          "md5": "f5a8327f6c6b7beea2aefcd58c1a83d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 416143,
          "sha512": "d364b404236d657ee0fed5576b019d7f21151a221726b1e169f002a171d5e85b9cab28440e6038b11a47afead9af2f09a8b6f4fbcfeea51916596c0fdb11f365",
          "sha256": "559becb4a71007ce1398f82221706247934c1bbaa61736d216b701335ff2e1b8",
          "sha1": "acfa4c0576fffca636b978bb20f9267448f3ae46",
          "md5": "63f470b201debc0aec8879e05d2e8230"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 65047,
          "sha512": "4cace66431c88f9130b81572a0738499a11c2720f2331a6db62bb0bc1ee76c39be2ae2cec2509dee2b2d8cf28349983de5544083c67247ff464dc03dc14b9f19",
          "sha256": "7f03c942a7e985b05a311e64816c18ae66faf1a96c79b096a1bf69a4869e41b8",
          "sha1": "83edfc6206a9f6bbb11857b5fa01e2e7f5ff631c",
          "md5": "adc68586adef564064969f40c1f2d0b2"
        }
      ]
    }
  ]
}
