{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-net-24.1.9-SNAPSHOT.13.jar",
          "size": 30289,
          "sha512": "06969940a1e393b5c98d6345a383470660e9f8e2c09623bb006ee6e5688787dd1d262eb9eef03b6a7c220156af046d1aa04d3a4c2739c149bb8bd909a86d2662",
          "sha256": "938d59fe7ae85f45902139d2c9abd568c9c8b1d5025e7ca8b0bdebfca540fec7",
          "sha1": "cb84a436827471a6fc52fd08f5cb39edd39db792",
          "md5": "d61fcbd49d34935628d45ca421a2eaf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-net-24.1.9-SNAPSHOT.13.jar",
          "size": 30289,
          "sha512": "06969940a1e393b5c98d6345a383470660e9f8e2c09623bb006ee6e5688787dd1d262eb9eef03b6a7c220156af046d1aa04d3a4c2739c149bb8bd909a86d2662",
          "sha256": "938d59fe7ae85f45902139d2c9abd568c9c8b1d5025e7ca8b0bdebfca540fec7",
          "sha1": "cb84a436827471a6fc52fd08f5cb39edd39db792",
          "md5": "d61fcbd49d34935628d45ca421a2eaf3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-net-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 154411,
          "sha512": "87696e39b971cfedfef3c471f75b3478d34e1f677fc5f779f9405ab3e3cd2f57cafbf38e57b919124215d2f82b7141e145c83e3a4fb545c91c9b59ee65e3b19f",
          "sha256": "f577618321e1a2d6fb1b886e5b690d11626bb43abd7425482ad6cc7498e72493",
          "sha1": "bf96d24eea8cbf0c33e6a36a1f778714cf2fa7de",
          "md5": "18381eabbf0459513a3338c7c3357c25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-net-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 10034,
          "sha512": "05d83aa430e26f99ecb7960921ef68a17e49341704221abdc021487401419a20e5f402859957d39bec2728705c1c29a386fa717f5b5c7856ea89c3ef37d8e0c7",
          "sha256": "44bb4b69cce42a7e87757bf8db69280a908c23c91fdfac40046477573b7fba37",
          "sha1": "991b10f1e12e80a863d4776d331a0f13244a5961",
          "md5": "f741777fec358cfe6e5f82e3867a6413"
        }
      ]
    }
  ]
}
