{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.2.jar",
          "url": "vectorx-data-mybatis-24.1.2.jar",
          "size": 106460,
          "sha512": "380e225c42792374eeb218008a6e45cdba1d908408e78fbd1cedb76308272c5ec77134990f0e448d0a48e4a09231ed95c104599a4612cf975fb3bee08fb09d02",
          "sha256": "66045ee8679fff88dae24611964854f4463c5834239b19256c633bc8924aaab1",
          "sha1": "4d866639a46b097eac7eb85ba81e5644d2a7a8fe",
          "md5": "cdc383a22ce3168c5d9754b79d9aaf87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.2.jar",
          "url": "vectorx-data-mybatis-24.1.2.jar",
          "size": 106460,
          "sha512": "380e225c42792374eeb218008a6e45cdba1d908408e78fbd1cedb76308272c5ec77134990f0e448d0a48e4a09231ed95c104599a4612cf975fb3bee08fb09d02",
          "sha256": "66045ee8679fff88dae24611964854f4463c5834239b19256c633bc8924aaab1",
          "sha1": "4d866639a46b097eac7eb85ba81e5644d2a7a8fe",
          "md5": "cdc383a22ce3168c5d9754b79d9aaf87"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.2-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.2-javadoc.jar",
          "size": 298609,
          "sha512": "cb40d1d88b63f29cb70ad5083160f340900e126eab9114327098a8463dc64e19909e63c210908fdb108fb430f9ed0158213859af35e1c82dcb5a0c53b6b0c083",
          "sha256": "bc0ccc43543a6e7f02402c4b757be17d1573c56d78c7fe03ca6f5199514ccf28",
          "sha1": "de36b62d7c03dd989fb84626d9440456cbc50a54",
          "md5": "576ecec40c8705246ae8ff37008f9499"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.2-sources.jar",
          "url": "vectorx-data-mybatis-24.1.2-sources.jar",
          "size": 68934,
          "sha512": "0731d798c5cac9aa11bf0081e1f8d00ddd761f101fdaa4a0e21baf7f782fc78319814b806005ecd7384d578dbb4f746b9c4d1d7382783fd855b41f35ce4dbf4a",
          "sha256": "a8ee1ef174954656eb49e165ad4553dabea0f368fed9c985a9e48c9f03095877",
          "sha1": "78ec4af93bc5681ca2dba4665ed729d764093972",
          "md5": "9b6f7c344c22598a753632a9732a25b4"
        }
      ]
    }
  ]
}
