{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.3.jar",
          "size": 148420,
          "sha512": "e7b499144f86fc5acb7152177f380ab2d70aff063db8f2a0a71b7b441902c6d58bd85d9d39b50af81a7050b59b0bdb2ba264cd1101d6c480fdd74be9f1a56e6d",
          "sha256": "500051b7258c536436596ab558d3c2e5dc8a57687f41e0cf4ab2e95c50ac2bc6",
          "sha1": "4375e70a0f2a848b7a90448c1a6290c1b8cbaeb5",
          "md5": "b832fdf97369056d45814724e9b1cbd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.3.jar",
          "size": 148420,
          "sha512": "e7b499144f86fc5acb7152177f380ab2d70aff063db8f2a0a71b7b441902c6d58bd85d9d39b50af81a7050b59b0bdb2ba264cd1101d6c480fdd74be9f1a56e6d",
          "sha256": "500051b7258c536436596ab558d3c2e5dc8a57687f41e0cf4ab2e95c50ac2bc6",
          "sha1": "4375e70a0f2a848b7a90448c1a6290c1b8cbaeb5",
          "md5": "b832fdf97369056d45814724e9b1cbd3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 316409,
          "sha512": "4495beb85c997d5ddc5d4162eee89b4fb3b9e36a5189473b5ea7257423dbb2249ed2a6edaf2421336c890cfe8a8ab40bd864cf76f24b8ceff53f18e03d56fe1c",
          "sha256": "6c2cf04908abc851a00371ee3251304d3dde926b5516e224240a3dd778e5e789",
          "sha1": "50822c17814ed683034a7d9d72adfe598921d696",
          "md5": "c08f605469f6a6709bb2c53060cf475d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 61389,
          "sha512": "8701375bf94fe9d89ac88e37cba73f9dafa24bcb92165cff67bd194f82a5aeae66d684afe5be1412702c567db2ff041434ca4d74a74a475d5ff9ccff8869005a",
          "sha256": "50a71741d441bceb5e12a5909f9787c476461dddc054bdda4e46c963af1a7207",
          "sha1": "b37bfac467a4a1882b4afcf0c10933612f09907e",
          "md5": "655a3472c6fc06a313ab4d3401110709"
        }
      ]
    }
  ]
}
