{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.9.jar",
          "size": 109230,
          "sha512": "012b0a361c98c86cc2d22446df69cdff320edc036e9f4bc4046fabe214f61979b2bd7296ba39950cd642a8f8741cbbd438d30196b399e0e4ed0b14d91bba3768",
          "sha256": "0021839ddd49fcc45155b980ee39b8ca9c2b03d0ae71991432b427c192a2b66a",
          "sha1": "c7d6fbf82b8521ea546d30652123751dda4a1cce",
          "md5": "677b5e22a29db0afa71d2f33eb52f6ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.9.jar",
          "size": 109230,
          "sha512": "012b0a361c98c86cc2d22446df69cdff320edc036e9f4bc4046fabe214f61979b2bd7296ba39950cd642a8f8741cbbd438d30196b399e0e4ed0b14d91bba3768",
          "sha256": "0021839ddd49fcc45155b980ee39b8ca9c2b03d0ae71991432b427c192a2b66a",
          "sha1": "c7d6fbf82b8521ea546d30652123751dda4a1cce",
          "md5": "677b5e22a29db0afa71d2f33eb52f6ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 417918,
          "sha512": "244089891b1a7e55bb5fe4de4da97c69c82f30222ea11fb00bd1c62d9c7cad393270288082d02a26eb93289dbbcac6281f8bd0445da4c8172bb2c8db9432b125",
          "sha256": "177a6f45196b6790a6240a38c6213b39d4ba6a517bf4539ab1af7a7b7bd32b8c",
          "sha1": "d0f0ec55b3f6213811f899aa766279a0281cec4a",
          "md5": "830aecb874e833c954d345417b95e7e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 66741,
          "sha512": "21353a6fa14e80ffd4514dcc1ecd38e1643534d36a8bfc1299c76a2d12d9c6c5c3b001d98a6cb69327efc62c788e57dfa88da5891695242a26e03c8a20196d4e",
          "sha256": "bdc501d947671ebb81de1b3edddba30001865b91e5c636e2ba542c7f5eff7511",
          "sha1": "93a87d9da37b5ea15f639c8419e71066a25563b5",
          "md5": "57520a7292fe5147d7f2729dcc0f719b"
        }
      ]
    }
  ]
}
