{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-test",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-test-24.1.8-SNAPSHOT.1.jar",
          "size": 31786,
          "sha512": "57b41a1c17b4fe1aad4e796f3ba98e30fb3cf9e6d30f84df1adfc1c0518ce83ec1b282c633bf4579991ebaa61594bd5995178e71fdaf4766536b74fbdeaa10e8",
          "sha256": "0ecdeca7149a8a48f6f1c3943704a45ad0ca8e5863c5c580e6ca54bf0064a762",
          "sha1": "43bdfb983e18de78fd74951f01db058bb9233f51",
          "md5": "608a83092283a3301006ea5715df8e4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-test-24.1.8-SNAPSHOT.1.jar",
          "size": 31786,
          "sha512": "57b41a1c17b4fe1aad4e796f3ba98e30fb3cf9e6d30f84df1adfc1c0518ce83ec1b282c633bf4579991ebaa61594bd5995178e71fdaf4766536b74fbdeaa10e8",
          "sha256": "0ecdeca7149a8a48f6f1c3943704a45ad0ca8e5863c5c580e6ca54bf0064a762",
          "sha1": "43bdfb983e18de78fd74951f01db058bb9233f51",
          "md5": "608a83092283a3301006ea5715df8e4f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-test-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 126182,
          "sha512": "1c854f2b0898589e669ec58db6a8fb7f1250f84b4f85852ebe6d34193f58274cd4c9f4cd72249cc7bf19831bafa57d120c5565a413f397166d82b4db97bcdd72",
          "sha256": "0604f411f5f74252750cdaed842ae4da04113ec94943dd155092d2df5d788d72",
          "sha1": "103bd46bc6341b785ee8bd20ca2ab56ecdf656d8",
          "md5": "538c9f802307dc29f35a8f01c54bc863"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-test-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 11947,
          "sha512": "f9487a87962510dcdee4dafc2fe5d325b6e80b93922e896c8df5f9886b9aba1c6261a1cfa2269272d7e0dbeae8ed273d314243c856af8234469f9640a332e334",
          "sha256": "9b2a62d066cde648db70414737e180b2569709b6cefc2c8113bb35fa883f48a6",
          "sha1": "fb37b8de55f418563281b89f073b1ff93016a346",
          "md5": "42912f39c233af06dd23ab07da173b95"
        }
      ]
    }
  ]
}
