{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.2.jar",
          "url": "vectorx-management-bo-24.1.2.jar",
          "size": 145412,
          "sha512": "df1e72f69c4910190d51ce1902f8bbd1ed34c625d1e5af82bfba2ea7422e0619c6b7916ca13933757fd783163c16b9753edc57c8bdab75d666e2f24887622d2a",
          "sha256": "d99e8a984c8c0bc9bdf430d2b01ef321c56d87a1d4c196069c54be83b5d991f1",
          "sha1": "91c3cd22b1696d85eed2fa2eb0279822dc388ba5",
          "md5": "3062af54cb028163ccf18641949b0b66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.2.jar",
          "url": "vectorx-management-bo-24.1.2.jar",
          "size": 145412,
          "sha512": "df1e72f69c4910190d51ce1902f8bbd1ed34c625d1e5af82bfba2ea7422e0619c6b7916ca13933757fd783163c16b9753edc57c8bdab75d666e2f24887622d2a",
          "sha256": "d99e8a984c8c0bc9bdf430d2b01ef321c56d87a1d4c196069c54be83b5d991f1",
          "sha1": "91c3cd22b1696d85eed2fa2eb0279822dc388ba5",
          "md5": "3062af54cb028163ccf18641949b0b66"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.2-javadoc.jar",
          "url": "vectorx-management-bo-24.1.2-javadoc.jar",
          "size": 305808,
          "sha512": "db0280978f06a2bfc7f88ec210d3179ee5ce61b3fd394e29f2aaf7765337acbeae4ff45a5f38c00b9b5b6e08ce728dc5c9c0bfe8c72888ba59d5ba209d8d7392",
          "sha256": "20c5dd3ec72cf6cdd1bef8ffa346b3a1b2c5c0ad5a567196a8365d21a72550c4",
          "sha1": "b3362ed810ef25eda40a48667d62e67d11c7c3d4",
          "md5": "f2cce636a9e72eaf1393bda969c9f7b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.2-sources.jar",
          "url": "vectorx-management-bo-24.1.2-sources.jar",
          "size": 59264,
          "sha512": "30d6b983fc18979d0254003430116e3aec41c7638fb2142aaf9cba90d2440fe628aa2f3ae6a138e5d530c7328cda89189862a98b4e4acd9c99a73eb849cc6c3e",
          "sha256": "e1053b437b09a77e530a7a715dad516abcc744b33c1b7d0bb0cdb034fca89639",
          "sha1": "dab7628090e6a2624f3ce290baa8c13e5de911b0",
          "md5": "4a83ce275ae66693d39ce107e504344e"
        }
      ]
    }
  ]
}
