{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-core",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.8.jar",
          "url": "vectorx-web-core-24.1.8.jar",
          "size": 9983,
          "sha512": "9ea6ef3b8112fab8e13ae972f644111d823580f361394acabeba0f6000057e6f4ed77723ed014ca5f1b69d6432489d4d5ee7eb424f03d2cd3420dc1e3fd3f8ee",
          "sha256": "b951ceda1b0629f8a5ee8945e0f6533392dbbae2a05cdea783c88687e761e840",
          "sha1": "3159f06e055fea2e294986104ca4abbea8ae81c8",
          "md5": "6ea7127b6ad81a06111287e4d2e3fa6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.8.jar",
          "url": "vectorx-web-core-24.1.8.jar",
          "size": 9983,
          "sha512": "9ea6ef3b8112fab8e13ae972f644111d823580f361394acabeba0f6000057e6f4ed77723ed014ca5f1b69d6432489d4d5ee7eb424f03d2cd3420dc1e3fd3f8ee",
          "sha256": "b951ceda1b0629f8a5ee8945e0f6533392dbbae2a05cdea783c88687e761e840",
          "sha1": "3159f06e055fea2e294986104ca4abbea8ae81c8",
          "md5": "6ea7127b6ad81a06111287e4d2e3fa6f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.8-javadoc.jar",
          "url": "vectorx-web-core-24.1.8-javadoc.jar",
          "size": 103618,
          "sha512": "82270e51a6c348817ff0b422c91531cc5c10e21b70f267852a093215e58f65a417705a6e7004f2037ed2c5c7c44d1cea108002a667bd4a79ebf37bb3a440c774",
          "sha256": "855ef1af174dfe48a2c2dbc88b166b850aecaf6f2d6f91f35385254b02645469",
          "sha1": "552d4b157827967f530b52d7e25b50c114d23ef0",
          "md5": "1550a9b13a266f4e7c61415e510df9dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.8-sources.jar",
          "url": "vectorx-web-core-24.1.8-sources.jar",
          "size": 5581,
          "sha512": "6c1894996d6eee5ad66636ac16595050cfec1a01aaa127e141e6a53e654a5e92e1b9df608ac32fa65476bf3a38b146d7d7566eeedf0baeec99331b3a0ed73fa1",
          "sha256": "76e2e518ccf7e5f97184ed970ceeb3729989fcddb3267da74856bb54ed2fa3f0",
          "sha1": "b7d90afefb17224c0962213fd5e39c99631cff63",
          "md5": "36059e419531624525c554d050f263b0"
        }
      ]
    }
  ]
}
