{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-eureka-server",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-server",
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-server-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-cloud-eureka-server-24.1.9-SNAPSHOT.9.jar",
          "size": 3042,
          "sha512": "52516dbb557c046b666823799adbfe93d7d364988d68b809d5a5d4ffbcbcb53b6fd68b88146341b1fda09b32781a9b074c1e9dbb6ad38b3023350ae07408d79c",
          "sha256": "f2312fbe5b32a59e3eb998dd7f6023b8847090004c74333dc006d43c2cfefdac",
          "sha1": "aa2c7842646662db8ff1655a24c29e1a19ac0fd7",
          "md5": "573f2ba8d4961a3881e84de3e604c94d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-server",
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-server-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-cloud-eureka-server-24.1.9-SNAPSHOT.9.jar",
          "size": 3042,
          "sha512": "52516dbb557c046b666823799adbfe93d7d364988d68b809d5a5d4ffbcbcb53b6fd68b88146341b1fda09b32781a9b074c1e9dbb6ad38b3023350ae07408d79c",
          "sha256": "f2312fbe5b32a59e3eb998dd7f6023b8847090004c74333dc006d43c2cfefdac",
          "sha1": "aa2c7842646662db8ff1655a24c29e1a19ac0fd7",
          "md5": "573f2ba8d4961a3881e84de3e604c94d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-server-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-cloud-eureka-server-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 70870,
          "sha512": "d30b4932162813191d7a142fa0343877e56d95e04c8bfe7d4c5c24460040669b1f0bf99e535b1f8751f6524d6a9a03563f416677305e5c33faa5bcbe4577b770",
          "sha256": "11c7a790bce82ff0986c1175aa1a9d872215d104be47c1a8a31b910a93adbb54",
          "sha1": "4056bbd118e71abccc1a74e5c257eee6df6076e1",
          "md5": "4908432ccb3489784141e4af0a54099a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-server-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-cloud-eureka-server-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 1454,
          "sha512": "051093ddb426f6d95b26f78f3b3d1a823ee7c27b5fe095889d6ad1c80c6eed99db3e5e775b63c9b1eb62d2692ef0e31134019a3889e4a4ac17d6f8b75fd70de1",
          "sha256": "d9eab7723c9d0b63e301746365178278476163dcd278e726255b8150e231efd4",
          "sha1": "182012892612e6a4e28e5eaac548d989372f7b4d",
          "md5": "f1eacaa60b41373972bdac16d92645e0"
        }
      ]
    }
  ]
}
