{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.2.jar",
          "url": "vectorx-batch-worker-24.1.2.jar",
          "size": 51881,
          "sha512": "49175940b0a493b6e7aacf00b44a72ccdae16746b5e9bc6ad1570259f94b48f419821fd89f2d431bcc4b1dac7c0b6b401b23d5e2653620b91173a42e18364c0a",
          "sha256": "ce138c2862d863ba946ee034465fd3920046ec6e980ef521c7641c0483123fcf",
          "sha1": "3fcd6247cda29ea9d34f65121880bee7c8cffe8f",
          "md5": "1ac0c66ee32aec13974614b00134ba6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.2.jar",
          "url": "vectorx-batch-worker-24.1.2.jar",
          "size": 51881,
          "sha512": "49175940b0a493b6e7aacf00b44a72ccdae16746b5e9bc6ad1570259f94b48f419821fd89f2d431bcc4b1dac7c0b6b401b23d5e2653620b91173a42e18364c0a",
          "sha256": "ce138c2862d863ba946ee034465fd3920046ec6e980ef521c7641c0483123fcf",
          "sha1": "3fcd6247cda29ea9d34f65121880bee7c8cffe8f",
          "md5": "1ac0c66ee32aec13974614b00134ba6e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.2-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.2-javadoc.jar",
          "size": 180004,
          "sha512": "bff466a45c39ccfd67907d8012ace0f40381ea693334050c5108574d727b2eff567abe66f73be6801fd28494362b3ab1419b2f3f15096097e1193f8feca08f84",
          "sha256": "e010c603c3719d78fa55224267d85e87e3e3f893167785c70c075dee52c82132",
          "sha1": "5713a380f7ee0216e97434e288733be8fc13fd76",
          "md5": "b852183bd6929005bf91b2d25b13cd1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.2-sources.jar",
          "url": "vectorx-batch-worker-24.1.2-sources.jar",
          "size": 23642,
          "sha512": "d15d8fc614803dc38f8198755380730f9932b0c8f6743323a750d813cc179c31c67ccc321fe0ee08d0b58c7818d3fa619d89c6efda38b21be5669a1c4cc5fa41",
          "sha256": "c5c1f571a9bc41913cfed4152e882cdda1461b96eed357b5de9eb1dc394b65ad",
          "sha1": "e4c23b4d4ce0d9224850423a154bfb17b0302073",
          "md5": "51232104054610324fdf94dfc0804add"
        }
      ]
    }
  ]
}
