{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-data-mybatis-24.1.8-SNAPSHOT.2.jar",
          "size": 110204,
          "sha512": "ab1f32b090b46177f9af5c1be362c523f61eb6a8d14f58fd05b17851fd4fb17f54be89682aab873f25f532ccd974bfc0aecad537795bf477fb4619e94659a848",
          "sha256": "7b97559db63e8ae1cb1c6d190616601ef901e9abffafb8e4974ff120ad4b6ce6",
          "sha1": "047c4f232265472496be1c6b30bf6394c95b10fb",
          "md5": "7617f5eed1d0ece9215a2662ac1c47f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-data-mybatis-24.1.8-SNAPSHOT.2.jar",
          "size": 110204,
          "sha512": "ab1f32b090b46177f9af5c1be362c523f61eb6a8d14f58fd05b17851fd4fb17f54be89682aab873f25f532ccd974bfc0aecad537795bf477fb4619e94659a848",
          "sha256": "7b97559db63e8ae1cb1c6d190616601ef901e9abffafb8e4974ff120ad4b6ce6",
          "sha1": "047c4f232265472496be1c6b30bf6394c95b10fb",
          "md5": "7617f5eed1d0ece9215a2662ac1c47f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 306404,
          "sha512": "50d46db367cf6737d4d5318c4a32592d9f34a60e5d62738f6d4fd5c46f6232c53985d9641250b2ab832d19c74c98259505b5dc613780152720021344c2673704",
          "sha256": "f69bd067814f6fcc445a35d4b7bcb0879408804ed9213b1839c744ee99524a6c",
          "sha1": "55be9bf93145df66ee5fdec8b4e9d052e8d2d498",
          "md5": "47ac8bfac37bc174305e90d58662cf81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-data-mybatis-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 70758,
          "sha512": "419cb6a66a12bb277cb67341e7caf011d7dcff20578b7024ba899225debed59a2dff55bb7b9cf22486547403f5cbbb6659b5880e2847869a4379d99bf7e769b8",
          "sha256": "8fe581fe7055360db7a85b5f0de4d3e493293397ce85a391a4e2792272dcf636",
          "sha1": "3e3352dc66840df4602772832ed61acfa43d90a5",
          "md5": "59e2364687dfebc669be952c99c75f33"
        }
      ]
    }
  ]
}
