{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-restapi",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-restapi-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-starter-restapi-24.1.9-SNAPSHOT.5.jar",
          "size": 261,
          "sha512": "49d45a0b34fbdf2dd3f7a9ecfb6b86ab51ef3c503695a0c6481637a841e907f5b8439e85f330cdfbf354b31d0f4de2e297575132d35e17ba9eaa678070c1b224",
          "sha256": "7d869c82392c16f7e512c982c067ebbf91317843f07d99219bfa2cdb80a59e45",
          "sha1": "63fc23f8a5e39161486292407dbb073e21aff3da",
          "md5": "6d1b73c364df8435831ee84803b36b93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-restapi-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-starter-restapi-24.1.9-SNAPSHOT.5.jar",
          "size": 261,
          "sha512": "49d45a0b34fbdf2dd3f7a9ecfb6b86ab51ef3c503695a0c6481637a841e907f5b8439e85f330cdfbf354b31d0f4de2e297575132d35e17ba9eaa678070c1b224",
          "sha256": "7d869c82392c16f7e512c982c067ebbf91317843f07d99219bfa2cdb80a59e45",
          "sha1": "63fc23f8a5e39161486292407dbb073e21aff3da",
          "md5": "6d1b73c364df8435831ee84803b36b93"
        }
      ]
    }
  ]
}
