{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.5.jar",
          "size": 148449,
          "sha512": "4b2ef11280a4ac3776b69f8e82c57ef82cf59071b0e5b879ac3e5f0c439b88e502a5a5be9a5a68c86b15f3d132d0e3d31aa44260038a58394d1e3bb9eb49ae57",
          "sha256": "a7d75c1d3b906cf9bd5e2d5a64192b84c5ca8eaf5b94883245027a53b80e30a3",
          "sha1": "0e2a2ab927e6a3bf6428df59a823b6b47cafe0d8",
          "md5": "b0eb57fac7758148b49b204adfe6275d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.5.jar",
          "size": 148449,
          "sha512": "4b2ef11280a4ac3776b69f8e82c57ef82cf59071b0e5b879ac3e5f0c439b88e502a5a5be9a5a68c86b15f3d132d0e3d31aa44260038a58394d1e3bb9eb49ae57",
          "sha256": "a7d75c1d3b906cf9bd5e2d5a64192b84c5ca8eaf5b94883245027a53b80e30a3",
          "sha1": "0e2a2ab927e6a3bf6428df59a823b6b47cafe0d8",
          "md5": "b0eb57fac7758148b49b204adfe6275d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 316433,
          "sha512": "0b0e65ba1591d38178609ae2fea249d4a1191d8109cb1bf41aa42a5b6f5bce6e2dfb7b39e6f712a946f0b8383bc94a5590852d81f03f11dd4de19e4a8aa64268",
          "sha256": "f50b3ea7bf89b058568d060565628a6b00167ad85753dcf6bed5ced132de8476",
          "sha1": "1516187829fdccb922b3df3b584ff4cd89b1532f",
          "md5": "3548098b51420af495f212fa6761949c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 61393,
          "sha512": "ddd35137f6a2a29c8578e5a5ac379ec16260e429779224025f1ee7a27bc199b8cfd361dcd51a9f6d9d4169e7d48e4511af316d1fac3bd8642938bafb8073c54a",
          "sha256": "5d013e018170eb31cab983a16b5254d46fa62ed75dfbcf1f1d7e03e7006f0449",
          "sha1": "62107c562027d30cc69b766ef82c50b5c6451bf0",
          "md5": "2e5a739f218bf9296a28868341ca102e"
        }
      ]
    }
  ]
}
