{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.9.jar",
          "size": 2775,
          "sha512": "eef974363685a4bc03f976e97ea9df807b40c573fd696036d102c270f65151ff03296a5164c3bdd654ae6ef9816a3e53291bb0ff10be2d7c55dd74bdbd893141",
          "sha256": "c73a1f4f62ab304d7d9827e2005dccfefca6630efe4f2312f65b7d70fc9db5e4",
          "sha1": "7426e2b136f27c073b5e503bc032a0abb7b13fbd",
          "md5": "0bf30e244247a29e56fd8bd0dc2ab79d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.9.jar",
          "size": 2775,
          "sha512": "eef974363685a4bc03f976e97ea9df807b40c573fd696036d102c270f65151ff03296a5164c3bdd654ae6ef9816a3e53291bb0ff10be2d7c55dd74bdbd893141",
          "sha256": "c73a1f4f62ab304d7d9827e2005dccfefca6630efe4f2312f65b7d70fc9db5e4",
          "sha1": "7426e2b136f27c073b5e503bc032a0abb7b13fbd",
          "md5": "0bf30e244247a29e56fd8bd0dc2ab79d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 70465,
          "sha512": "6be1469082667fa11991bfbe8deb7820455bb923834f69949b1b679318647b8fa95229e9e463c42f4fd4ec635064b1c531f1fec9ee128ee9acb06d66f3149ac5",
          "sha256": "abc478f4a209712c4ed82ba832b3d9f23a9629d31a0df8c08d2a15dc64ed5ba5",
          "sha1": "a0b09d908d5f6b4d399462535eadd529afaabdbb",
          "md5": "48b4878b620d3a2dbab408278232e55f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 1228,
          "sha512": "58d94c71d48bfd5c8f26e32d4f4f3579a2e18bcd5a10de98950675aa0928ef3baf9344d0bb36f5038cabf67edbace289391baa0a6ef04085d19fc0a66009594f",
          "sha256": "351051e06ce1cd14cb8ff6d723f0bc76dfdbbb88344bad003f939a260da5e16c",
          "sha1": "3bbe041e6735def19b08eded3b04d07046e807b8",
          "md5": "9983d1365b14cbbde647f6f93c510a1f"
        }
      ]
    }
  ]
}
