{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe-xplatform",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.6.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.6.jar",
          "size": 3380,
          "sha512": "1d9243a45931468a685159adddb21243cf3fc9cfbb11311dc3dd182c45cb47ed76e80d7b8f49eda2dd2d647a2d46137a9447d17eeccdb8ede36f23eb96d89fc1",
          "sha256": "4738b15952c5ce8ef6ea8adfd220bac69bcbc1dcf0dda02ec135c2b7dc276ccd",
          "sha1": "a9d33e51850a8595022cd09800af94fc67d37ee6",
          "md5": "5ec52db5bea0650ddc20021857983fa3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.6.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.6.jar",
          "size": 3380,
          "sha512": "1d9243a45931468a685159adddb21243cf3fc9cfbb11311dc3dd182c45cb47ed76e80d7b8f49eda2dd2d647a2d46137a9447d17eeccdb8ede36f23eb96d89fc1",
          "sha256": "4738b15952c5ce8ef6ea8adfd220bac69bcbc1dcf0dda02ec135c2b7dc276ccd",
          "sha1": "a9d33e51850a8595022cd09800af94fc67d37ee6",
          "md5": "5ec52db5bea0650ddc20021857983fa3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.6-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.6-javadoc.jar",
          "size": 70857,
          "sha512": "d70101d7f6e2aa2b827ec658a887c71f77c96caecdacf1510290ea940ed45a80e786178a092803e7e86cf5d6c2c3687481821195435c296a6623e48f294978f1",
          "sha256": "8bbe128592fba0d6d379d2388919d7f8ba6eeef80409a4e445b5ea67578434d6",
          "sha1": "88a001c32c4eb8327292474cd4e5e8ee4a95379a",
          "md5": "f9b9e4d6a4d71a70dee5f21ea95696b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.6-sources.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.6-sources.jar",
          "size": 1674,
          "sha512": "90f2d1eb059540fb6a278d598b9cd390874b97cf40d6452290af55553f341b0297ef4a9438bb4591dadafd952a6c08ca75d7157d73a55b18190a3ad8fbef4358",
          "sha256": "6c4e6b3d30f6050b410f6a86afa563616e183f007ebfd2301844c19122538a39",
          "sha1": "1ff352ccdc937441678e1008e0dd376daaff551a",
          "md5": "190d44138f3c4a4ea723a20b88480a4e"
        }
      ]
    }
  ]
}
