{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-core",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-core-24.1.8-SNAPSHOT.3.jar",
          "size": 213254,
          "sha512": "d7551c52a8e1c9715b19ba11e3271b9bd81e1cea778ce97d7726131eb5e6345d57c7b1193b9d90784328a032d0f25b25039709bc2da44e51b61e41d5a1abc862",
          "sha256": "027d0d0c4ce3599f093ac33f7b47dccd2b903bbf70678fc033b7c3c394f6a312",
          "sha1": "834f2d37a1bf99e0da48d09fb057c0d77e3196a0",
          "md5": "a65f232c1f06aa688c4f9af4ea9ad2b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-core-24.1.8-SNAPSHOT.3.jar",
          "size": 213254,
          "sha512": "d7551c52a8e1c9715b19ba11e3271b9bd81e1cea778ce97d7726131eb5e6345d57c7b1193b9d90784328a032d0f25b25039709bc2da44e51b61e41d5a1abc862",
          "sha256": "027d0d0c4ce3599f093ac33f7b47dccd2b903bbf70678fc033b7c3c394f6a312",
          "sha1": "834f2d37a1bf99e0da48d09fb057c0d77e3196a0",
          "md5": "a65f232c1f06aa688c4f9af4ea9ad2b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-core-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 508769,
          "sha512": "ad503661dfb6a81d84d611c6a0e0065263af9e662df5eba3bedb62a8b4219bb1f7d03488a8cb5c90a8fbf4797dc2441b1f764b7274ace1a2de50a532469e47d3",
          "sha256": "3d7ddedc81db0e386a7ced2ac800db13f7e3102a8c2e99824265165af0a47bdf",
          "sha1": "17a9c5bf8eb19cb77f28497687bc28738383baaf",
          "md5": "7a9b73e57022b8b83416dca517df493a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-core-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 102660,
          "sha512": "4f7d33cf98d7bb2ecb5305a22a25d5c0fcc593e9f705e5dbcf1e8e0023398a50b308ec302f37a1826de6535281650bb94da2380fafec782495a5c4932a485def",
          "sha256": "78adc1d3ad6f98234178f3dacee2dd6f11cbe2f0072c7c51523197f3d71be66b",
          "sha1": "c78361c8911614ce24d935a565a514a6f4850bcc",
          "md5": "0fe4b7ac349edef9cbe40a54906070f9"
        }
      ]
    }
  ]
}
