{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.7.jar",
          "url": "vectorx-net-24.1.7.jar",
          "size": 29717,
          "sha512": "3aedb2fe382795f99a0f3749d3fdf751a8ca459835b31387dee61c50e968e0d57b122b0104ebab78d1172ec48bf5acb2616635417eb93636a5bc4beb46fae829",
          "sha256": "acd5eec384cddd693241655ce37bccbdc929b30c0eedcd0d840c60c5525b2b37",
          "sha1": "caed031a2fa8bff753f54d84cd743554af22d438",
          "md5": "8ed7c64a274d63be02b2a3fab951b240"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.7.jar",
          "url": "vectorx-net-24.1.7.jar",
          "size": 29717,
          "sha512": "3aedb2fe382795f99a0f3749d3fdf751a8ca459835b31387dee61c50e968e0d57b122b0104ebab78d1172ec48bf5acb2616635417eb93636a5bc4beb46fae829",
          "sha256": "acd5eec384cddd693241655ce37bccbdc929b30c0eedcd0d840c60c5525b2b37",
          "sha1": "caed031a2fa8bff753f54d84cd743554af22d438",
          "md5": "8ed7c64a274d63be02b2a3fab951b240"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.7-javadoc.jar",
          "url": "vectorx-net-24.1.7-javadoc.jar",
          "size": 128277,
          "sha512": "ecafbc7f8f699f3ff09c5a492800057ed8dcb01740359cb03a496362e385c185ea32236d5c8d6ebe539499b6a9ca920ad8cb2fae6369e23ea1a6d70b8c402ea6",
          "sha256": "c2a7b355859c8831c353b7a7c18979677a2b3b910515211471daf3e7f98c46d6",
          "sha1": "d869f81b32cdd627da0aaa236fd6a34579102da7",
          "md5": "67bea6c917bcc8949a865eb127b7ac4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.7-sources.jar",
          "url": "vectorx-net-24.1.7-sources.jar",
          "size": 10137,
          "sha512": "cf455dfcf8af68179acf9119577b193d7c5b9d2a4e4d47fce4ee478434bbeb54b416c59661ab5e99b8c0ed296e2615c816c1eee0d3034f41b1b8cc21593007d2",
          "sha256": "33f923c4458af00e24c1d109986e00af63d3c2b373e1c84ec78b3348f57676c5",
          "sha1": "086f5907679b0a36bc320fe04db0baf9559885cb",
          "md5": "8613320e77fdcb1031df34a6f811bf94"
        }
      ]
    }
  ]
}
