{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.5.jar",
          "url": "vectorx-cloud-core-24.1.5.jar",
          "size": 2696,
          "sha512": "1e9c6bfe4efe7304fbe13590a559091caa908b8c39c4ba05f58218749abdb1a6d4a4ed2f231745dc6f954860bed030f81fc709958cad7a560a19d9c3e277dbac",
          "sha256": "3f06f04c5618d8711a8b22fef4daa9ea1ab373f87f9566c3af16a6dade85b159",
          "sha1": "5f9e4375f1a5d835fa5ed9a9c1814f614c79f58b",
          "md5": "21db93579a4770261d47e99f5ab93311"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.5.jar",
          "url": "vectorx-cloud-core-24.1.5.jar",
          "size": 2696,
          "sha512": "1e9c6bfe4efe7304fbe13590a559091caa908b8c39c4ba05f58218749abdb1a6d4a4ed2f231745dc6f954860bed030f81fc709958cad7a560a19d9c3e277dbac",
          "sha256": "3f06f04c5618d8711a8b22fef4daa9ea1ab373f87f9566c3af16a6dade85b159",
          "sha1": "5f9e4375f1a5d835fa5ed9a9c1814f614c79f58b",
          "md5": "21db93579a4770261d47e99f5ab93311"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.5-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.5-javadoc.jar",
          "size": 70381,
          "sha512": "fdc774bf5132b62eb7a8c8ff1366285072511f95e0ec951764dc23b902f1bf0827033511d80674e52f779472cfd7250588307ac1a3a5c538ee339cbb4552cbe4",
          "sha256": "48080e16474ae32b9632cb63e3b01a42ba6b0ea6ceb40626aaf612606ecda8f5",
          "sha1": "71fa578aff879d791131c08bb7ccef4d3c5f8f45",
          "md5": "4ddf52bd581ad8bcb5b25761c89989b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.5-sources.jar",
          "url": "vectorx-cloud-core-24.1.5-sources.jar",
          "size": 1186,
          "sha512": "1cdc7e56d2af21880a18ddf2a7715c6a44e41f128f54eecf2c8f77c2bc0c2c74024e13923f7c3676346087fc881bc3cfa95784b014251f1078502bca5b65a642",
          "sha256": "ff15afbebb2c5e8ac3b0f14c6f64fa2260d8e635a760b4fcc5fbe5f19bcb2320",
          "sha1": "9fc6fbf52ec781ed3e1d022c72299669124fc021",
          "md5": "9e6d56debc0d1bbaaaf219cabab0713a"
        }
      ]
    }
  ]
}
