{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe-xplatform",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.9.jar",
          "size": 3349,
          "sha512": "5cbf317f5c6541de30862a80b0581ec55845693aa61739ac58be37d3da104768743df9d065c1185aef3a6edabecaa3687c1896359dfe8e87b569b4f59a20f77a",
          "sha256": "20442ff47d6b45c38d87292b10ee179ae4cab00da7fbdcf30b83112ca456f18c",
          "sha1": "9e504d5e8ddc647ad706d37c407ffbb22e622765",
          "md5": "5e7a1a443334ce3ef96a03e3708e8607"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.9.jar",
          "size": 3349,
          "sha512": "5cbf317f5c6541de30862a80b0581ec55845693aa61739ac58be37d3da104768743df9d065c1185aef3a6edabecaa3687c1896359dfe8e87b569b4f59a20f77a",
          "sha256": "20442ff47d6b45c38d87292b10ee179ae4cab00da7fbdcf30b83112ca456f18c",
          "sha1": "9e504d5e8ddc647ad706d37c407ffbb22e622765",
          "md5": "5e7a1a443334ce3ef96a03e3708e8607"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 70958,
          "sha512": "40cde62d5eeefa580aa5cca5a37a8a20c4421f7f0a71d08d8ebc477f5b0f2a40a1767e63d88ae70c05cdd5ea6071af346b15050b497849cc8991ced882b95738",
          "sha256": "72c304353035c62df23f491476f040e69f409d3007c8ef821ca1d62b273eb8b6",
          "sha1": "7b9b6f8f4a88cdf7de0c5859c71ab7e42af8e911",
          "md5": "027a24020e34125502e69f2f19ce903d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 1674,
          "sha512": "cb539304db160847ee245baf203686e2673d6e1f4b784b7876c4f4dab3579c85e39f230bd521563f67cddcec642ab10202ba1b7546c63f6864f87b32f5e8d120",
          "sha256": "d6d0429d71905bcc99937a21187babd72e9fd44a045b215f73b85e4b819be4fe",
          "sha1": "bce7bcb08bb63f71089f2d7853e338e7267dcc31",
          "md5": "61938946830e945c4a950441e8cacb1b"
        }
      ]
    }
  ]
}
