{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.13.jar",
          "size": 2713,
          "sha512": "863a1abf2c84c6ce9adfe45d9b85a782a8c41467a15e1de6f253f1ca485d8739c1ae9ab9977060e88ab2d4635bb437c7ac96bbee405c5e4973eed4f65f3b1a10",
          "sha256": "e14ed10ab529a4acdab6da8c660399a61dacf67e69a93db42ce7ccb142245624",
          "sha1": "4b1898769c13518b41caec8f4d8f137ee1d8c95a",
          "md5": "e9505211bb302a9ad2410ee929650877"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.13.jar",
          "size": 2713,
          "sha512": "863a1abf2c84c6ce9adfe45d9b85a782a8c41467a15e1de6f253f1ca485d8739c1ae9ab9977060e88ab2d4635bb437c7ac96bbee405c5e4973eed4f65f3b1a10",
          "sha256": "e14ed10ab529a4acdab6da8c660399a61dacf67e69a93db42ce7ccb142245624",
          "sha1": "4b1898769c13518b41caec8f4d8f137ee1d8c95a",
          "md5": "e9505211bb302a9ad2410ee929650877"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 80922,
          "sha512": "2a89805da7ec8604f3450b2c12f3b18e9e69818bcce66883c230d8a963d423ab3aae0de1db5d90097bdcabe15a8e65b5b531e9aaef4f93a962b06c9949db7828",
          "sha256": "4a865718ccf66fa573181cd9333544be5b44c58e6ccec3af5a49def038ed895b",
          "sha1": "0f2fad548b1ee93b65980167d8e2476ef11ee045",
          "md5": "df2fd77c761ad77808e7cb43969f49aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 1180,
          "sha512": "eb32ac7f67b513f0dc5c85e10b72c92750c56a2183254cc06a52cc86c6d2be02e5e11a3a2fa5d5e80a37a7528ecbd689a4f89803c72278812f1ab31b12bd3c32",
          "sha256": "f5263699c2086da870f17ddb316f4d02d7077999a40224f72c193d373f945b12",
          "sha1": "aed6219891ca75e160056f42ac98e130b5f3fbd6",
          "md5": "f9f3bd9f153b3aec624b0b429339fac3"
        }
      ]
    }
  ]
}
