{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.2.jar",
          "size": 244276,
          "sha512": "fd5892b66d186d08137a90cef88a704351d7f360ce7121c9ae56ccad69a239f5b2b8a5588618c419c85bb0a861c143860a00d8b6bf418d856483579cdf7b2fd7",
          "sha256": "6dc41da3a25176a6530163ef18515d0483d18d845430d48178c069ef8c47f519",
          "sha1": "6bf700588b995d9d63b3f73d426261aefea2b376",
          "md5": "a4fd1de12b1b43eec068fb8d2ff05f8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.2.jar",
          "size": 244276,
          "sha512": "fd5892b66d186d08137a90cef88a704351d7f360ce7121c9ae56ccad69a239f5b2b8a5588618c419c85bb0a861c143860a00d8b6bf418d856483579cdf7b2fd7",
          "sha256": "6dc41da3a25176a6530163ef18515d0483d18d845430d48178c069ef8c47f519",
          "sha1": "6bf700588b995d9d63b3f73d426261aefea2b376",
          "md5": "a4fd1de12b1b43eec068fb8d2ff05f8d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 521733,
          "sha512": "03dda6a20296fd7aaf1eb866d65d5d59da2d38890d9eacf8c251b7e10caa28a64343534f1a035bdcab5cb4dea7d8f524b5ae8cec2f6616248baddb3dc0379891",
          "sha256": "1c9f7c58364394686f67bca3f4f15e7ed627badd54352b0ed38270ff29802e36",
          "sha1": "1ed53c475ec81b39ecafcdb004a727ab13d14eef",
          "md5": "002b7ee3f400028fbfb57cbe96cff30a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 102673,
          "sha512": "fa44c54b5b85c436b7147ee88d219f38a316bc0bc6e53b311bbda355afe65937365294b13e0fbd49a1c7a7d90bf09702c8df731e9fe09da94e37f7a1a4df3fb4",
          "sha256": "467f01be70df5d908b9342af320352f2289e71868cda89ca249c0c1ed6693f95",
          "sha1": "05b49cffb8a4d9ca758d4645c8eadec3bdaefd49",
          "md5": "a91afa004afb338904f7f6f33e63d987"
        }
      ]
    }
  ]
}
