{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.6.jar",
          "url": "vectorx-data-mybatis-24.1.6.jar",
          "size": 110125,
          "sha512": "1c52e507c690e889bef83e4d91a01ca03a1100fdc74b6f54c9890b55e68f5058765c27c100e31dfbe1870590844bf3a408ffb48863f539d9867f2b7a5c25c782",
          "sha256": "4bffd35c4cef9f0be8024f8ba6a3f3671de9f7045cbf6e35dc9303587cd4c99c",
          "sha1": "531619c79120c7da7df903758f60e72188f9f7d3",
          "md5": "9c7d864b6e4b3b8c1e83d259a1a3fadf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.6.jar",
          "url": "vectorx-data-mybatis-24.1.6.jar",
          "size": 110125,
          "sha512": "1c52e507c690e889bef83e4d91a01ca03a1100fdc74b6f54c9890b55e68f5058765c27c100e31dfbe1870590844bf3a408ffb48863f539d9867f2b7a5c25c782",
          "sha256": "4bffd35c4cef9f0be8024f8ba6a3f3671de9f7045cbf6e35dc9303587cd4c99c",
          "sha1": "531619c79120c7da7df903758f60e72188f9f7d3",
          "md5": "9c7d864b6e4b3b8c1e83d259a1a3fadf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.6-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.6-javadoc.jar",
          "size": 305035,
          "sha512": "537beba8eff4e39d2bcd7721da7155d39b4751b3182cd5a8b0cc22e4a7f3d86d0c6f381c5607856bcb47ab2efe057406ffd41c136dd7b121ab004526391ec34c",
          "sha256": "f99dee317940c786c35029c1fab31d46d0adaba2194a30e496f1124c5b7abc40",
          "sha1": "9ac8703aae12b6d0bb7d3e8045b9cedb61cddf9a",
          "md5": "2b66a78ea69f90382a8131f0b6013108"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.6-sources.jar",
          "url": "vectorx-data-mybatis-24.1.6-sources.jar",
          "size": 70748,
          "sha512": "cede1b7ebf152e38bd6f26989b5f0878000dd0f6a0f5952499759e7f97d66348bdc98c498ba92067af9b430c0fdef8f466d8a6ce9615bc28bc7696747c0ad0b4",
          "sha256": "19b3028171611b4d2cef3f2d5b6f1c7b37a66535ac88d2b850014338915e63c3",
          "sha1": "c262ad6997d7d31c4bd9bbfe57e0540ee7ea205a",
          "md5": "401bd13d950ec2046ed39ce283134c97"
        }
      ]
    }
  ]
}
