{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.6.jar",
          "url": "vectorx-management-bo-24.1.6.jar",
          "size": 145534,
          "sha512": "1af8ef48797c0ab533e3872f9027be028eb4c1264aa4dded78218faeee7346ce2e1b3174c3f08ef19ca798fe2355d8dd21833b87039989e3d48e58017e9e6db9",
          "sha256": "e4c3f583059ebf9b3e34bac8b6d7adfeb3d5c9c5e28e8d8114cd980ed9c7d20f",
          "sha1": "534468e6df0533746afa104329ac4198b454bcc2",
          "md5": "374bc701db1d8f1dda34adbdc29be520"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.6.jar",
          "url": "vectorx-management-bo-24.1.6.jar",
          "size": 145534,
          "sha512": "1af8ef48797c0ab533e3872f9027be028eb4c1264aa4dded78218faeee7346ce2e1b3174c3f08ef19ca798fe2355d8dd21833b87039989e3d48e58017e9e6db9",
          "sha256": "e4c3f583059ebf9b3e34bac8b6d7adfeb3d5c9c5e28e8d8114cd980ed9c7d20f",
          "sha1": "534468e6df0533746afa104329ac4198b454bcc2",
          "md5": "374bc701db1d8f1dda34adbdc29be520"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.6-javadoc.jar",
          "url": "vectorx-management-bo-24.1.6-javadoc.jar",
          "size": 305889,
          "sha512": "c930ce655b2ede95b6c5adbe7f1a549ee0e8e6c4d52ba47af7f0087ee47dc6f56f5529289f0273247b13f302797c250d5a298adc095cd557415f72e0c7d3e94a",
          "sha256": "f24e2246c9346b7e65aebc28551105e364b5f580a0a7f1b9f5b5578cd138c22e",
          "sha1": "3704f2391bb9e38243f89d703b9b14eafb1ca415",
          "md5": "08b03c706bba3d758dbbe34f0c308658"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.6-sources.jar",
          "url": "vectorx-management-bo-24.1.6-sources.jar",
          "size": 59353,
          "sha512": "de5db28dbe0d09a9d973a173536457ffd6dc58646a327242631f307a0d0efbf1e90d011880c268e83418245841acace9e59c6db4e1d2a9d34e6a254b8846b6eb",
          "sha256": "0e57c77dddecf60d0e8cb3a7e584b417ba3db314e94de459689af0e706f3fe90",
          "sha1": "300c059cc0f95c950560fb1f0320ac4ffece0903",
          "md5": "a30e5f6c6d768e5037c5204720258dff"
        }
      ]
    }
  ]
}
