{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-web-servlet-24.1.8-SNAPSHOT.2.jar",
          "size": 99520,
          "sha512": "0e9743102ae2507ea7928247eb9059405e1deb7ff8549a00539850ccbeb025e8b44c39c4ea5ad257837f91fa799489cac72a0ff5a54f5faf0808cdb8633115c0",
          "sha256": "97b23fc97da88ba4fd5c1633bdd52589307f0d059f5f61c46f735cdeca6ab081",
          "sha1": "8478dcb21426b2cb51d2cd193bdef8f9f64de766",
          "md5": "d8a5278b31bc40bf49eafed18fbd15bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-web-servlet-24.1.8-SNAPSHOT.2.jar",
          "size": 99520,
          "sha512": "0e9743102ae2507ea7928247eb9059405e1deb7ff8549a00539850ccbeb025e8b44c39c4ea5ad257837f91fa799489cac72a0ff5a54f5faf0808cdb8633115c0",
          "sha256": "97b23fc97da88ba4fd5c1633bdd52589307f0d059f5f61c46f735cdeca6ab081",
          "sha1": "8478dcb21426b2cb51d2cd193bdef8f9f64de766",
          "md5": "d8a5278b31bc40bf49eafed18fbd15bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 298990,
          "sha512": "c10406d8ff3155099b00c35e503d0fdec3612fb6666128d16175651ec65d0e2aff464c405d933e54429f0a65d0118a12b3951f12fde6e5a3ac073465b0d8638e",
          "sha256": "69b57c8cef826f191a49af409306562c2b8dc31654ddd2d60fa4a162add97356",
          "sha1": "1c63dd770a047107923152699dec040057c4df33",
          "md5": "f6bd70934d592f53c2607c5c6c76baaf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-web-servlet-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 50887,
          "sha512": "ca24c706f778b9330a03581ca2daeef4089c8e1ca2eb67a09dbb789c2a72d5043748b4e36960591dee1410aae3ae4aa46953aad49b534cfc54f79435a92b073e",
          "sha256": "0a38ac85d1bb7e3c3c942338878ce24dc5b6c654d223383fac0634ec0aabe396",
          "sha1": "65aa26b67de818ed6000080e0438473f3c8428f6",
          "md5": "f335dad6e6a1f1dcc4946550c680e9c2"
        }
      ]
    }
  ]
}
