{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-restapi",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-restapi-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-starter-restapi-24.1.9-SNAPSHOT.13.jar",
          "size": 261,
          "sha512": "fe51976233d26b1c20a86b448c1cd7734904e428cf59c3ecc21084d1022138bf13003864c653f45874a6624f54b2885211b79dee98b0f2ff886336358a74f7f2",
          "sha256": "379c98411dab63d76bf2c5512bb533b5fcddfa8c09499796ae27729093dcb5d3",
          "sha1": "eeb53cadf871db33dbd1e3452e9539a6d31b2392",
          "md5": "af853a5f8bdbcbd87fe74e65a410b4e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-restapi-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-starter-restapi-24.1.9-SNAPSHOT.13.jar",
          "size": 261,
          "sha512": "fe51976233d26b1c20a86b448c1cd7734904e428cf59c3ecc21084d1022138bf13003864c653f45874a6624f54b2885211b79dee98b0f2ff886336358a74f7f2",
          "sha256": "379c98411dab63d76bf2c5512bb533b5fcddfa8c09499796ae27729093dcb5d3",
          "sha1": "eeb53cadf871db33dbd1e3452e9539a6d31b2392",
          "md5": "af853a5f8bdbcbd87fe74e65a410b4e1"
        }
      ]
    }
  ]
}
