{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-mybatis",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-mybatis-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-starter-mybatis-24.1.8-SNAPSHOT.5.jar",
          "size": 261,
          "sha512": "b6760235ee876e9b568e81a706832cfc1253da1094b7e21d1866bc0dcc434384e0cdd91f796e5d909da543b80ce69cc94b7d645be65cae045332bff2982b4d1d",
          "sha256": "ac0e013ff7649f901a4d4e8e3685dd07a34d2ace8d5a6c73961f4cfe3e498ddf",
          "sha1": "51164e88ab59e9145a152bc4194c59c038d8136c",
          "md5": "55fce84e8b5050e9a368c7d16b92daaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-mybatis-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-starter-mybatis-24.1.8-SNAPSHOT.5.jar",
          "size": 261,
          "sha512": "b6760235ee876e9b568e81a706832cfc1253da1094b7e21d1866bc0dcc434384e0cdd91f796e5d909da543b80ce69cc94b7d645be65cae045332bff2982b4d1d",
          "sha256": "ac0e013ff7649f901a4d4e8e3685dd07a34d2ace8d5a6c73961f4cfe3e498ddf",
          "sha1": "51164e88ab59e9145a152bc4194c59c038d8136c",
          "md5": "55fce84e8b5050e9a368c7d16b92daaa"
        }
      ]
    }
  ]
}
