{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.2.jar",
          "url": "vectorx-web-servlet-view-24.1.2.jar",
          "size": 19208,
          "sha512": "04b0a507179818bf255278f8c9cdae04c75395b0cce9818e456d8fdfe52ded7b0623be173aefdfdf94b2e598b93c2072d5f1d9178103a09c30b3490be5dcc549",
          "sha256": "d4003fef1a73ea9a4267a754eb0b7562b0762303c058288cdc712662600f47fb",
          "sha1": "05a29fd976479d280592d10bf6b57de51f79dca6",
          "md5": "ce63ef7aed4b0c15a26870f45b735f67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.2.jar",
          "url": "vectorx-web-servlet-view-24.1.2.jar",
          "size": 19208,
          "sha512": "04b0a507179818bf255278f8c9cdae04c75395b0cce9818e456d8fdfe52ded7b0623be173aefdfdf94b2e598b93c2072d5f1d9178103a09c30b3490be5dcc549",
          "sha256": "d4003fef1a73ea9a4267a754eb0b7562b0762303c058288cdc712662600f47fb",
          "sha1": "05a29fd976479d280592d10bf6b57de51f79dca6",
          "md5": "ce63ef7aed4b0c15a26870f45b735f67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.2-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.2-javadoc.jar",
          "size": 132213,
          "sha512": "afe83365975f5801a15f23607bbcc57b2a85ed74c28e097c3d2403834841e36fe855726b5f3f355046c75b00295e90b776a6dfc2e33309553d03cde37008d22f",
          "sha256": "bec820aa6e1e2e99c21e43ef38c89a6f294aee3575607f9fcad9e30f2746a34d",
          "sha1": "8dbe9715f69d9f29a1ffddec6d62e3221d7a1a6e",
          "md5": "1c28f0997790d2f442e8e72afebd1fe6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.2-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.2-sources.jar",
          "size": 11247,
          "sha512": "7cd6fcd68132270368079a6d01f5d437c34dc6767e24da224528623c22c8768d66480b0ee747358b4e00171eae1a089f2c1551857d395d104f48a60219de65ad",
          "sha256": "e0ba82f288a5b2ad80dc699742a160f5bdf3af8bd35175f29e6330557f544b40",
          "sha1": "d57766b9f55f16a363637f01804e3b77ddd763f1",
          "md5": "8773b544911dd9194b3afda607e454d4"
        }
      ]
    }
  ]
}
