{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-restapi",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-restapi-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-starter-restapi-24.1.9-SNAPSHOT.3.jar",
          "size": 261,
          "sha512": "6e6e2032b15040e654e919200db7120e190da8ec14ae80cbd6f36e6ca517f827e4400724467c2e75c0a4efeff94b7d959b973102760049438c5a18f4b83ad49a",
          "sha256": "584059a9f4e4cd5f2978b6b914d2da2265fb697ea274b030a4cb53e26d2faeae",
          "sha1": "34965519ce3ebf236aae2e96cdfb13f0eec280dd",
          "md5": "c6165ff9a5726b2baf4752731976b584"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-restapi-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-starter-restapi-24.1.9-SNAPSHOT.3.jar",
          "size": 261,
          "sha512": "6e6e2032b15040e654e919200db7120e190da8ec14ae80cbd6f36e6ca517f827e4400724467c2e75c0a4efeff94b7d959b973102760049438c5a18f4b83ad49a",
          "sha256": "584059a9f4e4cd5f2978b6b914d2da2265fb697ea274b030a4cb53e26d2faeae",
          "sha1": "34965519ce3ebf236aae2e96cdfb13f0eec280dd",
          "md5": "c6165ff9a5726b2baf4752731976b584"
        }
      ]
    }
  ]
}
