{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.9.jar",
          "size": 51903,
          "sha512": "86cdcdcff6704413537c0f98e97bf0c99f11981ab8ead7e76aa4bc12d88f22beb32b636bf2a3ff0e41da50d40129f385bc720feec6c4f6190870295f5261ad7c",
          "sha256": "775bb369003e92c1be623c00927cdd960153112ae43954f1399bd16d215da936",
          "sha1": "b83c35816be8571016100dfb70347c240c99e48f",
          "md5": "1029358930f9e8a441665a050f9a1fa8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.9.jar",
          "size": 51903,
          "sha512": "86cdcdcff6704413537c0f98e97bf0c99f11981ab8ead7e76aa4bc12d88f22beb32b636bf2a3ff0e41da50d40129f385bc720feec6c4f6190870295f5261ad7c",
          "sha256": "775bb369003e92c1be623c00927cdd960153112ae43954f1399bd16d215da936",
          "sha1": "b83c35816be8571016100dfb70347c240c99e48f",
          "md5": "1029358930f9e8a441665a050f9a1fa8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 180616,
          "sha512": "0ea5837d28a2fe0ebf233f6f2cc24a4e2e11994532b1d718c2ad8d17ac906229b1e93f564913f2c5be5c249267119db8c60379360dcd6d82f74def6efcdf26e8",
          "sha256": "02e2b0ec1e05709ad7ea5b38698543814a1f14049fe8def81af3454eb17d79fc",
          "sha1": "3cbf31e81afb56c89a366cdf6efc8ccceede8504",
          "md5": "bc3cb33a812f4d444ac594bdb4b2ea99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 23642,
          "sha512": "a54af722385f69b3d52ca0687b2424c7e84c3a4fb17c12424ef9e4c5618f22c8227b4177faa3f66bd6e6ae0fdb6e1ea81f550be81da0e66b6e07e550e2860ebe",
          "sha256": "a8cfec4c5e214bf691f4b65776f376daeee1c0a38f9a73af40c57215d0b5af7f",
          "sha1": "50ad9ecce97ec72f4e5c73653e35a5627be780dc",
          "md5": "b9ce8571977a5508ee3dbc8ee527619d"
        }
      ]
    }
  ]
}
