{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.1.jar",
          "size": 110179,
          "sha512": "fccbabc6180c26e8a2dc5df6f6b51035291e0494a0fe237de78cd80a9ce5cabfb84680ba46f1967bf80da28a7c5128596645e6695abba3bf4edc266b955b9dd4",
          "sha256": "b9cb916081baaa3ba8fb9fce239eb244be0e16801612abc5a044b20c79dc245c",
          "sha1": "ae6888740576d6e544a96a853051f6aaaf91c1af",
          "md5": "097c74757a071ced10a1a3a6498578a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.1.jar",
          "size": 110179,
          "sha512": "fccbabc6180c26e8a2dc5df6f6b51035291e0494a0fe237de78cd80a9ce5cabfb84680ba46f1967bf80da28a7c5128596645e6695abba3bf4edc266b955b9dd4",
          "sha256": "b9cb916081baaa3ba8fb9fce239eb244be0e16801612abc5a044b20c79dc245c",
          "sha1": "ae6888740576d6e544a96a853051f6aaaf91c1af",
          "md5": "097c74757a071ced10a1a3a6498578a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 306419,
          "sha512": "31f00a6de0cd32b575e91d3750c4f3b6ef4c462ae4aec4e1d16ce250578d075a1d0089de4c3c0725d1328def7266d692c43d5082a57ad5653c9bfc2dd30d2346",
          "sha256": "731aa12b3d955a17a0cac8a92addd8430807f71776171dc63e94b2bf69b0c1e4",
          "sha1": "274a714d2e2ffe631ac27046c6893280b637a43d",
          "md5": "1bc5a25a85f7dc51104fe81f784e81c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 70735,
          "sha512": "89b4962be636324b899ee1552a051a284ca99e45df600d910635698ba8ea2e620539df6c92b85a87c4c902276af30803cecd45e3d362a5562cc4f18b9ede2467",
          "sha256": "94abe25df40cba128313c11dd72ae6febd1e8a92c5cd5727482c4509817b77f6",
          "sha1": "34dee56599d9350c94b3d5892676b635c6a456d7",
          "md5": "9521c64883fa5586aedc5754af0ee48b"
        }
      ]
    }
  ]
}
