{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.1.jar",
          "size": 2717,
          "sha512": "82dbded6503cc34ddbd38481fff6c0afe4f2f3451b558c6771871a22df76e2f87c245e3a6a998dff560d5dc6b17f2eff92771233f765cad57b9267d4d8979803",
          "sha256": "4857f4d54d41b8d8da4bdcd7c78584ada07911d1ccd102cc738c4b4e9e8da939",
          "sha1": "84cda9e9efa602640f59e58b5a22ff4ac84fefe2",
          "md5": "d61742573f77fdbed3736014aaa1d9c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.1.jar",
          "size": 2717,
          "sha512": "82dbded6503cc34ddbd38481fff6c0afe4f2f3451b558c6771871a22df76e2f87c245e3a6a998dff560d5dc6b17f2eff92771233f765cad57b9267d4d8979803",
          "sha256": "4857f4d54d41b8d8da4bdcd7c78584ada07911d1ccd102cc738c4b4e9e8da939",
          "sha1": "84cda9e9efa602640f59e58b5a22ff4ac84fefe2",
          "md5": "d61742573f77fdbed3736014aaa1d9c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 70479,
          "sha512": "1bb78e125af46f348cef17a7024f49b13600db2840a6c8ea379bebe32569438b36f8451f5b86ae3529f58a02a86edeadedfad8444e111b110f901e10400d6acd",
          "sha256": "fc9f13f1b7d8c327b4e1feb1c0958b8a7428f73da2e0e1036201f591d3d99c53",
          "sha1": "690d09eff43f8efcba660adfacd2eb723093b024",
          "md5": "9aa847793669c706c10c12000bab293d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 1186,
          "sha512": "8caa24bae97db63e052bde745513db52a19ef704df6d0560fccb4aab59fd8b58d19180296f43f4cf6441eb25a416066a832b5d530f0166ef71e9b137fb84f260",
          "sha256": "247513c4fde3db3d3aef8a097e7e8b8a96228c416dd6a8829613fb230cd91e96",
          "sha1": "d45e32aa4c10685aedb7a6f80a8944985121ff0f",
          "md5": "55876ee1e3b7d5d70d87c8fb52a12288"
        }
      ]
    }
  ]
}
