{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-batch-manager",
    "version": "24.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch-manager",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-mvc",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-batch-manager-24.1.1-SNAPSHOT.jar",
          "url": "vectorx-starter-batch-manager-24.1.1-SNAPSHOT.jar",
          "size": 261,
          "sha512": "7ee58ed3a7f525249734702b8acc0827ad46eeb444139ab76829fd7f0c990d026e599c316872a3eb5c61a67214cb649e323002df2be11e8ed4f06ca8ae67c63a",
          "sha256": "7fae4b6895d27e51d15b46dcd8b786fee6126fa1b9cf40898b19dbcbc78ac4cf",
          "sha1": "b5e62be60738e7b5898b5ec0817bb909891ea607",
          "md5": "c0240c861e60fd61d35bcb0701ffac72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch-manager",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-mvc",
          "version": {
            "requires": "24.1.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-batch-manager-24.1.1-SNAPSHOT.jar",
          "url": "vectorx-starter-batch-manager-24.1.1-SNAPSHOT.jar",
          "size": 261,
          "sha512": "7ee58ed3a7f525249734702b8acc0827ad46eeb444139ab76829fd7f0c990d026e599c316872a3eb5c61a67214cb649e323002df2be11e8ed4f06ca8ae67c63a",
          "sha256": "7fae4b6895d27e51d15b46dcd8b786fee6126fa1b9cf40898b19dbcbc78ac4cf",
          "sha1": "b5e62be60738e7b5898b5ec0817bb909891ea607",
          "md5": "c0240c861e60fd61d35bcb0701ffac72"
        }
      ]
    }
  ]
}
