{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-cloud-core-24.1.8-SNAPSHOT.5.jar",
          "size": 2718,
          "sha512": "f3a03a6acb4aceb9fd6a393ce3b0d62d91411a2ec7a058ef2b201ecd843cddca1108fff82a618de25afb396b9dbd89b4185771f5c82d10ea88d2bb71b324849d",
          "sha256": "fdd892b053ed1d1fc62598c864b81618c20ea4ad3fb00487aa384fc49d253fd1",
          "sha1": "c901e432a0c77d8127aeb6dcf4dc027e0f669e40",
          "md5": "575e57609c99689811929a6b3bc0590a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-cloud-core-24.1.8-SNAPSHOT.5.jar",
          "size": 2718,
          "sha512": "f3a03a6acb4aceb9fd6a393ce3b0d62d91411a2ec7a058ef2b201ecd843cddca1108fff82a618de25afb396b9dbd89b4185771f5c82d10ea88d2bb71b324849d",
          "sha256": "fdd892b053ed1d1fc62598c864b81618c20ea4ad3fb00487aa384fc49d253fd1",
          "sha1": "c901e432a0c77d8127aeb6dcf4dc027e0f669e40",
          "md5": "575e57609c99689811929a6b3bc0590a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 70482,
          "sha512": "d1e50988e0430c2e662320b9add5bf2ad3b03d36bed15d2dd4a2c13819375f6a3343020e933e9cb60c1b77d9a110bae2a32763a4683927712b157ad830c2466a",
          "sha256": "cb1d30ef52a7f993563e705e639cd1ef36d7f0ec893a1ab2c216bec951340fdc",
          "sha1": "8701e147a59c019580af3fa717c130610d7b5ddb",
          "md5": "3e3314bffb43b34de2d6770f5727baf5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-cloud-core-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 1186,
          "sha512": "8805819f52a3fe4dd9b18800c8713f3fc31e274d63744e33281a13e430d4d99b920311bf98ca20d4822e967ae93008d570aea4b1e31ccdd31a9e4f6b5f3f017a",
          "sha256": "6e64e846c5d499f692ecbf1aa29e34610376cde5a1eb33023a50f3833bfedf6d",
          "sha1": "2e5cd9f1adcfeff1b383d7138776e53129977c80",
          "md5": "84b706f674d6c5b018fb0a3e074cce28"
        }
      ]
    }
  ]
}
