{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8.jar",
          "url": "vectorx-data-redis-24.1.8.jar",
          "size": 9716,
          "sha512": "3d9db525521c8d941b3e273d488c389711c12afc6daefebca9f6e3196b2422dc1f97ba6f0a801f27532205a50b79ecca28f3dff1079b4af18342469bd92f368a",
          "sha256": "92b23d4e7d2d4e3321171c93b05c97d38eb84d4c43c76360cf6a650f148c4362",
          "sha1": "31565651301afcc0818e2101b76eb3151e8225fa",
          "md5": "841610378ac29c7c929d973eca4cc59e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8.jar",
          "url": "vectorx-data-redis-24.1.8.jar",
          "size": 9716,
          "sha512": "3d9db525521c8d941b3e273d488c389711c12afc6daefebca9f6e3196b2422dc1f97ba6f0a801f27532205a50b79ecca28f3dff1079b4af18342469bd92f368a",
          "sha256": "92b23d4e7d2d4e3321171c93b05c97d38eb84d4c43c76360cf6a650f148c4362",
          "sha1": "31565651301afcc0818e2101b76eb3151e8225fa",
          "md5": "841610378ac29c7c929d973eca4cc59e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-javadoc.jar",
          "url": "vectorx-data-redis-24.1.8-javadoc.jar",
          "size": 93503,
          "sha512": "ff9e3e01314a3746b15c932a5cf5248d910a12c9ef2b3ace3ff4ad11de5c373a191ab566442649cb43210cfea28461613bd8bf87c3a65d86fc0db429a604172e",
          "sha256": "111fe698cea9d9107c83e148bccce3b5f9b5c8ea28d850de505546bb2f6f3205",
          "sha1": "23751fae7dc0a1b744aae104accd40d67dfa993e",
          "md5": "ab6e1ee8ccc3ee94b156d09579b8137c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-sources.jar",
          "url": "vectorx-data-redis-24.1.8-sources.jar",
          "size": 3360,
          "sha512": "39b66ae39b7ee1e823cbb5bcfa97747cee89bf5a72f9069103dd3b6ff60e820af1ad19c8d9fb9df5b01e407a7fb2db8650b9e2d2489cf003c29a761527b42988",
          "sha256": "17d4c71613814cb2c1476f49d0391dc3599cfd8b242785116faa0e339086eb81",
          "sha1": "e9b9615a62cd6a3124baefbd88b79babe5454fed",
          "md5": "cfcd9eb808d257fcacc8943aa3f9a7ad"
        }
      ]
    }
  ]
}
