{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.6.jar",
          "url": "vectorx-data-jpa-24.1.6.jar",
          "size": 2692,
          "sha512": "edbb6e20b1e35ae585136cb6a0fa7352a16f8b4ad537fbc5e77772606f4d6cd7f0528fbbe846e4b5966e005d18abbc350a4e0f1ab7364729ae5a74ba94da277e",
          "sha256": "dafc0744efd4d2e248a607eb34a1681762549e18d2ffbdb917d87a13579aa356",
          "sha1": "06455d518bad75399d857a6709f9c8567d356b78",
          "md5": "db7e59da193f97f56cad547cb70ff992"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.6.jar",
          "url": "vectorx-data-jpa-24.1.6.jar",
          "size": 2692,
          "sha512": "edbb6e20b1e35ae585136cb6a0fa7352a16f8b4ad537fbc5e77772606f4d6cd7f0528fbbe846e4b5966e005d18abbc350a4e0f1ab7364729ae5a74ba94da277e",
          "sha256": "dafc0744efd4d2e248a607eb34a1681762549e18d2ffbdb917d87a13579aa356",
          "sha1": "06455d518bad75399d857a6709f9c8567d356b78",
          "md5": "db7e59da193f97f56cad547cb70ff992"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.6-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.6-javadoc.jar",
          "size": 70340,
          "sha512": "4daecaf90e033d3cc255749e4eb3379504454d034b8bc6359b638e2c1f970ab8fe0b0518531f6f994865f001cec1f9bdb05aa25c8a620681e43f83dd8766c348",
          "sha256": "ccf5514a4012c8feb2a839dd265e8e14ef3b74e4637e3117cafde7c0ca9b532c",
          "sha1": "5ba87d6744da6a2ca3f49b34caefe813d00e00f4",
          "md5": "4be25101f33cb0a961c62d7a48f59944"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.6-sources.jar",
          "url": "vectorx-data-jpa-24.1.6-sources.jar",
          "size": 1184,
          "sha512": "59db237a9584501290592a4cd1d8aa6655d3654c78b901c4b4cf6c05285a4c6e3740eb16cac332391f607d1e297f79b2a7bafcaf91dbbea871c9bdb478028309",
          "sha256": "fc3736504cb7e5127f56807989c45b1bc78f123bb312ae8775963234bc7413b6",
          "sha1": "e599a8d3d7306e9b800fe1ee529c0592a2766f23",
          "md5": "2a0b907d5f192aadf68a82090dc1446b"
        }
      ]
    }
  ]
}
