{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-test",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.4.jar",
          "url": "vectorx-test-24.1.4.jar",
          "size": 31765,
          "sha512": "7fe05c5d01b5db55addbcbf3109f2e945d227b53606c25ba0c4bd523dea4e8759b8eb789d1fae8926a2d7a8a03a798af6fada3e04884cbe5e42e9ab495ea7734",
          "sha256": "f31bea1e7380617da5ff33b134ff99f0b47fa23c733b3290054992edce14c9e5",
          "sha1": "110ea5c247bacf78e7f33f2cc44da94d91e43e18",
          "md5": "d4ccc481e1a37a4c6424d7ba696920d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.4.jar",
          "url": "vectorx-test-24.1.4.jar",
          "size": 31765,
          "sha512": "7fe05c5d01b5db55addbcbf3109f2e945d227b53606c25ba0c4bd523dea4e8759b8eb789d1fae8926a2d7a8a03a798af6fada3e04884cbe5e42e9ab495ea7734",
          "sha256": "f31bea1e7380617da5ff33b134ff99f0b47fa23c733b3290054992edce14c9e5",
          "sha1": "110ea5c247bacf78e7f33f2cc44da94d91e43e18",
          "md5": "d4ccc481e1a37a4c6424d7ba696920d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.4-javadoc.jar",
          "url": "vectorx-test-24.1.4-javadoc.jar",
          "size": 125842,
          "sha512": "b7e764459c81c72ef306177b1c27d833bea949a88faac058cd59f14b91982330b340694b6855ed43749ebf1046966f4d482ce8dcde18bcfd58e575f727d36e2b",
          "sha256": "aea17910874019a4a7728108e797c6005583ee4c23143eadf8406905ce0bdd01",
          "sha1": "f7195253f45e0296983874adc32542a379df9440",
          "md5": "7afd334edaae25bfc8e69f366d37d3f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.4-sources.jar",
          "url": "vectorx-test-24.1.4-sources.jar",
          "size": 11947,
          "sha512": "b4c612ed747b253e04e3132bf8c43194ebb27c5465ca098a03af82737848c5faac83218c71066725f17d56ba96a91a324a7d37b27a5c460a135e85f21f6643ca",
          "sha256": "55419dc73cc29880c02304c2e70e31e1aa00fcc8ca8c224c030c62d46f6bbe4c",
          "sha1": "930c604153550dc24786b080826713c80ecc91ec",
          "md5": "793e35db83f3cc68e1a0a372e8806fd7"
        }
      ]
    }
  ]
}
