{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.3.jar",
          "size": 145555,
          "sha512": "185f1b20daa14c4f787e102fc5d990b6156e230d47c7a22bedb5ee595b2b6b0d4755b17589fc20cc2488eed7fef8000ae9f395260a714335851e1603fd2e93ea",
          "sha256": "ced2e1a19231fbe9c6c75aad20f934b9d868c1d4bb1cd37fdb6c956fd7458ef0",
          "sha1": "9a5acb8d92d67b5f9fa2846b870d13a225c69e8d",
          "md5": "6af6400b06dbc70625db3387c19bb6cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.3.jar",
          "size": 145555,
          "sha512": "185f1b20daa14c4f787e102fc5d990b6156e230d47c7a22bedb5ee595b2b6b0d4755b17589fc20cc2488eed7fef8000ae9f395260a714335851e1603fd2e93ea",
          "sha256": "ced2e1a19231fbe9c6c75aad20f934b9d868c1d4bb1cd37fdb6c956fd7458ef0",
          "sha1": "9a5acb8d92d67b5f9fa2846b870d13a225c69e8d",
          "md5": "6af6400b06dbc70625db3387c19bb6cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 306888,
          "sha512": "62269a8e6d01b5fef2742cfe5c60d496ce8a0f760145eeb842723ace96f5259433aa6c2520a47ff2a583c38b99f7e6487f53025c80062d4e883ac506f493bc59",
          "sha256": "9ca60acdd56bbaba2a06f6afe25b8953638176c77d88e67baa9b8829de659174",
          "sha1": "b8c2a108141adf704d8a071ae75affedbb9918a1",
          "md5": "ec591338a40eaeefeea67c18070233aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 59353,
          "sha512": "799ba87866532e15a2db7b2909c11aefbb67d3a95008d817e1464e55ebdbec16ba734b589254b14aded0f1a62e972ee92905107cd5d0213212500b74f5171941",
          "sha256": "842dbed5fc7fe7935d2ce8f867465689d5530d5e9af2faec40297fca0dea53ec",
          "sha1": "5aef78dfaabec85cc5f4ed7648ecc9b5c9736e83",
          "md5": "86c8a763bafd9cc37439c75954e6882d"
        }
      ]
    }
  ]
}
