{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-rest",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.2.jar",
          "url": "vectorx-web-servlet-rest-24.1.2.jar",
          "size": 45045,
          "sha512": "238a6549dec3247496053ede829b29edc5e17565454b15196f4b1114d4c90067968526b0c0d7ae6fa16104a5cd474f553d104497bbbb8d73d19973e7ed703be7",
          "sha256": "a872fbb8fef463b3b533b1e51aa53e88ccc55db93f555291dcdc5ba3ae11adfa",
          "sha1": "4a53638e39625e29299a26a34f7aa96899093137",
          "md5": "517c83028585dfac23f6574d6487856e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.2.jar",
          "url": "vectorx-web-servlet-rest-24.1.2.jar",
          "size": 45045,
          "sha512": "238a6549dec3247496053ede829b29edc5e17565454b15196f4b1114d4c90067968526b0c0d7ae6fa16104a5cd474f553d104497bbbb8d73d19973e7ed703be7",
          "sha256": "a872fbb8fef463b3b533b1e51aa53e88ccc55db93f555291dcdc5ba3ae11adfa",
          "sha1": "4a53638e39625e29299a26a34f7aa96899093137",
          "md5": "517c83028585dfac23f6574d6487856e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.2-javadoc.jar",
          "url": "vectorx-web-servlet-rest-24.1.2-javadoc.jar",
          "size": 175778,
          "sha512": "ac2342aa611908b0490e061173760045239523d999ab140d5b9c00a02f409ae42957a3c16fa8dacc80c0969f013c0bb377cdfcce093b656bbefec90e8b0b5373",
          "sha256": "332e0b9424d663cda93d0bca3ed01e5edc7a94d89b913f2f702bfa4705602976",
          "sha1": "b02b88b63f758681921605a8a174c62128492cc9",
          "md5": "fce6eac6e68b22d6405cb76cdb5cac07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.2-sources.jar",
          "url": "vectorx-web-servlet-rest-24.1.2-sources.jar",
          "size": 23336,
          "sha512": "54b7182945fe3c392d0ccd09ed676c8c322ef16b51fed89b313970a850575a5cc433ed7ece8198433a22e8141d0a67707623de39f498ca62e428854f5433f960",
          "sha256": "1f205fa779575594f883503214d2110d19b728b13642ab687ea0c163d5ef33da",
          "sha1": "56524ad269e656a758098c238adb24a803aaef28",
          "md5": "7e7d7643e3a8bddf5ae2aeb90328e460"
        }
      ]
    }
  ]
}
