{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.5.jar",
          "size": 110173,
          "sha512": "8235171371f2a4482fdac08bc334237233ff3d8bf5f6120935ad9d3ea32ea319f1070673eb1b73c23f0370bf1280506d7f5ecc2b5aad444181255d805fd59b48",
          "sha256": "31ef8a1eded2521e7f14f2b955452d5ae0205d083017f7775dd2904c11e38a5e",
          "sha1": "b42e2e4da16b1d506f140e20ddb38cae211eb6e2",
          "md5": "3ef8c2bc005f94c6742f381d98357a69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.5.jar",
          "size": 110173,
          "sha512": "8235171371f2a4482fdac08bc334237233ff3d8bf5f6120935ad9d3ea32ea319f1070673eb1b73c23f0370bf1280506d7f5ecc2b5aad444181255d805fd59b48",
          "sha256": "31ef8a1eded2521e7f14f2b955452d5ae0205d083017f7775dd2904c11e38a5e",
          "sha1": "b42e2e4da16b1d506f140e20ddb38cae211eb6e2",
          "md5": "3ef8c2bc005f94c6742f381d98357a69"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 309298,
          "sha512": "df65e13b53cf3974ee5ea2b286216902564586856e1138ab546ea45bd638dfcea2c016d6e2917a4fc1d378f3d2a211beed1c7dee031050bf1bbf2f466594c213",
          "sha256": "6dbb14b0669d1a028b3b0e0bbb98a2e6a98ef41b8cc25c4eba6a2d34ba45ddd3",
          "sha1": "ef6e6e04f8e9ffcc1f6227ca777444da09d44952",
          "md5": "1c3f16bb33de1f5c9ff73aca6dfa474b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 70193,
          "sha512": "30ab5069ae8d550bff2594f1545cd6ee64ceebf804d1aad3cbf167211cef0271cc931623c90eb06adba1ee413c501b81fee5be078d8c86f32b14645cc756af7f",
          "sha256": "bee17297932c155aa71ec9dc5a54fc8f640a074fb3c9b6fa2d033dc91b33fa7d",
          "sha1": "2a33f854837d5b374c4bc9d6d671147e9aaa2da6",
          "md5": "0261491c7fb1de7363b497a231b27aba"
        }
      ]
    }
  ]
}
