{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.3.jar",
          "size": 107373,
          "sha512": "ec92da7e7a093481f8a7b3b92c3f99704ada9c0fbeb678e2f08421baab7574dbb3e79352b924c451904bde9b2e199360d789dfa267195a44afd4f0a55d73b6e7",
          "sha256": "c9228ec4e8cbad4806305e148f0f3291a7e37a27acd83bae6402dd04dede2fab",
          "sha1": "40c30dcb9a06b40ee1548441b9b2d514da6af2be",
          "md5": "1fccd3937757a65d41e999d7638c7fa8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.3.jar",
          "size": 107373,
          "sha512": "ec92da7e7a093481f8a7b3b92c3f99704ada9c0fbeb678e2f08421baab7574dbb3e79352b924c451904bde9b2e199360d789dfa267195a44afd4f0a55d73b6e7",
          "sha256": "c9228ec4e8cbad4806305e148f0f3291a7e37a27acd83bae6402dd04dede2fab",
          "sha1": "40c30dcb9a06b40ee1548441b9b2d514da6af2be",
          "md5": "1fccd3937757a65d41e999d7638c7fa8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 416134,
          "sha512": "0955197de301e5e7d629205478a78e20d7b7ed40df8b39fa0fa7fc8a83dd7900eb36426cbf4acf303af91a3e85d2b9527bddb5a853dec124f38e6f56f6bb78b3",
          "sha256": "fd97a6cd5a1de43b7b8bfc85294582a45371645c7a95832c6004cd83d680237b",
          "sha1": "8cd18cd8db1e9229416ab94a6086747c6945ec9c",
          "md5": "d19a67f5052e7978e51bca7b257135fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 65047,
          "sha512": "a333379e3fdc6c9b8ee679a88d5c9dee78dcc53bd14e437c9bd49ed23e464f294928709c39c684a29079686560ae0681b87b7972a10029d8c58a01169fa262ef",
          "sha256": "d674592da3819bdda9c3b8ea1e281b7133efb5fe6a2f8a44fa464f0008de2397",
          "sha1": "28b48964aeba2e88dc5ce6ff5dd8481045d27d03",
          "md5": "e8a84f3ba8309ea52cdd170d91cb2c4e"
        }
      ]
    }
  ]
}
