{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.1.jar",
          "size": 22993,
          "sha512": "f5b837a46aef0337fbcff007ee89e05fc5eac173b05085c8f38f4692ca51b07cc41c3a3d7905b2c6c3829d022095770ece43259aa2d17b63923a4c3ab8e4ea8d",
          "sha256": "11afacb94a9a8680c7a54bf9faa6f938afc4238ea5e73fde85367e3a18648f62",
          "sha1": "76a399a902384db5386f842c7687ca1a435c09b5",
          "md5": "70676f0d94bbaaa279efa1ef07d4d14e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.1.jar",
          "size": 22993,
          "sha512": "f5b837a46aef0337fbcff007ee89e05fc5eac173b05085c8f38f4692ca51b07cc41c3a3d7905b2c6c3829d022095770ece43259aa2d17b63923a4c3ab8e4ea8d",
          "sha256": "11afacb94a9a8680c7a54bf9faa6f938afc4238ea5e73fde85367e3a18648f62",
          "sha1": "76a399a902384db5386f842c7687ca1a435c09b5",
          "md5": "70676f0d94bbaaa279efa1ef07d4d14e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 128563,
          "sha512": "63435c193ffb9e9055b0bc067115ce241a46a8c72aa1963084c4d8905f7f6e6ebabeb1306b6f888bc8a408e6aa7861e40a12e75fe6b0b3b10b6c6e04e91399c5",
          "sha256": "e5c4c0aea73e7546acb5610228a86697da57a000377e90b9b940d73f4d1f03de",
          "sha1": "693696ef3412670903ab10ad49d32c8b5e0a746a",
          "md5": "13cae9d094d2626b13a7fa13e84c855d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 11406,
          "sha512": "b6446e2481891df6bc2ad0a89fa4c50861dab3ea28f3c069450a9c14e3eb5e81a260f59abf33b2c5190fa888e0ffcf1b01815b8d78d1781fa13cec2281ed98bc",
          "sha256": "7ee241ce919e825b845e80290b4310b4fcc1fc42c333eb6ed2b84dbd7957a89a",
          "sha1": "17296c67ee2cd007597dd750665323df2245deb7",
          "md5": "5b8c4e5c5c0acdba2d511919c57604ab"
        }
      ]
    }
  ]
}
