{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.5.jar",
          "size": 244276,
          "sha512": "b81d02ca273d2f4b346d92591884c9c1eea93a7df0f3b71965a44184649c61464f9cf06e3bde23873aa9c4761af90f0973fc63529cc693acc4deff2391e76dfe",
          "sha256": "d03322b31525e28ca305f333253d1216163b88a62c48676feff1a6b9efbe9942",
          "sha1": "4a73b8576ab13882274f87a2d162fcc57a269ada",
          "md5": "6fa14554a33ed8a88b4dced96822a87d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.5.jar",
          "size": 244276,
          "sha512": "b81d02ca273d2f4b346d92591884c9c1eea93a7df0f3b71965a44184649c61464f9cf06e3bde23873aa9c4761af90f0973fc63529cc693acc4deff2391e76dfe",
          "sha256": "d03322b31525e28ca305f333253d1216163b88a62c48676feff1a6b9efbe9942",
          "sha1": "4a73b8576ab13882274f87a2d162fcc57a269ada",
          "md5": "6fa14554a33ed8a88b4dced96822a87d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 521802,
          "sha512": "1ee4cb888a69d62c6c2955486cf027967384efd528226c5db3ef8b22d640ffc07ca7e2124a9cddd09c7dde7c081cb948eebf82a10d2b45c61994fb74295f43da",
          "sha256": "8c098e051345d3ba9359e6d0b4d54255bdac8ddaad007d480e208d0555da0c40",
          "sha1": "eba2e6e41890859878c1d45ffe0ffcf42fe79ff9",
          "md5": "1318b82e36321d68f0912a08c541d79c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 102673,
          "sha512": "c0d72fa79bf509a9d7f3a47e1ecf7a71af25f93ea046c4a4e695219280af9916b2825b39dc94dcbb26f922825e1eda21b828cf0325d291a119ee9b45e19b89a9",
          "sha256": "a62f0c9fdc30a42e6037582aa77dee063dd4beb4c4da64971a5c542bfddaef0a",
          "sha1": "a104a885f569ad2ef502f689848f0cad09fef8ab",
          "md5": "672ab4365298a5a3a891bb96973dc118"
        }
      ]
    }
  ]
}
