{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.5.jar",
          "size": 244188,
          "sha512": "803b718fc230ee19fbad97b295f235f3bc41135227faaf1c5d651de63a03d760addf92e8e092cf772c428d4cca1f9b9a40d7e0cd19f042a8ab3875d57fcc9973",
          "sha256": "569109a015b239fa7c5383b03c4aa4eb3ba715fbc4bbc13925e608b4c1900c7e",
          "sha1": "2501dd2576504931fed424df37f2921425ac6bd8",
          "md5": "7368546176b8ab6335c69fd940b292a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.5.jar",
          "size": 244188,
          "sha512": "803b718fc230ee19fbad97b295f235f3bc41135227faaf1c5d651de63a03d760addf92e8e092cf772c428d4cca1f9b9a40d7e0cd19f042a8ab3875d57fcc9973",
          "sha256": "569109a015b239fa7c5383b03c4aa4eb3ba715fbc4bbc13925e608b4c1900c7e",
          "sha1": "2501dd2576504931fed424df37f2921425ac6bd8",
          "md5": "7368546176b8ab6335c69fd940b292a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 524004,
          "sha512": "d8391e739f40b05db31cf3cb94f44720a4f1a5ae61ce847e90b976367bcdb35fbec94ed70e106547c35ad647106bb644167721d4d2162a5a971258abed18e873",
          "sha256": "9d118b3b24b284e5cfcfbd0d1f5a767874dc4b854016223058f9852854f77d44",
          "sha1": "ee68c0a44c155e7582c5970d6ba696fca89e4005",
          "md5": "fab511d335e118b55287651a2f02cbaf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 101772,
          "sha512": "7904c25aff9e2d88ecaf13ef8b5be466714809dcbd6a546f3706a55243d2a5b99823d30bdbb328d0809570d39695ed80b94798f4007d5f3f57292078e0993500",
          "sha256": "285e4f3fe3924ee7394ad9e12616a19751ed358ea823645915ec10480535107c",
          "sha1": "b92b4c5a0d7e16decd73bfef2393e14a55d56e0c",
          "md5": "3ae4e756c81c1a14141baa7d13a7448e"
        }
      ]
    }
  ]
}
