{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.2.jar",
          "url": "vectorx-data-redis-24.1.2.jar",
          "size": 9718,
          "sha512": "6ccaa0db095651ca23ca58944642daf800535a2135220e4c4baf4b2340cd60a417575e2c0fa6ae71a580499d3b7a1a1f38b361a2039b2c671171cdb9be0f2f3a",
          "sha256": "7d1908ab8649671dee99d844a10cd73e5509afc1fe1c7f0da98933f3b880c922",
          "sha1": "e7bc6124583bd6d21256c9f0266134d0712f7beb",
          "md5": "b8c05e54169b06152c412ed4872a5c41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.2.jar",
          "url": "vectorx-data-redis-24.1.2.jar",
          "size": 9718,
          "sha512": "6ccaa0db095651ca23ca58944642daf800535a2135220e4c4baf4b2340cd60a417575e2c0fa6ae71a580499d3b7a1a1f38b361a2039b2c671171cdb9be0f2f3a",
          "sha256": "7d1908ab8649671dee99d844a10cd73e5509afc1fe1c7f0da98933f3b880c922",
          "sha1": "e7bc6124583bd6d21256c9f0266134d0712f7beb",
          "md5": "b8c05e54169b06152c412ed4872a5c41"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.2-javadoc.jar",
          "url": "vectorx-data-redis-24.1.2-javadoc.jar",
          "size": 93490,
          "sha512": "8a9c40a64b13f797195bbdb6e845043899f3cb46f1f7303bf7f748e7061c5974bc711e8ee22cb855db9a26da87fcc8f19dd7b701856aae1c821e49eaad44c10e",
          "sha256": "e8435fe79375e356cf83a9e52910e9bd264843fcb2bb806dd4867e0c1ade9dfe",
          "sha1": "543d59f441de5211d3d2da7fe3148981fec70a79",
          "md5": "31cd4b3adc29999df0503e74e02edb41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.2-sources.jar",
          "url": "vectorx-data-redis-24.1.2-sources.jar",
          "size": 3360,
          "sha512": "324f58e7f5caa994978ef1ade990182da2e9ee4e9f7d8f7d7284c63802a6fafc66858962bf95e14188e71619728ad8cb8765bbc845c3053a30cc5dffe2a0c56e",
          "sha256": "a4af8f090371cc1a5ba896461e354d14a1d1fcf4c6d64b9fca999b4f91435695",
          "sha1": "66a9ab354b55dc646a659a5536d2e0d864bcac64",
          "md5": "e776016bf4433840a0a93722902b00aa"
        }
      ]
    }
  ]
}
