{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.4.jar",
          "size": 9737,
          "sha512": "48ffa06726e19d0a5acf6541ff097fafb38e697fce1d7f885c2db5f980cba9d147f1cbad32bd181d9f33b05e01a6a1b17867ec2b91b0bd2945e6f39f1fc4f3f9",
          "sha256": "da64464a110fe72cb3a6cea494e33deb7b4f0e65a0dd8206e3d2345e0c01b375",
          "sha1": "361a0166ffed7075a818fffb6abdc3f7e980141f",
          "md5": "b0e9744135788b8fe812848f6e0c34ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.4.jar",
          "size": 9737,
          "sha512": "48ffa06726e19d0a5acf6541ff097fafb38e697fce1d7f885c2db5f980cba9d147f1cbad32bd181d9f33b05e01a6a1b17867ec2b91b0bd2945e6f39f1fc4f3f9",
          "sha256": "da64464a110fe72cb3a6cea494e33deb7b4f0e65a0dd8206e3d2345e0c01b375",
          "sha1": "361a0166ffed7075a818fffb6abdc3f7e980141f",
          "md5": "b0e9744135788b8fe812848f6e0c34ad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 97296,
          "sha512": "7da388894675d8004b52a067e05633a122e6a64f0da7afcbda15711550d861abcad63c839aa22032aeb2972612bc798733fc70736f0b01c54c9d3ec42676b9fe",
          "sha256": "d920245bf9fb0b834e93eea72b37516c02d525b37bd3ca0975f340928e6f378e",
          "sha1": "4b0f5c5d6d57abcb93d0922cee1c14d88a53880c",
          "md5": "8f42301030052a2f6f36871d0deb614a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 3340,
          "sha512": "49fb690596c53775dd08da74dc0a39f0e6158a8e01f97eec5f03f61ac6f4f96c23c83da9adb7f1e062be1b0a638d5ca1b6eecabb03a28ab3835eccc06498eff2",
          "sha256": "9ebe80af990a27706b0d995e220a35909d6cb0014773aa9e74e34d3d44816612",
          "sha1": "0c27805e22ad8c3b72c2ce98a3e045d97ea55c37",
          "md5": "0d5d65a3818db675e59d4d1ee1b4380e"
        }
      ]
    }
  ]
}
