{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.3.jar",
          "size": 184887,
          "sha512": "df976767fe40de7dac2c7c107b74e3d4a143b4d9e9fb4b968bdbbd63feb972241c86d1fc2a823ce2a16bd85e4a0b01e5d48d719dd6be1c3e33917d12304a8a28",
          "sha256": "d421889d81bc138cfb5d010588f7372e63bc99cfe286253234505aff0c7c899f",
          "sha1": "2e0df16dec5d3ad46f187cbee5df6f62c82a8cda",
          "md5": "955568d9d4700d177bee5165a89184ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.3.jar",
          "size": 184887,
          "sha512": "df976767fe40de7dac2c7c107b74e3d4a143b4d9e9fb4b968bdbbd63feb972241c86d1fc2a823ce2a16bd85e4a0b01e5d48d719dd6be1c3e33917d12304a8a28",
          "sha256": "d421889d81bc138cfb5d010588f7372e63bc99cfe286253234505aff0c7c899f",
          "sha1": "2e0df16dec5d3ad46f187cbee5df6f62c82a8cda",
          "md5": "955568d9d4700d177bee5165a89184ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 276934,
          "sha512": "72b6337a1d41b963b7011f37f79a4fd5a5d9625955bcb2ba30503ae2ba8f64dcbe86bd4b8ac904c7f33ae279d0da69fe425141c95b960b68f871663bf9615b97",
          "sha256": "1f379f5e05d1bee2022ceba6cd563cfc8dcd46e510a0dfddf9667b15a99698a1",
          "sha1": "a8389a558f426125acd252585e295d1c1b19e1ed",
          "md5": "ab5b47f752d42c0364cdd57b0b0ec834"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 68978,
          "sha512": "124e237d7a63033054750f0459c154c1bf4344039df6643f2d7267709d86f3ff973bcfdaca861016adf3259adc901e5f32463d48efe97f2730ca37957a78dcff",
          "sha256": "5ac2a9f28bf440fcef3d91ff153d1ae1a464b765b7c3f4074454954dd1fff31b",
          "sha1": "8ea8f1cdce280dd1b5f56edefaa8f489f784be3a",
          "md5": "c03acc0d11201563248afeff332de63c"
        }
      ]
    }
  ]
}
