{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.4.jar",
          "size": 244187,
          "sha512": "371fd259b3b6c0e20115b9c589279b68fa259e04a64c91bb240cd5a0ce00793772e19c514c85e4a138a425fb51d91bf11b55e51eae026c9a870b718ff6818caa",
          "sha256": "43e09c8d7acdb362fc20e20241769a5db607215840e144b41897774686f0daa8",
          "sha1": "20153ce5cb980b5649f7e6a7bf6fe556116161d3",
          "md5": "2fc29394947dc376eca2765eeec628b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.4.jar",
          "size": 244187,
          "sha512": "371fd259b3b6c0e20115b9c589279b68fa259e04a64c91bb240cd5a0ce00793772e19c514c85e4a138a425fb51d91bf11b55e51eae026c9a870b718ff6818caa",
          "sha256": "43e09c8d7acdb362fc20e20241769a5db607215840e144b41897774686f0daa8",
          "sha1": "20153ce5cb980b5649f7e6a7bf6fe556116161d3",
          "md5": "2fc29394947dc376eca2765eeec628b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 523963,
          "sha512": "87cfed271329033939dacd18a44a62dcb782b15df46de4b913350142c7b3174988c184bd24c8865ce4b19dd118b4ee75fc8009e78233e993d5abc35d4f06d193",
          "sha256": "f832c42ad81e3668b1327c5a8ee88278703db09775d495a14717ef08d2c2dd9d",
          "sha1": "4113cf4ca2860cb52b9137cbc38155a79a6e777a",
          "md5": "0a11bb57a619134ddb01ebd691cad202"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 101772,
          "sha512": "6860d33f37bfaf47803393c14b0720de0fb69d078834c9ea42aa94ce717f695583ea2285892de91b7da0a221b2412806497e52f5e31b9b62afa1ac0a3ce177f8",
          "sha256": "7c9c27249be817fcf3d40d46b140fb8d444ed968591c7d73183b0a92c471aa28",
          "sha1": "2cb2d679d3b56441d709e337ae13a101ed8a44c5",
          "md5": "b5dbe8b0c01b72586fd3f9b11c0c5646"
        }
      ]
    }
  ]
}
