{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-web-socket-24.1.8-SNAPSHOT.2.jar",
          "size": 22994,
          "sha512": "a988446815f970c47fe1bf2d8f6fad33c91e06342b421947251d4dffd12d3c4a5e7f80ed7f4b77a89e1288788b62cdc770e94749f672b7dccae79eb8d9dcb47a",
          "sha256": "9727cff6f1a25aba95364f5b137c06fe3f305bb6fb08dfafbbd407fcda9fb85a",
          "sha1": "2710a31392beb08cebc5d84876900e47d1baf192",
          "md5": "b2ffb84571ce05f99f091df1e1a5da97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-web-socket-24.1.8-SNAPSHOT.2.jar",
          "size": 22994,
          "sha512": "a988446815f970c47fe1bf2d8f6fad33c91e06342b421947251d4dffd12d3c4a5e7f80ed7f4b77a89e1288788b62cdc770e94749f672b7dccae79eb8d9dcb47a",
          "sha256": "9727cff6f1a25aba95364f5b137c06fe3f305bb6fb08dfafbbd407fcda9fb85a",
          "sha1": "2710a31392beb08cebc5d84876900e47d1baf192",
          "md5": "b2ffb84571ce05f99f091df1e1a5da97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-web-socket-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 128564,
          "sha512": "cde9672b402b6df697e62c0e9f809450d0c40122a06029bbc091a1e4e5a029b990b15f882e37f08651cb34552328efeea8c1033efb197b65a883b06eea4e495b",
          "sha256": "58402f1b077723ca990b6b58debfe5c1646963ac396a5a3ab5ffd86118d5d04a",
          "sha1": "2ac3811babd3cb521d23ca74d9e09007e7fd08ce",
          "md5": "dc3f896f1fe751d693e408c7be281100"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-web-socket-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 11406,
          "sha512": "fb8306954919f97268b1e4dbeb564d2541bf7d2cb3512cae1e06d3fff7b077aa06a0da53bcd4807877eb185605eacc772a4c29b8500d36c140ad640151e08e33",
          "sha256": "b7b031c61b877b170e2bdada832608213299b34c732e3083d190eca2d038abdc",
          "sha1": "fb092f288cec71609f838f02145e14b1e2d90928",
          "md5": "94613e4047233689ac67562a2dbfe9a5"
        }
      ]
    }
  ]
}
