{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.2.jar",
          "url": "vectorx-batch-24.1.2.jar",
          "size": 244502,
          "sha512": "8cdaa06c6e19f8674277f97557afb732ffbddd27068b081b4278723dc39d7478d11e46205b3f5bd1573e18f032b88ce9aa68bdd1f6362a1aae47711c9dbe83e9",
          "sha256": "3380a0743712a015a338ef44d294b3971783c0dff394023f18196c07741ab947",
          "sha1": "73904bfc6a594cc019a77a3aa8937e57b329c900",
          "md5": "a4b9c2d2d515779568dde6fd506c501d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.2.jar",
          "url": "vectorx-batch-24.1.2.jar",
          "size": 244502,
          "sha512": "8cdaa06c6e19f8674277f97557afb732ffbddd27068b081b4278723dc39d7478d11e46205b3f5bd1573e18f032b88ce9aa68bdd1f6362a1aae47711c9dbe83e9",
          "sha256": "3380a0743712a015a338ef44d294b3971783c0dff394023f18196c07741ab947",
          "sha1": "73904bfc6a594cc019a77a3aa8937e57b329c900",
          "md5": "a4b9c2d2d515779568dde6fd506c501d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.2-javadoc.jar",
          "url": "vectorx-batch-24.1.2-javadoc.jar",
          "size": 520118,
          "sha512": "2a7f40ebefa98dd04ba12f8baca38710a6dc9937b31c9cfb5156968a5aea587e835edaf73054a968cca3d5e865775a2c4069f256b21c44e679fa7fb4301dec21",
          "sha256": "ad10b91ebe7f565a03b2fc00a6f14cc2bf4f7afeee284583c12dbda7c284c44a",
          "sha1": "f6af173c1c5f80922ccddf414ca44615164a3faa",
          "md5": "5f6fcaf6c2ce8d5567664cec1d90fa3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.2-sources.jar",
          "url": "vectorx-batch-24.1.2-sources.jar",
          "size": 102923,
          "sha512": "04f47b3f556610f68f8c16e4ff026b0c74e5e7842ee5503a4fb94027f09744efe5a2e45ac4682a518b5223f8889718f45e0a517df80fcf2e0415743b5ae783e7",
          "sha256": "4b998580ecd93ecb8ed60cbb03e9e4bead44e49f8398507a177f0376f142eed9",
          "sha1": "720f2e9a785273b8f7948305bf68f483002ff4e1",
          "md5": "021c107183c7e84a090081c36f449da4"
        }
      ]
    }
  ]
}
