{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.4.jar",
          "size": 2711,
          "sha512": "79d252464d3944de0209f70650a64e47ebc8ea0f3deff98a904a2501137e1195cb256869b5ebb976a6abf7e636d4b95342d91641d637c290b4266505bfc6b8a0",
          "sha256": "d0c3dfc3ef713e35c52c46f9687cf2fe325e55be31e54d5af361b5149da01447",
          "sha1": "fb994126ef05b3e697117ac751997077d5eeb958",
          "md5": "c30f5453d88caab4211cb78ebb3597c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.4.jar",
          "size": 2711,
          "sha512": "79d252464d3944de0209f70650a64e47ebc8ea0f3deff98a904a2501137e1195cb256869b5ebb976a6abf7e636d4b95342d91641d637c290b4266505bfc6b8a0",
          "sha256": "d0c3dfc3ef713e35c52c46f9687cf2fe325e55be31e54d5af361b5149da01447",
          "sha1": "fb994126ef05b3e697117ac751997077d5eeb958",
          "md5": "c30f5453d88caab4211cb78ebb3597c7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 74113,
          "sha512": "cbddd9882e5f0182917b609752095b45b83d50d346a358dbe1f85e288277d8b7fd6802b986bae4420e2d0199a5264a352d11ca2a4cd1048205d71bc1344fc88e",
          "sha256": "8dbdbfe781bf7efadcc23d2e5a9d6f0c34821153abcc2cb178e59a6337afc2ab",
          "sha1": "809615c788991ef944ee94838b45f192094824dc",
          "md5": "ef06c3c7f52c3466f82d2fe843cf02b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 1180,
          "sha512": "f471f9ab813a7c61ae6ba1c326d54010e5b1f14d858da12fd87f7ad9a692a4194b02b8992008d86d22899c027090e2c5cbe63029ff84757f961e28038f82f244",
          "sha256": "40ba6d0b1371cbbbf8fa69061ad0906be34e59afbe3fd9094bff344551f79a04",
          "sha1": "e2b9cb612a722c4bc4c10da6a8239c881a2e732a",
          "md5": "16920e6240cf36ba0c778c576d7e3f62"
        }
      ]
    }
  ]
}
