{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.5.jar",
          "url": "vectorx-net-24.1.5.jar",
          "size": 29717,
          "sha512": "5fc0262dd7720c27b0266a5071ee1da24584f6822085b8e1280f1c1dc359f13693b94752ba94c88dc270972837601ac00097ce199a4277c42ffde9e84cf9721b",
          "sha256": "9eb342f15abce8f79a4dfa0db914acdd2537f062e4f8329c521663114194e2dc",
          "sha1": "86128a160bd8507ab270de442b0d22b1bc87b97d",
          "md5": "5d82e738fd42ed2a479673a683ed7b34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.5.jar",
          "url": "vectorx-net-24.1.5.jar",
          "size": 29717,
          "sha512": "5fc0262dd7720c27b0266a5071ee1da24584f6822085b8e1280f1c1dc359f13693b94752ba94c88dc270972837601ac00097ce199a4277c42ffde9e84cf9721b",
          "sha256": "9eb342f15abce8f79a4dfa0db914acdd2537f062e4f8329c521663114194e2dc",
          "sha1": "86128a160bd8507ab270de442b0d22b1bc87b97d",
          "md5": "5d82e738fd42ed2a479673a683ed7b34"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.5-javadoc.jar",
          "url": "vectorx-net-24.1.5-javadoc.jar",
          "size": 128287,
          "sha512": "4f613ccba28d5deca89de2a58ffd8579661e5871e28d62f7a05793e33465d7940a266ba59837aae6c5238cc035858ed62c28674da17ac45efd30de39101d80a2",
          "sha256": "a01b2ad84a4a3e1dc9ae41b74746378c7e64f9dd918efc1f98c606eb46b4212c",
          "sha1": "64a3df715559093a18ec720500f45278a75419cf",
          "md5": "e9b7461d1d0dfb418dd9af1f9eda7e1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.5-sources.jar",
          "url": "vectorx-net-24.1.5-sources.jar",
          "size": 10137,
          "sha512": "0943a5514e5374b75c1df57c99a07c5420ccbf14747f7574c2dc5ba4723760d007204576da73f73d03a6c9fbb1063fcc0b432ff195c8d028ca7da9700d2df396",
          "sha256": "aa16125683c2bf55f30a37a86196d7ff3d0439a1507de6b65bdc3f59435847e7",
          "sha1": "308c737bba58536399ef956f921eae00677575fb",
          "md5": "edc877dd2a4087638f2577baa759bb5b"
        }
      ]
    }
  ]
}
