{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.5.jar",
          "size": 9737,
          "sha512": "c1ca78136164bd2d7cd0f74bc4123d9e6647c136900d721ae2801afa57d32e77f107aa42f256c3ef1b9c683e5c75c44677a2d4883db61cc2b0bf230f65fd99f1",
          "sha256": "2d473783876e0e70803f44a03d24ae63f93fed4095d50efd187811599cd64bf6",
          "sha1": "da5d179e1007d7964d4f9a26bba6ca70d19264fc",
          "md5": "51e027cc564103e555539e93fb6d0036"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.5.jar",
          "size": 9737,
          "sha512": "c1ca78136164bd2d7cd0f74bc4123d9e6647c136900d721ae2801afa57d32e77f107aa42f256c3ef1b9c683e5c75c44677a2d4883db61cc2b0bf230f65fd99f1",
          "sha256": "2d473783876e0e70803f44a03d24ae63f93fed4095d50efd187811599cd64bf6",
          "sha1": "da5d179e1007d7964d4f9a26bba6ca70d19264fc",
          "md5": "51e027cc564103e555539e93fb6d0036"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 97294,
          "sha512": "ca8d1e054df12ab95069d26207a6450c5e64ac47245bebc90682d417418b64a0d5940a284a982e06967bcb0755bec021ac9ffd60ba45324cafa804382ebf1a7b",
          "sha256": "8291954616821192d2a23829c2f1379e98c936acc8be53b783a366e397d56d54",
          "sha1": "b081d0838cce1800d0137f2d4a82f65a4f6fe77e",
          "md5": "84323a8a6e7703d73462d5c686b47d29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 3340,
          "sha512": "dfa043e187ddff46eeba6c0ab498761874cf264ac117e055ec7fcdbb1418524c499b59a803d5c503d4368442a5205dd72f018e541d9ea0d569182ccd8c886c9e",
          "sha256": "d002556be6d8022e1c2464284cf626a6fe4d9a872548226f1bc82f8556ac78f5",
          "sha1": "b41faeaab76a3b4f8022cb8d745b80e3839526f0",
          "md5": "f98141f3f7044a78a37b19ae9cc5afdc"
        }
      ]
    }
  ]
}
