{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-eureka-server",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-server",
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-server-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-cloud-eureka-server-24.1.8-SNAPSHOT.3.jar",
          "size": 3042,
          "sha512": "0efd09ab48998e651effc83a37e8981a2492fb941760d4850bccf25aa192820e75dd78b6d99e78cf7f8dca29548c098144e42c657f66f8110b6d38ec6efe89fd",
          "sha256": "8114cb6f9b951afdadf934854da1ddb7af89c9cce96672279eb6269a5592ecbb",
          "sha1": "5b592b1a9f47574ade68bd26ddcacfa937cc3122",
          "md5": "5dedfe8fd47c21a416db103c4d8aad96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-server",
          "excludes": [
            {
              "group": "com.amazonaws",
              "module": "jmespath-java"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-ec2"
            },
            {
              "group": "software.amazon.ion",
              "module": "ion-java"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-server-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-cloud-eureka-server-24.1.8-SNAPSHOT.3.jar",
          "size": 3042,
          "sha512": "0efd09ab48998e651effc83a37e8981a2492fb941760d4850bccf25aa192820e75dd78b6d99e78cf7f8dca29548c098144e42c657f66f8110b6d38ec6efe89fd",
          "sha256": "8114cb6f9b951afdadf934854da1ddb7af89c9cce96672279eb6269a5592ecbb",
          "sha1": "5b592b1a9f47574ade68bd26ddcacfa937cc3122",
          "md5": "5dedfe8fd47c21a416db103c4d8aad96"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-server-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-cloud-eureka-server-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 70866,
          "sha512": "df3f70795a81b936d0ad5c18a058c9e8a4c22116a3f9933e17c98cbd31862accf12e4aa414d8fe751ad84076c0416823690e6a1c9cf11dad77cf5f0caae2b9ca",
          "sha256": "a3cbd33359edbe1a1005ddbfb44590c7cd33688e4d2786961a96a1701effb3bd",
          "sha1": "d30d53478d76740e564cd320f397c8006462711d",
          "md5": "100f35b0ddd0958348d44f2eba14f0b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-server-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-cloud-eureka-server-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 1454,
          "sha512": "c88967ba17cd508aca689d59a157be79eaf0ab27979dc7b08ae4f968fe49f8716fe80140e9418aab722003895ca58133cb92d7e14a58fcba6302c7501d435f7a",
          "sha256": "b766d2004f618b602030a961d5b4ca1737db8b5969c22deee4a171a34891534c",
          "sha1": "62ae4643f8c23d87702e3a2bf3407d78fdd25540",
          "md5": "2760d987e6083c02d39d51d32393e2b5"
        }
      ]
    }
  ]
}
