{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-data-mybatis-24.1.8-SNAPSHOT.5.jar",
          "size": 110180,
          "sha512": "abb6f87b7cfd193912d8a66f9df0b8d2c4ec48a4ae963d203d47a75adb9b6dfe066abe958f30d20395834734795bc911bc524f8b2bf492570fecdd4ffa226267",
          "sha256": "39c74e5441f68acf4ef1de5da7cd27b5d985b02ad07a5db722ea083d066f4e30",
          "sha1": "0565d8f622d612743ba5e19798f8cb4954d8ea57",
          "md5": "3d1125d6c11efe4bd43b45f7ca203d0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-data-mybatis-24.1.8-SNAPSHOT.5.jar",
          "size": 110180,
          "sha512": "abb6f87b7cfd193912d8a66f9df0b8d2c4ec48a4ae963d203d47a75adb9b6dfe066abe958f30d20395834734795bc911bc524f8b2bf492570fecdd4ffa226267",
          "sha256": "39c74e5441f68acf4ef1de5da7cd27b5d985b02ad07a5db722ea083d066f4e30",
          "sha1": "0565d8f622d612743ba5e19798f8cb4954d8ea57",
          "md5": "3d1125d6c11efe4bd43b45f7ca203d0d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 306432,
          "sha512": "d77003b65a33a643d2a4dd10a24d709686e8b5c41e766edbbcc3a03c8f4d4cd3614d8a2c4ef0195a1f5b3bc23e52dfc9363bda21ad78cf8de90a9d89062afba9",
          "sha256": "af8bc9103dc87d7efda6a428f3e95f2f657e0b6e8e0366f22e5a0aa229d4d2fc",
          "sha1": "3d87509920854d473b350b4318a3290b6191ec1d",
          "md5": "9c5be4d7d49d42540079e9d26dd80678"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-data-mybatis-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 70735,
          "sha512": "3793ea45ff59de89b1bc19b2a35cf420c866018b1a857efce13b8aab50061ef42a1c6c6fb5b8ed1b2b5e6a7687e366a9d2c09ea86256124f1a11cd69bc9f7889",
          "sha256": "a5a8a1b17681999c3a57fc48dbc7e6d6d38a6ca56b236c12f68f9df4cfe59ddf",
          "sha1": "44add7b3a71e4e5a268a48ca20fb1429c8ee4b93",
          "md5": "3e181876363dbf841a156cb400fecf57"
        }
      ]
    }
  ]
}
