{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.4.jar",
          "size": 100136,
          "sha512": "0d7caf6cfa64a69efc10faf3c1594cbadaed351c7be0434da981d95e0eff7d0d3c596d27d11456e8cd49c7fa1cd49fcb006cfdd29b90977320e4d0c12a93c2eb",
          "sha256": "f6c81117eb8970ea6ed8f4e9a546a638b9c62e2a4faed125048113bed9066622",
          "sha1": "6c997c6138ddcf88b2611a34426f9fc82c0f150f",
          "md5": "bc570aaf719f6dbc4ff5999de3fad03b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.4.jar",
          "size": 100136,
          "sha512": "0d7caf6cfa64a69efc10faf3c1594cbadaed351c7be0434da981d95e0eff7d0d3c596d27d11456e8cd49c7fa1cd49fcb006cfdd29b90977320e4d0c12a93c2eb",
          "sha256": "f6c81117eb8970ea6ed8f4e9a546a638b9c62e2a4faed125048113bed9066622",
          "sha1": "6c997c6138ddcf88b2611a34426f9fc82c0f150f",
          "md5": "bc570aaf719f6dbc4ff5999de3fad03b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 301938,
          "sha512": "08650060eea314e987f99c2845bd1e609f4bda5b560eb80941caa0e55261be9a3a394a6e317a406d86faf72fbdc44abc4d7319b2cd6f387eba64d40e87d632a0",
          "sha256": "91e9bf38300a485cc00d3606bbc1dca14d6f934ef0cc705e90443089938c7139",
          "sha1": "5c5a78cacb5cb9b8ad099607202fb3826bf6d05f",
          "md5": "4b419ccc8a47982eccc34888eddaff8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 50820,
          "sha512": "d121786d8929737c14cb0496815d890b6824f9b894c6481faf4363bf0d726c4e08806efe3cee09b9c1dab53edffb1578838eba9b269c45227d9b7d4322662f9a",
          "sha256": "0292b46e61f934730ad1aed35a3bdb60abb3ef1654b84f8cc82a0509d4b2cc83",
          "sha1": "af2f5ac9cedc678913f27eff55365271582838b9",
          "md5": "242b7c55dec8c3568b06ee868ad10960"
        }
      ]
    }
  ]
}
