{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.9.jar",
          "size": 9740,
          "sha512": "8ec8f81c3bc2995366544116a48bb86b43ce6e4fde227a19ffc6e2a4953ab03b9248c6ceae9ba9e4c301a444cfd70d6e65e75176fcb8a31516a06a0efc71b1d0",
          "sha256": "f34a1526e36d010dc657a4943b861c33a1a4f6cda8e64e397a0409afad74fb87",
          "sha1": "35c5067c67ff8a83e26c4013b7d36d4fecb692c6",
          "md5": "80853ee1f007e9611dcd0b92789a3ceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.9.jar",
          "size": 9740,
          "sha512": "8ec8f81c3bc2995366544116a48bb86b43ce6e4fde227a19ffc6e2a4953ab03b9248c6ceae9ba9e4c301a444cfd70d6e65e75176fcb8a31516a06a0efc71b1d0",
          "sha256": "f34a1526e36d010dc657a4943b861c33a1a4f6cda8e64e397a0409afad74fb87",
          "sha1": "35c5067c67ff8a83e26c4013b7d36d4fecb692c6",
          "md5": "80853ee1f007e9611dcd0b92789a3ceb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 93721,
          "sha512": "4ff560e98bc027961127475f1827c0b89a5f35b201b4512272c025f32cd57ef6fff1378cffbdcaef2e958706bb9975da5881ca41b2fc89b3a1703d7805cb4768",
          "sha256": "8915dbac19f4100ecd775746c79209879a67f89fbe9e756086628cafe423d1d2",
          "sha1": "e15400b713a76b8c4829995a36c28aa49289bac6",
          "md5": "756828f6ed67ec2665c12dcc78dac4b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 3360,
          "sha512": "fd11963ddc1d5f59522570f6b9d1ac1fb99d36d5ccaf9e4366785944ab212220b439bee5cb4041ba75451068a97344a9cf6e0a523c1988fe8674ffa938bd9cf2",
          "sha256": "201890c4b99c5a7efbe16cb88b3f07b1e87c733d92ca938ff427d1654d56e232",
          "sha1": "bb51ec9b97849ce6d2bbe3b1a6da37fe876f75bd",
          "md5": "c1a12b4838d57e217a27e44e41062e4b"
        }
      ]
    }
  ]
}
