{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-data-redis-24.1.8-SNAPSHOT.5.jar",
          "size": 9740,
          "sha512": "037152da53aebc3b60fdb6c725a4742c4473a87e37c27328d50bcc46469d71da55dfc62596dbc71653a1018f50d061c7f27a45ac64107a97e722b9c99bf2840c",
          "sha256": "9852b33520347c81f9970d5e0585ec778203af9d2870317433be80b34f3b148c",
          "sha1": "952c04d9e3ffd079806cee0c605b8ee65f512068",
          "md5": "6ccc565c6861392da1647ea27a6cdbed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-data-redis-24.1.8-SNAPSHOT.5.jar",
          "size": 9740,
          "sha512": "037152da53aebc3b60fdb6c725a4742c4473a87e37c27328d50bcc46469d71da55dfc62596dbc71653a1018f50d061c7f27a45ac64107a97e722b9c99bf2840c",
          "sha256": "9852b33520347c81f9970d5e0585ec778203af9d2870317433be80b34f3b148c",
          "sha1": "952c04d9e3ffd079806cee0c605b8ee65f512068",
          "md5": "6ccc565c6861392da1647ea27a6cdbed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-data-redis-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 93720,
          "sha512": "392b30e126acb21f0808b8e634e195e232a08fc7e1ad7383d8662f5420f8ee139652ac2f498c0eef3fe66da5d4494c69505768e559ef628443ee30f26ebda06c",
          "sha256": "28a966547789779739cd3d40e2d1db85513603cbedb51f63ecb454c6758c0861",
          "sha1": "9af947820d65e942be626c030aab4290f7bcc0ed",
          "md5": "b93d9c20064e9693e160843a468ee816"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-data-redis-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 3360,
          "sha512": "afca67e81dcbd32103271357a325dee260555b026cfa391a416e453f8cc6a0a26ae80227890aa9aab97a7faba64e2837ba9376677d56791d3f3b6135c4ba0a02",
          "sha256": "00270735472b7b9f016e62f26d56dbe56a29de54b5981f87fdbd6bd466b0c884",
          "sha1": "f0aa656566879ad06500ef33a35b3636ddec2017",
          "md5": "557406668903d00fd4d51eef92481bfc"
        }
      ]
    }
  ]
}
