{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.9.jar",
          "size": 2714,
          "sha512": "3ecf5f7427b1e1a248948f0c54097036511665e77c4b320217901fa174eefd119970079f4c69eab584c8c58f4e7120fdfdad78c1a2a830e75e8fe6c81ae83259",
          "sha256": "1c708469655c316491508ef0b48919574989e9c925701928816b83d1f19e9de8",
          "sha1": "a77f8768e0330e46367cee4726b5c2088a9f2e47",
          "md5": "dee25c288e92e2a5482d73f5bc1ac541"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.9.jar",
          "size": 2714,
          "sha512": "3ecf5f7427b1e1a248948f0c54097036511665e77c4b320217901fa174eefd119970079f4c69eab584c8c58f4e7120fdfdad78c1a2a830e75e8fe6c81ae83259",
          "sha256": "1c708469655c316491508ef0b48919574989e9c925701928816b83d1f19e9de8",
          "sha1": "a77f8768e0330e46367cee4726b5c2088a9f2e47",
          "md5": "dee25c288e92e2a5482d73f5bc1ac541"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 70440,
          "sha512": "6f26ba3c688ffe940b20ec98dfb4d056fc7d09ef19019e8f094221e604d657662e8a88a5c8a2efc17a16f228a69aa1b89ab63c8048b3dcd45e35c44b39f4a05f",
          "sha256": "6d5027eba2196e3bbcf2575c279c4d45b8dfcb7fa5157563b6c69372fe705f3f",
          "sha1": "7d430e51ad39b0d52e0fb3ae802bd97b571af038",
          "md5": "274f13c02f40d310193b78f143be155f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 1184,
          "sha512": "46ad77e2e9c6f6d213262bd6cba11a2d5de08f81130279c140da359eeccbcc0b67ab6e225429c4b194cf275afda359573b1fa1dfb03e0eca7528772cf66aca49",
          "sha256": "f9f147d91cbfbbfb524b7658f55dcd09d269e35feff537d6573f0110059920b7",
          "sha1": "a7815b53cb5266050b1df5f36a02d773808c0435",
          "md5": "ad667ef88afb8d63daa9754ee118cb66"
        }
      ]
    }
  ]
}
