{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-mybatis",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-mybatis-24.1.7.jar",
          "url": "vectorx-starter-mybatis-24.1.7.jar",
          "size": 261,
          "sha512": "4573224cd6624519358c43ce4c0fa44bb0beac68cca76bba4ddb2e8be054edec5729531a209e10256a492810297e4d8eeb807a7e30d613e91dc5827bc04388fc",
          "sha256": "e1ac76bdfec3cae6bdf0683b784cf095979d05cac8f46cc5e68ac3b519e94c0f",
          "sha1": "5133ba91bad6e22caed4bd6100971ccc45ab806f",
          "md5": "19f1e5ebb0ef325b4ba4818e2cd85ddc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-mybatis-24.1.7.jar",
          "url": "vectorx-starter-mybatis-24.1.7.jar",
          "size": 261,
          "sha512": "4573224cd6624519358c43ce4c0fa44bb0beac68cca76bba4ddb2e8be054edec5729531a209e10256a492810297e4d8eeb807a7e30d613e91dc5827bc04388fc",
          "sha256": "e1ac76bdfec3cae6bdf0683b784cf095979d05cac8f46cc5e68ac3b519e94c0f",
          "sha1": "5133ba91bad6e22caed4bd6100971ccc45ab806f",
          "md5": "19f1e5ebb0ef325b4ba4818e2cd85ddc"
        }
      ]
    }
  ]
}
