{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.3.jar",
          "size": 244188,
          "sha512": "2b16dc81a7744b7d8389ca4341ae790822eb85dbc44cf43b08b5e90fc082306075c6e47569190840808c3b6a800d5fe019a6246e3d150f1079085a17b05e0270",
          "sha256": "2738ae222bfbcb64e4ef0463898679c431545df1b10b1e68e82ea977b0428ca1",
          "sha1": "a333ff17e1df0b10acafe8a3c8c46830ec4ad3fd",
          "md5": "283d0cc7a2c8f2de36554998ab370012"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.3.jar",
          "size": 244188,
          "sha512": "2b16dc81a7744b7d8389ca4341ae790822eb85dbc44cf43b08b5e90fc082306075c6e47569190840808c3b6a800d5fe019a6246e3d150f1079085a17b05e0270",
          "sha256": "2738ae222bfbcb64e4ef0463898679c431545df1b10b1e68e82ea977b0428ca1",
          "sha1": "a333ff17e1df0b10acafe8a3c8c46830ec4ad3fd",
          "md5": "283d0cc7a2c8f2de36554998ab370012"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 523957,
          "sha512": "9ead576d953b77401436405acdf7a9020c25a53b1d14f3c86ca350eda116e3cc3f1517228e944080fe96075168927867aeb4c448814a8b1240e472090849c592",
          "sha256": "e540fdf7f7d7d3b1b7e93378adeaac59403cfd3468ed01a57c09df1260fe0aae",
          "sha1": "dc7f48e47a39b6455011398017a78fe85e0f0108",
          "md5": "6ab4f960acb186cbafecddf0423b2b78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 101772,
          "sha512": "38ac26ac4d014410006b345ebb8797f99d35aecdd2a256808eae47926a074f23f0746acdb4bb9fed1b22970ffd06d4275c88beecf3f31d7023acc08ed1578cd5",
          "sha256": "2664609957aa96300359102b033d3d028bff24808a90fd87e53a70c4098551a2",
          "sha1": "252ec6b10b403d8882c10a2859e2eb57b90b6b01",
          "md5": "7dcc8f616fba5be66d262e01a0ef9dde"
        }
      ]
    }
  ]
}
