{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.1.jar",
          "url": "vectorx-data-redis-24.1.1.jar",
          "size": 9716,
          "sha512": "4a5eee43b340cb5fd00390a535433fbe5bc3db570c85dab55d218a76397aded58ba6ff342ebc1555bbb5088d9fa2b494b762c1e2248a2e9adf85a4fd08edec58",
          "sha256": "4bae56f4fd00191662f26741067c99962b48fbaad942dc6ca45bc6ee87b5ddbe",
          "sha1": "76e168d907a307f57fac2c59204b4cd77048b649",
          "md5": "4bf1cfe69ef33c688d7ff0ebd3f250fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.1.jar",
          "url": "vectorx-data-redis-24.1.1.jar",
          "size": 9716,
          "sha512": "4a5eee43b340cb5fd00390a535433fbe5bc3db570c85dab55d218a76397aded58ba6ff342ebc1555bbb5088d9fa2b494b762c1e2248a2e9adf85a4fd08edec58",
          "sha256": "4bae56f4fd00191662f26741067c99962b48fbaad942dc6ca45bc6ee87b5ddbe",
          "sha1": "76e168d907a307f57fac2c59204b4cd77048b649",
          "md5": "4bf1cfe69ef33c688d7ff0ebd3f250fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.1-javadoc.jar",
          "url": "vectorx-data-redis-24.1.1-javadoc.jar",
          "size": 93489,
          "sha512": "0d4ac8c6000e038a3b3de875b0b4ec55cce453869b12da5725b4cbdbee9a3266b0b4468c43877c61341de86423ffa55cde3e70c1b18cbfdf7f9c3e1b2133558f",
          "sha256": "f74da4c0a70431d46023b6395a63c0fa29551d82b03ab42ee1a691cefddb143f",
          "sha1": "3f96241fdfe10a01f35c5469ec797a7226d86713",
          "md5": "1b9b3f56f65d4c18a7fc01bce38acd6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.1-sources.jar",
          "url": "vectorx-data-redis-24.1.1-sources.jar",
          "size": 3360,
          "sha512": "85bef0274abd084311f1a9eca04a7bf76db3b5d03fec5b601ede8c0eb2f643bcecc8bb8d45e5a550cc3d81cb5d22f2867314936a476e749a34cbc83790a40db5",
          "sha256": "dd75846394cb1a06a09d7809446ccc0963602fb5ac8ee5a8e0842826ddcde761",
          "sha1": "832290324aa3124e266f2527c7844c86200e3772",
          "md5": "54853ef4f5e44c6c617a3b0cc8425f42"
        }
      ]
    }
  ]
}
