{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-view-front",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-view-front-24.1.6.jar",
          "url": "vectorx-starter-view-front-24.1.6.jar",
          "size": 261,
          "sha512": "41aad1dbf6c7b1222166d253221e538963d08ab2883947f6c4305a809ca6fd3daba4010209c0ca0334733d2b50318a99214f84c9226434d94ed6d6e2666c58ee",
          "sha256": "f45ca507ca20691c5754741cd46715ae1a61b8f9cd0baf4acd2ac6073dc887cd",
          "sha1": "1dbfb1715e8075afa98fee64db6336f9e5a60639",
          "md5": "be8f53767cd45c8cec6bdd60eddddd9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-view-front-24.1.6.jar",
          "url": "vectorx-starter-view-front-24.1.6.jar",
          "size": 261,
          "sha512": "41aad1dbf6c7b1222166d253221e538963d08ab2883947f6c4305a809ca6fd3daba4010209c0ca0334733d2b50318a99214f84c9226434d94ed6d6e2666c58ee",
          "sha256": "f45ca507ca20691c5754741cd46715ae1a61b8f9cd0baf4acd2ac6073dc887cd",
          "sha1": "1dbfb1715e8075afa98fee64db6336f9e5a60639",
          "md5": "be8f53767cd45c8cec6bdd60eddddd9e"
        }
      ]
    }
  ]
}
