{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-core",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.apache.tomcat.embed",
              "module": "tomcat-embed-el"
            }
          ]
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "dev.akkinoc.util",
          "module": "yaml-resource-bundle",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.5.jar",
          "size": 231959,
          "sha512": "2faa4f961b938ca651846797a0dc0f97a335d05e0d8632e8b4e24908cf3943b825604cb5b8086d85f077550c190803491dd21a6e33309d5677160a0ff0c848ac",
          "sha256": "46488c6a88fe4162b1d2944819b8124e1056d2d58e81e934a4c7f6ec98b8a8d1",
          "sha1": "44e3eb5e0ad0ccc8fe6d0347f24c2babbf785147",
          "md5": "14e0135ab5d647369769fc475e7ac1c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.apache.tomcat.embed",
              "module": "tomcat-embed-el"
            }
          ]
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "dev.akkinoc.util",
          "module": "yaml-resource-bundle",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.5.jar",
          "size": 231959,
          "sha512": "2faa4f961b938ca651846797a0dc0f97a335d05e0d8632e8b4e24908cf3943b825604cb5b8086d85f077550c190803491dd21a6e33309d5677160a0ff0c848ac",
          "sha256": "46488c6a88fe4162b1d2944819b8124e1056d2d58e81e934a4c7f6ec98b8a8d1",
          "sha1": "44e3eb5e0ad0ccc8fe6d0347f24c2babbf785147",
          "md5": "14e0135ab5d647369769fc475e7ac1c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 558127,
          "sha512": "85f85fa1ea0c3761370d7ff0a748dd37ede38874ca71b0e7b13523abb292161c4f2580fc10108132eb07ede193604b8714ef38992d8f4d71eae273343bf7b1e4",
          "sha256": "f200a43b454faf7bfb9e35081563c0a38f590f3f605807973c0bb5b27b879f77",
          "sha1": "9df2640fd1c4d64f3e1390fe40989668f08f1237",
          "md5": "3f11c566c5b347bd005d6d84e8d254df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 113585,
          "sha512": "1526771d19cef968559b4c80675d4ffbd5ed36f68105f3aeb18a8c03c51b198a742817fc5c85865cb46e6543b9064d471fb88f44a4252467a36e3dcf674f8069",
          "sha256": "c08d95fb4ae5cb30e3602785aa858e4ef0fe827f1e35445aa286dd3d1952a635",
          "sha1": "b65797938992594f634db437ba0c22ef47ebe28f",
          "md5": "eae6aa4b3727dfd9b71a4eed4da01f7c"
        }
      ]
    }
  ]
}
