{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.7.jar",
          "url": "vectorx-web-socket-24.1.7.jar",
          "size": 22971,
          "sha512": "59cfe098b3da67d41ec9d360d6b449fb0312d4461769564e9efdf6e60e91d352e11eefd3c5ea041ec123c26ce21371423147e85ed614647563fd2b14c9280e51",
          "sha256": "ce1e76bf560313f77853180c23d685345627e04b6586429f61131cc3376e868d",
          "sha1": "728f36d188e421f83b2e49b5b908b25da21bccfc",
          "md5": "2f6370c696dd39767b2e604f0f269f20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.7.jar",
          "url": "vectorx-web-socket-24.1.7.jar",
          "size": 22971,
          "sha512": "59cfe098b3da67d41ec9d360d6b449fb0312d4461769564e9efdf6e60e91d352e11eefd3c5ea041ec123c26ce21371423147e85ed614647563fd2b14c9280e51",
          "sha256": "ce1e76bf560313f77853180c23d685345627e04b6586429f61131cc3376e868d",
          "sha1": "728f36d188e421f83b2e49b5b908b25da21bccfc",
          "md5": "2f6370c696dd39767b2e604f0f269f20"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.7-javadoc.jar",
          "url": "vectorx-web-socket-24.1.7-javadoc.jar",
          "size": 128218,
          "sha512": "044c804d7d4472db5f09fd871e5c37e24557ba8fdc5eb822ee3957e0e17974fd0c66419a45c6a90d536ff010705754a3663b9b94211b2ce3fc36db23a0e69a66",
          "sha256": "4ca4733f2008928fb7a731a29faf09d1fbe2c59046c6845b72fed93190b5767d",
          "sha1": "f13d025a093d480dbce7c6267988865e8b454bd3",
          "md5": "01a75e6961c8b5e81abf110d8bb6d4f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.7-sources.jar",
          "url": "vectorx-web-socket-24.1.7-sources.jar",
          "size": 11406,
          "sha512": "06637d0ed1db6c5f1e51164b5f3ebe97570b48df7c2b2a2e09a4f59b618ded385b0b9e9e3869d37e99734fa2061cdac871fce7282163a391d4a4baa09c0a9405",
          "sha256": "74afbaea81ca747473f392084bbc8840c3517411f19c01b78769848c06318da2",
          "sha1": "b748e4925f337f828d795b47039dd7db4024dd01",
          "md5": "a7f7556c9112d1d83c81e50a175fe60f"
        }
      ]
    }
  ]
}
