{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-test",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-test-24.1.9-SNAPSHOT.1.jar",
          "size": 31786,
          "sha512": "bd56ce909bd4f0a2ee1d5d0f3988e93bebfc91fd35c42b1911c3dd18c913f325d63279fefd3e4e4cb05838ad4ecdda55d54658b362248f9c06f36e28f50b693d",
          "sha256": "ddcc4104a4f76dc0c2343743e16cee27e615c8aa2065bc60e6dcdc83711608fa",
          "sha1": "94115cf7c24829849b2073faeafd8490b3ac694e",
          "md5": "e4a1da1334bbff93b12a1ff4adec312b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-test-24.1.9-SNAPSHOT.1.jar",
          "size": 31786,
          "sha512": "bd56ce909bd4f0a2ee1d5d0f3988e93bebfc91fd35c42b1911c3dd18c913f325d63279fefd3e4e4cb05838ad4ecdda55d54658b362248f9c06f36e28f50b693d",
          "sha256": "ddcc4104a4f76dc0c2343743e16cee27e615c8aa2065bc60e6dcdc83711608fa",
          "sha1": "94115cf7c24829849b2073faeafd8490b3ac694e",
          "md5": "e4a1da1334bbff93b12a1ff4adec312b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-test-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 126187,
          "sha512": "4fab217435a2f536043e6e453c6217a99a53040efe6c2fcd31216ec8e5c397da7bb692d50674d7fa9976ea736e2e44af5f091f35c7bc88f33d09b7f5263da999",
          "sha256": "054a88659318962a2b457b6bf0312eec3c01a8601b6b91167b9dde366348c396",
          "sha1": "ebc7bad718aab2a621993c943e8e3ffdd34a57b5",
          "md5": "1f9efdc79c0e72ece2d730c12aecbce5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-test-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 11947,
          "sha512": "3410731537305c92994dbc3040c9629a14c7ce082117834c58cb5aeaaef1f8d796b7b4807acc3f8408ac5c433c5e6b8c96053a4214c08e07cf325e3753635d01",
          "sha256": "87125f6c88d7a1ea573f56378a021e5f771fbd6beac217105366b38db3046991",
          "sha1": "48b3c0a491f346e1e0e072240743c0df1635f9a2",
          "md5": "46867c0f2029c5b9c58d02f2c4902efa"
        }
      ]
    }
  ]
}
