{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.4.jar",
          "size": 107373,
          "sha512": "4f7a5ec1d57acb2f5f557f4ae7284ddb7a308a8da24b7055857646d450f78c71bdbb6f944f37274386fd46726a9451ea6effab08c73b20a34a36aecc46ca8ecb",
          "sha256": "c417ec506874356bc107d4e9bfa4f5f4f5d47f4d7d4aba344b96d8c584bf3630",
          "sha1": "02edfdb7161460638c04ac7ed1a45c49fd575274",
          "md5": "e930a39e73df5120082ad35a9f2d6da2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.4.jar",
          "size": 107373,
          "sha512": "4f7a5ec1d57acb2f5f557f4ae7284ddb7a308a8da24b7055857646d450f78c71bdbb6f944f37274386fd46726a9451ea6effab08c73b20a34a36aecc46ca8ecb",
          "sha256": "c417ec506874356bc107d4e9bfa4f5f4f5d47f4d7d4aba344b96d8c584bf3630",
          "sha1": "02edfdb7161460638c04ac7ed1a45c49fd575274",
          "md5": "e930a39e73df5120082ad35a9f2d6da2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 416151,
          "sha512": "dd2b74eccd775ba24b42da3753404474db05556bd9dc65831cbc41935ba110dd848a800420ab7ecf2550537952948b61d969d37b97776968916d1e60c0eaeb13",
          "sha256": "956aabd62d3dfa9f5538643bb79076d7f3b48b0af2314aded9a82c0e61c96668",
          "sha1": "69de8f86c7f64da313adf637ab76b4cb895d93d6",
          "md5": "f62d2166f8b3528d1e6e38450bf329cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 65047,
          "sha512": "c5c917d6916335467036c1a89f828b5a96a86e02e67d742696624ef6660f59c872bbb366ba27d0ea458dc1f37ef888bdda9eabff8a8b26f89c3420f259012901",
          "sha256": "798fd19dc9e56cabc2159f0610a9b94d82416b21b2ab7df173f61ad989983657",
          "sha1": "420991c047a81899ef445fbb3416fe5c6443106e",
          "md5": "0d6e39320182fd27f525fc39de1a1451"
        }
      ]
    }
  ]
}
