{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.5.jar",
          "size": 926734,
          "sha512": "de72fa4351d6f7043ac95c861794dce61561502d89430846610223b26554b02715ce110aa54102c66d03bccf7e62669a3cdb504ce2efb02a57f1c581b778321e",
          "sha256": "4b0319818165ba182e8a7ecc0a8dfa0c66e7953ac9b893e92f1e3921d0227198",
          "sha1": "56c4810d3f7e61ecf34eea27266b847cfea8c3e3",
          "md5": "cd6777cedb354b47dd586dfc0cfa1e3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.5.jar",
          "size": 926734,
          "sha512": "de72fa4351d6f7043ac95c861794dce61561502d89430846610223b26554b02715ce110aa54102c66d03bccf7e62669a3cdb504ce2efb02a57f1c581b778321e",
          "sha256": "4b0319818165ba182e8a7ecc0a8dfa0c66e7953ac9b893e92f1e3921d0227198",
          "sha1": "56c4810d3f7e61ecf34eea27266b847cfea8c3e3",
          "md5": "cd6777cedb354b47dd586dfc0cfa1e3d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 1351151,
          "sha512": "1d597a8036d628d026655fee985cab3eeaa792b88c86477d5525cda51b79b513bcef10de56c45a59673d491765c2e12e6d19f3df665d2f9da6813747c0bcb23b",
          "sha256": "507e43cb1ec157022ef04cbbe9eafa128e30554fb76cf370a1baa4f5f69f5f05",
          "sha1": "b905cb97aaff6b702c9c2db41db523df2b3cd012",
          "md5": "b183a7b225eeb8e1cc56fd0c6d0a877e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 331520,
          "sha512": "525427ac1486d86c963f42626be896dfdf58cf14501be69408ce2bd69dee611f4f9690fc3388adcc09111dd03331ba9ccc120665a8d4148e423d106447e5bf1f",
          "sha256": "ab5059e4bd567d697ecaf2d4ad1d09c5a63104ea0def4e97848c3cef4f7e6128",
          "sha1": "edfe26963575c1d18bd8fa0560971466c8cb668d",
          "md5": "c25baee16d54e6796c33a27fc82d92d9"
        }
      ]
    }
  ]
}
