{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-eureka-client",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-client",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.5.jar",
          "size": 3056,
          "sha512": "bd1b7b3278fc3837c62cffd8922f6f98be49e47a08aa2ccdeaaf947ff73f21faf0f0e9467b1d722be5bb75a0346a9b0e653f4667848b6d19aa558983ffa7265e",
          "sha256": "82f670e592980ab8961c2771b3f4ddbc55109beae26bebee1abe03ade765f210",
          "sha1": "727c0ad49703e059a8f31dd2e76fbef94e038ee6",
          "md5": "f22d5d30fac606cc0eb9b5576503bb5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-client",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.5.jar",
          "size": 3056,
          "sha512": "bd1b7b3278fc3837c62cffd8922f6f98be49e47a08aa2ccdeaaf947ff73f21faf0f0e9467b1d722be5bb75a0346a9b0e653f4667848b6d19aa558983ffa7265e",
          "sha256": "82f670e592980ab8961c2771b3f4ddbc55109beae26bebee1abe03ade765f210",
          "sha1": "727c0ad49703e059a8f31dd2e76fbef94e038ee6",
          "md5": "f22d5d30fac606cc0eb9b5576503bb5c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 74532,
          "sha512": "8d912b601e094e272954e042c286b9261437df9548337d902ea6b2b9f70b3bf815a7ce05cee365be7401624b0db9ef2b3e2ce3e9f193f898301bc895cfb78875",
          "sha256": "509299b149ff79039d644514d456cd1f8a527a1b650e983bef726406c4d42c00",
          "sha1": "f64399eb06a9f07ec4d553457865e1688074b9b4",
          "md5": "cca5fbada494e97d47784f1d5123fdea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 1467,
          "sha512": "b25b306314400242a4a3df22d2d9dd249b9897addcc50abfda61454f3936c0984bfeb5cb2f55e0dcf0d60a756dfae73b649e3229bc8d00710d1070118a16a4bf",
          "sha256": "5962ba26a5f2d47d1310d3302f8979caab659f2e0af73a287903ac0fd7dbdd38",
          "sha1": "f785a1b859b68f2b30f5fa4ba73c63087ae34910",
          "md5": "0763510df7de62872f84db44f55fb6f0"
        }
      ]
    }
  ]
}
