{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-test",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-test-24.1.9-SNAPSHOT.13.jar",
          "size": 32124,
          "sha512": "3ee540003f05aaa40bc4eca8edc5308c0223c6b5845e0f66c50fe2745cd7f9494bfade0c576a4823b0a892fae034caefa99e4dc4bd5dbb7f0afbb35fc97d098c",
          "sha256": "d064b50dcea5d45d11aa339546b46bfdda349f60dbf55b49d077d897e8243b90",
          "sha1": "28ba35e3e184dcfdf6d54832b99a332d1b41b438",
          "md5": "49e069289613c3b9e8dcfb1315acb9b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-test-24.1.9-SNAPSHOT.13.jar",
          "size": 32124,
          "sha512": "3ee540003f05aaa40bc4eca8edc5308c0223c6b5845e0f66c50fe2745cd7f9494bfade0c576a4823b0a892fae034caefa99e4dc4bd5dbb7f0afbb35fc97d098c",
          "sha256": "d064b50dcea5d45d11aa339546b46bfdda349f60dbf55b49d077d897e8243b90",
          "sha1": "28ba35e3e184dcfdf6d54832b99a332d1b41b438",
          "md5": "49e069289613c3b9e8dcfb1315acb9b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-test-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 147445,
          "sha512": "823980c96a27c24040d1ca02b7596cb4d9a2a15a6d0793d5198bf3ba7b5fd4d57b4ef311d951fcc8b52915f1d062f9406b631274e3c9dac6efdcabedca950dcb",
          "sha256": "13f0601cbc04c67068f0b2e3477e7610d69fa92ecf3e571db8cdfd0fb4669fc9",
          "sha1": "0d3f86861bfec5104afea3e5635eb1ebea0d94a2",
          "md5": "1ee3cd809d180ce168ddecf9646df1f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-test-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 11836,
          "sha512": "0cf2ce7c0a632ad9079ce5d6c65d697d03746efbfa2942b21f2d8ecab2f11517ce8e5dd6a85982f24c2eb5dff80845f5016870c58b401614d67b6433040ed51d",
          "sha256": "6e3b29ef11bde4df60ac60d9b79ec38b605dbfa32e7d98d2a2666e8a53ab1bd2",
          "sha1": "55b2b21be4f3f6700a6cf22d9841c8cd356b2f06",
          "md5": "2db9dc6af097d72ff8f7ce4d23200da7"
        }
      ]
    }
  ]
}
