{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.4.jar",
          "url": "vectorx-management-bo-24.1.4.jar",
          "size": 145412,
          "sha512": "89a82ebf0591d2ebfde7d7df7d004d16e4765b0ec891028530c0b4e0ebe60e21f18616e94d443828b718d1c96200b9287a97ddbb8eb7c25b023021f432fd86e0",
          "sha256": "0a5bbabe03754725b49f49164a2d3d1cf81188ddc089a07c0cfe5871235e96df",
          "sha1": "b0b2f62ffc3a3b26708e30bf696c8ec37dff19b1",
          "md5": "ed7802f3b2a95c66e914ea8184b1fd7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.4.jar",
          "url": "vectorx-management-bo-24.1.4.jar",
          "size": 145412,
          "sha512": "89a82ebf0591d2ebfde7d7df7d004d16e4765b0ec891028530c0b4e0ebe60e21f18616e94d443828b718d1c96200b9287a97ddbb8eb7c25b023021f432fd86e0",
          "sha256": "0a5bbabe03754725b49f49164a2d3d1cf81188ddc089a07c0cfe5871235e96df",
          "sha1": "b0b2f62ffc3a3b26708e30bf696c8ec37dff19b1",
          "md5": "ed7802f3b2a95c66e914ea8184b1fd7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.4-javadoc.jar",
          "url": "vectorx-management-bo-24.1.4-javadoc.jar",
          "size": 305808,
          "sha512": "357679f4d44fbd3486a7ebd0a1d30d9b775c5aa6447fb63756809e0bcc00b77441d80f1318a50feee489b91cc054879a6d649b6b7161088b8bbde06d2f63f798",
          "sha256": "cd86496d11f217fe6cbf9e51e98a6ad918b5c676172be3d5e84399376867fe51",
          "sha1": "9875bd9121bb9dcfc8b85dac1e636c65271e69c1",
          "md5": "050048a06b3fa199fef0e98705b41525"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.4-sources.jar",
          "url": "vectorx-management-bo-24.1.4-sources.jar",
          "size": 59264,
          "sha512": "0658d8b6050d7196014c743cc6689ef69fe50682a588b3c12e5ef45440dafc15d7feeb4fab7da249f445d2c4982c1569351f6196e837be73819cf9a375338033",
          "sha256": "d542c32cca62b7dd031cc1400b5a616b53454cd1cf33cf973403358ce2b851ca",
          "sha1": "c50e4665515b31ecb0abe38f9688d9dcd6cd6c4e",
          "md5": "cc9eed47bf5612328eeb3b8fbda4733b"
        }
      ]
    }
  ]
}
