{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.4.jar",
          "url": "vectorx-management-bo-24.1.4.jar",
          "size": 145412,
          "sha512": "134bab741755a5de60df3eba4c0632073038e3fb395db762972bd31de2b7525e31ae0bc39c7e3c116abfd8fc8396a880ec10add66ab06232963fab457726cdca",
          "sha256": "18b9c8e096d6a32fe7bfe5d5a5371922cab40ef3e8a714cd742a914db5ab5ac6",
          "sha1": "1e58e8e6bb7c0a1d040a172f73db0c1910df90df",
          "md5": "6fa4f738b4e26df9e75482c7c26fcb25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.4.jar",
          "url": "vectorx-management-bo-24.1.4.jar",
          "size": 145412,
          "sha512": "134bab741755a5de60df3eba4c0632073038e3fb395db762972bd31de2b7525e31ae0bc39c7e3c116abfd8fc8396a880ec10add66ab06232963fab457726cdca",
          "sha256": "18b9c8e096d6a32fe7bfe5d5a5371922cab40ef3e8a714cd742a914db5ab5ac6",
          "sha1": "1e58e8e6bb7c0a1d040a172f73db0c1910df90df",
          "md5": "6fa4f738b4e26df9e75482c7c26fcb25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.4-javadoc.jar",
          "url": "vectorx-management-bo-24.1.4-javadoc.jar",
          "size": 305808,
          "sha512": "d71d73c1a1903e08fd88a624f142320c4a960bde7ff079a0001d4900e9998b05f1ea2e9f5098117dba6995463495bfca23af217d825725c033ed8138bf42a4f2",
          "sha256": "262a4bff9a4e34a43c2e6893b466fb8dbb53b9c0cb387be4267d77b1f6680666",
          "sha1": "54fb61a18fa772cbe1cf625a997f7bab346ce0fe",
          "md5": "147b150fb30b1a8dd81c825190458efc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.4-sources.jar",
          "url": "vectorx-management-bo-24.1.4-sources.jar",
          "size": 59264,
          "sha512": "2598f3fcd6a029f94aa08efa37ef21efba541812b150acd7feda3c2b15498d805c5e04c4dc5ad17be2c11be1424aeafe4d495b12e9c0a33d22f6f0964e6501c8",
          "sha256": "073f07a0fb77cb12cebafc0c2eaa3810712e2745a545528daf567f33f507041a",
          "sha1": "90dec30dc41f6a637a99f747ee05499f164cf018",
          "md5": "042e1f9b5e7b164463a6a236fd77d90a"
        }
      ]
    }
  ]
}
