{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.3.jar",
          "size": 181419,
          "sha512": "aa4a06d905a4ce1b4fefb6c5851699c88c021f0d7dd739136954d05182d4385af8f30e9e1c0c91b7c9c0aa0072aacc5ab984d16cefe927f6197e86e373f39ecc",
          "sha256": "00e80b386f8a9cb1c04089cdb6a72ad3c7330b582c4283ee061ee893a9d4d985",
          "sha1": "17eea1d76c098d17f0d9714e4054d4f086e670e6",
          "md5": "93ff1c6f6e729d96ff601d5896679f59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.3.jar",
          "size": 181419,
          "sha512": "aa4a06d905a4ce1b4fefb6c5851699c88c021f0d7dd739136954d05182d4385af8f30e9e1c0c91b7c9c0aa0072aacc5ab984d16cefe927f6197e86e373f39ecc",
          "sha256": "00e80b386f8a9cb1c04089cdb6a72ad3c7330b582c4283ee061ee893a9d4d985",
          "sha1": "17eea1d76c098d17f0d9714e4054d4f086e670e6",
          "md5": "93ff1c6f6e729d96ff601d5896679f59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 274457,
          "sha512": "55959251710aceb90256a37e0128e0c34fd2adee66d57fa1392f4ece3e5b2ca69c50f735ce42fb26a73e18c556e299a354438722f19b21b2ee30a3740e49014e",
          "sha256": "4bbebec495b0513739482062bfff989dae8a49b5e2765a83d983736feaf7e7d0",
          "sha1": "6cac6774088bbdd05a06dbdc5268699960b971df",
          "md5": "6e71634c54e1ed22630b3ae95f027985"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 68190,
          "sha512": "152cf294aa4fdbeb925ec0f887af699b6b6fd99d693f2f7ec9304c25ebeb3845f3a19965274c27244633546d8b3afa5cd550e11e9d3df79c108fc6c1e19efbb7",
          "sha256": "e4458db0425082197b61ad7adcbbd2159af85ea866309b3d0cece11b0b109d9c",
          "sha1": "5cfcd87334196544ac83e28a734012756d72fc35",
          "md5": "a8823659787a3a2ffe0a71194f658b28"
        }
      ]
    }
  ]
}
