{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.13.jar",
          "size": 23342,
          "sha512": "3c31af5ddfed3e089039f47501ebd07dd483a864c146d5c2b8667e947ee3b01bd946f95296438e5587522851ce9b9eb6c48efe47a22e0bfdae3d2985d35b6820",
          "sha256": "abec4b4c9838660f41e36be307d1566605a76e18718403ea7db7ba5f7aa0abeb",
          "sha1": "641858e13f429bb184211bb0e4f202fcb082b8ce",
          "md5": "4485237c219e04ff957c86d70b3976ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.13.jar",
          "size": 23342,
          "sha512": "3c31af5ddfed3e089039f47501ebd07dd483a864c146d5c2b8667e947ee3b01bd946f95296438e5587522851ce9b9eb6c48efe47a22e0bfdae3d2985d35b6820",
          "sha256": "abec4b4c9838660f41e36be307d1566605a76e18718403ea7db7ba5f7aa0abeb",
          "sha1": "641858e13f429bb184211bb0e4f202fcb082b8ce",
          "md5": "4485237c219e04ff957c86d70b3976ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 143847,
          "sha512": "3a45cfb77b635f608d8177510d66149cb6e9425b6ae1f0f5e5d5c254fb535f7ff401bbb5a49a15315533597c4b50c221fb275734a943d625096083317ffde49b",
          "sha256": "633dc20f362753ba15ade6e32a6e17f27f1bb09f87d35b5fb7ce101d10e9daca",
          "sha1": "0119a4fbfe7808d9d312e6752248b355a1299deb",
          "md5": "399f2fbf73c48436ddace738aa1181f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 11319,
          "sha512": "146e41b36c21c21b477eb093ea78d92cc1740297958e5fc1e47babb05b55b36822f71f9c5180e710d6eaaad029cd6bb8bddb27e02dc85fe7d3fd0fc441507c84",
          "sha256": "e76c6aad8bdc7175c1c6db1c74e9dd8b2762c550fb0f953bd40c3741646ca36e",
          "sha1": "57d8de679ffb8773a149b8860d15c7b38c97b619",
          "md5": "5e7f73df56d8098ff421e792bf545750"
        }
      ]
    }
  ]
}
