{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-core",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.3.jar",
          "size": 10003,
          "sha512": "73b78b086ea0514e207ba10e2ea9d20c416d87f74afb4504de5799bd5a11bb3a18e4310f8de9fc5287ee5e4be886de1c5aac21413911de613bf0e56b5f7e2bd3",
          "sha256": "934d2c9969497e1ae50f823476e9f0333d6bd10f96dc464b00b6f690ab82b111",
          "sha1": "7ed34738537d63e079c36cef1f964d3b8ff18169",
          "md5": "2f64db37a6f086270ff635f8cbffd723"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.3.jar",
          "size": 10003,
          "sha512": "73b78b086ea0514e207ba10e2ea9d20c416d87f74afb4504de5799bd5a11bb3a18e4310f8de9fc5287ee5e4be886de1c5aac21413911de613bf0e56b5f7e2bd3",
          "sha256": "934d2c9969497e1ae50f823476e9f0333d6bd10f96dc464b00b6f690ab82b111",
          "sha1": "7ed34738537d63e079c36cef1f964d3b8ff18169",
          "md5": "2f64db37a6f086270ff635f8cbffd723"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 107424,
          "sha512": "2cc3568da9cca3fec75c5d05424b89e0e74d9b991e7845b4c00543468d9f953888b53967fc81f7b020a48b3ce0410d6b217ba8f7408387608297b3c75006395e",
          "sha256": "09c17d7bb4fd96556669d258ce37def0ae4a13f2430c2efcc9558abd795bd931",
          "sha1": "e081683917beff6321262b7065d4ba20f174aff6",
          "md5": "bb68f5255d516338ce0315aae2015842"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 5531,
          "sha512": "a61d910b83c5a747985a69cd74e29b4926e6b3b8a495dd10ef36921693b252e5a8b2f0327e8f86b817b4cdb0814b16e58ce266942fa13c4211ae9633c95ad8dd",
          "sha256": "b12b9ba6708ce73c9c9879e1db771da1c1ea4c26a09c13f8a03304548fe3f87c",
          "sha1": "c2956c2f84f06079f719459ed16a8a42970b8dac",
          "md5": "74db0ecbec7bdc7ae66d8ba3085048fe"
        }
      ]
    }
  ]
}
