{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.1.jar",
          "size": 145553,
          "sha512": "bfd725cbf739f41fdb647bb37ea92aaa2ae0454a4ce8f8d792f262d052ff483892e721511f5b27f4bf760a10b3a4dbeaa118c684127069fde58e087df0d12cd2",
          "sha256": "0e754d886ef99add1c3636069a2a7d99e7d6349999e55e6904a2bcacb86b7e34",
          "sha1": "0361b74eea6290501d0f20ece2d60aad41079b61",
          "md5": "2c48af129a2c869fc81b30c412a97d59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.1.jar",
          "size": 145553,
          "sha512": "bfd725cbf739f41fdb647bb37ea92aaa2ae0454a4ce8f8d792f262d052ff483892e721511f5b27f4bf760a10b3a4dbeaa118c684127069fde58e087df0d12cd2",
          "sha256": "0e754d886ef99add1c3636069a2a7d99e7d6349999e55e6904a2bcacb86b7e34",
          "sha1": "0361b74eea6290501d0f20ece2d60aad41079b61",
          "md5": "2c48af129a2c869fc81b30c412a97d59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 306929,
          "sha512": "f38b82f15120069662eae8f1e7ca78b0fb2e4584cd0abeecd5e59f311a4bdf7f09215b5ca5fe1cc52f48ce2214ecf0fa53cb71915fa5a419691b12115b7268e0",
          "sha256": "f9f2431234f1d9647dcfbb8b060c48699ed0e254ef14e48a49c9a36b19380ff0",
          "sha1": "db511142d882d7aee4ecfe297b75f1fa7dee0192",
          "md5": "3b6b315d2da667b19b9140e786a2a297"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 59409,
          "sha512": "7886515d4e9b57aeda7f52fa8f3352a556e9aacaa368ae94ba5d6c0ca5b6e61782faa9bcc029fe4adb13a3aff3fddef9f504b2d97cccbb68c7b7429fcfc963bd",
          "sha256": "fd73346045cd7fc192d844b4cc24f0d3b028bce6bdd8994231c0fddad16e3c9c",
          "sha1": "b2bd0fe591c0877e95b0084c3451add5708adce2",
          "md5": "c3a1865c09c29c58d58247a6653ae8c5"
        }
      ]
    }
  ]
}
