{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.9.jar",
          "size": 184900,
          "sha512": "7c76a4bb6b6286b13e9741c494a0364bf0bc96a043c3ff80a1538b5a1b2148705f747132aaf3c7490616270e15c6b39503fbca7eb5fb4c33af017efec0e8a1c8",
          "sha256": "90f83247aec432907c5df92ebd30ef8d2bfeb55bb4f03e1e961a864216de9ddd",
          "sha1": "9aa1fd2cd4f41662eda6704389028b0b575f57a9",
          "md5": "a903640c7cfcd96fd91561ff869717f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.9.jar",
          "size": 184900,
          "sha512": "7c76a4bb6b6286b13e9741c494a0364bf0bc96a043c3ff80a1538b5a1b2148705f747132aaf3c7490616270e15c6b39503fbca7eb5fb4c33af017efec0e8a1c8",
          "sha256": "90f83247aec432907c5df92ebd30ef8d2bfeb55bb4f03e1e961a864216de9ddd",
          "sha1": "9aa1fd2cd4f41662eda6704389028b0b575f57a9",
          "md5": "a903640c7cfcd96fd91561ff869717f1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 273983,
          "sha512": "7d80b212650d821ecf38819ee7147fea058365c0e8407670c101cab0071849cda71c43d694644f2bf928d0613b47a36e5e7262462b21695031bb2df2c919aaf8",
          "sha256": "8edf9ab1d0c5cf191ceeaeb49b640ea0ed2807750af5a2ebc8aa57252eec3718",
          "sha1": "468a13c8e08ef324bed2f8194ed1b134c2bd84dc",
          "md5": "ec2cefc82bfc5ba03b166e302962ed9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 69419,
          "sha512": "c74d84feb4fb27ed43563515669ffe2346efc3576c442b48606cd1d95f1788177f995ce8e86636ddd04862bf5d5a2123e20eea1fbb0d7a187701f604e84a952c",
          "sha256": "80b2958a8073851b48654f0a4ffa32c61c63c5993bb8d5e07b8682360034d426",
          "sha1": "d80e7bc10f91b07d5b46d05973c35a331ec06390",
          "md5": "ecc6c15e0fead08324c32c59cfe2091c"
        }
      ]
    }
  ]
}
