{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.2"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.2.jar",
          "url": "vectorx-cloud-core-24.1.2.jar",
          "size": 2695,
          "sha512": "cbd066d178876f9821a0bfa1cce79fb4407e1a1c4fa220ee5173dd288952f49f4e1bb8e89a24d1f7deca60f95501edfa907fec566bbee4ec4eb0333844ac7fcf",
          "sha256": "52c9d0e3b4494b96e19ac79a6fe579cdfc6017ab2c333aee10bb6fde92b7e364",
          "sha1": "0ed9ac900156e628b1222dc0246ecd28e9918f22",
          "md5": "d06269457548c20bf461362350fc7f94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.2"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.2.jar",
          "url": "vectorx-cloud-core-24.1.2.jar",
          "size": 2695,
          "sha512": "cbd066d178876f9821a0bfa1cce79fb4407e1a1c4fa220ee5173dd288952f49f4e1bb8e89a24d1f7deca60f95501edfa907fec566bbee4ec4eb0333844ac7fcf",
          "sha256": "52c9d0e3b4494b96e19ac79a6fe579cdfc6017ab2c333aee10bb6fde92b7e364",
          "sha1": "0ed9ac900156e628b1222dc0246ecd28e9918f22",
          "md5": "d06269457548c20bf461362350fc7f94"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.2-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.2-javadoc.jar",
          "size": 70381,
          "sha512": "05298f03d5f06891935d29ca44460b9384e154265c7e434e70f9a7bae6f9558eb705c78e37c7fb46a5e914a81889ad56df45365147d60636ed2bccba4c5767a9",
          "sha256": "159fb89725b13f58ded14303ed82a2cb7a97093cec71dcc2d1fa6e6f7f38d67b",
          "sha1": "1fea727c73233d9d397fce41a4f298dfd9e6986a",
          "md5": "e7072f1ca0722fd27e02b1da3285199a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.2-sources.jar",
          "url": "vectorx-cloud-core-24.1.2-sources.jar",
          "size": 1186,
          "sha512": "d3afe9d0d5bdd164fbb4fd8afab2d4e372273907051af5f3720e9026372aa352833034fc953ea55b3b702a20c5cc7f4d5f668d81453c57b213103321de16ed95",
          "sha256": "af15608712504ac9b78806bad024357f6e5f6f4294f16d8f9d4835a66a77addc",
          "sha1": "6f968e5b477ab261f255708550b4db01ad9efe07",
          "md5": "f467e799e659cd6422bfd198029abdf4"
        }
      ]
    }
  ]
}
