{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-core",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.13.jar",
          "size": 10086,
          "sha512": "47f7a96d07889dee6e4eb6dcbe4901fce4cedb4345ee2e346d6a7ae42ac753c5fec9cc14f9ce5361e72ff2eabd92c00421c984085e12ee4467e9ac154732dca8",
          "sha256": "54ed187c1411df9a7265eab1ec87a62eff28788ed9558a77cf0c8989e44e375c",
          "sha1": "715fd286895edcabcadd01e136265475484742d3",
          "md5": "5cb8eb0055a1faab6d712a4eda4e3c58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.13.jar",
          "size": 10086,
          "sha512": "47f7a96d07889dee6e4eb6dcbe4901fce4cedb4345ee2e346d6a7ae42ac753c5fec9cc14f9ce5361e72ff2eabd92c00421c984085e12ee4467e9ac154732dca8",
          "sha256": "54ed187c1411df9a7265eab1ec87a62eff28788ed9558a77cf0c8989e44e375c",
          "sha1": "715fd286895edcabcadd01e136265475484742d3",
          "md5": "5cb8eb0055a1faab6d712a4eda4e3c58"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 115044,
          "sha512": "0eab8048c036d3368755a77a7cdf8fd6b6ba03587b0e0d728019bf4d1f3886906e6a51853bd09a6c6bad4f1829bdaa420d9cbb5822cbea7b27e53dc02230c680",
          "sha256": "700b4ca36c23b23462995b19f82e67f2f00f396d283412184d77937b966492b1",
          "sha1": "f37601356d6e4510dd5b5ac641145fe41beb3384",
          "md5": "8ed4032ecad7f043f1894f6b45cb5741"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 5531,
          "sha512": "4105b598ff87b0ef773872407967c8c5a0bd279a7c2bf369a0f14b9e4871482a810006bb7302f0276a5b6b9bb3707c7716865e61e0a8d43b254ec63867a17f6f",
          "sha256": "b8fe2ea0fcc665e8699c929878befd05c415dd8331660bbae13ad1720a99dfd9",
          "sha1": "38e6c3e36e444e8749591d7389c506855e2cf03e",
          "md5": "cf0ffd0d6bb51876d9b36a85754b1b4b"
        }
      ]
    }
  ]
}
