{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.4.jar",
          "size": 184887,
          "sha512": "b0b22d13f1521279287fc9ffd3e78ed7a6ef1a435da535f07a30790098919a70fb606cf638050ca53c155ab4ecfef60f9e7c612131b477dddad48d7e46553a69",
          "sha256": "7506c603e273618f3e45ae3010a9fca12b0f69b509fedbaab9a1721cfd082a95",
          "sha1": "58c3636912f6c696d20f324b00d5dbf6d2afe5de",
          "md5": "b2970ed0030887653889ac2b3f9dd912"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.4.jar",
          "size": 184887,
          "sha512": "b0b22d13f1521279287fc9ffd3e78ed7a6ef1a435da535f07a30790098919a70fb606cf638050ca53c155ab4ecfef60f9e7c612131b477dddad48d7e46553a69",
          "sha256": "7506c603e273618f3e45ae3010a9fca12b0f69b509fedbaab9a1721cfd082a95",
          "sha1": "58c3636912f6c696d20f324b00d5dbf6d2afe5de",
          "md5": "b2970ed0030887653889ac2b3f9dd912"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 276930,
          "sha512": "7216ae844507be363d2fce63b22163fba01c8d8c022b9503d56452b7749e685535cd5e4287e7ab5a2328db697fe953b26e1a127fa3124dee1fc23a4317810f8d",
          "sha256": "fbb28e1395f41546c45a4d9815e5996c21d28a623cc2885906cf99c663fd0e2d",
          "sha1": "2b560880fc0a367327a69873356443eefab45b80",
          "md5": "2ba7f75b56d3f154d919fc5847f3acc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 68978,
          "sha512": "add82b104d33cc0209d7599eadc2e469fc43a9a191583821e15cc7165c9794ef4dd0346462554b2c13b252b05394c295a048ca5fab7e95c7f8cd41f024c5bd83",
          "sha256": "4e8e63fdfc26932efbf8aa8e9c26d2f55b95ceed028f682cdb4e4fcfd8ecd690",
          "sha1": "53cb33c933c8c236ef0f5c7791923466cbc22857",
          "md5": "6c30b3f784eca9bcd692fa52103bab76"
        }
      ]
    }
  ]
}
