{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-eureka-client",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-client",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.3.jar",
          "size": 3055,
          "sha512": "ff2c2076da88a4164aea31ef141f2b3b0fd944c4d6a37e9092e471b54ae1ed218c6deab6f7be3f03af6bf9dca5e7c07b5720cd294531bcf92ab3d0d4558dfd20",
          "sha256": "c55d8054206b4426a2a000032b1c399a7599d1e7c4cb3137312ef3cd766bd221",
          "sha1": "8c2a3d05394c923222ee4abf5885958a85d048b8",
          "md5": "ece58177f16eeb16468d25bca3efeaaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-client",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.3.jar",
          "size": 3055,
          "sha512": "ff2c2076da88a4164aea31ef141f2b3b0fd944c4d6a37e9092e471b54ae1ed218c6deab6f7be3f03af6bf9dca5e7c07b5720cd294531bcf92ab3d0d4558dfd20",
          "sha256": "c55d8054206b4426a2a000032b1c399a7599d1e7c4cb3137312ef3cd766bd221",
          "sha1": "8c2a3d05394c923222ee4abf5885958a85d048b8",
          "md5": "ece58177f16eeb16468d25bca3efeaaf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 74535,
          "sha512": "05449ff5c2a9c7acc735d6db0b198295030b1424cc685e24120161345730da4110eed8e86c17e0dfe723e85bf960164329cfb466aa7b1e1a06c86ab774cb253f",
          "sha256": "49c6de5df2cb86dc962aab02c07fa45593accb688cf40bcea96a3c99bc150382",
          "sha1": "824066cdddeb2f36333d64c710975d1d9cabf4e2",
          "md5": "2ccf69430dd80b9763f96b0b59c624fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-cloud-eureka-client-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 1467,
          "sha512": "656d8fa2d7f6dd14994eff59e1449e489535d7b821a1c065d3a3cc27b48445e03078f43e818d1e849b797f7de1792f01edc37a6f3d8f6a6b02ed966d9c2a2a37",
          "sha256": "5fa26139fa18f28d117bc08b78fbc57d7e034429d2a02d927e2b575c5f7ad31f",
          "sha1": "eb3f7faee23d93876631bd341e5965eba2ab73c7",
          "md5": "14ed4dd4915dff922110d629f4a0cb6b"
        }
      ]
    }
  ]
}
