{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-gateway",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-eureka-client",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-gateway-24.1.9-SNAPSHOT.1.jar",
          "size": 46836,
          "sha512": "8879f50f25163ef8f22a9ee58e10e4a488090db2870d9a1282192fb59c26c0d85f547e2e2be31402f06a6ef0adea52a6cb0a67c8855c0afd15a91057d30ed526",
          "sha256": "655215cf4c3312907a3189c8c297aa516b069cb9276edc2d176df6d591545e5d",
          "sha1": "e3737333a7e80b56bb9db976d08e139b015b828f",
          "md5": "1ae8e83b7eb14203607411066303e77b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-eureka-client",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-gateway-24.1.9-SNAPSHOT.1.jar",
          "size": 46836,
          "sha512": "8879f50f25163ef8f22a9ee58e10e4a488090db2870d9a1282192fb59c26c0d85f547e2e2be31402f06a6ef0adea52a6cb0a67c8855c0afd15a91057d30ed526",
          "sha256": "655215cf4c3312907a3189c8c297aa516b069cb9276edc2d176df6d591545e5d",
          "sha1": "e3737333a7e80b56bb9db976d08e139b015b828f",
          "md5": "1ae8e83b7eb14203607411066303e77b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-cloud-gateway-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 163120,
          "sha512": "e3fb12916f90e77525857f5d0a6f461c103586cb9dc9c4b9c068d89d2aea36d0e55945273fcfa2420b8c0807747c3fe1b135b90b3895ac0d8e8576abd37c40b8",
          "sha256": "bc526f9f09c6bb0f1bd3ba771a782f9bed78321d611b398302f6927608972368",
          "sha1": "70da97b0c8a263f435b46ba50028aff2ed09d408",
          "md5": "4671f8700938e8e23c38551df0861005"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-cloud-gateway-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 15249,
          "sha512": "9b0ddccfafdb62b7da80725ba9802d4d581dfb224d883c7181c24d3f3e3cd18717245b4fcf66d9fcf0b9dd1f13eb8b16348eb69cf0675c9a15393d6cf2d5b464",
          "sha256": "6299284632a664f09eae850ac8242636e1535c7baf8ad5dd8642901605d92047",
          "sha1": "3cbf45411b3853bb9eff9eb033348b64b6bea2ad",
          "md5": "8d764a00304e047846a4d4e2ee16b342"
        }
      ]
    }
  ]
}
