{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-net-24.1.9-SNAPSHOT.9.jar",
          "size": 29739,
          "sha512": "13626cc7982fcf5b19ccabfc2c30221b489eba15fd0ef65dcbfb2369f6bd7a9b1f6d38f8442b65ba4eff18e1550b625383477120dd42784d9c79f492ae57519e",
          "sha256": "2254eedf3841f01dc936a0b80a584e5a6493a19e7460143d5f6fd164999fd260",
          "sha1": "3376003e00fdcf31dcb7ed82a012875e4e09a199",
          "md5": "bafd0925a7b9f71ce8a9415f7393dd31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-net-24.1.9-SNAPSHOT.9.jar",
          "size": 29739,
          "sha512": "13626cc7982fcf5b19ccabfc2c30221b489eba15fd0ef65dcbfb2369f6bd7a9b1f6d38f8442b65ba4eff18e1550b625383477120dd42784d9c79f492ae57519e",
          "sha256": "2254eedf3841f01dc936a0b80a584e5a6493a19e7460143d5f6fd164999fd260",
          "sha1": "3376003e00fdcf31dcb7ed82a012875e4e09a199",
          "md5": "bafd0925a7b9f71ce8a9415f7393dd31"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-net-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 128687,
          "sha512": "559c40f43e9a23bae231843c3efdea461d3a4d6cc75efd95abe3c12988c17b84bb1dfeb5b199b3ade1e6a20efa934503d2624082e7239460a48dd09a237d0c50",
          "sha256": "4773ddd8f221933299aae1aa3f3ddab0589270eb4379796f034c5133a06ccf46",
          "sha1": "9883a0630f69d48a1a7087651e7812646b5392eb",
          "md5": "a5767289d6d4b6828fab6e3e7ccae110"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-net-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 10137,
          "sha512": "ec5841fabfb3d177e7168e01170e31521f3235ac295205a219d315cdab1c35fdef308653950725b52383a12de502c462ae8997fd1ad2097bf5357479a4545d20",
          "sha256": "222a4cc9bc8ea59cc14f5598b1ddbe3f16c09c6e0d99bc43920cacc5eae5047a",
          "sha1": "19a95532fa2f96ae087f798b0b6aaebe9dcd992c",
          "md5": "23b5880fe7d3178044478342c211a9ab"
        }
      ]
    }
  ]
}
