{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security-jwt",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.devskiller.friendly-id",
          "module": "friendly-id-spring-boot",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.4.jar",
          "url": "vectorx-security-jwt-24.1.4.jar",
          "size": 87345,
          "sha512": "335caa81f68ffdf59133df8d93de86641e885d77bb5898ed75fdd25f695101669aa29558d2e967fb8042024923d2fd5b9950ebd9a32b26c934a0d508c4fde545",
          "sha256": "6507dc59f3037a508155c6df312d982b46383a45a24fecd9ab762ec57bedcd52",
          "sha1": "598088e239669010e4345066a85d1a8114c44ac9",
          "md5": "1297c98076a3aadfa058f3b29759b222"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.devskiller.friendly-id",
          "module": "friendly-id-spring-boot",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.4.jar",
          "url": "vectorx-security-jwt-24.1.4.jar",
          "size": 87345,
          "sha512": "335caa81f68ffdf59133df8d93de86641e885d77bb5898ed75fdd25f695101669aa29558d2e967fb8042024923d2fd5b9950ebd9a32b26c934a0d508c4fde545",
          "sha256": "6507dc59f3037a508155c6df312d982b46383a45a24fecd9ab762ec57bedcd52",
          "sha1": "598088e239669010e4345066a85d1a8114c44ac9",
          "md5": "1297c98076a3aadfa058f3b29759b222"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.4-javadoc.jar",
          "url": "vectorx-security-jwt-24.1.4-javadoc.jar",
          "size": 251671,
          "sha512": "442f6ff9c61660a3705d470423e5b28ac6934fd549ec238d61ec9fc8675acee9087918b012f5153fbc6836fb8f40f0fccb41b2ce5e0fbe3cf3821ee5e1333598",
          "sha256": "ac8704654cebab951c67ebaff47a4efbe0925052602df7e3ca080ff73718b3b6",
          "sha1": "17b7e57682d1fb1a41cfb9bb38a929296275251f",
          "md5": "6de39f373d8a1be786b0530be4579a1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.4-sources.jar",
          "url": "vectorx-security-jwt-24.1.4-sources.jar",
          "size": 42985,
          "sha512": "1bbf3b64033f2ba35ae58e519061d168b9a858dee52f6863d8e0ad0771f14fbfe7a5ccb224bfdac4ade6482188e693d12a15f0e4403a2bec7ad7601753029556",
          "sha256": "a2838b9a1cd853856106fa329b3cbe7f536f383a99d16da790383df8fbfb1332",
          "sha1": "777f1a4f2b4a87b5250551323097b6e731db2b98",
          "md5": "c0a2142fc33a29e5bc2dae721dfd91f7"
        }
      ]
    }
  ]
}
