{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.1.jar",
          "size": 107183,
          "sha512": "b2979707eab07aba2fd310ce34e60eb0e241f86e4746792d1a9b59bf4d07a522efcaac16792a7e42db3872b9aedbd8892b006fd45bec28c9ea8a90fe31683c98",
          "sha256": "7d42c6571e675b0066b41eebfa631da01011ceaf2f4930d942656553305ec7b0",
          "sha1": "7786417ca826ff29c8bb8829678cb802b1c6f74f",
          "md5": "4308d636eae776bd0a24766c63040bfd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.1.jar",
          "size": 107183,
          "sha512": "b2979707eab07aba2fd310ce34e60eb0e241f86e4746792d1a9b59bf4d07a522efcaac16792a7e42db3872b9aedbd8892b006fd45bec28c9ea8a90fe31683c98",
          "sha256": "7d42c6571e675b0066b41eebfa631da01011ceaf2f4930d942656553305ec7b0",
          "sha1": "7786417ca826ff29c8bb8829678cb802b1c6f74f",
          "md5": "4308d636eae776bd0a24766c63040bfd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 413542,
          "sha512": "d4592f2c6d339066b75d0981314a601e6337916732bd6417962bf51b1a15da8fe055493a87f488cf2800708e65bf9b4e5107ffaf040f151a1079a3188d58add9",
          "sha256": "7c7553cef5ec1abd1353851d529b0f716ddd1f34af5aea0623029c3c34768f7c",
          "sha1": "51fb1d0ee405aafed6c96b58553aa29c0aef6916",
          "md5": "05c4aca7759ff7e2085d1ac54fc0e239"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-security-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 65616,
          "sha512": "b644ace8df9fc7ee4480969b1c29954e1e472a867e752859abc9fbbb7f7cde166e73ada2ec8d5f9ccaa2e0e0decfc6e3ce0a29e710d2a5b1f58a05388eae53ec",
          "sha256": "fdad94c1669bc6b58526cd8ddb85cab1ae6a62e1536993f2e6d098744c2eca30",
          "sha1": "0fb0e597db24e4b6e7ca9ec1c6f9fbb971af5a4c",
          "md5": "28c0004ef0a0ecf3bf744303147a74f5"
        }
      ]
    }
  ]
}
