{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.4.jar",
          "url": "vectorx-web-socket-24.1.4.jar",
          "size": 22971,
          "sha512": "865979ce70b7c57707ababc29e84066e69fb7636780684614c28194211ae604605391c70f94dca5dc30c94559f2ba75a458657ce3553ccf0802eb1bae3efa7d2",
          "sha256": "f97e7bf3bfd45bcb3b65fbaf2b64220decc2ec0f4d7f7ef3cbe2bdb6411bdf9a",
          "sha1": "306a71e18aaf76330abd0172313ffc49d54b60b3",
          "md5": "a3452742b9d50eff0435372451a414ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.4.jar",
          "url": "vectorx-web-socket-24.1.4.jar",
          "size": 22971,
          "sha512": "865979ce70b7c57707ababc29e84066e69fb7636780684614c28194211ae604605391c70f94dca5dc30c94559f2ba75a458657ce3553ccf0802eb1bae3efa7d2",
          "sha256": "f97e7bf3bfd45bcb3b65fbaf2b64220decc2ec0f4d7f7ef3cbe2bdb6411bdf9a",
          "sha1": "306a71e18aaf76330abd0172313ffc49d54b60b3",
          "md5": "a3452742b9d50eff0435372451a414ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.4-javadoc.jar",
          "url": "vectorx-web-socket-24.1.4-javadoc.jar",
          "size": 128220,
          "sha512": "7aec47f752a479cf5d5cc72bad8175eb5aad56573250711475c115f064a2de20376dd0fe964b1eaafb040859bb2d5bde52c89fe59aa31494d495cae1d6842a33",
          "sha256": "f498cc070ead3c74fa895bc65b2edb30c38e726e05ec440e57eb02fca4608d06",
          "sha1": "0d1f3ed34c0c0cf146d2360a801f45ee9df986d4",
          "md5": "ee0df5eb57f91833a7a0e6877da0ddfc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.4-sources.jar",
          "url": "vectorx-web-socket-24.1.4-sources.jar",
          "size": 11406,
          "sha512": "69b1b86395d619ef93601b67a586ee6ce08597e76a03d5e703f9f6ae9e323157db703fd7bc6edc84bd9d1f74e59dd776b52c467a5a9306791d81cea75834c39d",
          "sha256": "b5bafba8ce7cbee5786839c52a23800da4e18415f6c88690ad41edda9053ba6d",
          "sha1": "eee12cec963baeee4a156da2a5d6a57db902af59",
          "md5": "8b3b117682933e8addba2a2771b03e59"
        }
      ]
    }
  ]
}
