{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.3.jar",
          "size": 926456,
          "sha512": "0af1a716c92abff771f02e37183d4321f309e96010bffb66c491de39ef5d6784c3cec15ba91ba86a9b6790fdf925d3be81121a3cb40f60ce696fc2d3a94ea389",
          "sha256": "4bd31de8fad03542d3c9b38d39e7ea5a0ffddb6a0926e60d11f5ad4a36ecb00d",
          "sha1": "c3178dc1b4815d0dfa9a31ed2eb938f6fa1402ed",
          "md5": "9bf87265df1eb86547a6dc4865828f40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.3.jar",
          "size": 926456,
          "sha512": "0af1a716c92abff771f02e37183d4321f309e96010bffb66c491de39ef5d6784c3cec15ba91ba86a9b6790fdf925d3be81121a3cb40f60ce696fc2d3a94ea389",
          "sha256": "4bd31de8fad03542d3c9b38d39e7ea5a0ffddb6a0926e60d11f5ad4a36ecb00d",
          "sha1": "c3178dc1b4815d0dfa9a31ed2eb938f6fa1402ed",
          "md5": "9bf87265df1eb86547a6dc4865828f40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 1350447,
          "sha512": "122496455c6eac3fa83571c0458993b9cc9168812dd14e3c2da90923a07e7836234cc2df2876fbacefe2a8f5079a50be0878e6885259e4664dd99096bdf3c39a",
          "sha256": "d4ba6995c38ca2f2f42dbd6bf1955955a881a8b3dff0bb9b36dd3aed222c4094",
          "sha1": "c5044e5a3302dc7e6255820a91c426084f5652f2",
          "md5": "ecb75eb69bf2a594baa09d63950d2a9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 328558,
          "sha512": "0a7492ebebaf64511dc43e6505c236ab9a040fc1190d8989f599e64fae90aa354f674e12ee7484de0a625d8b871663a3723a34e965f755d5ecfb01241863b067",
          "sha256": "a733c53bc8a08f7f3ad43b7587a852a36c8613243df5317e5867af2654b672de",
          "sha1": "f180683380f829e95a492723d24cc063cd8022ee",
          "md5": "a27fb62b332a3258e0212f256e6faa03"
        }
      ]
    }
  ]
}
