{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8.jar",
          "url": "vectorx-autoconfigure-24.1.8.jar",
          "size": 184853,
          "sha512": "2eb6546121f1375f4a1aa5ef6df29426d51868ea2375ba7b080fd4d3b77c14bbd701152d414bbc1d39de9fb0b79d25622fd335b0fb601ec75e664509e91202e9",
          "sha256": "bb3c31bacf9014003e6f9aaa3904a47669835c25ed97b1949c4bad1881029006",
          "sha1": "0a9fec856de16ff1e8caf45975bb42215a25c74c",
          "md5": "ec1bec7bf433597064155223ee4e17e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8.jar",
          "url": "vectorx-autoconfigure-24.1.8.jar",
          "size": 184853,
          "sha512": "2eb6546121f1375f4a1aa5ef6df29426d51868ea2375ba7b080fd4d3b77c14bbd701152d414bbc1d39de9fb0b79d25622fd335b0fb601ec75e664509e91202e9",
          "sha256": "bb3c31bacf9014003e6f9aaa3904a47669835c25ed97b1949c4bad1881029006",
          "sha1": "0a9fec856de16ff1e8caf45975bb42215a25c74c",
          "md5": "ec1bec7bf433597064155223ee4e17e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.8-javadoc.jar",
          "size": 273609,
          "sha512": "04c4f4987580e11e147d3c32485d057f328e7833ad6a21c57d5600362436aed1fb7f35e296db7291481095156395147734615e90152703156c69ddcfe4d1ecbe",
          "sha256": "d7140d636ecdc9ca80da41c42db402cfc99dffd3059d1eb9e92429dddd6207fc",
          "sha1": "578ecc5289b4e8a7d8b48f0331c79335f3c96d77",
          "md5": "7a5ad96e1925b29d439cb542dabf30af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-sources.jar",
          "url": "vectorx-autoconfigure-24.1.8-sources.jar",
          "size": 69406,
          "sha512": "5d38c92be99da5201297fb6236da27690526cf6e97494c3fba9c52de2c8dcf0431649d8a8df9e169a75c9c4b6579cbe7ecb885bf0bb6db9d383ca74dd7fdad4f",
          "sha256": "6ae566715206a86cf296f09c2efe9f8a3de246a99670c80017b659591d49e958",
          "sha1": "08421586b183bb4a7de729df2e7100d13480b3ce",
          "md5": "0517912e3961591a3580d252c744e963"
        }
      ]
    }
  ]
}
