{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-eureka-client",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-client",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.4.jar",
          "url": "vectorx-cloud-eureka-client-24.1.4.jar",
          "size": 3037,
          "sha512": "72817ae16b187cfd0e301357c6b2a7f00b99469e7748b8512e932e24a600bb9d91267441c91d438f81bf5bd5238b434e8131f2ad8ae96660c5f75b1462d64366",
          "sha256": "3c725b2a0b5b63ca6a75b630595e08c3231bb360d61004a1547a713fd94d1dfe",
          "sha1": "2f5b3f7050584f1f0905bf5dfad04d5492c937fd",
          "md5": "daa0b640bfb1d6a84ab5d2396dac4dd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-netflix-eureka-client",
          "excludes": [
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.4.jar",
          "url": "vectorx-cloud-eureka-client-24.1.4.jar",
          "size": 3037,
          "sha512": "72817ae16b187cfd0e301357c6b2a7f00b99469e7748b8512e932e24a600bb9d91267441c91d438f81bf5bd5238b434e8131f2ad8ae96660c5f75b1462d64366",
          "sha256": "3c725b2a0b5b63ca6a75b630595e08c3231bb360d61004a1547a713fd94d1dfe",
          "sha1": "2f5b3f7050584f1f0905bf5dfad04d5492c937fd",
          "md5": "daa0b640bfb1d6a84ab5d2396dac4dd6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.4-javadoc.jar",
          "url": "vectorx-cloud-eureka-client-24.1.4-javadoc.jar",
          "size": 70758,
          "sha512": "55843d81215a87eadf4b78e99292421e81e8830092e23122bc500bcdcd4630c8efed2fb7a1c25391ea171056b9d1a3dde9d481087f58e209d060f225afac08a5",
          "sha256": "ccb955e6df1a77aac44bc56839d5b9aeb4430b3ea57da659d16b8b3887e95038",
          "sha1": "3f1ae851d8527286f01e1ebc27e417386c1ed6c3",
          "md5": "536cb9111690ddf8c197838ae872d25c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-eureka-client-24.1.4-sources.jar",
          "url": "vectorx-cloud-eureka-client-24.1.4-sources.jar",
          "size": 1473,
          "sha512": "402ed6695aa2692224f33410de20ace57ba70d8f19e96e5c399ba1f19c46177846cf7589d40344f2e24fcbd3ac8122cabfe5e547f91a3b3af13a2386ab507a41",
          "sha256": "d8ea74e026a4d1a317ab9ce55a376a50285354472e931d3906dd69a7f4738a5b",
          "sha1": "253993ebcce2a123c341ec2586dc3e0240e6f7cd",
          "md5": "23d7975953ffe41036b56ddba473fa5e"
        }
      ]
    }
  ]
}
