{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.7.jar",
          "url": "vectorx-web-servlet-view-24.1.7.jar",
          "size": 21072,
          "sha512": "5be11f8b410dcea040614b406b47a2b7e1e45e65abb24958cd87133a3c9fe8d24c06ef1c0dda4660db80d8557c9bfd236bdcbb5f84326c0b43748e8c7d1c693a",
          "sha256": "61a405390f524f4f9c6985102494c963d258462613b285c3a0f6a9f794c18b31",
          "sha1": "c91bf74166e59f8b4215e24ec44d363940ab8410",
          "md5": "4aec9b6c2d07f1f3c42e65a0ba24652a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.7.jar",
          "url": "vectorx-web-servlet-view-24.1.7.jar",
          "size": 21072,
          "sha512": "5be11f8b410dcea040614b406b47a2b7e1e45e65abb24958cd87133a3c9fe8d24c06ef1c0dda4660db80d8557c9bfd236bdcbb5f84326c0b43748e8c7d1c693a",
          "sha256": "61a405390f524f4f9c6985102494c963d258462613b285c3a0f6a9f794c18b31",
          "sha1": "c91bf74166e59f8b4215e24ec44d363940ab8410",
          "md5": "4aec9b6c2d07f1f3c42e65a0ba24652a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.7-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.7-javadoc.jar",
          "size": 134632,
          "sha512": "c03b25a89061deb468335708eda3410f3c11015b4374954df812cf6cda0da2c35c24cc80b1ff6472647497b29e703daf3ec3a7bdc61be606744fe0550b0612db",
          "sha256": "8b021fd07839158eb02982a8c79b51b89ffb9aa162ebc25d82401a0259bb50b6",
          "sha1": "fb90e3932d151fd36d7909c02aa915207a70e702",
          "md5": "828d2cf774923a85d775235241bc04ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.7-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.7-sources.jar",
          "size": 11406,
          "sha512": "e24949a339e36442f0c6530f3d9b0430aa3d5cbac1ed4d2d20ed7238ca48979138771b9368ab7da34cad272364abff4edc9b3d2d725cb80cb6902945cfdfb653",
          "sha256": "6ad131d8e152b4df59e075218be64534b26fa6e095633bb3d07b2cc09e298392",
          "sha1": "6441c66bd41afac78133c78144237bd69b81c9a0",
          "md5": "1e1153609365e491a1e0743d2f9304c7"
        }
      ]
    }
  ]
}
