{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-core",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.1.jar",
          "size": 10006,
          "sha512": "d6f4cc577e23e3b16185bae86f1c343cb0eb3c4288e31a07d0b32bceaafcfb46294b5a3dbae586326c7ae40c543594b0cbc780f7ee30122deaf3bc21e2806435",
          "sha256": "4760fa17ef050c33241c8246e9342f25ecbae5eb765506a1c85584e18894f8a0",
          "sha1": "95fb2dfc8a31d5d6f0301184f4e068d9ed1b1a06",
          "md5": "86569a0312d468e7c9a06f9a4d7be9a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.1.jar",
          "size": 10006,
          "sha512": "d6f4cc577e23e3b16185bae86f1c343cb0eb3c4288e31a07d0b32bceaafcfb46294b5a3dbae586326c7ae40c543594b0cbc780f7ee30122deaf3bc21e2806435",
          "sha256": "4760fa17ef050c33241c8246e9342f25ecbae5eb765506a1c85584e18894f8a0",
          "sha1": "95fb2dfc8a31d5d6f0301184f4e068d9ed1b1a06",
          "md5": "86569a0312d468e7c9a06f9a4d7be9a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 103875,
          "sha512": "d189bd5d6825a57f71edbc0e3a93a33830600b2356e0eb7884d319d3bccc9e5edd2446812f0c8fe19a688563713a5fdf7f0da5c7ff4543ed88f3368bea9169f3",
          "sha256": "56f38e323dcc1002c2bc44b48b7d36023126478237cdc52a2553a9d04fef5394",
          "sha1": "927d6d5ed816b28a159ab90558463d76320705a9",
          "md5": "e736ed8a1dae22067cfe4d5134a67d97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-web-core-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 5581,
          "sha512": "f72d1bbc1b5e74b811f8e24de2b27f3b93d5fdac63ef66e596f10c7e8fb8b65adb34c527933ad6bf2fac2effbcbc3c94b9afbcc4794cf66bb6695ed1f46913c2",
          "sha256": "92fa99449572d3597c9201a0eb75d2cba54ebcdf50f109622e321612d003db89",
          "sha1": "31f320b41ad43837224985d9da7ca0576068b32a",
          "md5": "5ba067d50da57529f24db5f11f69b242"
        }
      ]
    }
  ]
}
