{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.4.jar",
          "url": "vectorx-cloud-aws-24.1.4.jar",
          "size": 2750,
          "sha512": "701f0d2c5c8614e976a67b6f91eb10dae66291b3fc71dae89a19ad20efd36a8320d8958a132ce697ad4d9d1737e9321d5b803fd72eb009be441b5bea0390d1ba",
          "sha256": "6a4699878ea769a9fa5a68cdb4ff2f6f4ebcfd75d682e5aaed41c6cd05ba1137",
          "sha1": "1350bba9f3f80738ef342a0fd1b300e08ab5358e",
          "md5": "6b5f658c46a0e7148eaf67f0cfd354be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.4.jar",
          "url": "vectorx-cloud-aws-24.1.4.jar",
          "size": 2750,
          "sha512": "701f0d2c5c8614e976a67b6f91eb10dae66291b3fc71dae89a19ad20efd36a8320d8958a132ce697ad4d9d1737e9321d5b803fd72eb009be441b5bea0390d1ba",
          "sha256": "6a4699878ea769a9fa5a68cdb4ff2f6f4ebcfd75d682e5aaed41c6cd05ba1137",
          "sha1": "1350bba9f3f80738ef342a0fd1b300e08ab5358e",
          "md5": "6b5f658c46a0e7148eaf67f0cfd354be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.4-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.4-javadoc.jar",
          "size": 70365,
          "sha512": "1ed617dd66409fd63b390d9ab1595c0188fccff27498bc8b1039bc225ee7854db6cc64d4bc4baad170463a6bb1ba555d1de9ccdf6641539e82d3393566f3a93d",
          "sha256": "5ad02108a90903edc7d3cc48425ec7b18552b3ad1deffd0a737983f302108bc7",
          "sha1": "34ebfce52c611cad5a7610819a3c9c03a88c087b",
          "md5": "5069a4bc84adffaca4d3af106c7a345c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.4-sources.jar",
          "url": "vectorx-cloud-aws-24.1.4-sources.jar",
          "size": 1228,
          "sha512": "306d4e43206c08adc0c46da0c7b5ed7590c2a4a2eb2eaff199d78bf06b82ef2277f4d05eb6570b0a7b4cbe11d64c2fb8cd0f9fd766ce47d5d818f2011bca6559",
          "sha256": "3c89a24ee7f2d0e142546480785340ffdc2b3f3bd9cacfadc87e2cbedd74014e",
          "sha1": "6205a2a10c30f16a99b03e6d99b4c29ebbc32813",
          "md5": "324ded6dd8d2871d9dc5d2b531754c29"
        }
      ]
    }
  ]
}
