{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.4.jar",
          "url": "vectorx-cloud-aws-24.1.4.jar",
          "size": 2750,
          "sha512": "3701d3b79530e24d0651d03e4ff740ba7e687ac505b60188352aedd007b8a749efd2019a6febfbdb467fbc3035349f999df016d2d5643d117a0da2615a9b0291",
          "sha256": "8b3a68be44fa7f581456dbf2219233c2403b6573c29fbc3a243a75f98bd4db7a",
          "sha1": "98fe00e89293c5fc2324887d76503ad896dc5c8e",
          "md5": "ec64b35743b81f39a1465cd53cc6df5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.4.jar",
          "url": "vectorx-cloud-aws-24.1.4.jar",
          "size": 2750,
          "sha512": "3701d3b79530e24d0651d03e4ff740ba7e687ac505b60188352aedd007b8a749efd2019a6febfbdb467fbc3035349f999df016d2d5643d117a0da2615a9b0291",
          "sha256": "8b3a68be44fa7f581456dbf2219233c2403b6573c29fbc3a243a75f98bd4db7a",
          "sha1": "98fe00e89293c5fc2324887d76503ad896dc5c8e",
          "md5": "ec64b35743b81f39a1465cd53cc6df5a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.4-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.4-javadoc.jar",
          "size": 70365,
          "sha512": "fcac840c668ab837e2e5be006c2ef9603201c31dd213eec0cfc2a2a3640823aa860db3e620fd6d7e127783e416605daf5c5b8ba72ec2ff3ee5e738ec4760fe3a",
          "sha256": "98f56426305b3244ee043e6f785e95e1e09d970551e1425a9a94679214135632",
          "sha1": "8adb5a44c48662c62085010a463118a29406aeca",
          "md5": "47f3c7bfbc0166866b3ea95353cf447f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.4-sources.jar",
          "url": "vectorx-cloud-aws-24.1.4-sources.jar",
          "size": 1228,
          "sha512": "b434ac2e2e785f41fa363a23f74559c0de275bce15b4d500e5877edb5dab75967e0acdef4b45a0626a219d95f2844f010871920d86ddf97b05622da78a33bfa7",
          "sha256": "4980ea7b40282643c680bdd96918fd1bd92738fca32f6c8bffacaf3dd8c0a94c",
          "sha1": "34ab90ac5164af5923224ace6ce77fe203e2bbba",
          "md5": "6de196a108a95f150730c7431f69b8e6"
        }
      ]
    }
  ]
}
