{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.4.jar",
          "url": "vectorx-web-servlet-view-24.1.4.jar",
          "size": 19208,
          "sha512": "16053db2dc607b4a320f57fbd828e85beefddaec5f6f49dfe5306e225a86e61df9421093109624b455dc3d8156e6dd1ef76f0207de3f9bbcaa6fea579f7f21cb",
          "sha256": "a55ff4de5ee37a5b467660db24b852cbb9d97b14fa14bd756fe1160c21fb812c",
          "sha1": "dc2807d006f5483a162e0b5684310376f521c403",
          "md5": "c0b1b4800a1b8d250d7c821a37ee7cb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.4.jar",
          "url": "vectorx-web-servlet-view-24.1.4.jar",
          "size": 19208,
          "sha512": "16053db2dc607b4a320f57fbd828e85beefddaec5f6f49dfe5306e225a86e61df9421093109624b455dc3d8156e6dd1ef76f0207de3f9bbcaa6fea579f7f21cb",
          "sha256": "a55ff4de5ee37a5b467660db24b852cbb9d97b14fa14bd756fe1160c21fb812c",
          "sha1": "dc2807d006f5483a162e0b5684310376f521c403",
          "md5": "c0b1b4800a1b8d250d7c821a37ee7cb2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.4-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.4-javadoc.jar",
          "size": 132219,
          "sha512": "590a790a567aa78b65e807aad9e28499d6ad536ab133dfc4e4574bc2df02d12501e50b6e9ffef3b01e72086e6226223f4e4696f91aae0e4c36f1667c24a62aae",
          "sha256": "564705b3f4f9a9e6b553c11304b1be0aa19ad3c299ca7b70ddeb562d79f23342",
          "sha1": "66bb493043eff25d25156ec349f900a47924f0b9",
          "md5": "763e86fbd8b6fcfdd964550ae8d6721a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.4-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.4-sources.jar",
          "size": 11247,
          "sha512": "353085852ee1279a33f4188640437d650c8694fa83bb2808213fd54d6cd718fc649dc61373a144b45343357bde6e7e053d8500f0b328059da3c13b7fe63966dd",
          "sha256": "367ac788da3b161ba2864873994c8f1a3d80f408881f73deb6823e45d3a9a3c1",
          "sha1": "05706ec83fe81dc7f18d322cd5ac6057a77cc5c7",
          "md5": "82d5b3c0d155f2f22c71dda771c06763"
        }
      ]
    }
  ]
}
