{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.4.jar",
          "url": "vectorx-web-servlet-view-24.1.4.jar",
          "size": 21025,
          "sha512": "ce0b960bf4562b33c96df02e43fd9f901f9e5787978ea4cd554961e7a20f6a6f5bcd136ef0558f98526d495953c147f5aebda8cca494d2a5784667ed251d6f6e",
          "sha256": "c43a7d2df35ac8897854635a76db6d6656e0cf014716460e5b3af3a6fd2ae71c",
          "sha1": "38e2b2c7c8f6a515271bfb4577dbb43fcf6d7676",
          "md5": "9149bc9d20296ab36339cf4e4843ba3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.4.jar",
          "url": "vectorx-web-servlet-view-24.1.4.jar",
          "size": 21025,
          "sha512": "ce0b960bf4562b33c96df02e43fd9f901f9e5787978ea4cd554961e7a20f6a6f5bcd136ef0558f98526d495953c147f5aebda8cca494d2a5784667ed251d6f6e",
          "sha256": "c43a7d2df35ac8897854635a76db6d6656e0cf014716460e5b3af3a6fd2ae71c",
          "sha1": "38e2b2c7c8f6a515271bfb4577dbb43fcf6d7676",
          "md5": "9149bc9d20296ab36339cf4e4843ba3d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.4-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.4-javadoc.jar",
          "size": 134636,
          "sha512": "35fbd1137bc59517fcee5d66cd57ed1c3a4ada61f439d7c26cf0437d20cfc60a719a6b30d16504133e17ffc3094ef2977f3fd5d9b8209ea505b5ce40956bfcc9",
          "sha256": "2167bbbe46a93f929b8fd9d4a7135d57a40a59d1696586852adf13395a1e0a02",
          "sha1": "67f16a728efcb13b2fd7dc8fe3688681c250401b",
          "md5": "ed3c02759ded942a36f13e72fbd6110a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.4-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.4-sources.jar",
          "size": 11406,
          "sha512": "1a09a114a456c4ac5522b5eafa39b63add47259b2509ce66680e1142537cf004adb25ce8a4115cfef4618a0ba1948b3477b9a4d8c966079c695c673930e3ce58",
          "sha256": "9777d39e1c506c55ef3eed3fd6a1123e4b809f9fe10fd43c5a125d1b5245ba61",
          "sha1": "552c323805e00f0b57a8067b6ffb184198270cf8",
          "md5": "abf061aaca7b2cfe580be2792424fce2"
        }
      ]
    }
  ]
}
