{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-core",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-core-24.1.8-SNAPSHOT.1.jar",
          "size": 213253,
          "sha512": "bccdc1f3b7ebf92e00771b928efa59d7484842b9a59f27c55301397dda0d349e0896f2afd505202f54f81f6bea4fbdb238179070c0e7ca3984e0629e1c6f7af3",
          "sha256": "36d077b18874c7f97d68377376c72a8956edf0431f93470035947d4f3cba4579",
          "sha1": "d3a42c965e5293a3c646c0eb0bf60a22baae72fe",
          "md5": "cf12a3f0e20727c60d9e94a91a2c8d6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-core-24.1.8-SNAPSHOT.1.jar",
          "size": 213253,
          "sha512": "bccdc1f3b7ebf92e00771b928efa59d7484842b9a59f27c55301397dda0d349e0896f2afd505202f54f81f6bea4fbdb238179070c0e7ca3984e0629e1c6f7af3",
          "sha256": "36d077b18874c7f97d68377376c72a8956edf0431f93470035947d4f3cba4579",
          "sha1": "d3a42c965e5293a3c646c0eb0bf60a22baae72fe",
          "md5": "cf12a3f0e20727c60d9e94a91a2c8d6d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-core-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 508818,
          "sha512": "ebc888c3921ed6cafea3b397c05ab3c9d54b4ceeaf02380120b4909c8e345c014da99d1944affd7ef66305f0d37f9813340beb152d051ab9e433dac1a564ffdb",
          "sha256": "47471d3cb8363e7a3b711639cefab34bb6250fabf90a687b0e3c5860d1b96fba",
          "sha1": "83dbd5e8466f056446b9044476edfad0c60b8b1c",
          "md5": "231bcbd2b38ee88ae9ee86a217d981f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-core-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 102660,
          "sha512": "aba45b61f1e01f461030db21083e1423c7a50f5963ded4d58ae14416fc3b9808b4d9712319cfe19db0ef01ffd312b30d21187c12f75d5a36d8672c4c395e7871",
          "sha256": "b89d8c945a9bf89c5b2b350894796539880d86f5b6e63da280f6a9af6d837825",
          "sha1": "2f0ee2d4a80ad822fed9ec4124cfd093c81b4a6a",
          "md5": "cfaa0886f2dd1c2432b51c2087509583"
        }
      ]
    }
  ]
}
