{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-rest",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-rest-24.1.8-SNAPSHOT.1.jar",
          "size": 46273,
          "sha512": "57cc76e244925d69128418071899b62bad7b61e7e6f7892409fd82628c00f7cf2b4ce462daeab1fd242ce0a82f53aceed5f809fc541a14283015742ae686868d",
          "sha256": "6c8f3148d53788a5f2bb4bff0451dfd840581bdb05add8d3adafb7e234a66422",
          "sha1": "0a06b9ba73e3b0f2ca618205318579ce2da9b7f4",
          "md5": "46fe7e9fa90e3ece5749f23b9fd8da2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-rest-24.1.8-SNAPSHOT.1.jar",
          "size": 46273,
          "sha512": "57cc76e244925d69128418071899b62bad7b61e7e6f7892409fd82628c00f7cf2b4ce462daeab1fd242ce0a82f53aceed5f809fc541a14283015742ae686868d",
          "sha256": "6c8f3148d53788a5f2bb4bff0451dfd840581bdb05add8d3adafb7e234a66422",
          "sha1": "0a06b9ba73e3b0f2ca618205318579ce2da9b7f4",
          "md5": "46fe7e9fa90e3ece5749f23b9fd8da2c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-web-servlet-rest-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 181682,
          "sha512": "eb108e119f4500658b4b2f3633dd36c771c8687dff52f5eac7d752b47eb962be15d03055f99ed180bbb6adb6686cd4ffdedba1183bb75191a9aad2dd62b88d02",
          "sha256": "81ae2ab526ee60f5d709fcbbde54fa32973774b1f2deb5a2776964a0dad4199b",
          "sha1": "ffcc34cd2310cff83e46b366abb2872b0526846a",
          "md5": "fbefbb3fc32e43bc520f88bcd64ae834"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-web-servlet-rest-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 24303,
          "sha512": "03ab73f84e04812732f56246d73914cdc36ef553bd5a563e5c5cb57155a06087c5efc2e88982e81c8b3e9e3eda36fa38f4607ebeabc911192d11d021441ee02d",
          "sha256": "c9487e4deef90a051ecffb318b88a75daacccecd32fb2d3db3d4261d7401614d",
          "sha1": "30238e7bf9c5d6818c498cba71331fce17600aae",
          "md5": "5f51a4fa3b048440b0e685ad01e55edd"
        }
      ]
    }
  ]
}
