{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.9.jar",
          "size": 110180,
          "sha512": "0c9c6051d346fedcb4e8ba5c6f809cf7b94597abe065d42bb8f237ddf4c04b8980c7d37274c4b2b4bcf8fd3503edcb4d691841b78a85526937aadf2ed40308e3",
          "sha256": "34a85e4eebfb1c7da0ea95e0c8217e33fa28de0c90892889ce062732cfd34709",
          "sha1": "72b528a2297658b7f9a646f1ba6932533d3f0d4a",
          "md5": "8768cd5f7ceafd992690bb765b7a8da7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.9.jar",
          "size": 110180,
          "sha512": "0c9c6051d346fedcb4e8ba5c6f809cf7b94597abe065d42bb8f237ddf4c04b8980c7d37274c4b2b4bcf8fd3503edcb4d691841b78a85526937aadf2ed40308e3",
          "sha256": "34a85e4eebfb1c7da0ea95e0c8217e33fa28de0c90892889ce062732cfd34709",
          "sha1": "72b528a2297658b7f9a646f1ba6932533d3f0d4a",
          "md5": "8768cd5f7ceafd992690bb765b7a8da7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 306448,
          "sha512": "6c0113c82900c461f777cbc64ff34f01585756ff4c5cb9f48fd780f04082cc98230e51760667b8d61da53ea0157baa467c625be1be8109e924d88a860441c05e",
          "sha256": "1ee6e1f3e0ff0b2421931128957ad47cb1912c3e1aab33f0a9562cc363505cf8",
          "sha1": "b9d3488ea35177f6f6dcf2222ea83088cad3b42d",
          "md5": "ff398202bd24573ee6f527667c597a29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 70739,
          "sha512": "288927cbdb8eaf792941514599b70169786d1314adefcffa6c742e6de02c808efc66017777d1d25d3ada78a6fd11a65fe6acf6e8fab6c54c0a4b57bf43377d7e",
          "sha256": "08eae4eda3db2921c29475284eebc70e421c0cc37519761387c25f54c426f977",
          "sha1": "90ed562c5106b11ad93df2346b9e9dc91b251b8b",
          "md5": "73e582b067270df3e700638af38d927a"
        }
      ]
    }
  ]
}
