{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.6.jar",
          "url": "vectorx-net-24.1.6.jar",
          "size": 29716,
          "sha512": "e6e20a8f465eb1234fd29aa1e6e642d5c4f743298e8e344f4b0d6d57bdbe45f901cbf07c42f371712f4e40dcafd854fdf6d5f6dc13302c1f12d20c58231f8b75",
          "sha256": "b0d65bd0ae6cfc314d2a857116c0e0c607e2694483ba7d0fdc30dd05bb130b12",
          "sha1": "deec816708dcbf6618eb7d752eed311b4d42c194",
          "md5": "c62d24ea4dbf160fdd4fa490a769ed4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.6.jar",
          "url": "vectorx-net-24.1.6.jar",
          "size": 29716,
          "sha512": "e6e20a8f465eb1234fd29aa1e6e642d5c4f743298e8e344f4b0d6d57bdbe45f901cbf07c42f371712f4e40dcafd854fdf6d5f6dc13302c1f12d20c58231f8b75",
          "sha256": "b0d65bd0ae6cfc314d2a857116c0e0c607e2694483ba7d0fdc30dd05bb130b12",
          "sha1": "deec816708dcbf6618eb7d752eed311b4d42c194",
          "md5": "c62d24ea4dbf160fdd4fa490a769ed4a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.6-javadoc.jar",
          "url": "vectorx-net-24.1.6-javadoc.jar",
          "size": 128285,
          "sha512": "c445b6db460a48cdc21e5d4ca5158270220e4e8397f3df8a18190521cbe888c6ff3f1aac3219abd8f8f31eecc9830b7debf83764428da0715326d7dede5b5f95",
          "sha256": "553df547f2e1c63a36d66e3856f0d36803b97b5cf98c84847639df917b174522",
          "sha1": "8b91f556f442b160c60826e521422ddc9d0ab542",
          "md5": "cd98db32f79df435cee198b316e7dae5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.6-sources.jar",
          "url": "vectorx-net-24.1.6-sources.jar",
          "size": 10137,
          "sha512": "aefbfac593c92843857f26d12f2eea80dead22bf3653fefa982f7dcb0c6ddd5b37a3d9e62e161a1aafdab6e67fc43a1f7b936f6e3474c2a313cc021fa8d00fb7",
          "sha256": "303582b4c81815ae39afdadf35b142d0ddcd30dec80d099941a8c62e0866e6f5",
          "sha1": "f60ee13275598e051a4568e0a5f0a054194c5794",
          "md5": "db3fbc13265eb016036197b51e526e15"
        }
      ]
    }
  ]
}
