{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe-xplatform",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.1.jar",
          "size": 3348,
          "sha512": "e0042adbef1f9e187f12c361d496061099258910e6191a6d9d4f9b35cbc2aa0fe64c07c267077efe807062074a1aec68ebf04d78d9bc1f3715ebe659c8f39d52",
          "sha256": "3a1398239bce9386bf03b9e2488e2a0e720ea898094188bafddc0a63b9d97ca2",
          "sha1": "1a84a2652c3d53db33c93a1c25107a6ca73308f8",
          "md5": "dca0a38a29139c9f7dc01037ff5d2b33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.1.jar",
          "size": 3348,
          "sha512": "e0042adbef1f9e187f12c361d496061099258910e6191a6d9d4f9b35cbc2aa0fe64c07c267077efe807062074a1aec68ebf04d78d9bc1f3715ebe659c8f39d52",
          "sha256": "3a1398239bce9386bf03b9e2488e2a0e720ea898094188bafddc0a63b9d97ca2",
          "sha1": "1a84a2652c3d53db33c93a1c25107a6ca73308f8",
          "md5": "dca0a38a29139c9f7dc01037ff5d2b33"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 70953,
          "sha512": "e5ca46f281a5eebebd9dc794a6339b751c60a0d1d4287d82d717792fec74aafd8fe6fc2645196622835512896fb7f76d44c3a7f3e1f2c050726c431313149fde",
          "sha256": "0908de9b19a3454eb8dafc482c7402972d125b5d2f4b6a3f85d818ea3c7e55d3",
          "sha1": "60307a185067eec86e3ac0a7f2b550feaea3ad28",
          "md5": "ce97308cfb02c4f679ad5354d6d9fb91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 1674,
          "sha512": "d473b0b4798a577f59063226d8348d54853dc5413d042f96e1c9346706cf1721e71dc9fb2d1036ae9090a9b6641a50c3ae6c1e1597929d72198552d805383322",
          "sha256": "8c982aab5607f61320916917f78eb3bf8034c502dc36b09c808b0b659de34966",
          "sha1": "e25c390e1eee0cd681d0e027e4b1dbffcfc4106c",
          "md5": "cf24521c8238cc9f8b959f8c8222c4a5"
        }
      ]
    }
  ]
}
