{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-rest",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.4.jar",
          "size": 44338,
          "sha512": "cb760a6a9f49df40c245d8189e58efb916aed863249d97dd268a53b3f0f14e754af78256dd4852adbe4c433f61ab1ea6ea7299d563d5d0b2e70f31ddc8e35787",
          "sha256": "067919f3a32a6b65b10b8d7faa49ce7d3d83ca108d10316c56eba5a96977fe7a",
          "sha1": "dacaaf961706d48e137bdfe11c8c54364f8c3f40",
          "md5": "df8faad65b5f1d9b8b1a45c67d789b79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.4.jar",
          "size": 44338,
          "sha512": "cb760a6a9f49df40c245d8189e58efb916aed863249d97dd268a53b3f0f14e754af78256dd4852adbe4c433f61ab1ea6ea7299d563d5d0b2e70f31ddc8e35787",
          "sha256": "067919f3a32a6b65b10b8d7faa49ce7d3d83ca108d10316c56eba5a96977fe7a",
          "sha1": "dacaaf961706d48e137bdfe11c8c54364f8c3f40",
          "md5": "df8faad65b5f1d9b8b1a45c67d789b79"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 179714,
          "sha512": "5af5fe97228d10aeaf0e5b0ac2f73d4423c1f9dd167a94697c688d747be79d21a09302614b89a12bde5d0b360a9c4a5ae1a5b948413773581e81d5817fc47bed",
          "sha256": "b8a92eb3ba0968f1f9669683eab3e06be3a8f8efcd69b0ed668398c9e934cbef",
          "sha1": "e15a88219c06fec2fb84658e7a58de0e56df6a75",
          "md5": "88d7b14b833aad8722f671ad7c7e5b08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 23886,
          "sha512": "05ab0b6f7dc9238b374247888a65d44ad941e306643e1453677fdf3fcbcdbb3dc80d9e8e49c3fde7d1c11b63891037815a5c20ed21b8f8a5a327da33c6580858",
          "sha256": "5d724171b47c95c65b001dc4cfc5bab52564f58bf2a97313fdda3af3458c3b32",
          "sha1": "3bc33e5b941815c1b6b4a0eb6b7be51b94feac4a",
          "md5": "d4c7905565a387248f1cec3c2211280f"
        }
      ]
    }
  ]
}
