{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.5.jar",
          "url": "vectorx-cloud-aws-24.1.5.jar",
          "size": 2752,
          "sha512": "e70f85b8749c779d6fa763bfcca4d4b7f5fb6a277a729a323201aad73d05b0e493ace9f192ddecea6a9fe2734fb101eabe73f24fb2714fd64100d0bf0169a0fa",
          "sha256": "70ae556f0b18b793049dfc569bcd991dbe977618ab4128bcab606153e95eab22",
          "sha1": "3b44bed5043e54975e66b16ff7b6e7849c7744e4",
          "md5": "ec28049107ad89e1df56f6fcf2ae526b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.5.jar",
          "url": "vectorx-cloud-aws-24.1.5.jar",
          "size": 2752,
          "sha512": "e70f85b8749c779d6fa763bfcca4d4b7f5fb6a277a729a323201aad73d05b0e493ace9f192ddecea6a9fe2734fb101eabe73f24fb2714fd64100d0bf0169a0fa",
          "sha256": "70ae556f0b18b793049dfc569bcd991dbe977618ab4128bcab606153e95eab22",
          "sha1": "3b44bed5043e54975e66b16ff7b6e7849c7744e4",
          "md5": "ec28049107ad89e1df56f6fcf2ae526b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.5-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.5-javadoc.jar",
          "size": 70364,
          "sha512": "faccdc6ad31bc1b74a16cff0014c3827f172c0e803e3ae750791cc53e5579ef102ed46f0662adce9a5548a56f8f98bd293947e81129270f346576145b215fc40",
          "sha256": "b264a8217eaab1802e1989f21b3590827571104512cdaaa5e6fa18258656143e",
          "sha1": "a71abca180d945da954f66a43a57ebf2b2f3fde1",
          "md5": "ea7439b0ca991d36dc8504fca5466844"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.5-sources.jar",
          "url": "vectorx-cloud-aws-24.1.5-sources.jar",
          "size": 1228,
          "sha512": "8985a3a764ad99601e3846f6f8ea89477fc704a130ddd05d9d807688c3fbc81acce768918a6bc525153a0ed99fd1965dae37232b2c6662bc755bb51da8c1d52b",
          "sha256": "03d2c14d74a869836167d10d3c875aa9bddc73bafe91443c838ed12f47b7f384",
          "sha1": "b8c54a7f77f8ae9b6eca7acd971dce5d32084293",
          "md5": "d69d3f7e0f5ac15229225ee7feca21c5"
        }
      ]
    }
  ]
}
