{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.6.jar",
          "url": "vectorx-cloud-aws-24.1.6.jar",
          "size": 2752,
          "sha512": "35582797f62bae306b8cdab8ca43c261782daadc7cb0f72574091adfc2f0ac23c6781690653943052ca6209c452ea739dee27c3bd7bcc0b16b044a570961e91c",
          "sha256": "2cecb202ab48b50390db76716f3e26a8566364f0cb09eaba3e9202a5bce0a799",
          "sha1": "251d6cb6de37aef105a4a6ac5ca8716d77817fbf",
          "md5": "c20040413352d63462c635d791d883bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.6.jar",
          "url": "vectorx-cloud-aws-24.1.6.jar",
          "size": 2752,
          "sha512": "35582797f62bae306b8cdab8ca43c261782daadc7cb0f72574091adfc2f0ac23c6781690653943052ca6209c452ea739dee27c3bd7bcc0b16b044a570961e91c",
          "sha256": "2cecb202ab48b50390db76716f3e26a8566364f0cb09eaba3e9202a5bce0a799",
          "sha1": "251d6cb6de37aef105a4a6ac5ca8716d77817fbf",
          "md5": "c20040413352d63462c635d791d883bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.6-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.6-javadoc.jar",
          "size": 70365,
          "sha512": "96a0da4c1b091c348180d16e43ab76b782f717f727d555b933822c34a682aa2860b932ade9ea13228720b478e2d5e1229ab2f621dafdbf30b3064f93b7aaa204",
          "sha256": "7cc2025aa3d3ea2dd2d1f17be02e87e4e81f974cd97b0c53ef1f7e20cd50dd32",
          "sha1": "14c041059a3d34e5d0cbaf485e60832ed163360f",
          "md5": "2b5a04ad9eee4c61afa180c352a27223"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.6-sources.jar",
          "url": "vectorx-cloud-aws-24.1.6-sources.jar",
          "size": 1228,
          "sha512": "088c4eafa171a08bd1c887b89c6976ea4044c37a5520b9c730ebc79b8c137b7c23a87f2dc589e2f91c70bafbd02c5c5d9939d2c25e757f9cfe58c04c993d7d55",
          "sha256": "75eab951ee63edf5d50db56a15ffdabdd4775ca3f0a83e87e78f879678a83d47",
          "sha1": "27535e341b892126584b94ed7f5cd1e0933188ba",
          "md5": "d04ef161d255937624af09fb8c1fec37"
        }
      ]
    }
  ]
}
