{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.1.jar",
          "size": 145554,
          "sha512": "7f80baf7f7d51413ec16e06b73bb622fa33877f1a3a82d01c0bb54a3609351dbf7e567b7f87b51d93451bb5496a2257a7db5f51baa8f40180b487fd98def5f74",
          "sha256": "8f8517df0e7e41ce45c0ed29ed0512dfa0addfb0ab69eccb85ca24d9d9241792",
          "sha1": "9c94d6f746416b46a613d71ccc312c69586094e9",
          "md5": "d7bc19e4e4ac4e76ddd716322a686001"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.1.jar",
          "size": 145554,
          "sha512": "7f80baf7f7d51413ec16e06b73bb622fa33877f1a3a82d01c0bb54a3609351dbf7e567b7f87b51d93451bb5496a2257a7db5f51baa8f40180b487fd98def5f74",
          "sha256": "8f8517df0e7e41ce45c0ed29ed0512dfa0addfb0ab69eccb85ca24d9d9241792",
          "sha1": "9c94d6f746416b46a613d71ccc312c69586094e9",
          "md5": "d7bc19e4e4ac4e76ddd716322a686001"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 306901,
          "sha512": "7ed3a4ceea8eb79b10e3edbb70fa97749d8593b14e592c224bf076c6cc7677d6e99a75288b9276c68fdf48cf6760432ec42471a6fa3e7859f08792873c9c6e89",
          "sha256": "b405552e446753d25c69e6b78a06ae03994b54ae9b9584bdded251acabaaf5b0",
          "sha1": "694810979363eafcd0d62dbd0ed471d5bd35fb48",
          "md5": "3f71d23f841298e22ed580a2be005abf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 59353,
          "sha512": "85a142b6e01425fe6b4853bf6ffcbeeb69f1cf208c4d656f12f3f78e32c636e29409fee9b692c7e6325e40aab4413204e8df3f0fb6e347d882a2fe564918a412",
          "sha256": "7e562abf9e2573d017bc0452c3002b81c856af2713215470a722c1a2ff34f68c",
          "sha1": "0a432db50435b410aa3e4a9fd35bc77bd16f4524",
          "md5": "71acade317700315bd3c7192c242db04"
        }
      ]
    }
  ]
}
