{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.13.jar",
          "size": 22855,
          "sha512": "94289e560b39b67a9cbaa700f666d2b378f8b8e0df57c72e265d9bb866280a50f8d3065a212b31310fe0accb179ed24b8febb3e345fe20a0c5fd33eafe0b995e",
          "sha256": "3bea9acd8a1ee998f98b2530fdc3e80c84765178ccee96798c3f5b812b3239dc",
          "sha1": "3e813f95f5b91ba8d841ed83dcdf7f5770e4e8ec",
          "md5": "bdc007d4538770d165c0e7ce622c0d08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.13.jar",
          "size": 22855,
          "sha512": "94289e560b39b67a9cbaa700f666d2b378f8b8e0df57c72e265d9bb866280a50f8d3065a212b31310fe0accb179ed24b8febb3e345fe20a0c5fd33eafe0b995e",
          "sha256": "3bea9acd8a1ee998f98b2530fdc3e80c84765178ccee96798c3f5b812b3239dc",
          "sha1": "3e813f95f5b91ba8d841ed83dcdf7f5770e4e8ec",
          "md5": "bdc007d4538770d165c0e7ce622c0d08"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 152049,
          "sha512": "0427a2bedbaf91bf6aa5959e5ed45184c55a7f9a8b665feef4ed8f2b79c892fec68be29651552c1e336d2571d9297f63e586ec996d3f05548fe1dd60cf451b29",
          "sha256": "14ed4916b5ddc5ec4ceff5405dc1e1600407a52212a2264cee6ca2a18a2e13c1",
          "sha1": "4432e33a44eaacdb317761b2db40c79df198937b",
          "md5": "e4776a36d0717a88bf5b5d2f83f60035"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 12303,
          "sha512": "09774983656087c4af29d3b9b94017b2e3dd8f44d970dbbf25f115996c1ec74c88bd53192ddba1d9439bb6f7c1aa368f6ba4ff2473797991adb4a0fa167dcffb",
          "sha256": "78d8210ab99c8a83d81a884ece4aabd7f52f77c7da6268b07a2b0c67dc2f36f0",
          "sha1": "f7590aedd522deaff7c7d6a18a91b26aeb2312be",
          "md5": "0b0563265c80a66d40d792833fc8891d"
        }
      ]
    }
  ]
}
