{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.5.jar",
          "size": 22700,
          "sha512": "b792502b1ca3ac3c8e731f5a4c1c96b167ef9c29cdbcfd09b7cee1af3d7719cadfed268b8e7b8fcfa129d5f923063db7a578a80fba71c556e16f772645064211",
          "sha256": "37372bb29e8fdf50846ef87698d92dc4e87a30ca403c3b7a33ea6ea7a0022f04",
          "sha1": "c15cb45e7aeb4396703df330e96134626b384f45",
          "md5": "28f3a22eb131f08231cf9f4c9a63897a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.5.jar",
          "size": 22700,
          "sha512": "b792502b1ca3ac3c8e731f5a4c1c96b167ef9c29cdbcfd09b7cee1af3d7719cadfed268b8e7b8fcfa129d5f923063db7a578a80fba71c556e16f772645064211",
          "sha256": "37372bb29e8fdf50846ef87698d92dc4e87a30ca403c3b7a33ea6ea7a0022f04",
          "sha1": "c15cb45e7aeb4396703df330e96134626b384f45",
          "md5": "28f3a22eb131f08231cf9f4c9a63897a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 141572,
          "sha512": "1baf590c626a29fc33a8c91dfdcaf155a150a28eee5d48a0bdec162211156c3987ffcf9c3baa112edeb52112d7b67b07914fc031acdaff4afe4c42d50b0112f2",
          "sha256": "93d86fc3e2d7d177d17dc03ac296d6ada11d2864f7d093e9938c50280b20d2a0",
          "sha1": "a8952f8669c87bcd82e26b9e436c28bd4a596f37",
          "md5": "48a0b688b55ff4875efb2d59c8836528"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 12222,
          "sha512": "87405098608f71211082ee6ecec9acab3b94c0021f290bc37139b3c71c0ac10e2af5289c607e9153ae880bb9372cd49782cd2fc9977b7f906293826628f44564",
          "sha256": "4c57205aa1342650af28817c9127d31f260027016636bd3f5961d87948dc9fe9",
          "sha1": "682d3cfd435f82b4eebcaca242ec43e0c833c0ff",
          "md5": "93c8a412c856fd0192e6d9912f678dab"
        }
      ]
    }
  ]
}
