{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.7.jar",
          "url": "vectorx-management-core-24.1.7.jar",
          "size": 924083,
          "sha512": "4125c55f5691ec90497f849e3578da07c82c556cf94aa7fd7c3978ac81845160686350900f8aaacbc546fc2cd64fc8a120c72b91a4907acbb51e9e35fd2e391c",
          "sha256": "d683cdfa7f82b8a4b9b5335b72588f483984a3254d1b1e68b5a56d5b13776fbc",
          "sha1": "8232e5ac26e0c8c2f3b2f1edbddbd48dd9a634c2",
          "md5": "7144bedadf6a7dcd3a04c8a8b9526c70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.7.jar",
          "url": "vectorx-management-core-24.1.7.jar",
          "size": 924083,
          "sha512": "4125c55f5691ec90497f849e3578da07c82c556cf94aa7fd7c3978ac81845160686350900f8aaacbc546fc2cd64fc8a120c72b91a4907acbb51e9e35fd2e391c",
          "sha256": "d683cdfa7f82b8a4b9b5335b72588f483984a3254d1b1e68b5a56d5b13776fbc",
          "sha1": "8232e5ac26e0c8c2f3b2f1edbddbd48dd9a634c2",
          "md5": "7144bedadf6a7dcd3a04c8a8b9526c70"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.7-javadoc.jar",
          "url": "vectorx-management-core-24.1.7-javadoc.jar",
          "size": 1333215,
          "sha512": "8516fe7a1a1711ea27b692735ea6aa54fad48a2e1c8535db8e7dbe85766f37c3d9f756adac9572e07904cb0e7de211a0e36d20da360ff03d12c25fdfc3e4128e",
          "sha256": "35d558278589accba963dc1f23bb6b1a188099b486523b4efbea08c4f3992621",
          "sha1": "3ef381e86de876a12fe464372fa9f60dad4e68a2",
          "md5": "7f7ca068fa3980fe2da86ee67c34bc29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.7-sources.jar",
          "url": "vectorx-management-core-24.1.7-sources.jar",
          "size": 329481,
          "sha512": "34549247b2f4fa08caff387c5e0d16a111b91ef5fd2dd0e326c452ff9b7870d9ca3f0496f793755ece04925b14ed19808c48bce2904d5dd59f6f2f6db3bfaa3e",
          "sha256": "5089f9b040878684b6314cca3ea645091d04ebe30c82cf772d2b04d1434392fd",
          "sha1": "c9c00ba7c2bb5e0b2a02ba6628207a35fc823d1d",
          "md5": "b4f063e4bbbfa10ae9c2c4b3307ff182"
        }
      ]
    }
  ]
}
