{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.3.jar",
          "size": 2775,
          "sha512": "5a7743053fff0666588a8a8e692b22f08c6c93403da108b440ea2630656fdff30bb150cf12f815b5f9b431d895046ad38f4c95b4f06281fb8249b0547c7a597c",
          "sha256": "ffad368d392ed6e9afe4c6ec049b04bb9aed6b56b01fccbea2c3f66a08eb3e57",
          "sha1": "592bd291900bf1cab7f870d3f9b9860489cd74c4",
          "md5": "ddc6c8fac680e4ab33f1650660fd347c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.3.jar",
          "size": 2775,
          "sha512": "5a7743053fff0666588a8a8e692b22f08c6c93403da108b440ea2630656fdff30bb150cf12f815b5f9b431d895046ad38f4c95b4f06281fb8249b0547c7a597c",
          "sha256": "ffad368d392ed6e9afe4c6ec049b04bb9aed6b56b01fccbea2c3f66a08eb3e57",
          "sha1": "592bd291900bf1cab7f870d3f9b9860489cd74c4",
          "md5": "ddc6c8fac680e4ab33f1650660fd347c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 70456,
          "sha512": "6d907744d85eef81da81a1dfff0bad9a1b7a973ecf7941ab7aba5e3a3b3b2acc80504235303466d195cff864053d3e3f8deac72a9e9ba0638a98a3bb091c69cc",
          "sha256": "206f501ce94e511d666282280ce15ebff72d9368c0f844d9dd429d4a4a3efa70",
          "sha1": "922e71a96b719feee22be988df23d82f9395cc74",
          "md5": "d1bbbbb4d52762ba97ae2fccc30ae1d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 1228,
          "sha512": "27dfc9da125fea556f3e6743b5ba1d22a0a7a2640e277f1da0faaffd835e61e0d4bf68ea69957b01ebefd8af57f5d7ea433eaa27c027acc4959935e0cca2672d",
          "sha256": "49da61dd0409c6e2e8dd3b071ff4e968f7c87d4387a17c02f6396633a4acc68b",
          "sha1": "42cb0da12314af7f9ded34d8ac597a02f7af3a2c",
          "md5": "94e0ecf0e01ed764cabf512a71510078"
        }
      ]
    }
  ]
}
