{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-manager",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.1.jar",
          "url": "vectorx-batch-manager-24.1.1.jar",
          "size": 45152,
          "sha512": "26c042d9dccfb5217a20b6e74b6c29207c8ede20833708bac778487c8f20315f27e49d8880417b6cc8c055026d5b959fc3274562b26c02c2d1aefc987cee629c",
          "sha256": "0f6cb1e19c10f8285650ca0bf2e71250de068b8f6767b2e2945fc549d5caabe9",
          "sha1": "7cff329ae78dcb6e1828e940e5dffdf3b7af0076",
          "md5": "b1b925c6f969269ad533fa5a42cafb5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.1.jar",
          "url": "vectorx-batch-manager-24.1.1.jar",
          "size": 45152,
          "sha512": "26c042d9dccfb5217a20b6e74b6c29207c8ede20833708bac778487c8f20315f27e49d8880417b6cc8c055026d5b959fc3274562b26c02c2d1aefc987cee629c",
          "sha256": "0f6cb1e19c10f8285650ca0bf2e71250de068b8f6767b2e2945fc549d5caabe9",
          "sha1": "7cff329ae78dcb6e1828e940e5dffdf3b7af0076",
          "md5": "b1b925c6f969269ad533fa5a42cafb5a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.1-javadoc.jar",
          "url": "vectorx-batch-manager-24.1.1-javadoc.jar",
          "size": 139207,
          "sha512": "fc09e04de20cdcded6aa7c76a4265cdc431b05fb4aee9a12e805425d2be1267188bcc6b55e7d0c48628cafce2a564cc46f834a3a7d1a4f54ae2d4188da9833ec",
          "sha256": "55944c8234cec7770e10a98be2ce63c3b2660a9f14f3cd1ca08cd244bef26eeb",
          "sha1": "3b81f77668d4724028fc2b8bc3d57044a6157463",
          "md5": "47d7206afc4b52cd459a4840ddb17595"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.1-sources.jar",
          "url": "vectorx-batch-manager-24.1.1-sources.jar",
          "size": 20387,
          "sha512": "ee268563ccd534055ac13c563730652ef154532c93e398f6ad86360592b7be41f05d158e4278c4a01e91fd573cf9b3bf6b2d3e608311eb367cb615a3c3212e41",
          "sha256": "5eab97ec72f1fd3de5c6bd0228f50dffa38ce7036230a91e957dc7cde4f929ae",
          "sha1": "b996997a2d33947154e402c486e2dfe57733c3c5",
          "md5": "a2112502ea52bcb366138246becf507a"
        }
      ]
    }
  ]
}
