{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.1.jar",
          "size": 181419,
          "sha512": "a0a215b03f8c650fed254033d12e74f709a87e701191351efda86d76a0c1e6f0493d49c253f023362fd0f5d18a49411f8cfd55c9a01d6cd78c37043a533e56f6",
          "sha256": "ca845406131fc8e10b97df2574b64ea5fd6c82d6edc0608de3df1fb3378cb17d",
          "sha1": "282e2c20337667637a2c01dcac2dbd07e24a33f7",
          "md5": "b1e0bda96424657da261789cd20e0393"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.1.jar",
          "size": 181419,
          "sha512": "a0a215b03f8c650fed254033d12e74f709a87e701191351efda86d76a0c1e6f0493d49c253f023362fd0f5d18a49411f8cfd55c9a01d6cd78c37043a533e56f6",
          "sha256": "ca845406131fc8e10b97df2574b64ea5fd6c82d6edc0608de3df1fb3378cb17d",
          "sha1": "282e2c20337667637a2c01dcac2dbd07e24a33f7",
          "md5": "b1e0bda96424657da261789cd20e0393"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 274481,
          "sha512": "625d700b9f60f631d7eb817377555755440489e5cebd68226c125f3161f7c222f392c55456efc0136b3b1eb13289eeda110d92a5c1865a7b7f9cca790aca1b43",
          "sha256": "435dc92e2a204c7dd876efe5dc6f06f290e68e9ae33e7777c2e92c39c7d24699",
          "sha1": "09103329457fda367e7fdac7c778f47b17757915",
          "md5": "cc7feb2ac23bcd7526a1a34aa72d11bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 68190,
          "sha512": "aca5235f5cd0c9d9b3a0dffb2a9277b87c00834cbb971d9250934c836c95e72bab23b778d8a14ec12e88a4c51a36e92183b019674f6b760f4ebbef1c4db5dc12",
          "sha256": "c759df4b090d22b7cb15b2084ffc50f32105b3ce1b6479202d8aaad28555abb5",
          "sha1": "eefb5719210a838c73f20b046711bb42eb2272bd",
          "md5": "fcab4198d45389399eec3d3e4a5bc516"
        }
      ]
    }
  ]
}
