{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-24.1.8-SNAPSHOT.1.jar",
          "size": 99519,
          "sha512": "729b9d9504e23c70fd5f5a59482c2705d5b60ae3a48d1df43f88693e7e6ff52d37e79a0c3b2940932469bed89f82f67c32503487fc6ab36c605cf25310506955",
          "sha256": "98da5f37d920357df101c83ff11125b4bdb816306f77cff32640f64553f39d0c",
          "sha1": "0309d8b58ea3e2eec4eda24d61ff0a5b4b5006f7",
          "md5": "7954f27f3ad8029e5e23a61d0f6218d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-24.1.8-SNAPSHOT.1.jar",
          "size": 99519,
          "sha512": "729b9d9504e23c70fd5f5a59482c2705d5b60ae3a48d1df43f88693e7e6ff52d37e79a0c3b2940932469bed89f82f67c32503487fc6ab36c605cf25310506955",
          "sha256": "98da5f37d920357df101c83ff11125b4bdb816306f77cff32640f64553f39d0c",
          "sha1": "0309d8b58ea3e2eec4eda24d61ff0a5b4b5006f7",
          "md5": "7954f27f3ad8029e5e23a61d0f6218d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 298983,
          "sha512": "43036e434dd781fa4d3d5c709f15adb47ecb5053c04beea92a066de92a41d3dbba15318e8b8e9538696f3a6e220f957014b172000490c573f5dc3a1066df5f89",
          "sha256": "7fae089e75272938385a44598a4c2155e8fa95b0d03bdeaabfc202eaa4309856",
          "sha1": "4e2e377929c227ce21fa84495bb181eadfdaff3c",
          "md5": "9162a299e85506f20555567bc90c1df6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-web-servlet-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 50887,
          "sha512": "b8b89aaeaff7e3b62cc84b9d419d5f13827adb7b863e6e0b74876028a41559870c37abfc13a2b960f37e35c62bd68506816a06b5f69ceaa0df86e301764b7d8b",
          "sha256": "7cdd328c99ed566a291279964dcebd27a5911f27325af470d6bf13f85084ee63",
          "sha1": "5d2ee2a36ba5faf5d33c84b7404403999a0e290f",
          "md5": "1e5864ade5ab8258cfb62bc15994d21d"
        }
      ]
    }
  ]
}
