{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.7.jar",
          "url": "vectorx-data-redis-24.1.7.jar",
          "size": 9718,
          "sha512": "2b9bb9ca00fb4992246973feea1f10cbb2f73e90ce9cf71136e29ddc6366e7324dc8a650881a2b7591d8e3a72054fdb6d9b6e98ee91d26f72967729e2ece24e7",
          "sha256": "a65e034be9e17ad4bab59f87784965117be001121af1c5a8d7212e6f7f200be1",
          "sha1": "3fd67b4202cb9011295acc2280e0e9a858f8c996",
          "md5": "b46d5afca191cbd95c4d9c871b37d118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.7.jar",
          "url": "vectorx-data-redis-24.1.7.jar",
          "size": 9718,
          "sha512": "2b9bb9ca00fb4992246973feea1f10cbb2f73e90ce9cf71136e29ddc6366e7324dc8a650881a2b7591d8e3a72054fdb6d9b6e98ee91d26f72967729e2ece24e7",
          "sha256": "a65e034be9e17ad4bab59f87784965117be001121af1c5a8d7212e6f7f200be1",
          "sha1": "3fd67b4202cb9011295acc2280e0e9a858f8c996",
          "md5": "b46d5afca191cbd95c4d9c871b37d118"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.7-javadoc.jar",
          "url": "vectorx-data-redis-24.1.7-javadoc.jar",
          "size": 93495,
          "sha512": "2f12aab532092651e5d8c1de954005c9b239515536c32a038f372e9950a32c5f3cc9895b53179c000680f9358218035f1fbc6c200a6395c7d69345af31734f9b",
          "sha256": "8a395240ea52c3a0543eabb90d29467f07bb8d40388d551f1daf4aeb83096453",
          "sha1": "1564f4524583f36e8ddad1b247fee4b33aa70461",
          "md5": "d2161d6a157298590bafaf88f1e695b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.7-sources.jar",
          "url": "vectorx-data-redis-24.1.7-sources.jar",
          "size": 3360,
          "sha512": "1b3b076ac40ff00bf56d931cea4cd5b8422f1bac17197a9a98af9e91b2f0003a4b00b66927e5a10cb7180854c294ba5f08da0e0a36dc517ee3ac54c8df077812",
          "sha256": "5bfb183ac867a036912afee572844d52327b69706e40f4e00fcad6f0fbd76b8c",
          "sha1": "cdea56c818d8fc199310201eb46607a42c1fe4a5",
          "md5": "ea839cf76cfcde90acbc384fd003b8a1"
        }
      ]
    }
  ]
}
