{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.5.jar",
          "url": "vectorx-web-servlet-tobe-24.1.5.jar",
          "size": 811824,
          "sha512": "daa4d18568f4134a8f64a38c45fc6c19d78a85e1bed910296c01a34d7f3e339faefb0e0f9c6ce3f844f19d51628d956868ea0255a0e04cb066dc9c6561bd613f",
          "sha256": "80a10e2f1fe44254cfa6f7bcc13aee88df4b5687f456db941745c5429de36925",
          "sha1": "88b6e1a412ce48f30b1aa7b5815b30a7b6de86ae",
          "md5": "7ae26f58eb6196865bebdb6d1d699c94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.5.jar",
          "url": "vectorx-web-servlet-tobe-24.1.5.jar",
          "size": 811824,
          "sha512": "daa4d18568f4134a8f64a38c45fc6c19d78a85e1bed910296c01a34d7f3e339faefb0e0f9c6ce3f844f19d51628d956868ea0255a0e04cb066dc9c6561bd613f",
          "sha256": "80a10e2f1fe44254cfa6f7bcc13aee88df4b5687f456db941745c5429de36925",
          "sha1": "88b6e1a412ce48f30b1aa7b5815b30a7b6de86ae",
          "md5": "7ae26f58eb6196865bebdb6d1d699c94"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.5-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-24.1.5-javadoc.jar",
          "size": 1064762,
          "sha512": "3ea8d842ce9093e2975b1b57109e3269aea83745e4a2995b958ac319953049a82584d0bdfc23a5a861435c8714b740789bdcc351335b2a3c375bb36f93ac5e12",
          "sha256": "b71db088a01e0d7e9716d2f3a772bbc049a4ecbc99496583063fd2f946b8f8ae",
          "sha1": "36179d64ddde2bacb4c22930eea9fa4ab75855a6",
          "md5": "f686c3647ee511234641311c78a709fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.5-sources.jar",
          "url": "vectorx-web-servlet-tobe-24.1.5-sources.jar",
          "size": 413018,
          "sha512": "a9410930b17a27b1c69f4600d8a202ab68a7d615096205202150fff4dfece64c3a3c7ba5983bdd89726b42ea5fbc1d9ada1f5bc7de792b4235640dd107ffd649",
          "sha256": "a5d6b56ad17e6502b62972381aa9fff0a5050dde82dfb2f1f5bebf2e7efff85a",
          "sha1": "fc7367ec9ab57142154f7ba1fb8cf32b8581d1d1",
          "md5": "e21db032e13a8afaa15cd852a769ea86"
        }
      ]
    }
  ]
}
