{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-batch-manager",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch-manager",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-mvc",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-batch-manager-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-starter-batch-manager-24.1.8-SNAPSHOT.1.jar",
          "size": 261,
          "sha512": "7fad639831ab90e3c863acda2a3f03ac5b4a892b445363e280d6556fc37fe9c7ffc4bd821024dc51562bc1c057493ef041754d109c561a5d4ee830d74310ca36",
          "sha256": "9d4c7d07d10bdc11a291ed11af382a8e6030a627dba43c6bd5c6b6ad41fd0e4e",
          "sha1": "c86c7745d5e719c90b742a01d7663532980fd16c",
          "md5": "b3f935cf2a05b060885eb55062a4aecd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch-manager",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-mvc",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-batch-manager-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-starter-batch-manager-24.1.8-SNAPSHOT.1.jar",
          "size": 261,
          "sha512": "7fad639831ab90e3c863acda2a3f03ac5b4a892b445363e280d6556fc37fe9c7ffc4bd821024dc51562bc1c057493ef041754d109c561a5d4ee830d74310ca36",
          "sha256": "9d4c7d07d10bdc11a291ed11af382a8e6030a627dba43c6bd5c6b6ad41fd0e4e",
          "sha1": "c86c7745d5e719c90b742a01d7663532980fd16c",
          "md5": "b3f935cf2a05b060885eb55062a4aecd"
        }
      ]
    }
  ]
}
