{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jdbc",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.bgee.log4jdbc-log4j2",
          "module": "log4jdbc-log4j2-jdbc4.1",
          "version": {
            "requires": "1.16"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "com.itextpdf",
          "module": "html2pdf",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.jodd",
          "module": "jodd-util",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.13.jar",
          "size": 496820,
          "sha512": "66205086feb791e68fb4b2ea28a502aabbec10ea983eb06e633326108b1e7c091db3059b6f8ce7ac587ef5d5f8683e15998c64d5dc80dc678e5ae3da19ae5831",
          "sha256": "2c3966eefa3a5a17e1e7ca61900f07a04cf68f16646d3c5d4a9989cdc927ca3d",
          "sha1": "1e8c49dc0ada22b633bcfc40726405a9ed2a3c65",
          "md5": "9ef3d2675724e8566747cf449ac33144"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jdbc",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.bgee.log4jdbc-log4j2",
          "module": "log4jdbc-log4j2-jdbc4.1",
          "version": {
            "requires": "1.16"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "com.itextpdf",
          "module": "html2pdf",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.jodd",
          "module": "jodd-util",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.13.jar",
          "size": 496820,
          "sha512": "66205086feb791e68fb4b2ea28a502aabbec10ea983eb06e633326108b1e7c091db3059b6f8ce7ac587ef5d5f8683e15998c64d5dc80dc678e5ae3da19ae5831",
          "sha256": "2c3966eefa3a5a17e1e7ca61900f07a04cf68f16646d3c5d4a9989cdc927ca3d",
          "sha1": "1e8c49dc0ada22b633bcfc40726405a9ed2a3c65",
          "md5": "9ef3d2675724e8566747cf449ac33144"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 1261692,
          "sha512": "50aa99398ff4b90cc5fe45c8fac5e72ddd3f63e1625434ba4b3e31bd9f5d023ffe0ab2e7544a3bfd74f64895c3491471c55ff6a2d9d161adceb2d215c643c667",
          "sha256": "baa6b6c3adb4908b2103e1df82d363b96016e9278aed27a2a7b30f936f832442",
          "sha1": "73b1b29524ecdc3961c9d2b0c89f8a0d8cf6bf5f",
          "md5": "60b6ad2b94766d9b0131e7ae12f802f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 211123,
          "sha512": "6eb236781274a6356ff5c78496ccae1f761f6332c8e57a1858e485263ec8a1fd30ce0280dbe00dbacb50b71c3561b64b31eb5ed7d009bf161763de156f84df76",
          "sha256": "2c5e91d45b9627ad1d8984c8069dcc582627e9d6c796cb8fab06122c9d89624f",
          "sha1": "5b37a37286db196b7f969b4e021f5964a11354ba",
          "md5": "7f8840f1c84b398c94e836ade5c2644a"
        }
      ]
    }
  ]
}
