{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.8.jar",
          "url": "vectorx-cloud-core-24.1.8.jar",
          "size": 2694,
          "sha512": "b09ce200ae7f5bc3066949b4d97c3619da96c3adff90b296a6e34cd700f7bf5f90d6d4a464d20f99317c9a4db6510a89319b0cb39edbddb5a9932e2ff352f9fc",
          "sha256": "e9fba9c99e0a91a4aea282516ea61862508d34164d981eae79f77fc20a30a096",
          "sha1": "dab576fd35af0a16cf1c9fd7d6f3d3142c6b2063",
          "md5": "601c01950f59b41000d4d9475fec8550"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.8.jar",
          "url": "vectorx-cloud-core-24.1.8.jar",
          "size": 2694,
          "sha512": "b09ce200ae7f5bc3066949b4d97c3619da96c3adff90b296a6e34cd700f7bf5f90d6d4a464d20f99317c9a4db6510a89319b0cb39edbddb5a9932e2ff352f9fc",
          "sha256": "e9fba9c99e0a91a4aea282516ea61862508d34164d981eae79f77fc20a30a096",
          "sha1": "dab576fd35af0a16cf1c9fd7d6f3d3142c6b2063",
          "md5": "601c01950f59b41000d4d9475fec8550"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.8-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.8-javadoc.jar",
          "size": 70386,
          "sha512": "f69cc83a2cec8363e1c1a8a46d8de1c6c45e20fee27a08c901bbb765abf71186c737e3c12033d04db89d9425926640f9c38f9a872193b135c1a9f49f61e1db55",
          "sha256": "74bbeaf6f8935d23902654e9af30e5b3bde7f7e90e9d2e334f439d443052c899",
          "sha1": "78e7ff28752c7f5b88fd7331888598dac232b2b1",
          "md5": "867bd5f590f1726e126d0a8634b2060e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.8-sources.jar",
          "url": "vectorx-cloud-core-24.1.8-sources.jar",
          "size": 1186,
          "sha512": "0456543777bd0c4107b4aff5660bee4ea9140f6397fdb33646a6dfa6ead8a64982b196398b2ebd9125979e5a29b425eaba5eafd60bb8a0287093510ef46c79b3",
          "sha256": "d846f736a939cf189830e46f3fb42c82f41b45bb28ada1d4c442b4537e4756a2",
          "sha1": "e9dbf50e65e2b9abd70dd7878f98ce385ef29675",
          "md5": "21b1fc1419131572c39348ae324f38fd"
        }
      ]
    }
  ]
}
