{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.4.jar",
          "url": "vectorx-autoconfigure-24.1.4.jar",
          "size": 181378,
          "sha512": "d9d5ad153948b3e6c0933f8bb8bccbcd4a7d31f80336b2aa87ee4f9d62bdd74ea3cadd603a9e6e16136fce5d622d6b661dcf499c83c6a3e8ef5ded8ce625fb40",
          "sha256": "bce116b6fa6441adbc33439773af7ad33ef481246656734510929a24c17cb9a5",
          "sha1": "88b682369c1f2efe565f6eb9ddaba3e985840fec",
          "md5": "b3fb22bc7ccf6116b38e33cc1c581042"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.4.jar",
          "url": "vectorx-autoconfigure-24.1.4.jar",
          "size": 181378,
          "sha512": "d9d5ad153948b3e6c0933f8bb8bccbcd4a7d31f80336b2aa87ee4f9d62bdd74ea3cadd603a9e6e16136fce5d622d6b661dcf499c83c6a3e8ef5ded8ce625fb40",
          "sha256": "bce116b6fa6441adbc33439773af7ad33ef481246656734510929a24c17cb9a5",
          "sha1": "88b682369c1f2efe565f6eb9ddaba3e985840fec",
          "md5": "b3fb22bc7ccf6116b38e33cc1c581042"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.4-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.4-javadoc.jar",
          "size": 273507,
          "sha512": "3502378572a374c5a458b8013fe461d6ddf808c77b15c7d78bdb75f396c382c0c86f28ae50bc40ac58beda137bab9adcf801aa6f92c473313a3268d18aa56800",
          "sha256": "800306f28feb7ec9307dcf0b50960c4db3dbf762b3a481e482474586030d31df",
          "sha1": "3a00d47d02123df7258ce549069aaec14985dddf",
          "md5": "bd16d3973ad62ff155dd499c9dd7f81f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.4-sources.jar",
          "url": "vectorx-autoconfigure-24.1.4-sources.jar",
          "size": 68162,
          "sha512": "38f241f1a6f4e52dd7c8bc52fe7d99e96c440a68431a5db731a629beaa909363ccde7a1df066ddc527e3ebee8a51db736c073382c03b5375a6ac12fdf84d2c04",
          "sha256": "3b96935b9712d5ff62f35d4c6d356aa7c356e8c7f26385a1b5ac77ad60bfbba5",
          "sha1": "1441ae3c35ce2619a58da40b63029b92fd10fe60",
          "md5": "7f04d8aee3a846aa9b5e25b082d9e4ba"
        }
      ]
    }
  ]
}
