{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.5.jar",
          "size": 184775,
          "sha512": "4d1455ec6dc62e369f894417710b4f48ea8057179c4802ade7dd2feeeea8dade03e11303a0c7589f4ca780631295d79986abe0bbed0b13afdb9f23d3d17dce31",
          "sha256": "56226a118f130b11de41b7ba5842dbc0d08b3f8926b41725fdc0ba0fd6c011f8",
          "sha1": "8eff18626a613f5b09483e1e8a2751a6d9e286e0",
          "md5": "58106a5340c16fe915200e36746ef35d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.5.jar",
          "size": 184775,
          "sha512": "4d1455ec6dc62e369f894417710b4f48ea8057179c4802ade7dd2feeeea8dade03e11303a0c7589f4ca780631295d79986abe0bbed0b13afdb9f23d3d17dce31",
          "sha256": "56226a118f130b11de41b7ba5842dbc0d08b3f8926b41725fdc0ba0fd6c011f8",
          "sha1": "8eff18626a613f5b09483e1e8a2751a6d9e286e0",
          "md5": "58106a5340c16fe915200e36746ef35d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 274586,
          "sha512": "3143ae3e7d43c6469a9acbe90992f271d8b0978589ed5a88175be12b7935a8c92a1ff1171d26474ac25efbe7710fd2f8a73b8fca4535e756fcf239536773c94a",
          "sha256": "438023e8dc0ca4c64a7d60b04a1faa554bdea7e88d7ba9749ef41500c3e743d4",
          "sha1": "a072205ae01131d1afea55f9b27932403ec39dc2",
          "md5": "dda55de8a1024f082e98946f0b903084"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-autoconfigure-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 69356,
          "sha512": "b915e7e391447d7950ffa9a5f68bff5888cbced9786ee1e1349c4cb7ec3ad5bbfe80ecf7fdbeb1b9e43709e8a6ca9ab292ba27b53af2dde4c314064b040fa2c4",
          "sha256": "5c6fd595e130d40acc9440de5bf193a2714d72cddd3b6caee2926c9935f8cee0",
          "sha1": "92daf0b6245b8c627160629650d462dca069d42d",
          "md5": "4e368a4ee4111e2acbb76d58c5039bf8"
        }
      ]
    }
  ]
}
