{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-rest",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.1.jar",
          "size": 44393,
          "sha512": "6e5d630463043673b8d8e974d1a713630ba6506c864f82a41b3f033ee7cc43a4ca7c3139896dcdd2b03f23e00bb761041e3938d8afe24c82010fe2a95dcaa632",
          "sha256": "15daba04961363a718a1ec21711f912e9e55b8d8d2ad5336d7a89e711350ba05",
          "sha1": "5b0a88a1ee2755b852cd5ef062b619e7570e772f",
          "md5": "49bc690e0bd853d8d086da7838d57f47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.1.jar",
          "size": 44393,
          "sha512": "6e5d630463043673b8d8e974d1a713630ba6506c864f82a41b3f033ee7cc43a4ca7c3139896dcdd2b03f23e00bb761041e3938d8afe24c82010fe2a95dcaa632",
          "sha256": "15daba04961363a718a1ec21711f912e9e55b8d8d2ad5336d7a89e711350ba05",
          "sha1": "5b0a88a1ee2755b852cd5ef062b619e7570e772f",
          "md5": "49bc690e0bd853d8d086da7838d57f47"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 176418,
          "sha512": "07ee36a46ee8970f07cbbce2fc4f4cbb12465044bffa12eadc292e3f95a45689bc04c5abdc0107ac1c10ab8581d72ec75b4f46a84088d88c7478a039f5736f49",
          "sha256": "f5574075fbe582cbb8a17dc8478b675ab887873f7f46812fb5d86ad76ec239f4",
          "sha1": "01dcc33c7bfb9535eb128c4b455fc55c69d50c52",
          "md5": "33960789446cb828452e876462cdf7c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-web-servlet-rest-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 24087,
          "sha512": "8e18d19bb19ff8c7f1c0a49bb70fc57fa78abf339466282adf31af92f81adf21f6826d7cd0d4cb7691dbd8095f6c029f6f1127e3c1f77a79a7683d568804958e",
          "sha256": "902eee97a3bea6877f27b67082e9887155bd0e911091cbc234989ecb1aad3a70",
          "sha1": "5404a18924c111ee976a7862730d0d0ffd18fddb",
          "md5": "849f5688355168d47ff648d589fd8022"
        }
      ]
    }
  ]
}
