{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.13.jar",
          "size": 9880,
          "sha512": "982bc038b1365f26a98cd152938016900c25ee3185255c868a22acd539d1c16f42570df44888ec13d7ac031ca5f310e6c30ac9d64178307ade3fc925d0ae6a59",
          "sha256": "c5a67baac5a92c22c1dab0187fa22941766f2a213664970cfe0ae145ea210b63",
          "sha1": "fcb493e8aa412a4c35018f03a59927032223387f",
          "md5": "de7b1f296e666d41cbd6e2b4294d099f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.13.jar",
          "size": 9880,
          "sha512": "982bc038b1365f26a98cd152938016900c25ee3185255c868a22acd539d1c16f42570df44888ec13d7ac031ca5f310e6c30ac9d64178307ade3fc925d0ae6a59",
          "sha256": "c5a67baac5a92c22c1dab0187fa22941766f2a213664970cfe0ae145ea210b63",
          "sha1": "fcb493e8aa412a4c35018f03a59927032223387f",
          "md5": "de7b1f296e666d41cbd6e2b4294d099f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 261,
          "sha512": "0a67ba2caab65404f600b4fdc270a4514b0f0b94ec0968cff746d65a1a9aecf1b5405c993a10b1176be6b4a5537382af110cd79d31fffa1399d42e719dec7233",
          "sha256": "5743bbae002b4db1bf42c86787f4119fe809e65df208b3c536b95f28885b274f",
          "sha1": "61e2400cf3522e33fe84b8f5255065e0182fcce5",
          "md5": "290e991868337d225fba3687174e64db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 3340,
          "sha512": "f7cb13b62b1499269fa53e000593bd3da3db112221f9591114b91f89ad7faedf781f0b40e5fb0de0f2ce78c2ea46fa54c3a5100f6caf74f0feff5c9ca0a3be1a",
          "sha256": "9cd55ace1c9e0bbfd64e36d763c83229fc5b951834595872c57675bb128c5595",
          "sha1": "9bdd87bda13206e0124980e54bf110044f79be6d",
          "md5": "f084271b5a63f8fb530445bf48709b83"
        }
      ]
    }
  ]
}
