{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.8.jar",
          "url": "vectorx-batch-worker-24.1.8.jar",
          "size": 51879,
          "sha512": "6eb88d3cfe9bf8027c1e9fadca7ff963f1835b8277f63734e59a2c79d1a939bdab7f60c8d27b5d81c2452fce9fd8a9f214b5e1aa276694b73043f5b569982db9",
          "sha256": "737caf49963758c8b3e410fdc9123c5740df6d169d08759553ed749a7186f8bf",
          "sha1": "f5e83fa57a823a88b9a870c6a494b39b45b6f1ae",
          "md5": "974b53c27b8e35b96596dd032f6907a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.8.jar",
          "url": "vectorx-batch-worker-24.1.8.jar",
          "size": 51879,
          "sha512": "6eb88d3cfe9bf8027c1e9fadca7ff963f1835b8277f63734e59a2c79d1a939bdab7f60c8d27b5d81c2452fce9fd8a9f214b5e1aa276694b73043f5b569982db9",
          "sha256": "737caf49963758c8b3e410fdc9123c5740df6d169d08759553ed749a7186f8bf",
          "sha1": "f5e83fa57a823a88b9a870c6a494b39b45b6f1ae",
          "md5": "974b53c27b8e35b96596dd032f6907a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.8-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.8-javadoc.jar",
          "size": 180030,
          "sha512": "d2acc2fbf6f04acf41aaefab105eac2287087fa0b80524ae88920741a4eb49defe4841b33796d55c805bfd1d7b855b1277b141a5507dc20f23b52368f246391d",
          "sha256": "7a5f9528f747652e2b0349108631eb4abd80097efd92d9f92b523ca5fa774a17",
          "sha1": "06d40eee67c39c3b0d1131e518c3daf94e506607",
          "md5": "3b864b0efff251f53cf3a56a31c69776"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.8-sources.jar",
          "url": "vectorx-batch-worker-24.1.8-sources.jar",
          "size": 23642,
          "sha512": "47a8725225f2db2837676174e60da94aad7031806a3501ab724169312e27bd19dbd110951e285a1e8457a2890339a0c174eba0f37a4b1001fb01fcbdc04b44bd",
          "sha256": "f3901220d92c10f38eb1c92cd534dc7add7faad08cdb18099f10f9b2531badf4",
          "sha1": "b916703d6abf003b66bb5f5112d9000f57d807e9",
          "md5": "85f64d1ceea392b3baf1f2bda5f7acb8"
        }
      ]
    }
  ]
}
