{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.1.jar",
          "url": "vectorx-web-servlet-view-24.1.1.jar",
          "size": 19207,
          "sha512": "3f27e3c6c03b805521413e4215d4c467cb580f46d48fda350bc93bcf51100a7c7ba56324edc836b10c7e6bf40b56ea61d0fda2496c8be8e04139489f4a3e3a62",
          "sha256": "ce8953a2f9bc437bd0036cb2fd97f50be52b2d65c861deb1cb5a99d7c303ce73",
          "sha1": "b25f43aadf7db002812d65c4bb957c11f22b9bb9",
          "md5": "725090719df1e7912fa2b1c9866b38c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.1.jar",
          "url": "vectorx-web-servlet-view-24.1.1.jar",
          "size": 19207,
          "sha512": "3f27e3c6c03b805521413e4215d4c467cb580f46d48fda350bc93bcf51100a7c7ba56324edc836b10c7e6bf40b56ea61d0fda2496c8be8e04139489f4a3e3a62",
          "sha256": "ce8953a2f9bc437bd0036cb2fd97f50be52b2d65c861deb1cb5a99d7c303ce73",
          "sha1": "b25f43aadf7db002812d65c4bb957c11f22b9bb9",
          "md5": "725090719df1e7912fa2b1c9866b38c5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.1-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.1-javadoc.jar",
          "size": 132211,
          "sha512": "5a982f511abefe1fdc010da987e03ba65e9c25f8f430f8284b4fe0136b5ae39dc4c0be32878a24756466998f91867f1cfae1460006f5cc9e1081e0da0b1a0db7",
          "sha256": "6a9fa6efd2b1fcf607fa3ae726e2cd5f8e61eb430e60bc5f49c9f217df81863c",
          "sha1": "983126b64c4a972d0359f92616ff6563675378c3",
          "md5": "f5d73ce57a8fb55b7df4246eb461fd4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.1-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.1-sources.jar",
          "size": 11247,
          "sha512": "abb33e5aebb1985416c39de33111a37e2389fed13ed3262be285c8a40560efb66ac121f626ae0044ab2c4f27f78d23659aec97d5d4943f422aa9ef64d90ec90f",
          "sha256": "4127456ee53df3eef54c5c6ceca026a506e7883269a817a3611ad2d5bf6d371e",
          "sha1": "f29e7556fa968c33c8787a157bfa88ef4eacb84a",
          "md5": "5f4e3a6c07896608a309aa7ad432c5ac"
        }
      ]
    }
  ]
}
