{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-web-socket-24.1.8-SNAPSHOT.3.jar",
          "size": 22994,
          "sha512": "1fe5125e714c6230ef28fdde4a589999e3baddf71bda0e326d029a23de7e82110a11be70945cf9d543de4b52dc122a6a15c26a1cc809bd357ce0eb3a4e1488b0",
          "sha256": "bb472c5d1335bb1b9a61f2cc322b2fed481f8109c009dd2c66db1e10b9a52272",
          "sha1": "bd35e2038e56018745ab253846a7902ba6a3ced7",
          "md5": "d29051c7ea07f47b429fb9eaa08e435a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-web-socket-24.1.8-SNAPSHOT.3.jar",
          "size": 22994,
          "sha512": "1fe5125e714c6230ef28fdde4a589999e3baddf71bda0e326d029a23de7e82110a11be70945cf9d543de4b52dc122a6a15c26a1cc809bd357ce0eb3a4e1488b0",
          "sha256": "bb472c5d1335bb1b9a61f2cc322b2fed481f8109c009dd2c66db1e10b9a52272",
          "sha1": "bd35e2038e56018745ab253846a7902ba6a3ced7",
          "md5": "d29051c7ea07f47b429fb9eaa08e435a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-web-socket-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 128555,
          "sha512": "31bd91df15c50447c7eaceae417ebbc294008b803d78d36b620bf2f826e8e9f6d1acec260eeb14515894169ef4bf05c6886b61f1983033542200e6213ad3294d",
          "sha256": "bf3f944f36652a18e67aa853d6d8ec6f750d0c204ea96305033af3fc809a8f24",
          "sha1": "cd1919a36be93fe5e10fc00e9aa5f83c2b151acc",
          "md5": "633e427ca7eda63d5ee308288e245ff0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-web-socket-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 11406,
          "sha512": "1d0e7d7fbd543fb9d7dc86ec37b534a468f7aefcfd44c14c34120f20616be85003b24a2481558db921ef30afea38c357a781d430f31bf2b21c1ed7c6a1092e47",
          "sha256": "bc019f5dec42ea99ebfe13d54e1e0085580be132b7fc900dbfb89f9fa13c62c4",
          "sha1": "1a5b697069f7179275a4e369b0f774f9e9a60008",
          "md5": "44a6f6490c0c95a4ef9352eb06088549"
        }
      ]
    }
  ]
}
