{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.7.jar",
          "url": "vectorx-batch-worker-24.1.7.jar",
          "size": 51881,
          "sha512": "872d5743d426ccba31b9dbc4d6bccda25a27ed69c99d2b822685b287dd044a3a959800f32ea8c14afadf658cd7929cbdfaedce2d6566271185fd22b7e94d8c6d",
          "sha256": "3ec571272810ca5a725d87619b2e13b451c09e1ecca6953e554794f756153b9d",
          "sha1": "d1fed5160632027974282fb8851180aa2721f1a7",
          "md5": "f5b0749edd742c41703e2caf8ce55058"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.7.jar",
          "url": "vectorx-batch-worker-24.1.7.jar",
          "size": 51881,
          "sha512": "872d5743d426ccba31b9dbc4d6bccda25a27ed69c99d2b822685b287dd044a3a959800f32ea8c14afadf658cd7929cbdfaedce2d6566271185fd22b7e94d8c6d",
          "sha256": "3ec571272810ca5a725d87619b2e13b451c09e1ecca6953e554794f756153b9d",
          "sha1": "d1fed5160632027974282fb8851180aa2721f1a7",
          "md5": "f5b0749edd742c41703e2caf8ce55058"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.7-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.7-javadoc.jar",
          "size": 180010,
          "sha512": "b04b96bff8fc3b1b9ed6d019993385bc343e031fab536c97fc58e323d3cfd213c796966f45ef116e213ec33279154e32ea0b826279f733c6e01c68fe3592b929",
          "sha256": "21f2a2fce9b5fbe5f77d3186f81f0c313c8dc83153017b408fa9d71ac335e3e3",
          "sha1": "85fb2cb90e3235984011907014cb4f36abfa879e",
          "md5": "4c735f1f75c621ebe364faf84ddf524c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.7-sources.jar",
          "url": "vectorx-batch-worker-24.1.7-sources.jar",
          "size": 23642,
          "sha512": "a032b754f6a9cdb463b111c0bbe6cfe5292b7de48ac9c4f085caf1c73302a83d787c357e1eb57f0e7b7e195c50db40898f50d14e0999e0a3c70c72377a63c72c",
          "sha256": "56bcaf712150d2b375d2a2edbd07aebccdd2a86ad5ad6f47f7f75c894f520bf6",
          "sha1": "6defe50e22661781ad3190165676b32053b78386",
          "md5": "1d70fb2f677200c031a1dce9a17939ed"
        }
      ]
    }
  ]
}
