{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-web-servlet-tobe-24.1.9-SNAPSHOT.4.jar",
          "size": 811839,
          "sha512": "b9b5ec3e118824ac35a78c6c181a02cdb8dad5c611deb2f116e69c7393f72e7fc6302900a48cca14e762216a38fb3ba69bb36dbcc73339e18bc65dfc687de8d8",
          "sha256": "ed3da10c49e1552a764e8c936670c1d2e6b4d7884a0dba4246e6e59be95da52a",
          "sha1": "5520b68d9ae2db4f790535a76baec9bf58ea95e9",
          "md5": "409a1de92887387568b56466fae396d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-web-servlet-tobe-24.1.9-SNAPSHOT.4.jar",
          "size": 811839,
          "sha512": "b9b5ec3e118824ac35a78c6c181a02cdb8dad5c611deb2f116e69c7393f72e7fc6302900a48cca14e762216a38fb3ba69bb36dbcc73339e18bc65dfc687de8d8",
          "sha256": "ed3da10c49e1552a764e8c936670c1d2e6b4d7884a0dba4246e6e59be95da52a",
          "sha1": "5520b68d9ae2db4f790535a76baec9bf58ea95e9",
          "md5": "409a1de92887387568b56466fae396d8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 1068745,
          "sha512": "83bfe58679d7e9b4db86a3bda7a86f5dc2b6af8929b9e466d6a22cf4c8e8bfbe3b411c4b7905ab480606683b42a062a5cb74d6f7953dbeab365e8047d90094c2",
          "sha256": "b7b0670067707a7fa98babdc86106abbaba11154bab076a8e4b6f6ee5ff9ce28",
          "sha1": "8801be57a9a4780f380b4720e346a7baa5433991",
          "md5": "ce3846ba7ea3053e484e28ea51709b84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-web-servlet-tobe-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 409970,
          "sha512": "c345eaf4f9d9a8c62d8bf92aaa057c697c6603787ac45e54666b474268469ca75285be5aaada24719ab728c70e3ca2a586db55a4246a415c3e11094a6b77153b",
          "sha256": "712f0eb2e8f53d580292e715da01f8ddd45157c6f22fa22f763f8b702b5f4f4b",
          "sha1": "74075012c28f09b517d877d08d9d446c87cda3e7",
          "md5": "0ffdbffa9e41c730fc33b22fe63aec89"
        }
      ]
    }
  ]
}
