{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.5.jar",
          "size": 100179,
          "sha512": "b475839e4be8664c55d64d83f960232d36005946803ff84c94332734eda50caf8a3c81115da2e694a48b994cc94febb40942a5b89f4e5141d9fbad975c74557a",
          "sha256": "c3b159f60ce7ee6344f166b898590b88b8bb8c330ecbe340ae7802d77c5260aa",
          "sha1": "4dbdef300c2a4c5c452023e6ce07036f0c1747c4",
          "md5": "1fbeddadb565932da0b018121e13ea27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.5.jar",
          "size": 100179,
          "sha512": "b475839e4be8664c55d64d83f960232d36005946803ff84c94332734eda50caf8a3c81115da2e694a48b994cc94febb40942a5b89f4e5141d9fbad975c74557a",
          "sha256": "c3b159f60ce7ee6344f166b898590b88b8bb8c330ecbe340ae7802d77c5260aa",
          "sha1": "4dbdef300c2a4c5c452023e6ce07036f0c1747c4",
          "md5": "1fbeddadb565932da0b018121e13ea27"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 301952,
          "sha512": "f69d16ef794f8ca891f2515776eb12604d40c084db4a1de29ee7057673413eff7e3482d9c900b17dfa4c9ae3d018816221ec38f7f9ba20b9031a8d0121828a18",
          "sha256": "915827df848ca4c52dc030f5ac56ac495bc31dade1aa5f585ca0312df8eeaeca",
          "sha1": "c16ed54a4d417a777432c13e3682f6ef94d0006a",
          "md5": "71fe3fef79d48dec3131ecef1dc74df8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 50820,
          "sha512": "ff11fba5abc960c672764a834ecc7963b83855a0a68b53ab502b326984a1b9980e9b6fbf4d67f0e09e631a7ec4f698da3ccb6a3fd90e674e1d39ac77556db148",
          "sha256": "130b46571d454be9334979582bb67a79c6597ca822ac4647a0dd20acebef6ee4",
          "sha1": "25911483b9319120f6f6e51b668058408b8cff35",
          "md5": "20ce1c27a45f5c2e1bbc0901b0edff83"
        }
      ]
    }
  ]
}
