{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.6.jar",
          "url": "vectorx-web-servlet-view-24.1.6.jar",
          "size": 21072,
          "sha512": "d1fcedbede659e6d320624d2f51b600720f045030d01f03c5cf4c68436b129f5c8e838f1f272baefe1a1cc644cf966511c8df542a2b49afb8144fd65a87c503c",
          "sha256": "38963a65e462080faa50b2b077c64a8724df31cf72cedacb145bd5617a058d83",
          "sha1": "a644ee9ef126225f69b578ad480f6364bb6240cb",
          "md5": "707743ffbb509d7d15c4debf74b57b78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.6.jar",
          "url": "vectorx-web-servlet-view-24.1.6.jar",
          "size": 21072,
          "sha512": "d1fcedbede659e6d320624d2f51b600720f045030d01f03c5cf4c68436b129f5c8e838f1f272baefe1a1cc644cf966511c8df542a2b49afb8144fd65a87c503c",
          "sha256": "38963a65e462080faa50b2b077c64a8724df31cf72cedacb145bd5617a058d83",
          "sha1": "a644ee9ef126225f69b578ad480f6364bb6240cb",
          "md5": "707743ffbb509d7d15c4debf74b57b78"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.6-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.6-javadoc.jar",
          "size": 134638,
          "sha512": "5ac86d6f69bb363d12c3a8829df49dbe627be2bfa5513fbc91e3a633c12f034da6a8154bdcadecce4e0a2eb676a9c695c279463aaa89f8acba329fcc56bc92cf",
          "sha256": "d469e64b6402e1d9d988a22aad7eee6bff806e9c833912f3e3c71ac0186a7fff",
          "sha1": "bad3489ecb92d79cc18775ee8ca224fe93833b91",
          "md5": "0e7ba812ed24a4f72f5634aacb04752a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.6-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.6-sources.jar",
          "size": 11406,
          "sha512": "3618b4181a408af5177236050dad837d032959bc1b332b51e42ac971e099a6687a9092ca3b83c25f4ec37618dfa9f417c64b4cc4344c47307c06203c762580ed",
          "sha256": "c6be9d04daad539c1fa7973ba5e63def243248d88be5d103c5568c224192d24a",
          "sha1": "c51890b6c57df72a87188ed293bc48e1d221a30e",
          "md5": "2420076373721ee905bdba37ccff729a"
        }
      ]
    }
  ]
}
