{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.9-SNAPSHOT.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.14.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.14.jar",
          "size": 149946,
          "sha512": "398a35801694f4b781ad705ee29310cdf29ca1f2935f449aa2879a65648b570587d26da6d58facd4934b17c8354b2aed71b30439d98c18197bc2b2da17a0f2dc",
          "sha256": "bf080133dbc92c12bc0e2b87c72d878a6441a02310f69b3482f648446438eb6b",
          "sha1": "a71f48e43079a5f99b90ff99bfaf4f195545f5e2",
          "md5": "28d6ea81378ee1e4fcf6fb9b724ff56c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.14.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.14.jar",
          "size": 149946,
          "sha512": "398a35801694f4b781ad705ee29310cdf29ca1f2935f449aa2879a65648b570587d26da6d58facd4934b17c8354b2aed71b30439d98c18197bc2b2da17a0f2dc",
          "sha256": "bf080133dbc92c12bc0e2b87c72d878a6441a02310f69b3482f648446438eb6b",
          "sha1": "a71f48e43079a5f99b90ff99bfaf4f195545f5e2",
          "md5": "28d6ea81378ee1e4fcf6fb9b724ff56c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.14-javadoc.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.14-javadoc.jar",
          "size": 347534,
          "sha512": "471002d90d1876f1236450793f33622db6fd69f3dc3ad53d1f1213b21e132dc4e185aa31d760a44d6e44ea8cfb5c97ed451058713626536dd883bd971a1fe180",
          "sha256": "6c124f37a0bfcb4b988f67c3a5a60e4d0911c1d5a185598f9e23890b257e8c7e",
          "sha1": "6357b46c826d6df579405f90a085839f167fdea1",
          "md5": "259ee48f70e0e08726b9cacfeb336dd7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.14-sources.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.14-sources.jar",
          "size": 61776,
          "sha512": "5b6e5a558505f67bb541a4f3aa98b2890b4cf6e4ecde585423ab91470ccc06c4c42d038dab4880cabe501e1bff49ba917502cd6b246bcd921131eb2a3792b90e",
          "sha256": "8cc001cbd5e083bb1267346ff649d4f890a92ff59a0b43623f94d3700426fc15",
          "sha1": "7aed9d2769021c546e8eed73e1083d7b0e37ea64",
          "md5": "3b71477672dbb02b24f0b354da819762"
        }
      ]
    }
  ]
}
