{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.4.jar",
          "url": "vectorx-batch-24.1.4.jar",
          "size": 244252,
          "sha512": "77bfdf2f30d8be75d58513f70e8b549513dec537c99a17eb9c946903437fb3310bc66c2ccd673043b390a3079ffab9bdd85b92582300fa2795c398afaf8a0436",
          "sha256": "884144d5747542187e453e32e3880152e64f9044d60b3a2c9bb907122ee6c953",
          "sha1": "1164da5d2623a4e082aee4102a6b7387b57f86a5",
          "md5": "6a4973446211fc4305ddf854cca320c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.4.jar",
          "url": "vectorx-batch-24.1.4.jar",
          "size": 244252,
          "sha512": "77bfdf2f30d8be75d58513f70e8b549513dec537c99a17eb9c946903437fb3310bc66c2ccd673043b390a3079ffab9bdd85b92582300fa2795c398afaf8a0436",
          "sha256": "884144d5747542187e453e32e3880152e64f9044d60b3a2c9bb907122ee6c953",
          "sha1": "1164da5d2623a4e082aee4102a6b7387b57f86a5",
          "md5": "6a4973446211fc4305ddf854cca320c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.4-javadoc.jar",
          "url": "vectorx-batch-24.1.4-javadoc.jar",
          "size": 520133,
          "sha512": "6a21d42324de1ac5505d8dfc32ce46cb21157d9c39095108f412b6d66af24fdcbca0e65417aeafec29e67e6f059d653c377fd2ab2e202112ea5478b41db7ed43",
          "sha256": "2462c9d9592a6e8122615a96ad86a146d555e3be71fbd24eac6df63bd650a76b",
          "sha1": "e28dfcdc99791eb5d0fcbdab53116a789ac68e39",
          "md5": "b720af45885095305bf71c5525ba6b3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.4-sources.jar",
          "url": "vectorx-batch-24.1.4-sources.jar",
          "size": 102673,
          "sha512": "d969627b5f0b5e5ee919d1e7f4a35f314b2c56dbefec3496e588d9623ebfda3f82234ee6c11d51054ad8574665ff184b3b1506291de5804ad21309f770735bec",
          "sha256": "44b48c3528de1e48d3e285436a02a5bcca62ee7db039af22ff70f1064cde84c4",
          "sha1": "40f6a1127981a6b4b71da4396dfe73b18a617c1d",
          "md5": "aa720768ff45305820c51fe46b765ea5"
        }
      ]
    }
  ]
}
