{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.1.jar",
          "size": 924111,
          "sha512": "2ed5c161efe83ad550669eef4330f3853037ddbe13ebb10e5886305f7a11da8e1a43f65a340448e686218c8ab61612a976d1d57f25b55c9d4d254cceae39cea4",
          "sha256": "cd9a312acbc5d8883431fbe36834acfce83ce3912f9f2229a144169a66030434",
          "sha1": "a469ae81d601a2b39c55a67545a31860d857151f",
          "md5": "0c2c8cbdc5ff08fef76459be2d9583a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.1.jar",
          "size": 924111,
          "sha512": "2ed5c161efe83ad550669eef4330f3853037ddbe13ebb10e5886305f7a11da8e1a43f65a340448e686218c8ab61612a976d1d57f25b55c9d4d254cceae39cea4",
          "sha256": "cd9a312acbc5d8883431fbe36834acfce83ce3912f9f2229a144169a66030434",
          "sha1": "a469ae81d601a2b39c55a67545a31860d857151f",
          "md5": "0c2c8cbdc5ff08fef76459be2d9583a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 1338435,
          "sha512": "4a1224211abd9545a2824ef6b55febac0adbce943589eb3a0c2fdf3609098a9585a3a09fc2a1aee68b4db41e3734e9063dbce8f0677f5312e493c3e75b70f0e4",
          "sha256": "dccab9aef6c0717595e7a5a18ca238c73dd402fe63cc21d1ac5aaae123bf871c",
          "sha1": "c24c26273f9d914a7caa465a47cb41eaad30d727",
          "md5": "524cf2f7d43ae79741cec652d778a6e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 329499,
          "sha512": "16d82352d5f4df5c068b51975792f37e1518d61568b29daa0eb6c06221ec38073c866a217f2c84a6de8a115d02fbc359dd61b7c7e844eaf93a943421ea284974",
          "sha256": "f8c198a8618202cd56ba1ac5134ca5d06aef4ed292507e0afabc0c7a1d2ee866",
          "sha1": "6b14adbbccd13242e64967945451400a1567c993",
          "md5": "ad080eea836ea996dcf55c1cbd4e733b"
        }
      ]
    }
  ]
}
