{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jdbc",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.bgee.log4jdbc-log4j2",
          "module": "log4jdbc-log4j2-jdbc4.1",
          "version": {
            "requires": "1.16"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "com.itextpdf",
          "module": "html2pdf",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.jodd",
          "module": "jodd-util",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.9.jar",
          "size": 490928,
          "sha512": "dfad276a5196367ced7c9a8c52f4ddb8a37487d898005bf0004277935b71f978e90b43ad64e43b4b636f1b09d41ece9d5ee080c1cc3620d153da9ade7acb6dc6",
          "sha256": "a869ab194bfeb3181dd9b9dc448d5d6c1362d578f70b3531dd764000ae2b5c0d",
          "sha1": "b37164e80bfea9112569476acdedccf10797ba0e",
          "md5": "78d920facb6faee166f97d4d5ba417a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jdbc",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.bgee.log4jdbc-log4j2",
          "module": "log4jdbc-log4j2-jdbc4.1",
          "version": {
            "requires": "1.16"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "com.itextpdf",
          "module": "html2pdf",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.jodd",
          "module": "jodd-util",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.9.jar",
          "size": 490928,
          "sha512": "dfad276a5196367ced7c9a8c52f4ddb8a37487d898005bf0004277935b71f978e90b43ad64e43b4b636f1b09d41ece9d5ee080c1cc3620d153da9ade7acb6dc6",
          "sha256": "a869ab194bfeb3181dd9b9dc448d5d6c1362d578f70b3531dd764000ae2b5c0d",
          "sha1": "b37164e80bfea9112569476acdedccf10797ba0e",
          "md5": "78d920facb6faee166f97d4d5ba417a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 1079651,
          "sha512": "dac4e80ed42abba15455dca099dd12c9db3bb66fb755e1ea86f6e340b65557d3649430bec9cc281985a4768b3140d583f976d4b727a13b86d09c845f7691dc1a",
          "sha256": "8b9bc89cd4856d0d7ed8a7df3014ac87df60bf29d6b824b02bd9cf057cb7c35b",
          "sha1": "90a6f67b9a3585034b30d1135392006b499dbc41",
          "md5": "293b0e0fe90064afde178f473c1dd80e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 213023,
          "sha512": "d3c7829ef8d810db4e7eaaea2e2a6c23899233fe0536b5d6c081e32404873a772572cd1e0d2d3e6912d658a71999d1f3598af5267d865261fadb6ce71fa1f69f",
          "sha256": "4a05256c1848d05f02730f7f73c73842e30f09444e9e82e47a92ba56430e21cc",
          "sha1": "a3efad843236d88734ccb5d9b7a9c2ac781f9f2c",
          "md5": "5cd2c142122f04fa7b10215987ee14f3"
        }
      ]
    }
  ]
}
