{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.3.jar",
          "size": 244276,
          "sha512": "c1fb4d2535c79a323e24bc7a055f7dd4c1596be226b41ca0aaf8048de4b6a7cf2544ae863d35e20b8dbbff5022b8427c014a5db0f32219cfcbe94e7a9e9a731c",
          "sha256": "6576e58bc2b40760fa66219d393c5ce42f2f10a0a635664847bad43193bdeff4",
          "sha1": "c7527121fe43168e5ece5c11bb3984ef53949ea4",
          "md5": "1132d0bad6748ea97d1d67051a12e6d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.3.jar",
          "size": 244276,
          "sha512": "c1fb4d2535c79a323e24bc7a055f7dd4c1596be226b41ca0aaf8048de4b6a7cf2544ae863d35e20b8dbbff5022b8427c014a5db0f32219cfcbe94e7a9e9a731c",
          "sha256": "6576e58bc2b40760fa66219d393c5ce42f2f10a0a635664847bad43193bdeff4",
          "sha1": "c7527121fe43168e5ece5c11bb3984ef53949ea4",
          "md5": "1132d0bad6748ea97d1d67051a12e6d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 521680,
          "sha512": "7c39fee417448d82013a444fa0b79c3cb9457d9d05df41a41d173049a5bfdb6ca0059eac382aa56644ab0b2ca36ff23e233e72f683cdd07e53d524129118c43a",
          "sha256": "b2f912dd25116b3d1637ecd14311d25f396214570e7702953b4f960d0c58864e",
          "sha1": "f224f41d0bead939d335c996f5f2c6a710c788a1",
          "md5": "6cf57b94a8e47099ec6e06840f942beb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 102673,
          "sha512": "515da6b7e1a7b01e1b7e10b5e37e3a65c00ca8b828a8490822c6fd6ea647f7fdf1e52c7ef562a246736e8e445267c64b6f1c117659112eabc853df282395834a",
          "sha256": "aac3160b01eff635de1c3b26fff4e9b2ef78e59f9749cb94830803b4ffb7d37b",
          "sha1": "47d311a5f47cd33b2e9f189b455e5088138ce6fb",
          "md5": "0c0bb70eca786822c2dc362e7f16abc3"
        }
      ]
    }
  ]
}
