{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-net-24.1.8-SNAPSHOT.1.jar",
          "size": 29738,
          "sha512": "39768e50153f1a234f49f6d34773eae65486e03ddfe3a1e052ad4cbd8341ff14d6f589c3713166692d205f4f4f0747d7e57bd7eab3e7b5e61c7cbadd41c44c06",
          "sha256": "7c5ce25c1cdabe7a67254fd7f0a151801150aa7ee15e2b3ace9406982d15aaaa",
          "sha1": "2accfe052d9a696922a40e45c2bfa184f898cf70",
          "md5": "c8d4d59466019ee2e40d65213ce2e304"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-net-24.1.8-SNAPSHOT.1.jar",
          "size": 29738,
          "sha512": "39768e50153f1a234f49f6d34773eae65486e03ddfe3a1e052ad4cbd8341ff14d6f589c3713166692d205f4f4f0747d7e57bd7eab3e7b5e61c7cbadd41c44c06",
          "sha256": "7c5ce25c1cdabe7a67254fd7f0a151801150aa7ee15e2b3ace9406982d15aaaa",
          "sha1": "2accfe052d9a696922a40e45c2bfa184f898cf70",
          "md5": "c8d4d59466019ee2e40d65213ce2e304"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-net-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 128675,
          "sha512": "212ae7498b384838a8822c14ed124e043d023d3ea9cc8a0633fe42c81b8674100d0b12cc5d49d80d15d9876fd65b1019674674bee91650f0b2fad15ff90808d8",
          "sha256": "596d28f28d40ba62efa4efc72af079e3bf82a1a9e04ecc644b95670f8e38560f",
          "sha1": "5c12d522f7619dc34d5f79f11f41be9de29b722e",
          "md5": "950aff2c174be11830f6edbe0f29aea0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-net-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 10137,
          "sha512": "f4adc474df82cb71c87f94fc94df107808c5c3772cf2bcec5c2563fc2cb3397aa72dd8899c5f65ef1dda8306328ff4a3211f4e4c0c30fe830841e275839077cf",
          "sha256": "0ec09002fdcc796e03bca03b87cc463231e9e11b5ca3554ce39d6555be389f82",
          "sha1": "6209b6d23532bb1aa6fbdd85388aeffcf680c623",
          "md5": "8965d76e4d79aef20fb076013bb12fb0"
        }
      ]
    }
  ]
}
