{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.2.jar",
          "url": "vectorx-net-24.1.2.jar",
          "size": 29715,
          "sha512": "b6edaead03552dbae9ff66b4142737fba28363bf67c0d2fe6a8eb02960ff6b74a17e00ab3fc53fb4469ec52d86a0a356866ddd2c713f94f4dd0d7a9c7b1429c8",
          "sha256": "0b183fc01f6fd20c9ccab6585eab8440df4833179908a365130faecb6f19a4f9",
          "sha1": "ce28f68c52a55fcc4d32a49a3d214246d0908be3",
          "md5": "e18b85eb4aa133b303262d366b041ead"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.2.jar",
          "url": "vectorx-net-24.1.2.jar",
          "size": 29715,
          "sha512": "b6edaead03552dbae9ff66b4142737fba28363bf67c0d2fe6a8eb02960ff6b74a17e00ab3fc53fb4469ec52d86a0a356866ddd2c713f94f4dd0d7a9c7b1429c8",
          "sha256": "0b183fc01f6fd20c9ccab6585eab8440df4833179908a365130faecb6f19a4f9",
          "sha1": "ce28f68c52a55fcc4d32a49a3d214246d0908be3",
          "md5": "e18b85eb4aa133b303262d366b041ead"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.2-javadoc.jar",
          "url": "vectorx-net-24.1.2-javadoc.jar",
          "size": 128280,
          "sha512": "65d7440f89efa22029f5e205138d31062e7ed48841cbeac45ce7fe85ca356b5e8dc48121995446ad4c715001aeafd7296b9e2f44b956a05c9dfc2aac453a8e0e",
          "sha256": "b7f3efb1b1d7bd5e454b1a62d1652824054a35cb2f2d140a693cd76cd5dc48d5",
          "sha1": "e15cf880badea62ef110208aa46c7be1497f4155",
          "md5": "c9ce677de9a51b825088c0a839baeda6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.2-sources.jar",
          "url": "vectorx-net-24.1.2-sources.jar",
          "size": 10137,
          "sha512": "74c09f20d0ad060a582d73134f01dc2c70371d9a63ad3e64cc6303a2353806f193061e94bfeeb6fe7869a6a15eafdbd602669cddc877c48b8c544c0aba2c85f0",
          "sha256": "3fc0cbcc6285ac8cd68b11da7d9bbac58facf375c93d14a6c9bedb70ec88fb02",
          "sha1": "4da73a080fbea54a4c1a0d7122e88dd2de69c54c",
          "md5": "129e11172fc15be2b0a8f60202f30a10"
        }
      ]
    }
  ]
}
