{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.8.jar",
          "url": "vectorx-net-24.1.8.jar",
          "size": 29715,
          "sha512": "1910701ade3161bc3a8f05fd1c99317c81529805551b8769edc7d15b2e99d5b9efe4959349914929c82fd6d05cf257d04811c049862b9ff983f554339c87363f",
          "sha256": "38c235e8bb5f28eb873ba3bdcdc84b5a8f2e83719f5bc8b7fceaaec83ef7fbab",
          "sha1": "4730f69c67ca851f9245776212087c3cf5c901c3",
          "md5": "875202c1b3903401326887654c99a188"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.8.jar",
          "url": "vectorx-net-24.1.8.jar",
          "size": 29715,
          "sha512": "1910701ade3161bc3a8f05fd1c99317c81529805551b8769edc7d15b2e99d5b9efe4959349914929c82fd6d05cf257d04811c049862b9ff983f554339c87363f",
          "sha256": "38c235e8bb5f28eb873ba3bdcdc84b5a8f2e83719f5bc8b7fceaaec83ef7fbab",
          "sha1": "4730f69c67ca851f9245776212087c3cf5c901c3",
          "md5": "875202c1b3903401326887654c99a188"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.8-javadoc.jar",
          "url": "vectorx-net-24.1.8-javadoc.jar",
          "size": 128295,
          "sha512": "ce84ce5d94f6ac6c10375585fd7b32a8582c7b0fc82a7ad8881b035cfabcc3b659c2eab0c31c814601c5263bdba2b58ea4f7bed053c8b6cda8a9fb61ca69e69f",
          "sha256": "96c0757ae39f1dd48f598d3b3f684219987a128fdd0b70d3c518e9d4a3f75e8c",
          "sha1": "a84c6c96707584b46bc7d81d2dd0510cb2472327",
          "md5": "a2c31367d33f87d28b4b05b9acdbb5f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.8-sources.jar",
          "url": "vectorx-net-24.1.8-sources.jar",
          "size": 10137,
          "sha512": "c41ecd16136c84cf060793cc787caf3f030463ca6ae4698dc2a261ba2dc5f006d9a7ee10abfdd0f5f10f21e9e3b9a6d5a248c30f9f9d2fc8583a4475109d80cd",
          "sha256": "a98c5a501142d8d32c0d217e2a488e7d26053d44b9fdc6a958e74f88f4428d8a",
          "sha1": "55c9edfb9aa5e51794096c0fc01391936dd088fc",
          "md5": "3253ca119df39e32567d02e610c277e7"
        }
      ]
    }
  ]
}
