{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.13.jar",
          "size": 246000,
          "sha512": "35f9f3aa3c2eb678f7cc6fd8a93224b8c1866ded02996d3ad361e161c7b1176c8ffbc784145ae56a2e767977727a9c1322d20001a5912f92864bdbcbf32fbecb",
          "sha256": "56d260b96bbe792051df5beb74a4fc80cbf39df8f12821f2bd4af76cc99704e9",
          "sha1": "1b0b461b78287194b79f6be29920a26f94f360f4",
          "md5": "6a9fd2cc4393a95b2e08c908d3fd1f5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.13.jar",
          "size": 246000,
          "sha512": "35f9f3aa3c2eb678f7cc6fd8a93224b8c1866ded02996d3ad361e161c7b1176c8ffbc784145ae56a2e767977727a9c1322d20001a5912f92864bdbcbf32fbecb",
          "sha256": "56d260b96bbe792051df5beb74a4fc80cbf39df8f12821f2bd4af76cc99704e9",
          "sha1": "1b0b461b78287194b79f6be29920a26f94f360f4",
          "md5": "6a9fd2cc4393a95b2e08c908d3fd1f5d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 577229,
          "sha512": "b4b3f6569259f2c0f770d13d656901b5a1dfc5fe0c9cee3e9b3b01bf9e42d355c42bab006aa21151115280a14146eaa41062f6fb54a91492b0dfe5f16177dfc2",
          "sha256": "9381e85e3f7080f1af129f39c7c1eb3a6ea6723b0df11788b123651824143085",
          "sha1": "06c3ca020be7596c35b2cad66d985afc657db0f6",
          "md5": "15bcadc936e73c8912712b05ea6e02f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-batch-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 101772,
          "sha512": "9b9be978e17af4ff87e4c0def4eb50ae97e67afd3e551bfdd80c3e69a50e390ed1f5044b4497b32ca8f2121ddc25c0fcbadabd3ad7bd5fbefa467b183cd67f22",
          "sha256": "7c6b2657c7dceaf152e8911370f80e34f1a6e4e651661babac94c21f9b5e79e3",
          "sha1": "6f2c7a57b82d6c62151f85b70cb0c6a1f60b932b",
          "md5": "3e6ac2a7dd95d3532145a2aebe049f3c"
        }
      ]
    }
  ]
}
