{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.9-SNAPSHOT.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.9.jar",
          "size": 148731,
          "sha512": "1d77555f348c8f31feee7a226fc13ba93a88c958063d43d08998a806b6a150ad812a4b9d23a23691a365efe248b14f33dbb4577c1e3dddf57b9b6553d8e46872",
          "sha256": "36d3eef8718d143c9974156b4f77551a6f0b7ada13d998ffd8dacdc68e17a1f4",
          "sha1": "637d6d9dfeb550dd66c023ebe239d4468d79f196",
          "md5": "2d1b388d8b1f333c5f1feccd8cea8049"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.9.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.9.jar",
          "size": 148731,
          "sha512": "1d77555f348c8f31feee7a226fc13ba93a88c958063d43d08998a806b6a150ad812a4b9d23a23691a365efe248b14f33dbb4577c1e3dddf57b9b6553d8e46872",
          "sha256": "36d3eef8718d143c9974156b4f77551a6f0b7ada13d998ffd8dacdc68e17a1f4",
          "sha1": "637d6d9dfeb550dd66c023ebe239d4468d79f196",
          "md5": "2d1b388d8b1f333c5f1feccd8cea8049"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.9-javadoc.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.9-javadoc.jar",
          "size": 313979,
          "sha512": "2d433158d027d79c2b5bb492be6481c959005f92490fcb34949b77330dcac24a4fbe204cccbae72dbf3e79e4b588ba865431c4c22e27fb0404eb7e7215f0f173",
          "sha256": "6f0de2fb28bb931225f2d16518a49542921db302362317ed0564dd269eca1bbd",
          "sha1": "5e63513d2f86aad14be5509b18c8431eabd6004d",
          "md5": "cd92edfe714437f277500f39c0e21ba4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.9-SNAPSHOT.9-sources.jar",
          "url": "vectorx-management-bo-24.1.9-SNAPSHOT.9-sources.jar",
          "size": 61959,
          "sha512": "42466c2db274f2d774efd46dfb5d9d1199e0df0c7a77d9f9d572c782b35a0b1f838b930ae1f915f6ebf27297d7c67bc3d3780e20fbcf44439549892814716a83",
          "sha256": "f794a44d226ee12d817ffb800cead513920778ad0df960fcb8ccca0d056cf90a",
          "sha1": "58bf9958a41fbad1464b49f5c391add70c0db53c",
          "md5": "1b113bbf3049bac4950f1f4232389365"
        }
      ]
    }
  ]
}
