{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security-jwt",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.devskiller.friendly-id",
          "module": "friendly-id-spring-boot",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-security-jwt-24.1.8-SNAPSHOT.3.jar",
          "size": 87367,
          "sha512": "701f15d75d76dde87aef1f036dc1ad2e1b4a635a7042238751b10a2636a9396b01b3fbbba01dc7f34ed44f76c545e5ddccd6b4580e096ac80bb36aaa22cc4fe3",
          "sha256": "076ce9c2a8d6de5cebe47a88813fcb15d01d49accacb9bc6d2c6cebaf6a4d20a",
          "sha1": "45b7116117b05f97d5d813164bcde1df11d3c6f8",
          "md5": "33a23958dc424624559724d2e810814d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.devskiller.friendly-id",
          "module": "friendly-id-spring-boot",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-security-jwt-24.1.8-SNAPSHOT.3.jar",
          "size": 87367,
          "sha512": "701f15d75d76dde87aef1f036dc1ad2e1b4a635a7042238751b10a2636a9396b01b3fbbba01dc7f34ed44f76c545e5ddccd6b4580e096ac80bb36aaa22cc4fe3",
          "sha256": "076ce9c2a8d6de5cebe47a88813fcb15d01d49accacb9bc6d2c6cebaf6a4d20a",
          "sha1": "45b7116117b05f97d5d813164bcde1df11d3c6f8",
          "md5": "33a23958dc424624559724d2e810814d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-security-jwt-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 252467,
          "sha512": "64dbfa769777d12f5ccfd339a35d0b2d4edc032dc647764518121cce8b3cf84f98cfd1f1f7def60d89cc1f31ea87d6026eae471824eb896c945ba1639e5e20ae",
          "sha256": "0188f6aba568c576d3ae4cc90b97ebad7c01b827268814b95895d062477fd70b",
          "sha1": "4513be7561962600308c6297cdbc6575c48b2ad7",
          "md5": "8db3ff55f013324693b4f39fa13d2900"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-security-jwt-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 42980,
          "sha512": "48e2e1fa4c33f99de5a47df0c6efacfda99ac85f9f42131ed77b7942244f8dbc526ca88b27fc60846f3a2b270d83c39f35564659eebf0f2b5437e439ab4206fa",
          "sha256": "14cf739b948f6632fe94d70cce1e06929a83c28501d53743ee1290c1d45f73fb",
          "sha1": "6d2e662a2d6db0af5ed31888b272498fa9e04311",
          "md5": "1691eee874a0fc4fa0604709424ce12e"
        }
      ]
    }
  ]
}
