{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-gateway",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-eureka-client",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-gateway-24.1.8-SNAPSHOT.1.jar",
          "size": 46835,
          "sha512": "8286b3fcfeb02a038adc53400e44cf08b5eef3d34ed5b0deb54c7cec40d36a1222f27c61e62ca573d03736c258c1a406bdad2287138560f9bd36e6095f886429",
          "sha256": "466ba0f6927e3a8c9157d463952dfa1d19625721eb39171785664b6fa3df9d81",
          "sha1": "e7ee06b7e0d3f42f78fdce93b01749d202f2385d",
          "md5": "d7068950d96ae564223516dad7686c3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-eureka-client",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-gateway-24.1.8-SNAPSHOT.1.jar",
          "size": 46835,
          "sha512": "8286b3fcfeb02a038adc53400e44cf08b5eef3d34ed5b0deb54c7cec40d36a1222f27c61e62ca573d03736c258c1a406bdad2287138560f9bd36e6095f886429",
          "sha256": "466ba0f6927e3a8c9157d463952dfa1d19625721eb39171785664b6fa3df9d81",
          "sha1": "e7ee06b7e0d3f42f78fdce93b01749d202f2385d",
          "md5": "d7068950d96ae564223516dad7686c3e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-cloud-gateway-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 163104,
          "sha512": "3e81ccd6b2ddf111275b9f0f0cac012779a41452386dfe648fa1d0675043aaef6b8f91bea73a230854eefdb8230b13d5765926f2e99d411deb136fab659f2fb6",
          "sha256": "1ac272d8a7c15adca24039637ee548b4fd4569502bd9866a75496b0876699612",
          "sha1": "141a35e87990c4002d7eaeaa4c2701b929dfdc91",
          "md5": "25407dbb9c7937e5c3203a6b1b117d33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-cloud-gateway-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 15249,
          "sha512": "b9f3a6f432038830c3312f79827416bf5e42fb9251748433d900915fa2c4e008319af824e02af3833ef57c6b68d60828c02af98a1dac6a9eabb858bf17a46094",
          "sha256": "7c55abdf2a5c26b08dcd91c979f7ea7357dc8388a377bd467b2b0908b5c689bb",
          "sha1": "a31e0c7c8cdab8e6519be6f21fbea7b5b9aaa5ba",
          "md5": "735320da3eb4e076e65d84c5b9fd3c50"
        }
      ]
    }
  ]
}
