{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.2.jar",
          "url": "vectorx-autoconfigure-24.1.2.jar",
          "size": 177007,
          "sha512": "07d58feead0b22688d0ad15fc86b1bb35b93c4eddca6dc8e4879c0e2fedb2f3f5dff0418c0ea1f92bc528b2eeb6b592b47987ee406c8cf98ee3dc211bd397209",
          "sha256": "5e30794c34c19b79259d0e691e0151eda5b340f287131f609a92ddf2ec8451c1",
          "sha1": "e73ab55553c5e8822c0596d4ba066cf0a8794902",
          "md5": "9863061d188a0f3ca8b403084ec51430"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.2.jar",
          "url": "vectorx-autoconfigure-24.1.2.jar",
          "size": 177007,
          "sha512": "07d58feead0b22688d0ad15fc86b1bb35b93c4eddca6dc8e4879c0e2fedb2f3f5dff0418c0ea1f92bc528b2eeb6b592b47987ee406c8cf98ee3dc211bd397209",
          "sha256": "5e30794c34c19b79259d0e691e0151eda5b340f287131f609a92ddf2ec8451c1",
          "sha1": "e73ab55553c5e8822c0596d4ba066cf0a8794902",
          "md5": "9863061d188a0f3ca8b403084ec51430"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.2-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.2-javadoc.jar",
          "size": 273486,
          "sha512": "145d822acfb6a702170182f94a52fb9369ca6ca0393b0b49d31b25d783ec82fbec4aea3bdd9a88641e753630501093c510ce2ae1bae6889aa8bea3d9e3d05071",
          "sha256": "52605d8cec44b4eb63546afed1a588f1d1b61be6c234c4b2f3e384a333fa911e",
          "sha1": "242dadcbc8574a8ed240bb0bf614e75c70555719",
          "md5": "57a30c31d048927baa0d2a18a75ce993"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.2-sources.jar",
          "url": "vectorx-autoconfigure-24.1.2-sources.jar",
          "size": 67654,
          "sha512": "7acd67a65cea9b6344b2bc517fc87009bc2510e7c31f81b0e7df72a30989823e3194cdae83ff91f6e00c69708ae0096749fabdd1fb606cede85a9a14c77ada55",
          "sha256": "e4398c45e17009e9a046664eb7a2b76b97689d4369aad82f31cdd1dcbe4f7fdd",
          "sha1": "0a4751414688685b1747de1f6c82ae6184e7b900",
          "md5": "62e0bb9891934643cc31684ba8cb09fd"
        }
      ]
    }
  ]
}
