{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.5.jar",
          "size": 184887,
          "sha512": "8ac5e0ebefc9e8d625c4dc7d9893bc413883aa2a21f7d0e71ffd5b55815689cf04c24443463a88692fb06419f6d4b1187da451fed47fdebf3d4d431542f7c872",
          "sha256": "1322a190dd7fb6a1a919823a5fce5e22c8a8eb5460b52c1c7ea478ce13729761",
          "sha1": "e9475aebcec888faeb5ed78013addd4591cef454",
          "md5": "fbc688907d8c88cf252535433bbcfcbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.5.jar",
          "size": 184887,
          "sha512": "8ac5e0ebefc9e8d625c4dc7d9893bc413883aa2a21f7d0e71ffd5b55815689cf04c24443463a88692fb06419f6d4b1187da451fed47fdebf3d4d431542f7c872",
          "sha256": "1322a190dd7fb6a1a919823a5fce5e22c8a8eb5460b52c1c7ea478ce13729761",
          "sha1": "e9475aebcec888faeb5ed78013addd4591cef454",
          "md5": "fbc688907d8c88cf252535433bbcfcbe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 276942,
          "sha512": "217669c88ce7d87c660bb6a32fbc23724377b729367f154876867ca355727ff9997d2c2dff91eb747011d148a10d62a07e77cabd71ffdacd94a68cddc38fd361",
          "sha256": "bf4ff1d6ec8ae0122f8d8a12d79dbcedbe20c8611e59391cf4c703f86aa92f37",
          "sha1": "6b50eee7875775032fc8fabb07d773f4c673da77",
          "md5": "83517e68b693b043ef90cbdd5125d0db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 68978,
          "sha512": "7e4ed5f40e1ff069aeae485cd2600f86c478eb71e04d4b3e889e984db40a47b0c87891b14c34a6547b6616426b577ccdead93ba4ebb260707fb166cbc2429e24",
          "sha256": "99d2ee0997dabfd47a028f76cb5087e9ed005820380a91837292a5b06f24f368",
          "sha1": "f1628a93ee03c7917d49e58aa6cfdf65a43233fb",
          "md5": "2524a7b33238b2f05bc78f48aa2ddda1"
        }
      ]
    }
  ]
}
