{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-security-24.1.8-SNAPSHOT.5.jar",
          "size": 107184,
          "sha512": "ab1dab4468a280ffea3c184d5212156cdae6be424b70bd3cd025e5a3a6fe6e358e3927d396d02510283d51649e68f77fc6ad27916a5e387354693bde10ef9568",
          "sha256": "1b2150ca9b56c3e60aa1200e55ca1cb3b7da9e010aa2f904e6f31314cda94090",
          "sha1": "a5b535c121764bf487c83169289796e6785fd147",
          "md5": "1f194e329c120ff87347565373bcec82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-security-24.1.8-SNAPSHOT.5.jar",
          "size": 107184,
          "sha512": "ab1dab4468a280ffea3c184d5212156cdae6be424b70bd3cd025e5a3a6fe6e358e3927d396d02510283d51649e68f77fc6ad27916a5e387354693bde10ef9568",
          "sha256": "1b2150ca9b56c3e60aa1200e55ca1cb3b7da9e010aa2f904e6f31314cda94090",
          "sha1": "a5b535c121764bf487c83169289796e6785fd147",
          "md5": "1f194e329c120ff87347565373bcec82"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-security-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 413565,
          "sha512": "cec72656b250ae81acce5200e626c70cab5a2644fda934d17580d5bc3f438fa0b56457034b2a2fc95bdd684919420cf872ae9b051daa85978ec6760f647e237f",
          "sha256": "9a905c7c2edc063a92250b596d9d5236b43b157d014d7edca55549226339f8ae",
          "sha1": "7a6fbd8d5d16314b2e1bb631726e4fc0361edd78",
          "md5": "0c5dbd22372b66ccec3038b0523a5e51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-security-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 65616,
          "sha512": "51197724d3eb19f1c3cc23cbfd1b9135b0f10dc72801c175116150247146236966f9bfc096c7871aa80822a5d3cbb34eb680227fa5efa5279d9be84f5c55ac54",
          "sha256": "d57639c7e2574484e20eebc97da1a48219d00ed48da7d6501e4d0c4aa68e9785",
          "sha1": "b9aca2d7f8f3eb290b4dff50cdb23d4e1780753e",
          "md5": "3eab81bdaf7e0b1936a5b7e0873f6ca3"
        }
      ]
    }
  ]
}
