{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.4.jar",
          "size": 51899,
          "sha512": "e202f78975ac2e5ac704baa10b494534727e37c10ec1478582d0ef4571d12dbeae70c490590f0927a0f6a3da69835da6097da8c505d8be05ee5547b31080166a",
          "sha256": "dad2fba8eadcb543817af4aa926e3e382973afccf81f5fc0d08a9390d4dcba00",
          "sha1": "874baa7d3a42c14e0e9a389c5905a67dd9bc8dfa",
          "md5": "855b77cdf4b28c016ad69dba896050ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.4.jar",
          "size": 51899,
          "sha512": "e202f78975ac2e5ac704baa10b494534727e37c10ec1478582d0ef4571d12dbeae70c490590f0927a0f6a3da69835da6097da8c505d8be05ee5547b31080166a",
          "sha256": "dad2fba8eadcb543817af4aa926e3e382973afccf81f5fc0d08a9390d4dcba00",
          "sha1": "874baa7d3a42c14e0e9a389c5905a67dd9bc8dfa",
          "md5": "855b77cdf4b28c016ad69dba896050ec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 183878,
          "sha512": "b07af812ecd62526b9f359e4062d6e79f03ca7ad213df14ae3509c3d162855f751f9751a9313101c81ec2600deca47e4501cc21b5957bf8df6d304c1df434519",
          "sha256": "7e7f15d974582d473b9941c1217ac9435a5a01e830af2344bc406ac232130d8f",
          "sha1": "cf268855cb2e285427f9300da1c7baa263873f8e",
          "md5": "20da7773f78b1f9eb4f65c9fc1352701"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 23397,
          "sha512": "7a1e5b4fedc625eb37e351345a049573e3b5cda6b65a560e1cd5e90b445b3feccb2bef83804290233d51d4305c126acbb252ea7651a5b46582fa2dd1435c0045",
          "sha256": "c26bf9e98c4c18d009b5d4465481226ba48aa26362d5633838afd4096c2e0d53",
          "sha1": "134e616d898e10eb26990b120fe9a01c4e92b987",
          "md5": "5915fda62bbf80a3e8e34715f0fb1e3f"
        }
      ]
    }
  ]
}
