{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.2.jar",
          "url": "vectorx-web-servlet-24.1.2.jar",
          "size": 99309,
          "sha512": "07133790c5231b97cf6e0074e0e4f343c8e6acecb8bd6ef06b0319dab8e6f2b0d3118ee337a478a6cf14b066cf7cc4174367c085c3c36ca7372276b0a8365b2e",
          "sha256": "221ea0632f2bccf10d34263ec0ad8f6c18240f3d82a79c8bb48b6efc7b864fac",
          "sha1": "6e0b7e4e84e664f914dc05a1af40687244280c55",
          "md5": "010db5a47b4b25ffc7991d992e59d7f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.2.jar",
          "url": "vectorx-web-servlet-24.1.2.jar",
          "size": 99309,
          "sha512": "07133790c5231b97cf6e0074e0e4f343c8e6acecb8bd6ef06b0319dab8e6f2b0d3118ee337a478a6cf14b066cf7cc4174367c085c3c36ca7372276b0a8365b2e",
          "sha256": "221ea0632f2bccf10d34263ec0ad8f6c18240f3d82a79c8bb48b6efc7b864fac",
          "sha1": "6e0b7e4e84e664f914dc05a1af40687244280c55",
          "md5": "010db5a47b4b25ffc7991d992e59d7f5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.2-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.2-javadoc.jar",
          "size": 297845,
          "sha512": "8d7f04f8aca4064611288641c49e652852fbe165f2b6e41ac0824c5e97b7c6abf81fcd17b0cadae80759b41bf0de20fd705e65a108fdb8baeda4701b6251b0c2",
          "sha256": "d70c64358e86a4209084d5e9a3ab67b9ffb709a8f40401e19cf5cc01f98a2f64",
          "sha1": "27353b3e95c3e6d9ffc8cde38a0249454936e1e5",
          "md5": "ce32bac6bd7b8d4ed7d98a6cd004dd69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.2-sources.jar",
          "url": "vectorx-web-servlet-24.1.2-sources.jar",
          "size": 50810,
          "sha512": "f407dd99f3c52e60c6183e61072a7a74f37a719d391e067e3820ed89588160f0f818c98bbb63a854e00fceed810758a3318865d6bf5f113b97801456cfa2e0d5",
          "sha256": "af59cdecefa845bb818066c94234a7e815ee5ee796db76dc55a68229c8e8be97",
          "sha1": "cf85e2fd8f77e168cad408e356e05070edfd765e",
          "md5": "5e150004ce0a0d92d7c91f90b876d3ab"
        }
      ]
    }
  ]
}
