{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.1.jar",
          "size": 2713,
          "sha512": "c2077531e5559bb580f5da6b4cb1296675438d13a9755ff8e694e551b8ba4e542a10a0ba8b47c8711a787d9c048780da871ded6e4233eb0cd47d8c83ef6e7a3d",
          "sha256": "d790cbc9b409c5299a732eca715fc9feedd0b6257dc302f39d8cb557a58b4337",
          "sha1": "60e375d8e3b9f36977dac74d965dce3b9b1b6cf6",
          "md5": "54437754f7fe2b4ce704c459bb4b0f2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.1.jar",
          "size": 2713,
          "sha512": "c2077531e5559bb580f5da6b4cb1296675438d13a9755ff8e694e551b8ba4e542a10a0ba8b47c8711a787d9c048780da871ded6e4233eb0cd47d8c83ef6e7a3d",
          "sha256": "d790cbc9b409c5299a732eca715fc9feedd0b6257dc302f39d8cb557a58b4337",
          "sha1": "60e375d8e3b9f36977dac74d965dce3b9b1b6cf6",
          "md5": "54437754f7fe2b4ce704c459bb4b0f2b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 70438,
          "sha512": "7ec62cc7655280eb304b629df614edf82a3e033fe7193ea6353037ee42075e85e86ab411f669e5e2f5e97801d66bac604e186892a1a2012a1d4b0bdf6e1eb532",
          "sha256": "ce4f7795e48178e42b06552613a4b289820538015b2e071ba83331fd8a4d7a0c",
          "sha1": "681a549a485300d890e984db10352cbf94664602",
          "md5": "b5e1e532d39bb923a0ccb666273985d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-data-jpa-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 1184,
          "sha512": "9348f6a42c40504a6ff5c6f3d15ea980bc6d3cf5aeccf3079b2fb832ebbf81a2497351659fb91f92a6d2bc6c018a3c0fc9586c833824a1226b945cdba20fbb88",
          "sha256": "ad79a751a3c72d601b0d1e0592f17778aad6e0c524bac5bf82a4c6800a150e1c",
          "sha1": "0cd69510a9c08a5a397006a30b20077774854880",
          "md5": "ae3d0ff24bff3b6e087b111d3b8a124a"
        }
      ]
    }
  ]
}
