{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.4.jar",
          "url": "vectorx-data-redis-24.1.4.jar",
          "size": 9717,
          "sha512": "dc5e903d05503d3c03eb982240e63e8ca16787270965af6614d5355b72e160b7f36c9fe38d8cc67a9893ce970dcf87fb74e6ac48b62bea3427dcf9775dc41af7",
          "sha256": "29fa62825d13aa479c0be6464e7764aee203caaee4fca1097c3ac15d5913fca6",
          "sha1": "9a82994f93d3a5920ecaa3d827b9af03982ccc1f",
          "md5": "c5bad7f932b9b328904786a4377c3321"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.4.jar",
          "url": "vectorx-data-redis-24.1.4.jar",
          "size": 9717,
          "sha512": "dc5e903d05503d3c03eb982240e63e8ca16787270965af6614d5355b72e160b7f36c9fe38d8cc67a9893ce970dcf87fb74e6ac48b62bea3427dcf9775dc41af7",
          "sha256": "29fa62825d13aa479c0be6464e7764aee203caaee4fca1097c3ac15d5913fca6",
          "sha1": "9a82994f93d3a5920ecaa3d827b9af03982ccc1f",
          "md5": "c5bad7f932b9b328904786a4377c3321"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.4-javadoc.jar",
          "url": "vectorx-data-redis-24.1.4-javadoc.jar",
          "size": 93494,
          "sha512": "3a150d723e30625969c9178639df594b63bf029073b85de5dc79a49d2274bbe0e4fb65ac6c14416af596cf15bba53dc07e4f470d136b495457939f8b915ea3d5",
          "sha256": "36b14807039e166fc4738e9371bfbf45d7cf846dc727eab79224ef2e8f6ef23b",
          "sha1": "d303ba4828445134c42fd451a952f9686b967367",
          "md5": "abd7125614e1f3aa11aef2acc4400b5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.4-sources.jar",
          "url": "vectorx-data-redis-24.1.4-sources.jar",
          "size": 3360,
          "sha512": "580ddb6c9e635e894a3e1f186ab9495e68775f66771e6adfa2b88a317ab0b8ac59b963f22a650e67ffbae847a39bcbd144e866d304537c93d932d26d20ceff66",
          "sha256": "276cfa9395502a67e9d769d0536194998cba05961908cd90069292ee8c2a3a7e",
          "sha1": "fe3dd7b92ba0472796e64b802a684fbc7a70107e",
          "md5": "a103ae4d921a8d904d72bfaf91320d48"
        }
      ]
    }
  ]
}
