{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-rest",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.1.jar",
          "url": "vectorx-web-servlet-rest-24.1.1.jar",
          "size": 45044,
          "sha512": "ea3631248dfecaecb3a645b7d5cb97b39cc80c4a1aeae8bfc1a2894555155510f41cee7ed8714d09d779c767123c55c69beeca5369d8e55dc660a13910836a61",
          "sha256": "9498b1d4625825d298f4ffcc7c3b2f7f0628b858fb87c2966c802e2c12cb2e18",
          "sha1": "8a9da0714e40e3cf626f4aad2e2bf0f30a11d9b7",
          "md5": "1f3f2bac4fbee8da4a0aefde7b6fac32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.1.jar",
          "url": "vectorx-web-servlet-rest-24.1.1.jar",
          "size": 45044,
          "sha512": "ea3631248dfecaecb3a645b7d5cb97b39cc80c4a1aeae8bfc1a2894555155510f41cee7ed8714d09d779c767123c55c69beeca5369d8e55dc660a13910836a61",
          "sha256": "9498b1d4625825d298f4ffcc7c3b2f7f0628b858fb87c2966c802e2c12cb2e18",
          "sha1": "8a9da0714e40e3cf626f4aad2e2bf0f30a11d9b7",
          "md5": "1f3f2bac4fbee8da4a0aefde7b6fac32"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.1-javadoc.jar",
          "url": "vectorx-web-servlet-rest-24.1.1-javadoc.jar",
          "size": 175774,
          "sha512": "e8a58f9ba1aaf9cf11722a8552e435cdff5b26ac29d56b18abe0f2a695de262f6498cb9498fd92a9441aadc2be62d5f4a758d4d4a1a6e3f4525dec5e9ede4d9c",
          "sha256": "a8f4c3ed75fdaff30b873849eb49275f7cc160eac41645c810e7dabf3a029395",
          "sha1": "44c4adc37c745695d7634d75ac7bbcb47695f7a5",
          "md5": "94b7c1fe12c219b9bd2767eb3039587c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.1-sources.jar",
          "url": "vectorx-web-servlet-rest-24.1.1-sources.jar",
          "size": 23336,
          "sha512": "8e7c01b3bfa8062a5887259fd13bef33a138d28c6816b7746f9a94f2eb05101c3ca9e33924dcd7ff882f32bf2f0fac8246924278beb3640ed1f59b47434658f0",
          "sha256": "1bbb895f6a932da931e547cf8676e37b192d1a6811d305b8373ff9805ccd1586",
          "sha1": "3ec2419c8ba138dd34284c65ebb1868605f20e01",
          "md5": "22264fb6992af464fa8c4963e95d97f8"
        }
      ]
    }
  ]
}
