{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-manager",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-batch-manager-24.1.8-SNAPSHOT.1.jar",
          "size": 45174,
          "sha512": "8a540e564de2200b46dd8932d9af17a54a9869e5f58c691d783652bc4148ff954b58485b7f5ddb0a58f90b933c43951fe152b82c4b49857194d0ee737b7d4f09",
          "sha256": "1e89026e6576564be453fe947a492d9e00901ff77f25ac9a8321e5b2f58e1fe4",
          "sha1": "3f428e2605f3122d295fa792b21f7234e71a9d8c",
          "md5": "624e5131d7ee7b33249e1812bac2a12d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-batch-manager-24.1.8-SNAPSHOT.1.jar",
          "size": 45174,
          "sha512": "8a540e564de2200b46dd8932d9af17a54a9869e5f58c691d783652bc4148ff954b58485b7f5ddb0a58f90b933c43951fe152b82c4b49857194d0ee737b7d4f09",
          "sha256": "1e89026e6576564be453fe947a492d9e00901ff77f25ac9a8321e5b2f58e1fe4",
          "sha1": "3f428e2605f3122d295fa792b21f7234e71a9d8c",
          "md5": "624e5131d7ee7b33249e1812bac2a12d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-batch-manager-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 139596,
          "sha512": "8e914929259e3adc5f3b47ae6e990cea96965577ae49f607f7d841f688dca341f457ec339ea05951016955499452036378b5d3595a3faf07a993217952188b92",
          "sha256": "b6be4c45690cc0114dbc9952de8da6e9b2fc7450dfab4ea5e7d3aea94d1596d2",
          "sha1": "3da992a9efcdd84c6f4545aa8f56551f930ded76",
          "md5": "8cdaef98cd7b65139941a6d51371ff65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-batch-manager-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 20387,
          "sha512": "d338926454d08e63a16400a19c0529cb558b075bd3e92003ce6c07457f171f7272569cd79fd4b03d2eddd3a7dad6ab8cc4cb400001ffb68eb1cd4b5381ce26d1",
          "sha256": "dae0baf4271be1c852ef1b72930af298a9d19a1024d3181aa1a44c702bf2ee6d",
          "sha1": "1550e70da1ee81894820487dceba61d4d31d2f29",
          "md5": "73ec437e904769c915d7aea1f8994827"
        }
      ]
    }
  ]
}
