{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-view-front",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-view-front-24.1.8.jar",
          "url": "vectorx-starter-view-front-24.1.8.jar",
          "size": 261,
          "sha512": "212b3a4ed5366c45f62f5fb92701eb785fb8a920c2088ed917ef5b681c13f98e7f1dc1639ff9c6125c7546491aeaaa385f34a233c38c0e27417ab0ba4a508d4b",
          "sha256": "c6b4af9aee772814159a0d1cf87d71b4e8b1be1a3d3afdbc81d803cba89e51be",
          "sha1": "eee135d261efe2b2f4fde583ee84071bcbe8b80d",
          "md5": "5108564d3539b0992d32453fcd0dfc73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-view-front-24.1.8.jar",
          "url": "vectorx-starter-view-front-24.1.8.jar",
          "size": 261,
          "sha512": "212b3a4ed5366c45f62f5fb92701eb785fb8a920c2088ed917ef5b681c13f98e7f1dc1639ff9c6125c7546491aeaaa385f34a233c38c0e27417ab0ba4a508d4b",
          "sha256": "c6b4af9aee772814159a0d1cf87d71b4e8b1be1a3d3afdbc81d803cba89e51be",
          "sha1": "eee135d261efe2b2f4fde583ee84071bcbe8b80d",
          "md5": "5108564d3539b0992d32453fcd0dfc73"
        }
      ]
    }
  ]
}
