{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-rest",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.4.jar",
          "url": "vectorx-web-servlet-rest-24.1.4.jar",
          "size": 45090,
          "sha512": "c857eb7b408e16946ca637e519af01d3f77477075af3d287af1467809ad443eb55b1a5fc73f47491c1cba2bec6b34e80841bbe23f3e208080cc5bc814caf4142",
          "sha256": "8b9224f738b211cfd740054bb462242810d8ba01932f8361885942e4b48d905e",
          "sha1": "aa65f07e08da971717ed031910c72f333f7a2fe0",
          "md5": "bc352f770127d4a9e60a1bf8caca0745"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.4.jar",
          "url": "vectorx-web-servlet-rest-24.1.4.jar",
          "size": 45090,
          "sha512": "c857eb7b408e16946ca637e519af01d3f77477075af3d287af1467809ad443eb55b1a5fc73f47491c1cba2bec6b34e80841bbe23f3e208080cc5bc814caf4142",
          "sha256": "8b9224f738b211cfd740054bb462242810d8ba01932f8361885942e4b48d905e",
          "sha1": "aa65f07e08da971717ed031910c72f333f7a2fe0",
          "md5": "bc352f770127d4a9e60a1bf8caca0745"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.4-javadoc.jar",
          "url": "vectorx-web-servlet-rest-24.1.4-javadoc.jar",
          "size": 175850,
          "sha512": "515b8016bdaba6e8f4e61cf73e0d751cc56d7736312d0a624daa1fde6354c4854bfd636504bf4af98603ee9ffeb9434772da6e8523bc70a8790cae4f578aa0b9",
          "sha256": "b580958a30e591d76fa1a7940ecdb892a739fe5c10d2190d7c00ae3a2b6ccfc1",
          "sha1": "7044c3192b55a35ec952dda6bd7b7853d28381c5",
          "md5": "8abc4a2076dfe3baa986fb69e0bd1ae7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.4-sources.jar",
          "url": "vectorx-web-servlet-rest-24.1.4-sources.jar",
          "size": 23382,
          "sha512": "14902d68290e9afa2c5a6ccf2f54b840488e418a160f4d0d9d951a6bad0f06722bacce0a43075bd5bc6a8fa40dcdef27a6f4e6993d3d700aeb70e639e0708ee8",
          "sha256": "38ef8037916bc6e07272fee805efa8d2bd8d7095a620e8c2956d6a9940bf07fa",
          "sha1": "6e32be3db39a52d6be80a266410cc80767fc7aa1",
          "md5": "0aa9203ce8fe7e261fce33eb06e7f48e"
        }
      ]
    }
  ]
}
