{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-rest",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.4.jar",
          "url": "vectorx-web-servlet-rest-24.1.4.jar",
          "size": 45045,
          "sha512": "716f8c8f35d9a63b9e44f97f4057b74252bfbb05559c2aeb031caf3b3c5b1cce587f967be31aebf2efb907bd95d225a03cfdf6157feb76e7a2f46ddcefda612b",
          "sha256": "57c728c0351e0a71250b2966a128dd7799eb5a172d92f322ca42813e05429882",
          "sha1": "77c09b514d3c4a666aebd7b0bc7becd1634de7b1",
          "md5": "2376dd383ba8b5f7cc26addcd9defc3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.4.jar",
          "url": "vectorx-web-servlet-rest-24.1.4.jar",
          "size": 45045,
          "sha512": "716f8c8f35d9a63b9e44f97f4057b74252bfbb05559c2aeb031caf3b3c5b1cce587f967be31aebf2efb907bd95d225a03cfdf6157feb76e7a2f46ddcefda612b",
          "sha256": "57c728c0351e0a71250b2966a128dd7799eb5a172d92f322ca42813e05429882",
          "sha1": "77c09b514d3c4a666aebd7b0bc7becd1634de7b1",
          "md5": "2376dd383ba8b5f7cc26addcd9defc3c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.4-javadoc.jar",
          "url": "vectorx-web-servlet-rest-24.1.4-javadoc.jar",
          "size": 175783,
          "sha512": "83854444c5449b16e7f5713d77f31f75de9e5fd64e2cd250cf19a2cf450f85920b9a0dfa089c30b0a46c62469b7a6f529218c1611c9298d9c9b4b81da84b9bfb",
          "sha256": "09ead20055d3cc0886bb97f8b665b6e820d9ead877a2caa17504d981c54a7e07",
          "sha1": "e5f6a832183d5a459c3d5df86fadca2ef4ecade5",
          "md5": "d625ec9d14ebb411ce212b79f3bd2e31"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.4-sources.jar",
          "url": "vectorx-web-servlet-rest-24.1.4-sources.jar",
          "size": 23336,
          "sha512": "13f61ecd05e8cc85794bf4bd789801e2693a732295581433eb426a53f8b2e362c1946f922219dc3de3c0a9e5dfddd7a4f98ba6039529cf312ab0e57c8cfd8f7c",
          "sha256": "6061c8a7a92d921af76cb6ec2d01ebf6ae17a59da405bfbcd98385ccc950d83b",
          "sha1": "415337d66140c22b8caccd1ae93f13b51e208b02",
          "md5": "250c5e7753b48d3b97691b98bf913e23"
        }
      ]
    }
  ]
}
