{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.1.jar",
          "size": 2774,
          "sha512": "97ccba2e8169f17dff6e52a01729e7e5eb989764e07e6d754c98264824e8e188e181186dc703109fb663afc877b20fbf96c4509fe54c2a81f2670b064d5fc7b1",
          "sha256": "9189db83ebc6031d82af187c40500757302c66ec60bd060aac73ff58a8d9294f",
          "sha1": "7fc0330bbc4335b305800a507c175a31b6892cae",
          "md5": "2d76d51b050bfd16ed1fdc844086e6e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.1.jar",
          "size": 2774,
          "sha512": "97ccba2e8169f17dff6e52a01729e7e5eb989764e07e6d754c98264824e8e188e181186dc703109fb663afc877b20fbf96c4509fe54c2a81f2670b064d5fc7b1",
          "sha256": "9189db83ebc6031d82af187c40500757302c66ec60bd060aac73ff58a8d9294f",
          "sha1": "7fc0330bbc4335b305800a507c175a31b6892cae",
          "md5": "2d76d51b050bfd16ed1fdc844086e6e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 70462,
          "sha512": "10c7d1b8028eac23f555e1473942116c336449aa6aa7806299800a9796793306cf6640ec1d80d1c9310e5a288eff5aa55c49724b32426f59dade8f357086ce9a",
          "sha256": "baf2f118fbdc9375c91c5279bdf8d4db524572234a1d6629b25a58a5e155d445",
          "sha1": "044a291844dfb513785b5c6b54e925f3c36bd50d",
          "md5": "0a822ce3981b6fcf69de3be938bdd869"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 1228,
          "sha512": "8127f4b26437dd0546195e31a5f31feb324ac9a28f8521e1889d4ff8e1bbc88c85ea793b49ef83c580371cbabd4588b0f17ccdc565849b2628043b8a8635fe15",
          "sha256": "52ef4bed5dd62724eb58bb115033fefb9006619795498881ea573a71becd1379",
          "sha1": "d0e105fb9a1cb92658f0381e6a327ee1acbe6724",
          "md5": "5106e5abbd04a350c4559bee23581ae6"
        }
      ]
    }
  ]
}
