{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-test",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.5.jar",
          "url": "vectorx-test-24.1.5.jar",
          "size": 31765,
          "sha512": "ade467be95ea2bd155ebee9bfd16356f30a2b8a787df70e9d57747fb6315c3030a0cb0cd7a75795bde01f0d03ddb333599880b2fcfc1b65d86ee04b5c0b22a73",
          "sha256": "6b2cd8566e16b06b9b8997682c693299e4835d7de2cf0d90070836ecb352f8af",
          "sha1": "380c6b5ecb32af50a138e5d9f9d6175854200659",
          "md5": "a5ae3b49814dadf9d3a12415e4784e59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.5.jar",
          "url": "vectorx-test-24.1.5.jar",
          "size": 31765,
          "sha512": "ade467be95ea2bd155ebee9bfd16356f30a2b8a787df70e9d57747fb6315c3030a0cb0cd7a75795bde01f0d03ddb333599880b2fcfc1b65d86ee04b5c0b22a73",
          "sha256": "6b2cd8566e16b06b9b8997682c693299e4835d7de2cf0d90070836ecb352f8af",
          "sha1": "380c6b5ecb32af50a138e5d9f9d6175854200659",
          "md5": "a5ae3b49814dadf9d3a12415e4784e59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.5-javadoc.jar",
          "url": "vectorx-test-24.1.5-javadoc.jar",
          "size": 125844,
          "sha512": "2e4ee298db9ec88bbbe1d86438919ef6ceff95acce59a282527f394c9bf81248cc6ecf38009d69fb2e2b6ed8bfbac85682162c5375cf87b77c18cbb971d080ff",
          "sha256": "db56dfff9f3a7750dc5d5c7bc62e615657cd221d62e874c581ee605fd9c479e2",
          "sha1": "f5e36e66efaf554bb1feae1870c6450db2bc468d",
          "md5": "6c2a1723c6bfec63826766b45ce3a51e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.5-sources.jar",
          "url": "vectorx-test-24.1.5-sources.jar",
          "size": 11947,
          "sha512": "bb36c06726150ea45c4b577cbc40acb2164873354dc50c8650f4bf3ab5bd63483d10ffd4a0fdf81e96bb6b8b21712ab38edd962c129e23adf573d9f32cc5da49",
          "sha256": "ee6b4e26f58ded7ab93c84fd10dcbc2a874ee389cfbe14b2141dd3deed235fa4",
          "sha1": "e0c058a0959f593734cdf10c3b526db374dab12e",
          "md5": "9ed5f788d7194f3757e47bfb1d8a3e52"
        }
      ]
    }
  ]
}
