{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.13.jar",
          "size": 185545,
          "sha512": "8910e23a24a5647e23332ee9e25e8b2e37ae4221d6c7633ec4b5d961c062ab1b14b4f37837992aac76bb4af21f3bbc7adbabf8fd484dd2f843a47a7bfcd111a7",
          "sha256": "5f870de078da73d770172e730e14232829356326c8bc46b5f53363c77bf8f4d4",
          "sha1": "746ab933bb806da7576bfd2b9ebb1cc3d5721b65",
          "md5": "45d97dfe44d11a1ab64f9782ea2e9ef9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.13.jar",
          "size": 185545,
          "sha512": "8910e23a24a5647e23332ee9e25e8b2e37ae4221d6c7633ec4b5d961c062ab1b14b4f37837992aac76bb4af21f3bbc7adbabf8fd484dd2f843a47a7bfcd111a7",
          "sha256": "5f870de078da73d770172e730e14232829356326c8bc46b5f53363c77bf8f4d4",
          "sha1": "746ab933bb806da7576bfd2b9ebb1cc3d5721b65",
          "md5": "45d97dfe44d11a1ab64f9782ea2e9ef9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 296296,
          "sha512": "1f6b2706e81444061b2bc3ea8e527f26097532af4ce1d1fa79cf323ba9c5855d6ec6195084e3dda82ffe6c1384b3af8f685383811d797e66c1bf0ae7270a601a",
          "sha256": "7b97e10c97af4238e6a0273721f867133835126c1944330b139718c421e0ae8b",
          "sha1": "c06db9d2910035c00dd4c3a4f7e2d3590991960c",
          "md5": "51cfe2d66ff065dc568d852279c34ec5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 68982,
          "sha512": "295e4dcc9c9800d885f49d07d0e0f7503fe54f1e1248318c3fe8a92a91274e3602d47eaf416fb4cd8d2fd5bfc7d66d7548efe4c9fb10bb7f2a53c91e2c1e6c29",
          "sha256": "90687ac512f45e1b2b6e3a7c88ff0d2e23e8ceaca45b090a44a4eb8949e0c5aa",
          "sha1": "abb979b43a85fca9e638ff0fe12bf9301d959210",
          "md5": "5264706f6802b01f09286010bad4d688"
        }
      ]
    }
  ]
}
