{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.5.jar",
          "size": 145555,
          "sha512": "2edd27efb10d59ca35d3508287e8ac5207d4178d147c4d05380f1f9478b77cf1ac3f732e6a03753770b12051f1c9050d7e433fa2ddbf37e85085dcedb384f293",
          "sha256": "5e2795c8393c05a7045adef9b6497172a91406ea1544037a7c60f61886093fbc",
          "sha1": "ee5598b5300cc1768a3a4f35067c556d0cc8f6a3",
          "md5": "adda904d0bdc5fe0651f7c6b0c986420"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.5.jar",
          "size": 145555,
          "sha512": "2edd27efb10d59ca35d3508287e8ac5207d4178d147c4d05380f1f9478b77cf1ac3f732e6a03753770b12051f1c9050d7e433fa2ddbf37e85085dcedb384f293",
          "sha256": "5e2795c8393c05a7045adef9b6497172a91406ea1544037a7c60f61886093fbc",
          "sha1": "ee5598b5300cc1768a3a4f35067c556d0cc8f6a3",
          "md5": "adda904d0bdc5fe0651f7c6b0c986420"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 306945,
          "sha512": "8c18a52d190fde81c771dfef9b39816b98a1468b8c546fddf9983818eb8714ba67f6be2e97412348892c8980b6a9ad41b7b60931980e9577779a608452c332fa",
          "sha256": "757688178e093d4d673c90178b14b240d18a361dff8cc2726939e444c5e8c7a3",
          "sha1": "eb620411a45dcdbeb669d946b9a89fdc067800ea",
          "md5": "9bf7dbf441e149aeab1b9dd0333596a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-management-bo-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 59353,
          "sha512": "7c5f79853bf81f3149b93391e33dc3eae2d7c5b0f0ac4ed4d2dfd1e1968e3463b38df24132f80515b7db50d34219ba95882c38fcc03c2c88e600f81fd21c1921",
          "sha256": "26faf021ae699af89a6e47e532ed9120334447f51f98398c6b468f9bce34cbef",
          "sha1": "adbdef785ae454f8d27d489452ec5f21ba1d21fc",
          "md5": "0c6175a450a913e821c2f38ac6e161a5"
        }
      ]
    }
  ]
}
