{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.6.jar",
          "url": "vectorx-web-socket-24.1.6.jar",
          "size": 22971,
          "sha512": "03d1a21bee29c477197bb7fdeb5ac39e486bada50fe8512b9c198b3baa504e8af9334db54bbee15a6c638f546373b8aeb9a9f7a58a6f7c8f56afd16f538503e5",
          "sha256": "d65a9d3d77810d2e82ee21bb1071f992ca7f12f49b18f7e24a463139194eed61",
          "sha1": "90b8f4b2a27d8f0cb4528a849b8f9164c76ab6db",
          "md5": "32455501b90e42f44768af4cad4c98e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.6.jar",
          "url": "vectorx-web-socket-24.1.6.jar",
          "size": 22971,
          "sha512": "03d1a21bee29c477197bb7fdeb5ac39e486bada50fe8512b9c198b3baa504e8af9334db54bbee15a6c638f546373b8aeb9a9f7a58a6f7c8f56afd16f538503e5",
          "sha256": "d65a9d3d77810d2e82ee21bb1071f992ca7f12f49b18f7e24a463139194eed61",
          "sha1": "90b8f4b2a27d8f0cb4528a849b8f9164c76ab6db",
          "md5": "32455501b90e42f44768af4cad4c98e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.6-javadoc.jar",
          "url": "vectorx-web-socket-24.1.6-javadoc.jar",
          "size": 128221,
          "sha512": "160e798887b5d0ac91f3a475c51e2446bcff2b254b478be1ba5c6d2ddb1d3a7013d3915755d91639859baaabccdb2b7c204f77916213b7e9a370000b5ac70c3e",
          "sha256": "315b9261b639a3d843cb2358335fadd6f486553e2f60e236579c29612dbdb86e",
          "sha1": "a294870670d5c3dd343fc3d04cd1c98b15646a70",
          "md5": "77f13994eaa103ff75619d8fa67c48d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.6-sources.jar",
          "url": "vectorx-web-socket-24.1.6-sources.jar",
          "size": 11406,
          "sha512": "cf6a0ae3e6019a36f267f9d794decc6704082d39303b524e6b373dce7dd01757eca1bb0b244f6ff0aac9f355a18dfb14054583aa3d312283eaeb987acbd04d72",
          "sha256": "981a187048919b4af646fb03d0f45a656482b17222bf6e56a27f2fadd332fbd7",
          "sha1": "ea0406ff1a40dad65c159e37310cccd60ad15108",
          "md5": "6337918f971fe40157d389b0d1dca249"
        }
      ]
    }
  ]
}
