{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-socket",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.3.jar",
          "size": 22999,
          "sha512": "6bdb9a5bcc744badb72896f957ee827f95318c969f907e9366ad7d972090b35c17a9771f7ec2721259cb969116c83acce628e9f79564b60ffa4e41d2485f2100",
          "sha256": "89adb4ed7719e5b8eee6a179131a098a7ee760ce759ce92a3253f0173c9b2e21",
          "sha1": "31528a5066aff409e9f97e0a5506d5ac18f9ff00",
          "md5": "c7c21300e65f0efc7a48c390e9ec24f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.3.jar",
          "size": 22999,
          "sha512": "6bdb9a5bcc744badb72896f957ee827f95318c969f907e9366ad7d972090b35c17a9771f7ec2721259cb969116c83acce628e9f79564b60ffa4e41d2485f2100",
          "sha256": "89adb4ed7719e5b8eee6a179131a098a7ee760ce759ce92a3253f0173c9b2e21",
          "sha1": "31528a5066aff409e9f97e0a5506d5ac18f9ff00",
          "md5": "c7c21300e65f0efc7a48c390e9ec24f3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 132054,
          "sha512": "c982d57e7f32525b6f85f42db3a1b1f0f88bc90107decfcf7ec391505779f693cd616a1135c116d5b8fc49be1e8c302574dee5ee9d5f793559c0418be446f578",
          "sha256": "59b6f570769c82377116f365af4806cd4d1347d4afd0e1a86b77005dd0942eaa",
          "sha1": "a7763ffbd72d5cb6520b3c4401e2b8f4a96f79cb",
          "md5": "2fb1f2abb6f5e7d4d88e09b3c27dbad0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-socket-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-web-socket-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 11319,
          "sha512": "c4cab1ae56d689f2cf3ea1a6a9f2ca7368f94b655f3c6e507dc0edbadebf4147e7d811de352abbd0bcbe20237db0246ed3a479031fcfd6364f91889d4179f754",
          "sha256": "12f2eef8be09287c2d3a7310a4fd1c62748159d56a71ff51cd32bcdd2f841bbf",
          "sha1": "8a7801d9999ff2c01c8bbab9dc15cadb3693a640",
          "md5": "6f430a9544d0466afecadb353387a3dc"
        }
      ]
    }
  ]
}
