{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.7.jar",
          "url": "vectorx-cloud-core-24.1.7.jar",
          "size": 2696,
          "sha512": "5e39a2b5ee7ff8c69117bf7b275dd82a50aa6cb7450d7789696be33d811de754b25344ecb5a62f62687edea097d69a01320009ec0978f4a57511e789c7df7ac2",
          "sha256": "ff565f0f372b28b7d699d52651884c620930cc36ab748099eac17084fab3fb2b",
          "sha1": "ca148ce15d9c332edb1a5e3e210942e5d2fca995",
          "md5": "f2fb60da6972153160c79429491e2601"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.7.jar",
          "url": "vectorx-cloud-core-24.1.7.jar",
          "size": 2696,
          "sha512": "5e39a2b5ee7ff8c69117bf7b275dd82a50aa6cb7450d7789696be33d811de754b25344ecb5a62f62687edea097d69a01320009ec0978f4a57511e789c7df7ac2",
          "sha256": "ff565f0f372b28b7d699d52651884c620930cc36ab748099eac17084fab3fb2b",
          "sha1": "ca148ce15d9c332edb1a5e3e210942e5d2fca995",
          "md5": "f2fb60da6972153160c79429491e2601"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.7-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.7-javadoc.jar",
          "size": 70381,
          "sha512": "c66a7142af30ce836ff6735c0dd823e1a3612a45e02f530361c36fa99d7a27b54463804f89a88d554e191be5dbb5182e4411c3a8d41e81ed879ed8c0434b7359",
          "sha256": "a50cfb8df371e9420366bb174c4c2d555b04c13cbb3cbce164bdeeca32fcf71d",
          "sha1": "fd6cfffe9b5f3a2684db2a7f73ed8b733c3732b0",
          "md5": "5c9ad930664b73eeea0f3e317fa99684"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.7-sources.jar",
          "url": "vectorx-cloud-core-24.1.7-sources.jar",
          "size": 1186,
          "sha512": "c5fd4baa305512086cc3143f6fe7e808849bfd9ce0abd044fa1fcea861c8b33d36cba168f5a39749fa89c43f3732fbb97f2be0e4affd210ad8a2ae56e4a7ca7d",
          "sha256": "363a0d03496e00c0a75412a413ac59df760f2792799034fc43705a715878a235",
          "sha1": "aae8167c63745744d333e4f795e1026059a7cf2d",
          "md5": "b2c88e68bf9b1b09ce5351e3038189ff"
        }
      ]
    }
  ]
}
