{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.5.jar",
          "url": "vectorx-data-jpa-24.1.5.jar",
          "size": 2692,
          "sha512": "e65ee16c8cca8a2d2318a4f6583a363fa0020848ea53adda5470a8eda0b99295368fddcff831401a53f9d17d88dd3c078a6e9065c7fd870e615c85581d175782",
          "sha256": "88edfac9388ac8bdba7fbc65a8af7aa655da46dabd66aef4ef1e64573f5f0203",
          "sha1": "13e65f858a7b3d87fcf739e83fa062c7cb40aa2f",
          "md5": "6103f2d38206d6d3bc096ff80bbf2c14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.5.jar",
          "url": "vectorx-data-jpa-24.1.5.jar",
          "size": 2692,
          "sha512": "e65ee16c8cca8a2d2318a4f6583a363fa0020848ea53adda5470a8eda0b99295368fddcff831401a53f9d17d88dd3c078a6e9065c7fd870e615c85581d175782",
          "sha256": "88edfac9388ac8bdba7fbc65a8af7aa655da46dabd66aef4ef1e64573f5f0203",
          "sha1": "13e65f858a7b3d87fcf739e83fa062c7cb40aa2f",
          "md5": "6103f2d38206d6d3bc096ff80bbf2c14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.5-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.5-javadoc.jar",
          "size": 70340,
          "sha512": "a115f58389b01f9463554c4cf9a283e1435ccc61e77f634f22f52e2f5d1d93479bcf657bbb6c54bfb14b1614b739d7cfc31fac9620c8331b175dbb8d30aba1d1",
          "sha256": "00c619713e1f9a44f6ca75994e1dd4419cd4242f09fc789545a1cd29c69adae3",
          "sha1": "3fd493bedc1735bf7351e0279a85e35c8d5740f1",
          "md5": "fa050f328c5c77acf94a24a2ec8068cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.5-sources.jar",
          "url": "vectorx-data-jpa-24.1.5-sources.jar",
          "size": 1184,
          "sha512": "7ad8e47201c4431c8aa24becb5c662058a3020099ab0c2d8877e8a6b76139b17c22b72214c6550a50e93dbd28a13c56e261705e725ae3257341e98cdd0a5a2e3",
          "sha256": "2b4ece743cd2fa0954c42f97ff7ac62f971cc5f97e0a3f69e27a67c193040ade",
          "sha1": "a44ad80aac5a4b02f370394afe77ccecd7c1e880",
          "md5": "1004b369664aefe8aaa650c75d926cb8"
        }
      ]
    }
  ]
}
