{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data",
    "version": "24.1.9-SNAPSHOT.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jdbc",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.bgee.log4jdbc-log4j2",
          "module": "log4jdbc-log4j2-jdbc4.1",
          "version": {
            "requires": "1.16"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "com.itextpdf",
          "module": "html2pdf",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.jodd",
          "module": "jodd-util",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.14.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.14.jar",
          "size": 497252,
          "sha512": "3ef6fc304faec1fa1e927cea50c0cc866b5be27f2c6862209da01c3fc12f735a509d45b58ba0d7f8539067e3d6abb63115636593b138ddbcf48d5787b6c20c8a",
          "sha256": "2aa526736c333089a2ac8ed82194dbd1c65f5007b8bf60a5fec89b054544313c",
          "sha1": "6235dfddc27ad2cd5bf25c3a653dcc756222e467",
          "md5": "a9e80fd07c7d98420f6945570a359c31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.14"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jdbc",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.bgee.log4jdbc-log4j2",
          "module": "log4jdbc-log4j2-jdbc4.1",
          "version": {
            "requires": "1.16"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "com.itextpdf",
          "module": "html2pdf",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.jodd",
          "module": "jodd-util",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.14.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.14.jar",
          "size": 497252,
          "sha512": "3ef6fc304faec1fa1e927cea50c0cc866b5be27f2c6862209da01c3fc12f735a509d45b58ba0d7f8539067e3d6abb63115636593b138ddbcf48d5787b6c20c8a",
          "sha256": "2aa526736c333089a2ac8ed82194dbd1c65f5007b8bf60a5fec89b054544313c",
          "sha1": "6235dfddc27ad2cd5bf25c3a653dcc756222e467",
          "md5": "a9e80fd07c7d98420f6945570a359c31"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.14-javadoc.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.14-javadoc.jar",
          "size": 1261910,
          "sha512": "92731a2765ead8c5f84efa3df6056e3345f942ca3fb5bd757da5670bcfc686553a4cebf6c85fe2c84018abf311ab74b6323ce0f318020d2a1d50b736a2bfca8f",
          "sha256": "1833b510ceaee08096ecb988fd374ae65a025590b9768d100063ba8ae4067bb4",
          "sha1": "67ee4507c13bebf05b7928e2f258c43bccd86673",
          "md5": "ceb103ae1ed6f33542004bf81b35ca00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-24.1.9-SNAPSHOT.14-sources.jar",
          "url": "vectorx-data-24.1.9-SNAPSHOT.14-sources.jar",
          "size": 211464,
          "sha512": "38d805ee08e18f7667b8b31d278ac229df5d96e149922934a31a4e6f9da035b2c8542862fda5a396622cb8370c60e396dd035fed31ef4269be46cd52c0bf1c9a",
          "sha256": "13624b7f47060cc605b55a6a7dbd67fdd7928d07488c57c4d99dc6b8d6bb61c6",
          "sha1": "ad8011d40d138a77a107426b6169b4de9b2343f0",
          "md5": "367cdde7004def6f853dd4bd58922be7"
        }
      ]
    }
  ]
}
