{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-rest",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.8.jar",
          "url": "vectorx-web-servlet-rest-24.1.8.jar",
          "size": 44319,
          "sha512": "42d972b1669ff4b8eb35c9277c922ac86a26d0458452cd9f090ab8c29d8d36bed71269ece18232002fd65eaf793c5f8832e2d6ca38608c2f9ff872415b764c63",
          "sha256": "f2cf9b050c745566b56f60116ff874a0e7dd74708bff1067f953b01656b64a7c",
          "sha1": "c701825b2ce53bb5be748be4dbb833f627c61bbf",
          "md5": "32b71363a7592f9082dbfca2cfa48fce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.8.jar",
          "url": "vectorx-web-servlet-rest-24.1.8.jar",
          "size": 44319,
          "sha512": "42d972b1669ff4b8eb35c9277c922ac86a26d0458452cd9f090ab8c29d8d36bed71269ece18232002fd65eaf793c5f8832e2d6ca38608c2f9ff872415b764c63",
          "sha256": "f2cf9b050c745566b56f60116ff874a0e7dd74708bff1067f953b01656b64a7c",
          "sha1": "c701825b2ce53bb5be748be4dbb833f627c61bbf",
          "md5": "32b71363a7592f9082dbfca2cfa48fce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.8-javadoc.jar",
          "url": "vectorx-web-servlet-rest-24.1.8-javadoc.jar",
          "size": 175878,
          "sha512": "60f127c7c5287fabf2c3f5149264686c393bceaa4274efb35da126fee83cac2af43814431bdd02b1e2c3c1a88fe5411e35b2df4fff5b1eed29eaade256390403",
          "sha256": "6280f7a4611f5bdb6162d8aaadcd46e3db8f85c24c3773866d5e967da1a47307",
          "sha1": "3c93b78ec842a8bcf126e0eb9ca292e1ce367da9",
          "md5": "409412ea03bca39d094d213fbf737be6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-rest-24.1.8-sources.jar",
          "url": "vectorx-web-servlet-rest-24.1.8-sources.jar",
          "size": 24087,
          "sha512": "fbc597095cd3382fc0a1a5c27cf2d5dfd3d2d89aa8f8206bc05a412c27a9470781c3c59e97a74558d3e9ef5888cafc2957f1f0eb7d8c115d80d2788e0e76009f",
          "sha256": "828a24647467c85730d2ea948991b43ee7f472c3194aff542b08348f8bc99cdc",
          "sha1": "73bb566fcfdede098eada4f89ea571f1dcc72bb7",
          "md5": "5f9c193bdccfda8180de00e59eb2a809"
        }
      ]
    }
  ]
}
