{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.7.jar",
          "url": "vectorx-web-servlet-tobe-24.1.7.jar",
          "size": 811829,
          "sha512": "e0a4c62e7540b0518d2d34ba3c357ecc53679fe8856e65438fc2f9c0cecb6c732fa988c109d3c02ebf3e472631c04408be0281b6a12ccefe49cedda3b7d3c53b",
          "sha256": "f9b58b6bc2d3738174a326dedc85c997ed16d4e7ce01796bc6f4fbe513bf2743",
          "sha1": "07bd78ccf0aca273fd51054003dca57f99bd125e",
          "md5": "5c20080b0d4b18e6e92cf98760811cc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.7.jar",
          "url": "vectorx-web-servlet-tobe-24.1.7.jar",
          "size": 811829,
          "sha512": "e0a4c62e7540b0518d2d34ba3c357ecc53679fe8856e65438fc2f9c0cecb6c732fa988c109d3c02ebf3e472631c04408be0281b6a12ccefe49cedda3b7d3c53b",
          "sha256": "f9b58b6bc2d3738174a326dedc85c997ed16d4e7ce01796bc6f4fbe513bf2743",
          "sha1": "07bd78ccf0aca273fd51054003dca57f99bd125e",
          "md5": "5c20080b0d4b18e6e92cf98760811cc5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.7-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-24.1.7-javadoc.jar",
          "size": 1064716,
          "sha512": "764d419ca9663ecfc298478c2f49b678fcafa30c29f6f0a6199fed6e65da5f4f2144a74916215f67e78c765bbaf9ac09820244dbb4c37c6be0fadb635210838c",
          "sha256": "bc9ff95d6ce21f105c48bb1cfdb7e4b580ddc740c162e3b8bdd33304e0fa10e0",
          "sha1": "dd662c9f9c37e6667e1c2df1b3c2a04e0f0b1d89",
          "md5": "a83467576fd8a61e1872d150f120ea25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-24.1.7-sources.jar",
          "url": "vectorx-web-servlet-tobe-24.1.7-sources.jar",
          "size": 413021,
          "sha512": "2d2370c72b89ec354f25784b3333c2571859318b40e6d9d6bff83f36b581a11fe27c784d11d436df75b544f190b53ccfc107e71527f57dff7615f8460cdaac25",
          "sha256": "83beea9615eddf8db7f011d5c56abb548c2ba85f98713a6470369960c744388e",
          "sha1": "6c2cdb52492ad118ee4f457b71545e7a6ba53c34",
          "md5": "06d6ce915c10fd3bf554446f4293e468"
        }
      ]
    }
  ]
}
