{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.3.jar",
          "size": 51899,
          "sha512": "69cc61c2df310cca9dbd7445a4a844eab0ebe5855ea087a7726f489016fae6cd6d85743b29fce08110bade4f9ff8ea9a29cbac5df40154828fbf4ed18ce4abbe",
          "sha256": "cc44823de6a377f8a64112edd310c7a889c8678408b6471f5b89e1d0b5a154b2",
          "sha1": "05750bbe0506f3b7503c2dd2fc02b53ca0049aa7",
          "md5": "c2c1912b1a5a8f0c953e42f21300e23c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.3.jar",
          "size": 51899,
          "sha512": "69cc61c2df310cca9dbd7445a4a844eab0ebe5855ea087a7726f489016fae6cd6d85743b29fce08110bade4f9ff8ea9a29cbac5df40154828fbf4ed18ce4abbe",
          "sha256": "cc44823de6a377f8a64112edd310c7a889c8678408b6471f5b89e1d0b5a154b2",
          "sha1": "05750bbe0506f3b7503c2dd2fc02b53ca0049aa7",
          "md5": "c2c1912b1a5a8f0c953e42f21300e23c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 183876,
          "sha512": "633a789b15869185b1f494e2ddd6a5cb7ab2a4e179eef56b408a7380627c18085ac319734092a436eb2436b0229d72835cdf16bdae284a2ebef256a790662fc3",
          "sha256": "11c553c78ae61b63759d97dd9e4cb4dd2185064b799d25f9c77d06603883a5c2",
          "sha1": "779f69f34944312504767dde990ad6c7ab1b105c",
          "md5": "3a039d0b57d3190c3811c3aac9744bec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 23397,
          "sha512": "dfc590f483579d0bae4a6779b5a0a3a6fd51f5a81ca96023071aec0108bdf7eb3725be2925e01af4c4e9cb20aa127887bbed61a7b26655a342f6754f3b19b2f1",
          "sha256": "7a006c61755ef471492f45f16cb692f3ce29e81d82675bf2485f80528cfd6f9e",
          "sha1": "fe156410ee0259806bb7e493bceed683bf69b067",
          "md5": "084b8499dbfc6c29a841b00909626a11"
        }
      ]
    }
  ]
}
