{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.1.jar",
          "size": 244275,
          "sha512": "e83c793439dfb6d38560791bb2b9f19a3127ca66e715a7b17092c72073d552924bf5f06056095d92fc0fec0f6ecb22d2e024991c6f0709c31ff708c7dc70ecad",
          "sha256": "5543f159ab80a31e3a46929e9b778e87182c09ed83de446edeb03f9923cac876",
          "sha1": "5bae6611843ff465a4db4d3f14ed7f03ff58f072",
          "md5": "d1265621ff1b07d1471cc2baa7909960"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.1.jar",
          "size": 244275,
          "sha512": "e83c793439dfb6d38560791bb2b9f19a3127ca66e715a7b17092c72073d552924bf5f06056095d92fc0fec0f6ecb22d2e024991c6f0709c31ff708c7dc70ecad",
          "sha256": "5543f159ab80a31e3a46929e9b778e87182c09ed83de446edeb03f9923cac876",
          "sha1": "5bae6611843ff465a4db4d3f14ed7f03ff58f072",
          "md5": "d1265621ff1b07d1471cc2baa7909960"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 521721,
          "sha512": "11d1bca1582e9f544325d67c5e2bc0bf7a513b0b8846550ee6bc8183a0b13bc236512d92a8756e632d4204cad883b08ff04ea2e5b8d6e673cdd3de44613b98a9",
          "sha256": "6462650938e75c02be531b6bb415eb6b88c64e846673be278405ba26a0cb6546",
          "sha1": "456794e44a85e1124dda6253d6b95466868543e1",
          "md5": "2c4ea865ae0cc2eab32cd61d970b1218"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-batch-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 102673,
          "sha512": "e4e8f88f4237d4761bee1bdfb351a6fcb9775d4a1e804c5b7cb86c63f3757eaa0423e171348ad06e46fd437ba698af39cf389b4c4c4228511c1ec0d3f881d455",
          "sha256": "ce3a1f0a004359d1f105842975852da015e0ff28631db7f736f1c13069ca5ad9",
          "sha1": "34905fd8133a9528d9ee9247bbd8e2945165ccbc",
          "md5": "c8d8a325c9018aea351926c93c5cf656"
        }
      ]
    }
  ]
}
