{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-security-24.1.8-SNAPSHOT.3.jar",
          "size": 107184,
          "sha512": "86500e62c0499ed704a15a45a0b8b740f6548730381c1ffc31be77bb492b3959aace8c94e88c3be81a4dd7f3ea7afe2fdd9d21b12efbdd7904d62c51620263cd",
          "sha256": "799126fee8a4ac446321d6c2d737fa2f33f9b8afb31e7c089c5081bea259c964",
          "sha1": "8db288f1d3353066bb83200164411bcb9927fc96",
          "md5": "df6eac9b973e237804d44146924bca8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-security-24.1.8-SNAPSHOT.3.jar",
          "size": 107184,
          "sha512": "86500e62c0499ed704a15a45a0b8b740f6548730381c1ffc31be77bb492b3959aace8c94e88c3be81a4dd7f3ea7afe2fdd9d21b12efbdd7904d62c51620263cd",
          "sha256": "799126fee8a4ac446321d6c2d737fa2f33f9b8afb31e7c089c5081bea259c964",
          "sha1": "8db288f1d3353066bb83200164411bcb9927fc96",
          "md5": "df6eac9b973e237804d44146924bca8f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-security-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 413464,
          "sha512": "2857a87601dd17e351db7a39eafce98780121a7dcbb9421997dcaa32b05a753ecb0e66d16b843074944eebb1283327e77e55d8f4f8ee149fb85e9594c13bad6c",
          "sha256": "09bd9650b50cc885f0b5389e6d12fe6545d3e41c08222c2b20946039b9f7c24b",
          "sha1": "1048ba212614f3b6812e4c864df2b764af3b03a6",
          "md5": "97b4c9f9a75a7c1303ea902a44d610df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-security-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 65616,
          "sha512": "71e5d27fed8632182d92dc42ebf754f88a08dfa5fedab9c4945441fdb87294a06e9b288b74c0f7cae41cf5a6edbfc837a6bff55179720ec78c62524a96cf13b3",
          "sha256": "187200539549b47a0fbc7ce32a4aabe702d47f2574c23765da221a414f4581a5",
          "sha1": "18bb729c8e7563675c1862ac936005982ce28746",
          "md5": "447ebba0148a70aa0ee354856a6d431c"
        }
      ]
    }
  ]
}
