{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.13.jar",
          "size": 52700,
          "sha512": "7f5106c4e9fbc088a0285acc674bb0c2ad4bc23bef379cae6da858ab5e26c9571fdbfdb7ec4965600ac8b0968033bb4ce9e9bdd33823d3b94820b2f1d8574480",
          "sha256": "dbe7067302ec7d33202b9ceaef23de795de7c0c349e90f4f90846c1c020c13f0",
          "sha1": "e7c083417ac577106ef6b7b108b988b48a5676a8",
          "md5": "c69f4fef57d2cbf5432881a0ff3d09d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.13.jar",
          "size": 52700,
          "sha512": "7f5106c4e9fbc088a0285acc674bb0c2ad4bc23bef379cae6da858ab5e26c9571fdbfdb7ec4965600ac8b0968033bb4ce9e9bdd33823d3b94820b2f1d8574480",
          "sha256": "dbe7067302ec7d33202b9ceaef23de795de7c0c349e90f4f90846c1c020c13f0",
          "sha1": "e7c083417ac577106ef6b7b108b988b48a5676a8",
          "md5": "c69f4fef57d2cbf5432881a0ff3d09d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 196234,
          "sha512": "0c5f057d9de5113266451389cea30eca68a4c7aa0f7f318dd529b3713943c124d4ec49fc24ea8951304017fa7607e4a0d48afe4c2ca09d68fa91fa2c312d0481",
          "sha256": "ef4157b761df0339bb4f233f55fbfadec2699cc642363f82b740367225cfff5e",
          "sha1": "91f384824b4f02d35da1ade138733943efba1c72",
          "md5": "6df7554b1e32663b43181fd951421274"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 23397,
          "sha512": "1e88cfc926bcdd52592c3699a3bc998e2939e40889c9c41f5817f9b1e5e29659b09240bf13ae969027fcc848f9961bf50787bf3cfe7931125646f0e08a3f7826",
          "sha256": "1c3ce4440e101695ad4d4dadb59ecc3325100b51f3911741f31e61bb965d34bd",
          "sha1": "b56e1d95021d3c26cf5e9adcbab9c5b3bfff62cb",
          "md5": "6b9a0ecbc45c70ddbdafff8107257b06"
        }
      ]
    }
  ]
}
