{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8.jar",
          "url": "vectorx-web-servlet-24.1.8.jar",
          "size": 99527,
          "sha512": "4250504cdf1f9b436a522b67ca1c74f76cb11adf775c1381230706a224c509a7c3e2374cbe43156f7375c8c637927cd9c012ab82fcbbcd21b6e5845c5b8de4e1",
          "sha256": "e2cee40143c9c7db083d6c7229406b36057b1adfdfa04a4904b72755be0320e5",
          "sha1": "a8798086fdd2d2fefe51d4c19acd3d13117dae0c",
          "md5": "b6c55ecd646f95f3eb96c3b9f0e8b569"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8.jar",
          "url": "vectorx-web-servlet-24.1.8.jar",
          "size": 99527,
          "sha512": "4250504cdf1f9b436a522b67ca1c74f76cb11adf775c1381230706a224c509a7c3e2374cbe43156f7375c8c637927cd9c012ab82fcbbcd21b6e5845c5b8de4e1",
          "sha256": "e2cee40143c9c7db083d6c7229406b36057b1adfdfa04a4904b72755be0320e5",
          "sha1": "a8798086fdd2d2fefe51d4c19acd3d13117dae0c",
          "md5": "b6c55ecd646f95f3eb96c3b9f0e8b569"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.8-javadoc.jar",
          "size": 297998,
          "sha512": "96254c743943f6b336937a84821250435dcd19a1514f86e4f4d68ad6d3d75d3ea70bbc2d8f3b4973e82c7f2c07226fbb8213ae86635ed30633cb1fa0ea7a766e",
          "sha256": "e6f9c448e9fa08ae13b61f7d59a69aeaa9fb9fbfd60307604174605a4e788194",
          "sha1": "df2f5fea214ab8190400788c09990232d329faf7",
          "md5": "f8e166116028766631a1d944ec6ebbb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.8-sources.jar",
          "url": "vectorx-web-servlet-24.1.8-sources.jar",
          "size": 50938,
          "sha512": "bcbb6b4f76bc5e89ee0c5a3bf7aa6077ff1e18d440e44b9a52f0c79ff5321fffd1805ef3ec58d64039435d708855cf7283646877a6aa94f81e3bd6a44610acd6",
          "sha256": "ee0d53af7561c231e4be1fe890a9a0de8c7f050ce405ecdac3d0c88dbedabe27",
          "sha1": "4e779825120401d5458fffacd68899dff49fa39f",
          "md5": "2554fd1dc80945b7e2ef5ceb4eaf1517"
        }
      ]
    }
  ]
}
