{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-test",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.7.jar",
          "url": "vectorx-test-24.1.7.jar",
          "size": 31765,
          "sha512": "9dd3a0dd42ac2722903f85a08e73fa1a712b8fa9873403aedbee3ef1082524906b484eadce4ed8ba050ce082ef8a3b455d6dac091b18102eb5d522c7c048e502",
          "sha256": "71cbb39f3508c75d08162f0699e8c853fba7d8de1f13889a97f2ec5f874640ba",
          "sha1": "888d2debb5201622bc5829cf04dcf1c5feac0bd4",
          "md5": "b6f0add157207871c66a6592919ee64b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.7.jar",
          "url": "vectorx-test-24.1.7.jar",
          "size": 31765,
          "sha512": "9dd3a0dd42ac2722903f85a08e73fa1a712b8fa9873403aedbee3ef1082524906b484eadce4ed8ba050ce082ef8a3b455d6dac091b18102eb5d522c7c048e502",
          "sha256": "71cbb39f3508c75d08162f0699e8c853fba7d8de1f13889a97f2ec5f874640ba",
          "sha1": "888d2debb5201622bc5829cf04dcf1c5feac0bd4",
          "md5": "b6f0add157207871c66a6592919ee64b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.7-javadoc.jar",
          "url": "vectorx-test-24.1.7-javadoc.jar",
          "size": 125834,
          "sha512": "c27e11506c3c9bf994ae512f930f5c99ff4e31f0b9cf82dec4620c04ad16121f0ebf4afaa5e443ad4187926c5b19a7bc3036bc3f345881564c81d7d7aedfe844",
          "sha256": "dacd1dab8cc59b707ffe7d511dc5b782fa96214abe64f14cd7638ce9628fb1bb",
          "sha1": "a60e0f76fbd998bbb7a9d2daa5aea7ca1d82f3f0",
          "md5": "fe668245a273fda6472610b41100dd8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.7-sources.jar",
          "url": "vectorx-test-24.1.7-sources.jar",
          "size": 11947,
          "sha512": "b7eccb10c378cfc67ebe48ff96c2b20d5c6ed05bd32738cee30f48ed3cd094b1b50e9e8db9c843a8dec55ca456f7e246a6ce347557634c32db5fd4a47de85551",
          "sha256": "ec2cec62ea9ccb7539d189c8148e58e4e39d95a64c01f1adbcac8a83eaf313ff",
          "sha1": "ce913aa0793f6425139980632caf36bf58caba41",
          "md5": "c2d253ece435613181c711c122a13f80"
        }
      ]
    }
  ]
}
