{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.3.jar",
          "size": 924230,
          "sha512": "cc77bce2af982089d79f578874dbb23f024b67d36614cc8cfc8f1bbfbf1f6fb9c68e1b268283da47cfe887fdf11ec857f3630e7d9622d982c570bc97468fbfa4",
          "sha256": "21a7cd1af45063c258a76af4f887953825060d3ee8ac41962d383f48e03025d7",
          "sha1": "458f84f9813d6e58e6bac09501879c9291a040da",
          "md5": "9710e8e3adbf3c0d697b3a3e55deff1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.3.jar",
          "size": 924230,
          "sha512": "cc77bce2af982089d79f578874dbb23f024b67d36614cc8cfc8f1bbfbf1f6fb9c68e1b268283da47cfe887fdf11ec857f3630e7d9622d982c570bc97468fbfa4",
          "sha256": "21a7cd1af45063c258a76af4f887953825060d3ee8ac41962d383f48e03025d7",
          "sha1": "458f84f9813d6e58e6bac09501879c9291a040da",
          "md5": "9710e8e3adbf3c0d697b3a3e55deff1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.3-javadoc.jar",
          "size": 1338273,
          "sha512": "cebfc5f06957cade2ac541b7945118469704602f410eedabda15cc4b7f22353baaed8398ac9892151bf6965334b6d59d8152797f3d6e9bd0c61f00cc62bda260",
          "sha256": "e85df91792c01d37662b4f0912c5a3ee04a89b632a2b2cbdda3cf0fff75104cf",
          "sha1": "a4280860bfefd8ca7ca3de39f13c34808ebc3fbc",
          "md5": "e7c30d7e6858d1195ab252e0c57d6623"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.3-sources.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.3-sources.jar",
          "size": 329617,
          "sha512": "f10a65f0523552defa6e5c850317c2b4680181178f4a574e9e17c30ae9e1ce871df61be99d9f4f5acc024cd5bd76735ce1fc724278b787013dcd529c2510f768",
          "sha256": "bd807e549fa059e199aaf0ed0f40962e1d648e953b5b237e7e54bda32b15fb48",
          "sha1": "1cff416f115b9d6148defbb21bf6b55f0563ecd7",
          "md5": "b56a0f74940d50232f88ec7c207d4c2b"
        }
      ]
    }
  ]
}
