{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.4.jar",
          "url": "vectorx-batch-worker-24.1.4.jar",
          "size": 51881,
          "sha512": "deefe6ed407ddc68d62423d8ce53ed3bd63baee94c0de6b79a9f8db816eab1cefb6ce400431a238e6d237440a2700ff7e7f15eb4a52fc3cb56cab54b0c738aa5",
          "sha256": "114234eb7aee4a772750b31657f25d9ffe41144f84db15b2164048e88d078ba6",
          "sha1": "63f17fe94f7e5942ba558b7a68a5d7da0313e0c2",
          "md5": "7b3b4164bcb86def9ae96a9f8c4b4fb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.4.jar",
          "url": "vectorx-batch-worker-24.1.4.jar",
          "size": 51881,
          "sha512": "deefe6ed407ddc68d62423d8ce53ed3bd63baee94c0de6b79a9f8db816eab1cefb6ce400431a238e6d237440a2700ff7e7f15eb4a52fc3cb56cab54b0c738aa5",
          "sha256": "114234eb7aee4a772750b31657f25d9ffe41144f84db15b2164048e88d078ba6",
          "sha1": "63f17fe94f7e5942ba558b7a68a5d7da0313e0c2",
          "md5": "7b3b4164bcb86def9ae96a9f8c4b4fb9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.4-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.4-javadoc.jar",
          "size": 180005,
          "sha512": "fbc32762201ec4fc7b99168357ed01fb8935a154e33d8b7255611b2bcf34ab16afd8cd66de97b80e5ea62da1372907f3aa9de468d69afe46a2449a24e45fc260",
          "sha256": "0d986b45986567184d1fb8cf8b6ca72758e733558ce20092ff2502002949a180",
          "sha1": "a13bf449bddb8dc5f5f7fcf33c3deb9cdc98540d",
          "md5": "0dde81273afb252a50cc4195fdac2d1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.4-sources.jar",
          "url": "vectorx-batch-worker-24.1.4-sources.jar",
          "size": 23642,
          "sha512": "3088751896adf5ea3483a38a7b2dd1f837aabb8e033c53ca29edad387815ca96b504471828aba6cb9d605c7dfcce94c95b42b886a29a79d03507203e0f8c0166",
          "sha256": "a731f1cba45ec08ac7748fd6842959d8d08888be00adae127649089c8dc6800d",
          "sha1": "e864e33c9aecc232889a4c1e6c78600c52c17472",
          "md5": "7be6cc3f5863f30324bcc5e5866145ec"
        }
      ]
    }
  ]
}
