{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.4.jar",
          "url": "vectorx-batch-worker-24.1.4.jar",
          "size": 51881,
          "sha512": "85223ffe57b173ad3deda73099820eaaa6cb151b67bfcf820f2b8207bf82fe11e75cbcba10fbe382811340969c6d840d60b3fbe90c700f11358e181c02350f62",
          "sha256": "b9df069880824e7a70dd733bb525d58b2c29a0edae2034bbe14a918449678f8c",
          "sha1": "f35c03cdeab780b43ddb814e5c9b061c4202318a",
          "md5": "bc7f773d7177069eece91b00459328e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.4.jar",
          "url": "vectorx-batch-worker-24.1.4.jar",
          "size": 51881,
          "sha512": "85223ffe57b173ad3deda73099820eaaa6cb151b67bfcf820f2b8207bf82fe11e75cbcba10fbe382811340969c6d840d60b3fbe90c700f11358e181c02350f62",
          "sha256": "b9df069880824e7a70dd733bb525d58b2c29a0edae2034bbe14a918449678f8c",
          "sha1": "f35c03cdeab780b43ddb814e5c9b061c4202318a",
          "md5": "bc7f773d7177069eece91b00459328e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.4-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.4-javadoc.jar",
          "size": 180005,
          "sha512": "bc3ff3fe960718295aad85876d7097e5e7628417ea0b25d60b3b543303fed71a3c6a98f1732eef2e71693d328beca2b7c99e2a5acd695300414de74b3bd40648",
          "sha256": "3b30b450c201b6e01800d32ab6a3e81af09cf020d127bc0872a09cb78fc38cfb",
          "sha1": "d0b4ae7e75b6511500ba4391e9edaa500ea001e9",
          "md5": "69ef2058b073921f34a4121cee44fe5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.4-sources.jar",
          "url": "vectorx-batch-worker-24.1.4-sources.jar",
          "size": 23642,
          "sha512": "2b711d4ecfb96ddcf2d7f7dcf468ce85831717570a6f94fca2f067aa2955c8944447ba9dba9e1f3aec2357dc866f7f3862d8698efe83f2fb49bee8748e97006e",
          "sha256": "ecf4e50c17eba8109fa08ca37027817a2f52a2d0a63e15a88c944735f3a2a7be",
          "sha1": "03106a5e5ca7838ba60ca355a3f3b95a011590f8",
          "md5": "a9577e17d87a3715e5a602f56de7f4fa"
        }
      ]
    }
  ]
}
