{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-net-24.1.8-SNAPSHOT.2.jar",
          "size": 29738,
          "sha512": "60df458005d532a9c048875246d22cd5db17b3a2ad2db631ee9b18910ad42beac90dbdacefdd42e52f2e02ed9a8a2a2a41e6eddc07e5c4e9e25bdf88e340692e",
          "sha256": "8b03adcddc770ea24a543e899f5f1fa02c5486e079133979ae22f396ef1edfa0",
          "sha1": "6f12b8e49253dc45229ced1e0d294c8293a1005e",
          "md5": "901dba35d53588bbc63a8f5ef2be7813"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-net-24.1.8-SNAPSHOT.2.jar",
          "size": 29738,
          "sha512": "60df458005d532a9c048875246d22cd5db17b3a2ad2db631ee9b18910ad42beac90dbdacefdd42e52f2e02ed9a8a2a2a41e6eddc07e5c4e9e25bdf88e340692e",
          "sha256": "8b03adcddc770ea24a543e899f5f1fa02c5486e079133979ae22f396ef1edfa0",
          "sha1": "6f12b8e49253dc45229ced1e0d294c8293a1005e",
          "md5": "901dba35d53588bbc63a8f5ef2be7813"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-net-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 128679,
          "sha512": "8e3e0a741830231181d806f0e6a5b6bc6b978879448b876d064be00f52bc3b77d8506e301c66cc47ee19ba69b4f9c09a5d4354157906f6222d241e260bfb6861",
          "sha256": "ed1fad05bb10102ffea32897160b6237ef2a218ddd6f866a433a5ce150155d5f",
          "sha1": "ef3a58ee9702e1ba95691622a6bade306bbd12c5",
          "md5": "c21684957002c6d7a1f9a79d4cd12786"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-net-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 10137,
          "sha512": "2d88ee83bf18fd22e5096f3905763623b56d755aec7f57a4df2a8edf2ab38f3162b968e6b0e5e6aeb41e6eba254e6c9cb4eff6760f72755ddb51e436d7238954",
          "sha256": "34cfd3db2ca50bda324ac6667138872f28cf27135118a6750a882b561aef0477",
          "sha1": "31d2a22ad14365cdecac334290aad2444cf25372",
          "md5": "a39e5e1e95ca89685539b7106e738786"
        }
      ]
    }
  ]
}
