{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe-xplatform",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.5.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.5.jar",
          "size": 3327,
          "sha512": "1b39df7997204616081e0a311c102070f750eff3deb4eac64131026c8d3c527e020a7d175287ed31c93bc45458c883968473bd7ca9ef76619f746d4a9ff68288",
          "sha256": "646a2c0889b82af691cb21269648242fb2d8c24ca4bb44c06cc94d9e484eb48c",
          "sha1": "9dc1d7cb2aa61a430557d5dc008664cd2cf63359",
          "md5": "a2dbdb470e71ca4941e70800c17c16e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.5.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.5.jar",
          "size": 3327,
          "sha512": "1b39df7997204616081e0a311c102070f750eff3deb4eac64131026c8d3c527e020a7d175287ed31c93bc45458c883968473bd7ca9ef76619f746d4a9ff68288",
          "sha256": "646a2c0889b82af691cb21269648242fb2d8c24ca4bb44c06cc94d9e484eb48c",
          "sha1": "9dc1d7cb2aa61a430557d5dc008664cd2cf63359",
          "md5": "a2dbdb470e71ca4941e70800c17c16e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.5-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.5-javadoc.jar",
          "size": 70857,
          "sha512": "562cd7a50eeb014797dca9cdb03915a78ccbf8a5004496c34f3bcea6d5cd7605ad5ba88e87d6e3404f6e3e461e4a1bed6c4c6dd7e24dd98b2a0ab440606eb47e",
          "sha256": "9b204207009d73d702a81ded88793371302bc512db2594ac31879a8ff9d5ad70",
          "sha1": "97367a8de3c69c9067baaa9baa9daba440c9c109",
          "md5": "304dbd18f205086b59428bf53a734325"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-xplatform-24.1.5-sources.jar",
          "url": "vectorx-web-servlet-tobe-xplatform-24.1.5-sources.jar",
          "size": 1674,
          "sha512": "6b8967480fde1d51c7a5d3ee92092724d239530748d801177dfe24bdc903dd617df02fe21c554c9fbd3321d6fb236c905aecb4854e9142be0976d0ec1ee52d74",
          "sha256": "bb88b29211f092e6369061b485e6c5464b025196ba39a614e5f21d75fd087ee8",
          "sha1": "a83b6cb40feaeed2b8267b0575a557f696c5f2c1",
          "md5": "63a9e603b0153ca1ad01067f006043c1"
        }
      ]
    }
  ]
}
