{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-view",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-web-servlet-view-24.1.8-SNAPSHOT.5.jar",
          "size": 21251,
          "sha512": "6db9546743a20456922c2972c2c7d42aa2f0deb3e8a0f55df220fec66312f0af686609f698b90e3f35b0ba3fff1bd292618be662799396e0bc05d867bbc80f8a",
          "sha256": "f835e3e2ea17878ebff0afa7360d7bf056e053db9d159ef3078b594c9380670f",
          "sha1": "ef046bd7ad5ab1ccfd3ae64f302ab886aa5dd50e",
          "md5": "12ee90f6881e1b645038426a70323a1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-web-servlet-view-24.1.8-SNAPSHOT.5.jar",
          "size": 21251,
          "sha512": "6db9546743a20456922c2972c2c7d42aa2f0deb3e8a0f55df220fec66312f0af686609f698b90e3f35b0ba3fff1bd292618be662799396e0bc05d867bbc80f8a",
          "sha256": "f835e3e2ea17878ebff0afa7360d7bf056e053db9d159ef3078b594c9380670f",
          "sha1": "ef046bd7ad5ab1ccfd3ae64f302ab886aa5dd50e",
          "md5": "12ee90f6881e1b645038426a70323a1e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-web-servlet-view-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 135047,
          "sha512": "bd4134672504cc40eb4acb364821112e438627eeb3ea3527703fa576098047c3cfb99b76763aca6e0f45fb683bdf1aeb5c378f1c307a3a3ae366ff8fa2f727f4",
          "sha256": "ac37275043e62a2e4f959e68936b1db18b1a175ef7f63a67d2c4584a6cfe3755",
          "sha1": "ee26b07fc818f4dc62c2c4b05491fd829bad3354",
          "md5": "21879b96d7f5b9474541797d6b884cfe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-view-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-web-servlet-view-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 11471,
          "sha512": "be46c7df7195fcd28174bcdb82e15e6e3bfdb8b7862becd6c50ce3309d19ab92baf9d87810bdb7ed2f3456db52600839a2b9c57ae5d8d3927bf00be604213a1c",
          "sha256": "8f7e4273009ab055b5f927e23a1c4ff4448ea755a0cdc9ac8526dd400ad2716e",
          "sha1": "1c06a583605f9a04cc4c25a29ce2a78d877fa55a",
          "md5": "a2d5c0a46f2bca81d63323d3c0598a43"
        }
      ]
    }
  ]
}
