{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jdbc",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.bgee.log4jdbc-log4j2",
          "module": "log4jdbc-log4j2-jdbc4.1",
          "version": {
            "requires": "1.16"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "com.itextpdf",
          "module": "html2pdf",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.jodd",
          "module": "jodd-util",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-data-24.1.8-SNAPSHOT.5.jar",
          "size": 490928,
          "sha512": "016de752c2bf8dad899f17738e816c890e73a8b6d3e44d5c2634ffd7d7f3ecb9d0f7f4c80e7ea4de8183c4c46c94465dcdd2ad9c8d8bc25813f7e36bea2a613b",
          "sha256": "5e08bdfc5d631f259b6350b98e822daa8d5f53c6d39b3aaea1c14f740201ca72",
          "sha1": "5de80e67c594bfb0f70d620487bf8d3c56da025a",
          "md5": "07846b703b6e6222857f697aaa11b9b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jdbc",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-thymeleaf",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.bgee.log4jdbc-log4j2",
          "module": "log4jdbc-log4j2-jdbc4.1",
          "version": {
            "requires": "1.16"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.itextpdf",
          "module": "itext7-core",
          "version": {
            "requires": "7.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "itext7-core",
              "type": "pom",
              "extension": "pom"
            }
          }
        },
        {
          "group": "com.itextpdf",
          "module": "html2pdf",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.jodd",
          "module": "jodd-util",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-data-24.1.8-SNAPSHOT.5.jar",
          "size": 490928,
          "sha512": "016de752c2bf8dad899f17738e816c890e73a8b6d3e44d5c2634ffd7d7f3ecb9d0f7f4c80e7ea4de8183c4c46c94465dcdd2ad9c8d8bc25813f7e36bea2a613b",
          "sha256": "5e08bdfc5d631f259b6350b98e822daa8d5f53c6d39b3aaea1c14f740201ca72",
          "sha1": "5de80e67c594bfb0f70d620487bf8d3c56da025a",
          "md5": "07846b703b6e6222857f697aaa11b9b2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-data-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 1079483,
          "sha512": "6b90d879d36ca289368425f2c59fb0590baacd28aba423ffc638d25fe004bf125f1d560e31ef69a36074d76a45eb619bfba29eccbc44801f823eb2741f2beb24",
          "sha256": "f7dd475eeb0ce7ac02e35e2660f626bfe4f66b972db3e03dbec2585e71bcd79e",
          "sha1": "77cb028e7b8ef41e7f7d6ffe56137a1e63e86afc",
          "md5": "6293e9072200244424fe89a8dbe323c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-data-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 212963,
          "sha512": "430ebd72000a0b10c1dda535f21f29839f4dcfe4c9205df2dad97b7f8c5a37dca51e1fd8d719f1d9d54988dad38b9595e598422c23fb25f7d708772962af0bcb",
          "sha256": "31ab8c327e1d227bef641d0a94bf88879d8ca98b956e18376aec9dc9bb82ace8",
          "sha1": "3fd03e61422a0193f4f5753940ee591cd4af1ebe",
          "md5": "46490235655edd07d8b1c4ec6df132d1"
        }
      ]
    }
  ]
}
