{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-manager",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.4.jar",
          "url": "vectorx-batch-manager-24.1.4.jar",
          "size": 45153,
          "sha512": "74b527b577b8c74ccbf7d7e88443aa2bce3c825e0b4e138b5c7fe309ded49d734783037e87f66d96fae51b5b5a5efeceffcc20704b1acdce56770ed467ddc8bf",
          "sha256": "827de4291cde9daee86424b542b5e5b2e9a919fd6db16228e88315cc002c78f2",
          "sha1": "8abec7c02f4917cd0a098e4f34ae6ef613593e10",
          "md5": "20798ead50709ee4c798dcaef302da88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.4.jar",
          "url": "vectorx-batch-manager-24.1.4.jar",
          "size": 45153,
          "sha512": "74b527b577b8c74ccbf7d7e88443aa2bce3c825e0b4e138b5c7fe309ded49d734783037e87f66d96fae51b5b5a5efeceffcc20704b1acdce56770ed467ddc8bf",
          "sha256": "827de4291cde9daee86424b542b5e5b2e9a919fd6db16228e88315cc002c78f2",
          "sha1": "8abec7c02f4917cd0a098e4f34ae6ef613593e10",
          "md5": "20798ead50709ee4c798dcaef302da88"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.4-javadoc.jar",
          "url": "vectorx-batch-manager-24.1.4-javadoc.jar",
          "size": 139217,
          "sha512": "6f0ed0e1b9390d3cdcbe78b843f9a951bcec3f60d7883bcf79335cb91d41fb045beb8538525752d07b333625ccbee051a44665b3859e074d679b8859f28c4816",
          "sha256": "06bbd4eb7bc9822ff01d6b21fefc66b3356280abd89cf58c3126cc13873de41c",
          "sha1": "5e63e881595a31fb8d3409550913f34a803aa75a",
          "md5": "a364f81644248904670217420840d7f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.4-sources.jar",
          "url": "vectorx-batch-manager-24.1.4-sources.jar",
          "size": 20387,
          "sha512": "b9d6ef218a1e813424f3ebb91b0bc5ab946433af8ed5678c673852767ef25917e51dfba59b916da794d2da2e17335fcbad27a3698ba3adcddfbc494b3111a73f",
          "sha256": "d76cc65c51ebf23a7135f1d54062fff8f9506c5394d4647693f1b494210f6efe",
          "sha1": "11f4bea161e9d1239c2ad38668d38134cf4fed2b",
          "md5": "4fe33358965b5b80fbda4b6116832065"
        }
      ]
    }
  ]
}
