{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.4.jar",
          "size": 110172,
          "sha512": "6646d78acfeedb4bbb2b246dde739840d3cab5d0eee72895391eb516c1306198631530da09698794c409e17701ec40d65685590f634730fe7b3c7c2ac9cb9d45",
          "sha256": "6604fc2f40efde7244a43b5f29529021c89a390cf819ddf96e0563fc20ac99da",
          "sha1": "ef8ccaf6a8462a1753379b66a4d9c51d354a7758",
          "md5": "3a1b10f0e70f23992eac15f1e0587273"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.4.jar",
          "size": 110172,
          "sha512": "6646d78acfeedb4bbb2b246dde739840d3cab5d0eee72895391eb516c1306198631530da09698794c409e17701ec40d65685590f634730fe7b3c7c2ac9cb9d45",
          "sha256": "6604fc2f40efde7244a43b5f29529021c89a390cf819ddf96e0563fc20ac99da",
          "sha1": "ef8ccaf6a8462a1753379b66a4d9c51d354a7758",
          "md5": "3a1b10f0e70f23992eac15f1e0587273"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 309289,
          "sha512": "f9be0628fa7471eea9bad2d742dccf35d52858a1290448f5de1b2b52d41abf14cef61fbecbd1122bd3fcf7af13a127cc8554ed18f0260ffe5d3c4cc55d9f5dab",
          "sha256": "3d12585c1e192e551701ec350c94169c83ae311f9e70f33690f2f193002977cc",
          "sha1": "0b3ee8ef8cf2737da95eaf962ef269ef8f98aec2",
          "md5": "2a3db8ea521de9bf25037f775d51f61c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-data-mybatis-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 70193,
          "sha512": "f95188c29cb709cef0b8a3497a67b56584f8df514d7318f25e260bf51ed80b10db3f3af737dcfd33d9b6e6398376a976ab7a4db30f8fe4604a693ea03505be16",
          "sha256": "0a3ffa05d5581adb63153622926a97d58b1166466f39d14cf6011b467fbd5087",
          "sha1": "3ba13b9060f6997afe5ada4a90edeaf51db7ad2e",
          "md5": "7dfa4828f88ecff771fc83aedd8b659b"
        }
      ]
    }
  ]
}
