{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.1.jar",
          "size": 926807,
          "sha512": "68218d6f5d1d70839e79a41aa505bec1d182a4a6320e886b6dbfaf190d8bcfb35caea359277a7792cf1c2cf21160065cea46573409c69b96540747f6aa1e9d48",
          "sha256": "dda176ec47ed7d49d72f669edff87e26993d6232c095d6e3153ce116e0be3295",
          "sha1": "e35e9119a2572f02b097291933c1590a2895a6e1",
          "md5": "019c9cb8b11a303e8e1cf61cd9f99970"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.1.jar",
          "size": 926807,
          "sha512": "68218d6f5d1d70839e79a41aa505bec1d182a4a6320e886b6dbfaf190d8bcfb35caea359277a7792cf1c2cf21160065cea46573409c69b96540747f6aa1e9d48",
          "sha256": "dda176ec47ed7d49d72f669edff87e26993d6232c095d6e3153ce116e0be3295",
          "sha1": "e35e9119a2572f02b097291933c1590a2895a6e1",
          "md5": "019c9cb8b11a303e8e1cf61cd9f99970"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 1351035,
          "sha512": "616c79e7882133c5baa2ae24a5852fe912c0b362fc6e00b22b4f82af66dc53337c92dcf52db7739906be29ff154bea628f9fe33cc98b2ba2d1261031518a1ebb",
          "sha256": "2fb7e140bf6d605bf396d9ab1264ddfa15d5ea9a4f22b485ed61661078c18bbc",
          "sha1": "fc2fd9fc9b29878b785f7d2e1d4be839cd0c72c3",
          "md5": "d769c9e5acab6388dd8481b894c0050f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 331578,
          "sha512": "f7c55b68a1a83b7254ffa580dd04ccd1c013ca097b3608a564e6256dbfb748108bc9ac0160752cb94280e640317033a42af617fb88fce772c0fdc88f5344d884",
          "sha256": "a7f6a9b2a579fb9409c1d67b08b1cea48ddaaa41cd45cc3862f4013eb155f567",
          "sha1": "b695107dc932bffdd388c683805db0f5bc366ee9",
          "md5": "4436bbb7a641184f788e50bef609c9b6"
        }
      ]
    }
  ]
}
