{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.2.jar",
          "size": 924186,
          "sha512": "726198ee82657c41157b5ca6e2b657b34c1c68fa5d3dcbc5969ea5ca99d2bc138d56373d3593631cebcd3f38dc30d6a731ea2e63ad2fe7d411af8abb3bb9533c",
          "sha256": "5e214669eb10ef355d702e9a6fa129815cb6e8bd3de683dfa8f65ee76af0d1b1",
          "sha1": "5a56bfef7533a275442f84fe1bbbe29740b8f93e",
          "md5": "0a083f99a49fa5c62c2fb20cb7cbf417"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.2.jar",
          "size": 924186,
          "sha512": "726198ee82657c41157b5ca6e2b657b34c1c68fa5d3dcbc5969ea5ca99d2bc138d56373d3593631cebcd3f38dc30d6a731ea2e63ad2fe7d411af8abb3bb9533c",
          "sha256": "5e214669eb10ef355d702e9a6fa129815cb6e8bd3de683dfa8f65ee76af0d1b1",
          "sha1": "5a56bfef7533a275442f84fe1bbbe29740b8f93e",
          "md5": "0a083f99a49fa5c62c2fb20cb7cbf417"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 1338504,
          "sha512": "8321222ef6c670c245fdbb8c0c46bc62014b497d8073c1cb4d4494a571dde5e4b3b2a3993c190c4e64f824152ad06ea6a7dcba151ac43830d57f2fe35bbcc4df",
          "sha256": "9458c70381e9d9fb47ffcec945c781d8714c4b5353622d8ec9eb652f1f2a1ce2",
          "sha1": "01e1aadd25a567f39ff15842674e0e86434ee160",
          "md5": "f5fbae6ed393632cc3fdb84e8d98c5c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-management-core-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 329573,
          "sha512": "9f518f89f5e816300489e5b6a903e703b61f87e289d06e883f5c51ecf502887a3930c7a6a70516dafc9806dd56aed36bfe74539ca9825e41104f303faf15d386",
          "sha256": "91a1f1c385c046f9333602bb456fb286133f93b3f370240e9649a0cd11bff0af",
          "sha1": "e394f50c0fe7ac8c48113f6ee0656d6bd01dd5f2",
          "md5": "f67da6b020b320b52ebe6918f19d60ff"
        }
      ]
    }
  ]
}
