{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.6.jar",
          "url": "vectorx-security-24.1.6.jar",
          "size": 107161,
          "sha512": "ce150fcb0494a05be2b9c61c2096075a914551957d7a0e4f27b0fc42c94aaf17986ac6d6b11f01e2159592b3da04cbb7c6fc3d897ebcccf9f0949d917277a153",
          "sha256": "4e26e50436a899efa2c1d0206ca0c08d93e56b5e86e51dedc287d34c2c3c791e",
          "sha1": "94a4800ade14107e016b1f84783af004607327d8",
          "md5": "51fbfa33e40c56de034b246a04feaa32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.6.jar",
          "url": "vectorx-security-24.1.6.jar",
          "size": 107161,
          "sha512": "ce150fcb0494a05be2b9c61c2096075a914551957d7a0e4f27b0fc42c94aaf17986ac6d6b11f01e2159592b3da04cbb7c6fc3d897ebcccf9f0949d917277a153",
          "sha256": "4e26e50436a899efa2c1d0206ca0c08d93e56b5e86e51dedc287d34c2c3c791e",
          "sha1": "94a4800ade14107e016b1f84783af004607327d8",
          "md5": "51fbfa33e40c56de034b246a04feaa32"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.6-javadoc.jar",
          "url": "vectorx-security-24.1.6-javadoc.jar",
          "size": 412015,
          "sha512": "0201b8b62e640b57297e9224dc9b7d0270c2297841cc7a992ab131dadc00b5631bde32fc517f25742a501adb8bab19d498282f42b29bcd7a517b0c34ec78f396",
          "sha256": "1771d99638ae9499f7036aa8152ba3aaf34e538303202400eaeb62e38c1d6400",
          "sha1": "e864cfea20a98c6c8d807926bae93a441e59021b",
          "md5": "e3b00a93021d9dd593d3ebba1b113168"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.6-sources.jar",
          "url": "vectorx-security-24.1.6-sources.jar",
          "size": 65616,
          "sha512": "bdf252edffb796eb1c7dbb2b25f56b9d4893ab150d93819cc3105d024541cc57aae1d86d127392217ac4cd6d7fe83a31cf0d45520ef486bbf92f9ac4cf132529",
          "sha256": "5f4a7e3d4d737f0c04756eefbaa3580d189df3d73b624e7ecc323bf559f47477",
          "sha1": "bb79b36590c46bb000d633d591f65895a2093cd4",
          "md5": "47eb947bc801f4c11bb6dce2b50bfffa"
        }
      ]
    }
  ]
}
