{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8.jar",
          "url": "vectorx-data-mybatis-24.1.8.jar",
          "size": 110157,
          "sha512": "c28a8d62b03cbc674681ee5d9ac5a0b5ded7db17d81decb1293d1e0d4e538f447cad732fe2aa1739906389965c260df4245757f0f3a31cc957ae7d768f74ab92",
          "sha256": "32163bd71b649159d027060268b80c572e9f9b4395f17c96f2620783aea10fcd",
          "sha1": "9b25b93eadfb7e0b84b7124c8b96c64d23f3a8a4",
          "md5": "095e58e62e2d696f7e66ad7a551c1d25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.9"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8.jar",
          "url": "vectorx-data-mybatis-24.1.8.jar",
          "size": 110157,
          "sha512": "c28a8d62b03cbc674681ee5d9ac5a0b5ded7db17d81decb1293d1e0d4e538f447cad732fe2aa1739906389965c260df4245757f0f3a31cc957ae7d768f74ab92",
          "sha256": "32163bd71b649159d027060268b80c572e9f9b4395f17c96f2620783aea10fcd",
          "sha1": "9b25b93eadfb7e0b84b7124c8b96c64d23f3a8a4",
          "md5": "095e58e62e2d696f7e66ad7a551c1d25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.8-javadoc.jar",
          "size": 305403,
          "sha512": "22824fddfab4e9516008e8c082ad9f1a7daffcda0277602322f0c4c600803ca5c34fab5e032673162c2e214c6bed8de68c3586dabae99c7d8ce3f79806db0635",
          "sha256": "2a8df0125ec4158e7c85de063ddb385ed47094843bf57b769b8d514569291995",
          "sha1": "8e8092d476a8d25a4c4b4c0ffc403c86aa24b4f8",
          "md5": "f901358c71babf2c6af0380f9e5dd82f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.8-sources.jar",
          "url": "vectorx-data-mybatis-24.1.8-sources.jar",
          "size": 70735,
          "sha512": "9e316acb4e4f9390339cf4c7326f55a1b98235e37aea82f6b983ae450bbc6d905947ce6c9f05db361eefa2c501ae4c6933f161647bf0b87101d70d4597d05805",
          "sha256": "29ed2b79f16498240847f915f72f8d4beab20e884ad8a7062a5254821e644ebf",
          "sha1": "fbef2c1a4420819a4b67c5c40ba110f182b3cfc6",
          "md5": "5260c458fa72831c6f813227b2ad4865"
        }
      ]
    }
  ]
}
