{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.2"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.2.jar",
          "url": "vectorx-cloud-aws-24.1.2.jar",
          "size": 2752,
          "sha512": "968b66a9dcdf061caecdfdaae285e301dbaa19f1fa52138dc14a36177fed160c4eabcb650389565f4043df25e276548736f8555c246dcddba16624446450698d",
          "sha256": "9bcf959fc009b7b5bbb2bae2b80cf3fb4efddfc147c6e113f02cf556fe68c062",
          "sha1": "2fb8ff24affad4eda1c46c21e7aa35ef6496c800",
          "md5": "3e417fcafcb14c8a3a83909683484251"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.2"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.2.jar",
          "url": "vectorx-cloud-aws-24.1.2.jar",
          "size": 2752,
          "sha512": "968b66a9dcdf061caecdfdaae285e301dbaa19f1fa52138dc14a36177fed160c4eabcb650389565f4043df25e276548736f8555c246dcddba16624446450698d",
          "sha256": "9bcf959fc009b7b5bbb2bae2b80cf3fb4efddfc147c6e113f02cf556fe68c062",
          "sha1": "2fb8ff24affad4eda1c46c21e7aa35ef6496c800",
          "md5": "3e417fcafcb14c8a3a83909683484251"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.2-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.2-javadoc.jar",
          "size": 70363,
          "sha512": "dec5e2123c07e502ccdaa8f438a534cb0ec27dc4a71a118f3724434a6a82af5991665c889d8b406e61ee17d09e4869a8685f66bd693f1137dd54e96c9d945c46",
          "sha256": "da54ad18e7aa2518b5640821451a36e359ee1a0b364d41cecf943a8b59f77323",
          "sha1": "c8786912254f3198df64878eb0243421f93cddbb",
          "md5": "62ea99a65a7691d2c41a573bbcbbe742"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.2-sources.jar",
          "url": "vectorx-cloud-aws-24.1.2-sources.jar",
          "size": 1228,
          "sha512": "ed839e15d3488fa23de343e59aeac2143f93ac4de3d587389e22f21575d4750a66753f66edc706b0d64350d985e70730b744c5b12ebc39dbb222e68ae56efe72",
          "sha256": "c4da79c358d478bedf4fbda646c171f4ca395ec8bf8bf6e5303d603c886f2ab7",
          "sha1": "66db094d070de14fb8535a42cb73551bf0d5f8b6",
          "md5": "cc5eaa9e7362cc49f07720bc3af569ef"
        }
      ]
    }
  ]
}
