{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.6.jar",
          "url": "vectorx-web-servlet-24.1.6.jar",
          "size": 99542,
          "sha512": "568c46db833e15266b30fdfac9b1a8be3093058e18357be85f9b886324da7c9737a3ddfec29d7b329fb61f2413a1b450a092e5f10b6a033c70ba5e2c67c655e0",
          "sha256": "0226f8ad630c98153543da1ec8373b9eddcf158946660236872e5c6eae92f2f1",
          "sha1": "38f6eb437a249f9c118982b09137aa3af8dcc42b",
          "md5": "c63d9372cf14aa8eac083a54faf881d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.6.jar",
          "url": "vectorx-web-servlet-24.1.6.jar",
          "size": 99542,
          "sha512": "568c46db833e15266b30fdfac9b1a8be3093058e18357be85f9b886324da7c9737a3ddfec29d7b329fb61f2413a1b450a092e5f10b6a033c70ba5e2c67c655e0",
          "sha256": "0226f8ad630c98153543da1ec8373b9eddcf158946660236872e5c6eae92f2f1",
          "sha1": "38f6eb437a249f9c118982b09137aa3af8dcc42b",
          "md5": "c63d9372cf14aa8eac083a54faf881d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.6-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.6-javadoc.jar",
          "size": 297959,
          "sha512": "92831064e77997bf07e9bb8dd055fb48f4aa0d6e4fc0ef9d49379fadf37899258aee9f162bdad2f48c10bcb53a4031de45991ad6df260bc861c8e11dd8b4e24a",
          "sha256": "536b022f9cece40dde9ec25639093ac1c1ed9a683915f00f0eed3595eb73f7c8",
          "sha1": "305973908e1bc63e533fe475fa63acbeab1dc9df",
          "md5": "8c1d8f9c5b1bc718015e1a7f9bfb6401"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.6-sources.jar",
          "url": "vectorx-web-servlet-24.1.6-sources.jar",
          "size": 50887,
          "sha512": "70e4130bdd1b7f191af3993335b55e24afe1df8f3401bf59de7b8194a9ecf4c5f67bdb64f31905907356c2fbce9627fce3bd7591a3f60ee82cffda2094c93681",
          "sha256": "ec063690de0242b93f04e700d0a1acde851039e70c31b620da1a2c25e27639c8",
          "sha1": "850550795c9cbd4e8cd5a9481805542fbf56d450",
          "md5": "1735dbe8e9aad32e7154c9769b3875e6"
        }
      ]
    }
  ]
}
