{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-batch-worker-24.1.8-SNAPSHOT.5.jar",
          "size": 51903,
          "sha512": "b9d6c574bbf927bfa272d0916a7f3489774b80b25b961d9355905e1e89d4e3d66c0857ed1224acd1cc29a99bd450d161c8115bfd2269c45ad12a421c705e8e28",
          "sha256": "7a868e30da3e827e9dd176b34108e2182521dc89351751c35973d3b11ea35449",
          "sha1": "fea5641e0f2727fd3ef8d08c7f2e6b5d53f3b729",
          "md5": "f588b666b87a68d40f3e9ad0ce6833e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-batch-worker-24.1.8-SNAPSHOT.5.jar",
          "size": 51903,
          "sha512": "b9d6c574bbf927bfa272d0916a7f3489774b80b25b961d9355905e1e89d4e3d66c0857ed1224acd1cc29a99bd450d161c8115bfd2269c45ad12a421c705e8e28",
          "sha256": "7a868e30da3e827e9dd176b34108e2182521dc89351751c35973d3b11ea35449",
          "sha1": "fea5641e0f2727fd3ef8d08c7f2e6b5d53f3b729",
          "md5": "f588b666b87a68d40f3e9ad0ce6833e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 180613,
          "sha512": "775d02d71e4cd455fc1362e755bf3436604f3712e950febfe7c71f0f2cddfd146082333943bb4319266326f8175681c88c778d3bd37e6b3f8dbc27e922f3ac86",
          "sha256": "524f568de4ed60c98a59629c04f077f13516b1300cf2943a9e75fced5ea5182a",
          "sha1": "8d2a1cf4a44456941068006058b5c2aedc3053da",
          "md5": "2bc86c3e8d67deda7199d4f420de83e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-batch-worker-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 23642,
          "sha512": "60f0e66f23d510ed5375efb2eebe54ef51b04e734f37bfe809a8850470bf7e21ecd098275799fde24980c0da064d415289fd27c3e47ba7d9b963b939e42979d0",
          "sha256": "44529da058d3323def8766725df65f5a0181c852d5adfabeb46a8ddb5731322b",
          "sha1": "c48b60682fffd4548c11537466aca0619a3aa0f8",
          "md5": "e8ef6b21040a4c839516876aec59225c"
        }
      ]
    }
  ]
}
