{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.4.jar",
          "url": "vectorx-security-24.1.4.jar",
          "size": 107161,
          "sha512": "7b303707277e0884325af77112a64d3a2b66fa7e1a7f2a5d64aadb5b2a7622ac307e43f9e1590d402b59ca7429aa38aa1deeb20d8a91ce1d36a5df26b4b523e3",
          "sha256": "5136c310aa8e79f6f175471ecb0ee898eb9473779bda7b1c42af6c2f51a33783",
          "sha1": "8305e92f7d0a46366feac305b56432d8a3d6abe3",
          "md5": "453b7732b01d0c72cf484087df704ec2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.4.jar",
          "url": "vectorx-security-24.1.4.jar",
          "size": 107161,
          "sha512": "7b303707277e0884325af77112a64d3a2b66fa7e1a7f2a5d64aadb5b2a7622ac307e43f9e1590d402b59ca7429aa38aa1deeb20d8a91ce1d36a5df26b4b523e3",
          "sha256": "5136c310aa8e79f6f175471ecb0ee898eb9473779bda7b1c42af6c2f51a33783",
          "sha1": "8305e92f7d0a46366feac305b56432d8a3d6abe3",
          "md5": "453b7732b01d0c72cf484087df704ec2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.4-javadoc.jar",
          "url": "vectorx-security-24.1.4-javadoc.jar",
          "size": 412008,
          "sha512": "d7699199d2b4f926846da2843736c6d66f85f3e76ff7210a8d1570ecbd98f9671994ec77e8d7f6d0a075ef5d32aa6806342b8b03e255e49e2a2a027cf190fc19",
          "sha256": "c89e55a2ba4216117f804be3f3de1a3bc0428cc18a89c98f0f6263f23059b50a",
          "sha1": "61b738fd19c41b90ec71c09594bb7dc855618194",
          "md5": "a9ff7d17080454e2db5c94cef45f8e81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.4-sources.jar",
          "url": "vectorx-security-24.1.4-sources.jar",
          "size": 65616,
          "sha512": "e49688ee00302c27c61b0d808f791f608fdf02334204ceab7938a7c1544849aff29ea3fa18b2af9bedb1e01fe9751cf999b28a754dc847ccb980e8cb3d38ebe0",
          "sha256": "8005727a98de0d3a1cfce7060ee6108b28f234648a0971cdd814ef28d61d8ebd",
          "sha1": "c0e553c38bf153fb6e2f7410b93d1266a4cee746",
          "md5": "601d7dee1c19c249d01e963f737f4bd5"
        }
      ]
    }
  ]
}
