{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe-nexacro",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-bo",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.2.jar",
          "size": 38568,
          "sha512": "d41849d50e61d9ef6edde2c75f064282147ca63f11a930fb475cf15225904af24005ea8cbac356fa1dcf5e7583c40a513020058150ec47f5eba22b138a4e043b",
          "sha256": "c36c9b1b8dddc42e352c21db86cb21f6b157a354028687f0b9e9773af1630b41",
          "sha1": "f9273dec28001ac73b3e2b99a86270d9fa4d7c28",
          "md5": "1b6ae750bd9ee42e3e996c8b9e8eea57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-bo",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.2.jar",
          "size": 38568,
          "sha512": "d41849d50e61d9ef6edde2c75f064282147ca63f11a930fb475cf15225904af24005ea8cbac356fa1dcf5e7583c40a513020058150ec47f5eba22b138a4e043b",
          "sha256": "c36c9b1b8dddc42e352c21db86cb21f6b157a354028687f0b9e9773af1630b41",
          "sha1": "f9273dec28001ac73b3e2b99a86270d9fa4d7c28",
          "md5": "1b6ae750bd9ee42e3e996c8b9e8eea57"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 150808,
          "sha512": "3e032ac03c8a5ac9083d927a52acef75cd6b72cc1afa467d74b725d354c278ae78bf0b8316a8439966a3cc062ebac598238d1ace9fee00b438f68a89b3301202",
          "sha256": "a830c187287b0b4950177c6bc0b1f455223fa12bedec8128ff0db36dd85e7eeb",
          "sha1": "459cbc677156ea82ac245b3d083ea9a50308424d",
          "md5": "adaf0014528150424e3d9b4b902370e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 21316,
          "sha512": "5e85922e3f6b06e262f68494f5be48c067b38e9d14b2fedecd0b89e46bcf638b8d9eb5ddddd4896b4e404b85ee6f481173b429f59ce57e98dd5e5db50a38bb6f",
          "sha256": "36c667ee621319f63c4ef33c775c4020dea10b188a5ae986bef4f9e77d85697a",
          "sha1": "002ec084765d4ef55fb98fa40b6d1e1b4ab97fcc",
          "md5": "85c558860d14d4f13feca038a9a82750"
        }
      ]
    }
  ]
}
