{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe-nexacro",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-bo",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.1.jar",
          "size": 38569,
          "sha512": "988e01fbb6fa89a95662844f2f710b613abfb72445b58974beacf779c889b3d334298cc351290f5e81ac6679d6598f13c796bd196df1828925d8cdec59112b50",
          "sha256": "2f303757f3bb9a7af99587c1f9a41483d15cee7c314d0826f7b95a2ad86712c6",
          "sha1": "51627f632177a00d8b575b09742701fc872d72ee",
          "md5": "35015a1b5559a51d8d9ad503b0f0baa2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-bo",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.1.jar",
          "size": 38569,
          "sha512": "988e01fbb6fa89a95662844f2f710b613abfb72445b58974beacf779c889b3d334298cc351290f5e81ac6679d6598f13c796bd196df1828925d8cdec59112b50",
          "sha256": "2f303757f3bb9a7af99587c1f9a41483d15cee7c314d0826f7b95a2ad86712c6",
          "sha1": "51627f632177a00d8b575b09742701fc872d72ee",
          "md5": "35015a1b5559a51d8d9ad503b0f0baa2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 150806,
          "sha512": "4115fcd7c97f0203f5da231c6eb6c5b838dc497b2597844b919c02049334564417a93270cfb424bb565aecec99b3c4d275d49db229d4904c2987572e0de1010c",
          "sha256": "67fe6b14ae4b153ccc1e08d650a4d340467db29e68d344b2a85d1502a3cdec1f",
          "sha1": "766c55c26b12db973cd4464991b9ac80a72adf6c",
          "md5": "560a8e866e60f5f56f8fae37c19cbe50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 21316,
          "sha512": "349a7086fdeb7d4a717242e416f3b72b58acf97b9db5f658fcd249f8fd9b116bc3869173230a5d3a47742c64e79844c40436c46243e0f21fbd5ad62853edf216",
          "sha256": "edc9a6414464224bd51fe49eff295134bba885d2984571b32a1614f1ff7214dd",
          "sha1": "40eed417dd68d8f33377f70856864d38abc8f412",
          "md5": "2b4e943f0bd6e4267fc3a9295f779aca"
        }
      ]
    }
  ]
}
