{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.2.jar",
          "url": "vectorx-data-jpa-24.1.2.jar",
          "size": 2691,
          "sha512": "db9c407fb05ec99dd57a3757f99bf8edefcf03f9974775d6eb8e6ac04f0512883f3b240b9a3b0faf5b4f46730caf60103c4f031b536db33a586591cf4e4a46ed",
          "sha256": "e8ef42fad8d68fc786e852d4014652fd004dfa39cb9c76168039b5f6af4f17a4",
          "sha1": "63b77e21d052af3986c6acb1108af1807813603c",
          "md5": "9e2697099b8c31b767a33cdbd07f1fdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.2.jar",
          "url": "vectorx-data-jpa-24.1.2.jar",
          "size": 2691,
          "sha512": "db9c407fb05ec99dd57a3757f99bf8edefcf03f9974775d6eb8e6ac04f0512883f3b240b9a3b0faf5b4f46730caf60103c4f031b536db33a586591cf4e4a46ed",
          "sha256": "e8ef42fad8d68fc786e852d4014652fd004dfa39cb9c76168039b5f6af4f17a4",
          "sha1": "63b77e21d052af3986c6acb1108af1807813603c",
          "md5": "9e2697099b8c31b767a33cdbd07f1fdd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.2-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.2-javadoc.jar",
          "size": 70339,
          "sha512": "afdcbb5d5ca38c940e44b47bee56b1b7b33498fabb43a0f071bfba5d4ee2248c23baa5249302f93734e1aae8bfc0dfc1224f331100bbfa9e9086754c36c074b2",
          "sha256": "25300e18e1a1397a63c323353e4e2ed2320dae57b37b685eff5f00769bf9cd2c",
          "sha1": "ca4621f060d62679025b5e47a713bc59881e8d37",
          "md5": "e8fd3e434a9edc1072805207a130c2b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.2-sources.jar",
          "url": "vectorx-data-jpa-24.1.2-sources.jar",
          "size": 1184,
          "sha512": "3168fab0f5d4fdc558163743b98055ef3d6ac6b497c67c518be15ec452c17525229b94cb7c6e2f5614aaf58182528037c665c35034b7e9f9f5ff6558f552fd92",
          "sha256": "de4bd477e44329a22cc53d9ab7cee0a433ab37028bfb494b5709ffeda81d18b7",
          "sha1": "435bd6d30c36f3f03ba8e2e1f32dea0583471ba5",
          "md5": "5b1bbe90cd13b625de26f2fac75754e2"
        }
      ]
    }
  ]
}
