{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-batch-manager",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch-manager",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-mvc",
          "version": {
            "requires": "24.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-batch-manager-24.1.5.jar",
          "url": "vectorx-starter-batch-manager-24.1.5.jar",
          "size": 261,
          "sha512": "5445c31d99254a782e324d1681096723a9bf906d0a09387837570079ec726dc3c0546a9ae96292b13ef611d3f4b1790b545a0cc326075c10897002b360d3cb7f",
          "sha256": "c8de4c826ee72d31100ebe1d62acfeb4fa3c921a22715f11d474457133b148a3",
          "sha1": "86395ff040c4c994a6c4e44b5e77d476d54c24bc",
          "md5": "39527830c70f252f7c4e366ffd04124e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch-manager",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.5"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-mvc",
          "version": {
            "requires": "24.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-batch-manager-24.1.5.jar",
          "url": "vectorx-starter-batch-manager-24.1.5.jar",
          "size": 261,
          "sha512": "5445c31d99254a782e324d1681096723a9bf906d0a09387837570079ec726dc3c0546a9ae96292b13ef611d3f4b1790b545a0cc326075c10897002b360d3cb7f",
          "sha256": "c8de4c826ee72d31100ebe1d62acfeb4fa3c921a22715f11d474457133b148a3",
          "sha1": "86395ff040c4c994a6c4e44b5e77d476d54c24bc",
          "md5": "39527830c70f252f7c4e366ffd04124e"
        }
      ]
    }
  ]
}
