{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security-jwt",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.devskiller.friendly-id",
          "module": "friendly-id-spring-boot",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-security-jwt-24.1.9-SNAPSHOT.13.jar",
          "size": 89000,
          "sha512": "c6ba4eb5bc39194ca24b6d49d5e742ae0b2b1f02340a7563890c42ba9543a8add6abba1023fa09805fa499b4deeb7691db0ea7f8bca8f99943f6e7f80eceb294",
          "sha256": "05ec66ae0cdc4f1b3872fd2d901ef429859be6c4de70461283cc2e59226b5ea8",
          "sha1": "27bbe1cb4e3af8da7e1d1bdf752b87789f43c256",
          "md5": "7684e33c1680185d45b7dba769300845"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.devskiller.friendly-id",
          "module": "friendly-id-spring-boot",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-security-jwt-24.1.9-SNAPSHOT.13.jar",
          "size": 89000,
          "sha512": "c6ba4eb5bc39194ca24b6d49d5e742ae0b2b1f02340a7563890c42ba9543a8add6abba1023fa09805fa499b4deeb7691db0ea7f8bca8f99943f6e7f80eceb294",
          "sha256": "05ec66ae0cdc4f1b3872fd2d901ef429859be6c4de70461283cc2e59226b5ea8",
          "sha1": "27bbe1cb4e3af8da7e1d1bdf752b87789f43c256",
          "md5": "7684e33c1680185d45b7dba769300845"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-security-jwt-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 291130,
          "sha512": "05f44b9e0a787becf64af6674c15ea3902b5d37ff6c7ce26ef54a6cf56bdc3669e57dbd6c4b982312b45720479309088941a98d541347fc8bffe73d76e42b879",
          "sha256": "5c60fa86a934236b9c6e6bb63a4482ad1aeb52135cf7b30ac4930b6b340b3cbd",
          "sha1": "71414538836fd52386040e346c544bbad48c1030",
          "md5": "fb5f9434334547d7c9e50dd499e43729"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-jwt-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-security-jwt-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 43000,
          "sha512": "0594b58e5a7ab08585e3e839be3aefd4086b1b504b708b034254f5adfdcdd98321b07845c0e326271b00513ae18182d5553946cb091e7619d4501e1b03c0d9f6",
          "sha256": "4a9db761803b0c25132580959119bc39951d7bb58573e647b1e9c47fbb8089e5",
          "sha1": "675d4cd9feda29d0adc908899bff100155f9af20",
          "md5": "399fecfd34e87e09b608f28f055dd45d"
        }
      ]
    }
  ]
}
