{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-test",
    "version": "24.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.8.jar",
          "url": "vectorx-test-24.1.8.jar",
          "size": 31763,
          "sha512": "46c4560f2f9abec3baac29e07a539eee122e6071ed23cd4f85d623691a77e3646df0e516dc1329948191824038103faab81ac89ba81d46738b176160f1b4ddda",
          "sha256": "b04d95d5e7a184b6348e61a7d1dbb9d7102da2103054de6f53a20b429dcad7d8",
          "sha1": "ebb8dacf0ea9e3698c527f5764465184ec83fbee",
          "md5": "78a89a08e60abb8c491aae49ac4ad318"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.8.jar",
          "url": "vectorx-test-24.1.8.jar",
          "size": 31763,
          "sha512": "46c4560f2f9abec3baac29e07a539eee122e6071ed23cd4f85d623691a77e3646df0e516dc1329948191824038103faab81ac89ba81d46738b176160f1b4ddda",
          "sha256": "b04d95d5e7a184b6348e61a7d1dbb9d7102da2103054de6f53a20b429dcad7d8",
          "sha1": "ebb8dacf0ea9e3698c527f5764465184ec83fbee",
          "md5": "78a89a08e60abb8c491aae49ac4ad318"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.8-javadoc.jar",
          "url": "vectorx-test-24.1.8-javadoc.jar",
          "size": 125850,
          "sha512": "88a49ac673f29071e2e8a76a9747690b25083dc9e7fa92ac8d871601d47fee8c27941b425d4340d8b1cba46751e5d7ee3c8524c6b73b123e1a7fd7673847a899",
          "sha256": "b07628c7ff12c33e37cbfa2abc5f9b7546a5ad97b8947aca1ed1d0c47653e8cc",
          "sha1": "01b501c33efde8ba301d243561d77193ae4dc090",
          "md5": "c3f653d878e38f747b811711d9e1502c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.8-sources.jar",
          "url": "vectorx-test-24.1.8-sources.jar",
          "size": 11947,
          "sha512": "57a87d9e5bc4ba79d4775a8179e02439b55ad47c235ca9461d658bc75ec97f0ebee959943a6ef9d4ad6d066b90b5f7eb0381f91e633e2641569d7fdaaef9ccef",
          "sha256": "64b34c08046a795c6aa1187ec774cac33f432fe394100ea08ed1b7d5b0cd0bc9",
          "sha1": "07373f92e9a25f17e6617b13c58ce50a0163ac98",
          "md5": "b4b8cf01733d04c1dc1a682e4982a6c5"
        }
      ]
    }
  ]
}
