{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-core",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.4.jar",
          "url": "vectorx-web-core-24.1.4.jar",
          "size": 9984,
          "sha512": "c13cb1588c693396a725bd0dbc00130aafc34fbedfd14091a7d1391103a89b9341f588e51c6f40926ccdc1b7411935a2400eea17e5838cba3128627ca0be2280",
          "sha256": "7942819c7c1911e5c3434ab1e7c8c8911928fdf28ede9f74cd70887d8c74a430",
          "sha1": "0cf6d89030c2b7b458e426415f318c3e192dd6d6",
          "md5": "221df9e907b061b28f9991baf61f74f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.4.jar",
          "url": "vectorx-web-core-24.1.4.jar",
          "size": 9984,
          "sha512": "c13cb1588c693396a725bd0dbc00130aafc34fbedfd14091a7d1391103a89b9341f588e51c6f40926ccdc1b7411935a2400eea17e5838cba3128627ca0be2280",
          "sha256": "7942819c7c1911e5c3434ab1e7c8c8911928fdf28ede9f74cd70887d8c74a430",
          "sha1": "0cf6d89030c2b7b458e426415f318c3e192dd6d6",
          "md5": "221df9e907b061b28f9991baf61f74f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.4-javadoc.jar",
          "url": "vectorx-web-core-24.1.4-javadoc.jar",
          "size": 103610,
          "sha512": "84df0e699d3544075ccf4bf200bbb1b55a36f9b4b50ab0f7403bd1c634f49fe285b2fcd4aa3f36cc163cf2385cee6736d5c95de193dcc281b85902c66c913eee",
          "sha256": "46493d069943f005e604a9b854bb0a804d68b29de2459f8d473f5ded26cb0b47",
          "sha1": "f467fa47f8d3f1549060a5999a6a9938d7fc3222",
          "md5": "95d742ef5e2d53184e50a7b1dcaa26da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.4-sources.jar",
          "url": "vectorx-web-core-24.1.4-sources.jar",
          "size": 5581,
          "sha512": "c3e6816d95ec4256c73d93fcfbaa50fb91dbee12ec6b6fc6d04f24bff2964594a7b4291a9a24d349fac4581ef8857a3189415bcc6a16527fd1b2d4fd49941a14",
          "sha256": "417ad83f2b51b542c460c224e5c40bd71bb532dc941ba1f4960563a721511a92",
          "sha1": "3a51c6bdaec1e294a99b2cf36f229ee19ee92e5b",
          "md5": "d58fed0e897e47ef1a4a9f9a669e240a"
        }
      ]
    }
  ]
}
