{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-core",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.4.jar",
          "url": "vectorx-web-core-24.1.4.jar",
          "size": 9984,
          "sha512": "eeec629b8bb82dbc41b2110462e838e5addf06ed09c3d4ef60695ffdd103e7d60dbdb2a6f212cb6a80194c4dec053a4487df814a9da33ca7c60da7c61c53f77a",
          "sha256": "b69e37c1741d3bf995b3ce1d839cfbeb55b914edb1a5d81ecef9e584e6a8b294",
          "sha1": "ba81839dfa178c95adb7ad8a2cfdd3afcac9a0b8",
          "md5": "00e4b79f265d33755554aa95a56e82df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "*",
              "module": "spring-webmvc"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        }
      ],
      "files": [
        {
          "name": "vectorx-web-core-24.1.4.jar",
          "url": "vectorx-web-core-24.1.4.jar",
          "size": 9984,
          "sha512": "eeec629b8bb82dbc41b2110462e838e5addf06ed09c3d4ef60695ffdd103e7d60dbdb2a6f212cb6a80194c4dec053a4487df814a9da33ca7c60da7c61c53f77a",
          "sha256": "b69e37c1741d3bf995b3ce1d839cfbeb55b914edb1a5d81ecef9e584e6a8b294",
          "sha1": "ba81839dfa178c95adb7ad8a2cfdd3afcac9a0b8",
          "md5": "00e4b79f265d33755554aa95a56e82df"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.4-javadoc.jar",
          "url": "vectorx-web-core-24.1.4-javadoc.jar",
          "size": 103610,
          "sha512": "153712013e879711cb8a034aa891ef7ac4429de7e446c70950cda10b96ab14856457d5ca0077bb0c2da256f47f666489ff7b1db8669ac1c27ae09f3c713a9895",
          "sha256": "f7f35ff052c4fb57e7f01765b0df06e929e8b0f37545558bb7a75bf79cd1a8fe",
          "sha1": "293b2b102fc0e68557cc44a9ba489274dca0deeb",
          "md5": "2bfeb6c0b868d450a37e849f9290f7d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-core-24.1.4-sources.jar",
          "url": "vectorx-web-core-24.1.4-sources.jar",
          "size": 5581,
          "sha512": "c28195bba25e5d56eab89c7508e359a466125bbadcdc15307ba11113ebaf3264f83e2d29c29d558afcad14770004ae273bf29199dbe5511411ec3776d58f4fa8",
          "sha256": "cc514ced57f9a94309b61eddedcf758219b9696f4c80cbf1b46e5c08d24d56c6",
          "sha1": "f7c6ddd196c23474f096f2eb64f456aac6d9278f",
          "md5": "f34ac91833166b04ab611fd30d486c28"
        }
      ]
    }
  ]
}
