{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-worker",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.1.jar",
          "size": 51902,
          "sha512": "272e1c8569f20db2a878b39728b00dd58aceb7750fcccfef06bee0a99301c381fcc6336ac11a5de7c4577d443a0ad5025e6af4072195ee94ce96245641a38cc1",
          "sha256": "d18afde68cc6abf2ccbcb0b50b6f9a88dab2b9ab9df10f7e0d881525fc0e5d19",
          "sha1": "ced792dc08da6832c0c1808826e57f5c09fe98fa",
          "md5": "243a95474dcede7455a2b13d4c1701fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.1.jar",
          "size": 51902,
          "sha512": "272e1c8569f20db2a878b39728b00dd58aceb7750fcccfef06bee0a99301c381fcc6336ac11a5de7c4577d443a0ad5025e6af4072195ee94ce96245641a38cc1",
          "sha256": "d18afde68cc6abf2ccbcb0b50b6f9a88dab2b9ab9df10f7e0d881525fc0e5d19",
          "sha1": "ced792dc08da6832c0c1808826e57f5c09fe98fa",
          "md5": "243a95474dcede7455a2b13d4c1701fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 180592,
          "sha512": "32c623aafd7c9d158b37b85f23dbf16a2e3312a9ffb5030722ba2c62db6eb8a7a899a7cfabc7d3b1e398e75df84e07b5ee99814ea5157c042efad0c7471634e7",
          "sha256": "9cfc3a46247aa753641d93e82fde1c297255dbdce912038afdb9f6e1a391f324",
          "sha1": "be26f37275281b093a8cfd3e1ce801143e3340a2",
          "md5": "25f70e663fd01dab563213d0e95deea9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-worker-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-batch-worker-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 23642,
          "sha512": "b3b8fec3e7ef52dbbb5fead0a4f7fa5480c6af6d598dd81ce6092e170499bf14cdd57ac1c1bb15354131aa620b7dc037fc13b89eb91e388c109a9dab40ab98ae",
          "sha256": "d0b675a70a26a06a73781e328d1edb6b1d961e5b65072c596657728a0037cfda",
          "sha1": "3d997d0edd24eae2ab903ebd75acada4d398676c",
          "md5": "976af26c639a1ffde9ac076ad91a4fc5"
        }
      ]
    }
  ]
}
