{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.3.jar",
          "size": 9737,
          "sha512": "53b375dcf06fadff237aad3b4a146598f2b03b04563d87f1e70e7019fbfd7c2aa16452d7eb405f9e996af4a1a2078029a91807c0cebcd53c401b504030406117",
          "sha256": "6d694be74f6812d0e51f581e11162da7b1cc525fd8fd948e4b2a2c04b3ba5f5f",
          "sha1": "339cb85f06194df267fd17ee8827da1367e9a141",
          "md5": "8dcaa55b7726e5a30ea24031d869da5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.3.jar",
          "size": 9737,
          "sha512": "53b375dcf06fadff237aad3b4a146598f2b03b04563d87f1e70e7019fbfd7c2aa16452d7eb405f9e996af4a1a2078029a91807c0cebcd53c401b504030406117",
          "sha256": "6d694be74f6812d0e51f581e11162da7b1cc525fd8fd948e4b2a2c04b3ba5f5f",
          "sha1": "339cb85f06194df267fd17ee8827da1367e9a141",
          "md5": "8dcaa55b7726e5a30ea24031d869da5d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 97294,
          "sha512": "7a116f4935c555d20f201a1f47b22e16ec9f92227295ffb86675bfb1f58272ad08884d1163e868f9cdd72ceacb8b5a36c3eab8dc1a1071255c63ae00e0c9fbb3",
          "sha256": "01843267a993d1e7a77b5d634f1c79a9f19109f1060018f73bb72607dee2e39d",
          "sha1": "db7a53f5ce44bfe2f7f97c646d63845d75ba22c7",
          "md5": "aebb1786d921916912e62ee10f38f3ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 3340,
          "sha512": "a63f80d391ab3a2ab54013a94cab759e5cce93af3000c72ff03905358667c7b1f5270cb193d83cbcf40a20b46198857f64c333fa6a815a37f3df02586cafc40c",
          "sha256": "cf145c6f72e8679e81bbc63b190f4386a621561d12e2ef537f6a290c26cf1bd9",
          "sha1": "e63c5bf4d2ab1df7d150256dc3309718e560f77e",
          "md5": "46f5e1f0dc0a0b7d13d0401da5b4cecc"
        }
      ]
    }
  ]
}
