{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.4.jar",
          "url": "vectorx-web-servlet-24.1.4.jar",
          "size": 99309,
          "sha512": "0b25ff67c483cab9384f19d0f56171f0984dbb7452150d2d57b3e90a12f81a7840a6a3208614966fd18894e4b6c7581e44b28b6fa2dec8b25a91fda6aec13796",
          "sha256": "d363a30ab1fa1b3035e670248bd254f7a2b52e233b5433213f69cf77979de409",
          "sha1": "940412d498a8432e05f9b3cceb2abf458d1137b7",
          "md5": "a4fd6e049b68ab5ad2a0bfff03568811"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.4.jar",
          "url": "vectorx-web-servlet-24.1.4.jar",
          "size": 99309,
          "sha512": "0b25ff67c483cab9384f19d0f56171f0984dbb7452150d2d57b3e90a12f81a7840a6a3208614966fd18894e4b6c7581e44b28b6fa2dec8b25a91fda6aec13796",
          "sha256": "d363a30ab1fa1b3035e670248bd254f7a2b52e233b5433213f69cf77979de409",
          "sha1": "940412d498a8432e05f9b3cceb2abf458d1137b7",
          "md5": "a4fd6e049b68ab5ad2a0bfff03568811"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.4-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.4-javadoc.jar",
          "size": 297863,
          "sha512": "0442df544c709d2c75770f21215d6e934ef7ffc346229f25694d7a06f8ecca200f620f308f17e713f24e3c570ac26f6881aa6e7e17409e6f8f4c00faf4ce561c",
          "sha256": "ad18c1e9c55b7d7439affc7e2698a64697e2f296a96e64702dde2c6f633324ba",
          "sha1": "8cdeb280506a81fea11205cc70874c0f602b6189",
          "md5": "661f028c6a1bbf3cc6f4fe605c097080"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.4-sources.jar",
          "url": "vectorx-web-servlet-24.1.4-sources.jar",
          "size": 50810,
          "sha512": "f7b2fb5c0ad3eb10da550150eba781712370943bb6dbfbab67247d2be1b1ae6da5c7a1dd5b3165f25a02d5adc73285787cb2af2d8e394b6000f8ae04137bde8d",
          "sha256": "61e016c8ffd72a57b4691f348278739a633cea80ee04d70377e24b3506ecca2d",
          "sha1": "8b344fd4411e03dd6d7da7e6c5c3146a596f90c5",
          "md5": "6514689fc9c4db0132fb28df4beb27c6"
        }
      ]
    }
  ]
}
