{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.13.jar",
          "size": 2774,
          "sha512": "06bc901052e72b4fe280918434dff82215dda5c384dc40e5701f8f2df00d75595a3150b389ecc31ed242aa30ffc8fc6b0cde9bba4d0121c360cd9b20bafd89fa",
          "sha256": "509a558d0a2d696876a6f11fa10e5b2cffbac6fe438df62eee6ee2e978e83647",
          "sha1": "7774029700dcaa5bfdea388f776a52449c481ce7",
          "md5": "f84fc4a3521cc425f9c1e118c18254c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.13.jar",
          "size": 2774,
          "sha512": "06bc901052e72b4fe280918434dff82215dda5c384dc40e5701f8f2df00d75595a3150b389ecc31ed242aa30ffc8fc6b0cde9bba4d0121c360cd9b20bafd89fa",
          "sha256": "509a558d0a2d696876a6f11fa10e5b2cffbac6fe438df62eee6ee2e978e83647",
          "sha1": "7774029700dcaa5bfdea388f776a52449c481ce7",
          "md5": "f84fc4a3521cc425f9c1e118c18254c2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 80946,
          "sha512": "b3ef0a8ae4bc1c45127504ed0417601f95317765c2476a3258d175886056e25408ff464c91dcb1b207a8976802fde455f326e8a1e2ae028ec24b64f10ea76ff4",
          "sha256": "2c71199016e716771d84ed5ea5260502f01bfad6f0d8adc0187afa45a6a2718f",
          "sha1": "21e7639be5fd0a341a0908dca1b9ea8d920a64f1",
          "md5": "3f8c75972834df53a28f73f5143aa363"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-cloud-aws-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 1224,
          "sha512": "5e7461c4b2293bcb5e69e7b406a708d2aa244b808191cbbd1ead8815deb073c2661d3996bc8d4ba0993488e43045d99ee3aaf12dab48237a0a54161aacd90658",
          "sha256": "948c8765c6f6902dc01c232801be9b5cead4a104722198c5700b8fa442ba87f8",
          "sha1": "dbd2a629f6405e8d81ab6751d3931ccba5d2693a",
          "md5": "5821a22e29246c8b516d92b8b58e02cc"
        }
      ]
    }
  ]
}
