{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.8-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.5.jar",
          "size": 2775,
          "sha512": "ee6922cec6e308eea5d5ec2a837b207b2aff267d2f0c15639f39ef5e21bbb09a91b9a3f0a73439829032f604ad30f6697bd5d47930933da377c1a1ea68136de8",
          "sha256": "3fbaad9409f38584b50da141f228fdb6d1937f4391fa1f47851bd4ee32453b4b",
          "sha1": "cc6cf60433826a6352a27f95356ca65527e44a5b",
          "md5": "4da7738f6122d9d269941358650e5bc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.5"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.5.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.5.jar",
          "size": 2775,
          "sha512": "ee6922cec6e308eea5d5ec2a837b207b2aff267d2f0c15639f39ef5e21bbb09a91b9a3f0a73439829032f604ad30f6697bd5d47930933da377c1a1ea68136de8",
          "sha256": "3fbaad9409f38584b50da141f228fdb6d1937f4391fa1f47851bd4ee32453b4b",
          "sha1": "cc6cf60433826a6352a27f95356ca65527e44a5b",
          "md5": "4da7738f6122d9d269941358650e5bc3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.5-javadoc.jar",
          "size": 70464,
          "sha512": "4e258d6fcfeb708c410c1d7641233128a4e7105dc741844e27405ba269917f605e812444859c5f9acc751d76b3cf962cc13724266f6e1868972f0df42605016a",
          "sha256": "5bcd9c53bfcabad365964f803070d00bf5798051be3e3ec4c973881e48ecf756",
          "sha1": "54281252468e94292ace157c665ca865645b90fb",
          "md5": "9d3fe7a30edb90fe6eb5d174552fd3f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.5-sources.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.5-sources.jar",
          "size": 1228,
          "sha512": "f533efc3d732d4ca3b643c5857269a3d981b5c1aa9f0765e6a321fce38fc5e267c13431f0ea81f7e117e79425b9aa00688f257d18c0a8873187b5fa39828db69",
          "sha256": "0ea9a966fec5439832285faed3edc6c38518c679440176e9a7eb088baeb12de6",
          "sha1": "fad7e209d16b02d6cc6e02af9d427b79c5f20919",
          "md5": "94700787d70c8043475a5a39bd524ee2"
        }
      ]
    }
  ]
}
