{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-autoconfigure",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.1.jar",
          "size": 184876,
          "sha512": "a53e177b7cd27ee7754d4ca403c08cdcb1255c69b49ea63c387ab1c9868b1a6a59b3a520947f599fbf8ebe14bcc34dc1d564b81febd2bbb07635bafe145e7de5",
          "sha256": "5d8c0c1b6c1308c59c2865b45e76afd364a84832cd9c005e87c13b21c3ef88de",
          "sha1": "a2f1b2475c9114f7af725d8f418c8dcbdbecb208",
          "md5": "461f98830778e271f8b98aa1e6ade05e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-route53"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-autoscaling"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.amazonaws",
              "module": "aws-java-sdk-sts"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.1.jar",
          "size": 184876,
          "sha512": "a53e177b7cd27ee7754d4ca403c08cdcb1255c69b49ea63c387ab1c9868b1a6a59b3a520947f599fbf8ebe14bcc34dc1d564b81febd2bbb07635bafe145e7de5",
          "sha256": "5d8c0c1b6c1308c59c2865b45e76afd364a84832cd9c005e87c13b21c3ef88de",
          "sha1": "a2f1b2475c9114f7af725d8f418c8dcbdbecb208",
          "md5": "461f98830778e271f8b98aa1e6ade05e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 274565,
          "sha512": "a159854c5f8ac23e28e3f1e2a686eb639a19f3e8daae2fa9c6779692a9a7993ff170f25b133cf0989216de705383803f371810823f1431267c1d6f73a910e9d8",
          "sha256": "bbad68596c0e3fdc5a0b5427d0b47ce3d81501f9d470ece63a27acf8c28f741d",
          "sha1": "5b36c5cf5aaf52d2abab7c6063cc60d0db605f9f",
          "md5": "1cb5edc57a110b2b780f9e42dab85aa6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-autoconfigure-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-autoconfigure-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 69406,
          "sha512": "4aae035995dd0fbd569c809ce6036055ce55f00e9a5d3008d3d9778d5715ff2b443bfd26a817d55310fb9c3ae0a6920f272666e677fe0b2ca66c99427d7d4904",
          "sha256": "05a5339e4f0deba4fb631791c4cb9497a33b7d6143b79a2e06810644a4eb31c2",
          "sha1": "f2374bafb84a610b37ad5902bf593f9ef80af87c",
          "md5": "c6547923ef0028f726c35d435145dd58"
        }
      ]
    }
  ]
}
