{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-net",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.4.jar",
          "url": "vectorx-net-24.1.4.jar",
          "size": 29717,
          "sha512": "e5e18c5429109fe957477fa9f4747b4b1e8da98b53452934f91f8689e03678838d2ead67ad8c568d85a812ae1a4510c326f572ff191986d36688d911ccbad8df",
          "sha256": "c9e279469d8dfc47e60564b229362b086facea8c846d4d6500a26a0adacf201a",
          "sha1": "8c6157814423e22c9f311f85aad12d866700e589",
          "md5": "112941c67dc67fb48298fc2f830927e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-net-24.1.4.jar",
          "url": "vectorx-net-24.1.4.jar",
          "size": 29717,
          "sha512": "e5e18c5429109fe957477fa9f4747b4b1e8da98b53452934f91f8689e03678838d2ead67ad8c568d85a812ae1a4510c326f572ff191986d36688d911ccbad8df",
          "sha256": "c9e279469d8dfc47e60564b229362b086facea8c846d4d6500a26a0adacf201a",
          "sha1": "8c6157814423e22c9f311f85aad12d866700e589",
          "md5": "112941c67dc67fb48298fc2f830927e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.4-javadoc.jar",
          "url": "vectorx-net-24.1.4-javadoc.jar",
          "size": 128285,
          "sha512": "fe9fe31e7224e895426f43cb7a19a9813c2f5546913ea2a624c2755b24323f7506cc9816f21117e5e747cab532a865fc846ab12e297addd82106d5f88e4ce92b",
          "sha256": "161f6c3a2c28ba83747ca1835e21d504d29a1fdf2b75444960ab386524a33cb8",
          "sha1": "d9de9affa55dc5ab51086e07ab5afaecf47475d9",
          "md5": "58ee9d554d8f7f140d9f2742620e152d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-net-24.1.4-sources.jar",
          "url": "vectorx-net-24.1.4-sources.jar",
          "size": 10137,
          "sha512": "3e9ec06ff859721a68cfa98d63ef33653c7354053a85171d470d365ed58611e2756bb072af4b405f28c59b8aced9f73aa0ba77c28c8f2bebc740f29f194b0982",
          "sha256": "d5c44b82f61a8f8e9b967e9a3b1968deaad818fba25de56783aa0665bff9716f",
          "sha1": "2b7e8d8711a9d712e960fd67970b150357dff6ed",
          "md5": "1d264bb9239b3ad2a0ff0ff258e866e8"
        }
      ]
    }
  ]
}
