{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.6.jar",
          "url": "vectorx-cloud-core-24.1.6.jar",
          "size": 2696,
          "sha512": "e9c87ea80645c2a3c3a62545374176480a5b832fbc35848d3375b80e95619c1144349127f83a9d5738d57dfbb61edf29d5a2c6c41a816a9c8c945d0a2597f4e9",
          "sha256": "dd07c5b875d02fec0a030a1558483be5e77a8f0d40eb0654defa901020be43e3",
          "sha1": "992389badaa97b66b007f3152c1e30b8ebd07cd6",
          "md5": "6433e943964fd3023c11e371c45f6228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.6"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.6.jar",
          "url": "vectorx-cloud-core-24.1.6.jar",
          "size": 2696,
          "sha512": "e9c87ea80645c2a3c3a62545374176480a5b832fbc35848d3375b80e95619c1144349127f83a9d5738d57dfbb61edf29d5a2c6c41a816a9c8c945d0a2597f4e9",
          "sha256": "dd07c5b875d02fec0a030a1558483be5e77a8f0d40eb0654defa901020be43e3",
          "sha1": "992389badaa97b66b007f3152c1e30b8ebd07cd6",
          "md5": "6433e943964fd3023c11e371c45f6228"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.6-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.6-javadoc.jar",
          "size": 70383,
          "sha512": "602a3ad1ca9cd9c2fb401acf9025fd30d6034e394869c9f99711053554bd7929e0ea24133a8e87bcbfa753555fe8e63e7672fe68d4cfccbf2bf998dcdced7c7e",
          "sha256": "2aee9e629f946fa3e4720abb86035f1d6c194a3f3e20ba102b0d9d61c87ace0f",
          "sha1": "acbd728e3b04f46443b824a4f353b8abf87380cf",
          "md5": "b351b1bc592a0a40eb815719ba9fb399"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.6-sources.jar",
          "url": "vectorx-cloud-core-24.1.6-sources.jar",
          "size": 1186,
          "sha512": "832cc4c4887e57332166de5052a39132afa8a2fc52eb4f782048a328f552e44f0b07c18e8c23cc713d8d9abc949d2eddcb362685807af06e2dbf1dfdea92dc12",
          "sha256": "63a3371f4752176971ef06e6ca19c79ea2ab79be70e2d4e4539ee376234ee4a2",
          "sha1": "a8f5ac7aa049639b2105e2a4bf9cdc4ac831957e",
          "md5": "ea1fc966b8ed3b23c93e8964776179ca"
        }
      ]
    }
  ]
}
