{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.9-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.3.jar",
          "size": 2715,
          "sha512": "af6f113bb0fb0d227db2be5e34f5ed36b05bcc4398ddf177bb46561ac1ab74f404bf19034a35ad91ba0aca018a2122744578a40822d7624cdd9405e7e774bb6d",
          "sha256": "ef0211f39c6b33bd96887da751c1e4572d64d7b512031a357fea5daf0f2fdca8",
          "sha1": "427f6f24e32bd1ce4803b721af1dac428c90fbdc",
          "md5": "565edcfb281108849f451354d0dc0d56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.3"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.3.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.3.jar",
          "size": 2715,
          "sha512": "af6f113bb0fb0d227db2be5e34f5ed36b05bcc4398ddf177bb46561ac1ab74f404bf19034a35ad91ba0aca018a2122744578a40822d7624cdd9405e7e774bb6d",
          "sha256": "ef0211f39c6b33bd96887da751c1e4572d64d7b512031a357fea5daf0f2fdca8",
          "sha1": "427f6f24e32bd1ce4803b721af1dac428c90fbdc",
          "md5": "565edcfb281108849f451354d0dc0d56"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.3-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.3-javadoc.jar",
          "size": 74155,
          "sha512": "ab5cc5dfc86858e6d8b938cfbe52a188d7619b50bbf900b5e37593cdd11277e54719bd3080c66cb0e58c7322e414ce28d34b7d29608a3cce605ee45fcb1d66c6",
          "sha256": "aed34e2f2741d3a31c446bceb73cb2513b37f738c88b1ce044612367e65f3f98",
          "sha1": "af5a31ce99f4be220141c75e48d8ea1925e13459",
          "md5": "60917aa65ab833c891340599d3a57164"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.3-sources.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.3-sources.jar",
          "size": 1182,
          "sha512": "b7fa7f4d703112f71b5e883e7b238d24aee08aef78bf090195885e16875c0ce5e9dba652ebeee2894b07ca145f2364a717635a02b48ec92ec82c66a7bb93f7e6",
          "sha256": "b95f1827b1f380918b06d1770c01402addf764332f26de6bf5001e8b5c4959aa",
          "sha1": "8cde0839b4050c41c25e2152ec69b5830253987a",
          "md5": "9a621d8df11ec2d8ecc43301cc49abcc"
        }
      ]
    }
  ]
}
