{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.13.jar",
          "size": 101040,
          "sha512": "b62ed3730df9ba4ce801a4f4544dfe9db8e373f38eafefc4e1c4c87ad0bae90388fda7bd2103c2dc8ff9e4a885da2c1920598403e2007447ca116c69131fbe12",
          "sha256": "46b9f9b6203007e3981185d60f711caf96092fec88696b19f7b436c123cc9827",
          "sha1": "d0cb889b3f414d437899a65049c1117aa97a0ba3",
          "md5": "0ac32cff273eb7ed93f10d2744bac3da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.13"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.13.jar",
          "size": 101040,
          "sha512": "b62ed3730df9ba4ce801a4f4544dfe9db8e373f38eafefc4e1c4c87ad0bae90388fda7bd2103c2dc8ff9e4a885da2c1920598403e2007447ca116c69131fbe12",
          "sha256": "46b9f9b6203007e3981185d60f711caf96092fec88696b19f7b436c123cc9827",
          "sha1": "d0cb889b3f414d437899a65049c1117aa97a0ba3",
          "md5": "0ac32cff273eb7ed93f10d2744bac3da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 320017,
          "sha512": "2e3c5f173c9bff4856e0c589393d08e63ff8eaa2fc3db725413bf1c81c973051e9be58cccbdffc777274d045889f007d2267cae2bbebce18b7eb90c7dc92bc99",
          "sha256": "f0edabe2bdf628bcea5e7aa1a06657893c39587ab1597cc92b3f0deccf049dc3",
          "sha1": "432c1560899b6ae28506381be68d6e76bf74b878",
          "md5": "530d86e5e3c73cab3974a548c7c5d397"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-web-servlet-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 50851,
          "sha512": "9f5be2951ee364708e540623adab2982744317f61ec48073a862e5db366c36004f84a2afe242f8fd5e3b999b596c95a1818b50546f1345f8f59082acd1fd4a9e",
          "sha256": "09da49d20a3c12361aff1c1e36b13ce3314ebca1fdde298b591f8752a01ebc0f",
          "sha1": "8cda29d3b3cf58d84a22cb9f2279f5ae517ebaeb",
          "md5": "4f4de55eccb5a8605fd295a981136eb1"
        }
      ]
    }
  ]
}
