{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-core",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.apache.tomcat.embed",
              "module": "tomcat-embed-el"
            }
          ]
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "dev.akkinoc.util",
          "module": "yaml-resource-bundle",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.1.jar",
          "size": 229101,
          "sha512": "fea4ccd5da765c9c07ebdfba287467d38a4690d234d1f1b0fa59254c986ad7506c7cda00cb438de899b5cd2025d50d413d2320e380cb55df7058bacae33e2b00",
          "sha256": "d9a7ed41fdd69333bd03f2f4f16239fdbcdaaed179a1894e22ccea3f8626d5ff",
          "sha1": "449b400df487f32db45ee61c935117285ae8b727",
          "md5": "fd42b53ff1f25827b94b430b435804ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.apache.tomcat.embed",
              "module": "tomcat-embed-el"
            }
          ]
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "dev.akkinoc.util",
          "module": "yaml-resource-bundle",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.1.jar",
          "size": 229101,
          "sha512": "fea4ccd5da765c9c07ebdfba287467d38a4690d234d1f1b0fa59254c986ad7506c7cda00cb438de899b5cd2025d50d413d2320e380cb55df7058bacae33e2b00",
          "sha256": "d9a7ed41fdd69333bd03f2f4f16239fdbcdaaed179a1894e22ccea3f8626d5ff",
          "sha1": "449b400df487f32db45ee61c935117285ae8b727",
          "md5": "fd42b53ff1f25827b94b430b435804ba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 553672,
          "sha512": "b9274e5f346be70c579f852db21f9670494c4eb776f081750f43ca053f4266a0ade52ef6480153ee28fc5f1a9315a7e5eb2e94ada006df9aab3852ab078fc9bc",
          "sha256": "47e6d41bffd09513da559601873bf04186e54e9d80afb7d6cb080d85321471d5",
          "sha1": "c458c8299bb71aad66b807850d943d0c208dbf42",
          "md5": "8474277c5ed961db33376c240cc62610"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 112964,
          "sha512": "8cf37a8525a13e7ca8c2ee513c334b83ed4c59d8bbf0f3069e68a5a1bf88010099ae72ea9c5d09bd0cc6a83e727f0d50bc6efb1a68cfff3b3de690b2454bd8a0",
          "sha256": "aa1f25ad1d8c6f2d668cc25a6a60923b73c4a9c9c66d0dc5a53d4ab54032eabc",
          "sha1": "044a0fd5a7903b710affee92c439a400ae71cd29",
          "md5": "a0828ef1bd17d6e5df371ebbbf100eb4"
        }
      ]
    }
  ]
}
