{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-aws",
    "version": "24.1.8-SNAPSHOT.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.2.jar",
          "size": 2774,
          "sha512": "bcd5a2c6c6eafdaff25efb24f56450f857c48b0fe670cc720037fbef199d1f8db343d8373f78cabccdea2376086722aadc7d6c1f18bb4128422aed4d6f069b29",
          "sha256": "1772c29cfeaeecfd0c31b4aa0abce622b55f7e8569db2f1b05e4af1f002b4eb1",
          "sha1": "015ea12a1d20ddfaf337974b0f70da146c38d867",
          "md5": "e8635df7c32ee2e3a2410f5647bd841d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.2"
          }
        },
        {
          "group": "io.awspring.cloud",
          "module": "spring-cloud-starter-aws",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.2.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.2.jar",
          "size": 2774,
          "sha512": "bcd5a2c6c6eafdaff25efb24f56450f857c48b0fe670cc720037fbef199d1f8db343d8373f78cabccdea2376086722aadc7d6c1f18bb4128422aed4d6f069b29",
          "sha256": "1772c29cfeaeecfd0c31b4aa0abce622b55f7e8569db2f1b05e4af1f002b4eb1",
          "sha1": "015ea12a1d20ddfaf337974b0f70da146c38d867",
          "md5": "e8635df7c32ee2e3a2410f5647bd841d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.2-javadoc.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.2-javadoc.jar",
          "size": 70460,
          "sha512": "210131f189cfea6e25e8e6f0b23ec3c081ad7c48e38dced5d570add48b3631464c5d6bc9213def49f02c4b26b6231d6d7a13aedb8ec2b2f283776f81daa6bee6",
          "sha256": "fbc1149593112e37cedea02ae1406a4c90f9fc48a35eddbb937e7459802eafa6",
          "sha1": "2f02d9799ca53e85825c080628b9bf9f795c5011",
          "md5": "4088254524b593c31e9c3dd25097efd0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-aws-24.1.8-SNAPSHOT.2-sources.jar",
          "url": "vectorx-cloud-aws-24.1.8-SNAPSHOT.2-sources.jar",
          "size": 1228,
          "sha512": "24cd724b0617fc2cd591be4b6b0b4b6c68cdf6103c3f366b93dbe14f52ac2a9fa7329466474458fd3750ebb0a5dd8bf1b4ee2d0fce0e80f49c89c01ca79e517f",
          "sha256": "028fdf5f046d751ffc71e438c30acdcf6a6a6d727ef1e6c3646fa3e5afc12c55",
          "sha1": "b2dff3e8e1e6ef1f7ac69e7daefd6b8d3981051f",
          "md5": "05747fd10c49c17e666febc433a4a056"
        }
      ]
    }
  ]
}
