{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-batch-manager",
    "version": "24.1.8-SNAPSHOT.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch-manager",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-mvc",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-batch-manager-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-starter-batch-manager-24.1.8-SNAPSHOT.3.jar",
          "size": 261,
          "sha512": "30b05d4a6ee28cbf47de81903a26e037b113d712284a20fbfedac7256ea40cbb8ef6347a7cf879af9dad599cf49a1d38b2c4cc6241c21d4568139e70b849a28a",
          "sha256": "eeb40da1473ba0e43696b39d8205947f91de33968356be2c3b397c4dbd2b6d17",
          "sha1": "f416f45ff5167d9511dc2d859364e85e20eeee7a",
          "md5": "a0641443beb3c7d4449ec301fe21ef62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch-manager",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-mvc",
          "version": {
            "requires": "24.1.8-SNAPSHOT.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-batch-manager-24.1.8-SNAPSHOT.3.jar",
          "url": "vectorx-starter-batch-manager-24.1.8-SNAPSHOT.3.jar",
          "size": 261,
          "sha512": "30b05d4a6ee28cbf47de81903a26e037b113d712284a20fbfedac7256ea40cbb8ef6347a7cf879af9dad599cf49a1d38b2c4cc6241c21d4568139e70b849a28a",
          "sha256": "eeb40da1473ba0e43696b39d8205947f91de33968356be2c3b397c4dbd2b6d17",
          "sha1": "f416f45ff5167d9511dc2d859364e85e20eeee7a",
          "md5": "a0641443beb3c7d4449ec301fe21ef62"
        }
      ]
    }
  ]
}
