{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.8-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-data-redis-24.1.8-SNAPSHOT.1.jar",
          "size": 9739,
          "sha512": "0b4425c6a8f537b84ea2fd7f23b034cfbe80c285b4c8d6e61351e79c0d46c9d105f45c7fa8d7bc689eecee282893ab32aae1167499f445615943faaf354fd958",
          "sha256": "f3f37c07d08b448c7240bf353a36353ed4031071075647a432297f3460ba9d61",
          "sha1": "99f3135471a3b21c5fa3b4da3f6bbc0c1dea46e9",
          "md5": "258a3eff0bf8874e6e438fdcf7e0e0e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.8-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-SNAPSHOT.1.jar",
          "url": "vectorx-data-redis-24.1.8-SNAPSHOT.1.jar",
          "size": 9739,
          "sha512": "0b4425c6a8f537b84ea2fd7f23b034cfbe80c285b4c8d6e61351e79c0d46c9d105f45c7fa8d7bc689eecee282893ab32aae1167499f445615943faaf354fd958",
          "sha256": "f3f37c07d08b448c7240bf353a36353ed4031071075647a432297f3460ba9d61",
          "sha1": "99f3135471a3b21c5fa3b4da3f6bbc0c1dea46e9",
          "md5": "258a3eff0bf8874e6e438fdcf7e0e0e3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-data-redis-24.1.8-SNAPSHOT.1-javadoc.jar",
          "size": 93713,
          "sha512": "58c6e34d75918b6460bf621b2cbee4e03fa22db0595a39d9265535b7ea171df69fa016a3a93f9f30f7058842c7856f7758dec032f4502719cabad51a4f667070",
          "sha256": "aebd967f15c431e1c92308285a8559b37985ef9da7762435efc43e00915ad239",
          "sha1": "d26852fc71ecbe9660973eae0f8c49fd0064eaf8",
          "md5": "aa6f9855ca3ced9a3173d151b7fe6520"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.8-SNAPSHOT.1-sources.jar",
          "url": "vectorx-data-redis-24.1.8-SNAPSHOT.1-sources.jar",
          "size": 3360,
          "sha512": "bd6d83b64561fc50710c5001720a49cfc0c89be290e5efb1a93a8941f17ae6eac25aa74c14c86689570bfcc21080f72e055b3376d93969482644955370d6f3da",
          "sha256": "26b9f0ad993433fb3b722d25c7f415a16cec093159aff73e40ef262299334b7d",
          "sha1": "10aa6f39227ccbc3f3bbdc56ec1598a9d26fae9b",
          "md5": "2fe4daf9181cfe417e778ad06b0f1c32"
        }
      ]
    }
  ]
}
