{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-core",
    "version": "24.1.9-SNAPSHOT.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.apache.tomcat.embed",
              "module": "tomcat-embed-el"
            }
          ]
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "dev.akkinoc.util",
          "module": "yaml-resource-bundle",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.13.jar",
          "size": 234603,
          "sha512": "0fbd60fbaa305422c66507ba1a7bd6f6b76f5468e4ef43b72edb2ac8009bcea08f86d24fc3a6084d055bc643ecb36954065a7acc5b4c0b4b56fd0b9367005217",
          "sha256": "b3c658c9e5cb8df7bb9f6d4ba7cb13da5babb58197c48d3731165d215530ba22",
          "sha1": "4a424366efa936744c133945b910cb9ae9c9d565",
          "md5": "00117745939339c9d7dba799d21bea6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "org.apache.tomcat.embed",
              "module": "tomcat-embed-el"
            }
          ]
        },
        {
          "group": "com.github.ulisesbocchio",
          "module": "jasypt-spring-boot-starter",
          "version": {
            "requires": "1.17"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine"
        },
        {
          "group": "org.ehcache",
          "module": "ehcache"
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.sun.xml.ws",
          "module": "jaxws-rt",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.jai-imageio",
          "module": "jai-imageio-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.github.kostaskougios",
          "module": "cloning",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "dev.akkinoc.util",
          "module": "yaml-resource-bundle",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.13.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.13.jar",
          "size": 234603,
          "sha512": "0fbd60fbaa305422c66507ba1a7bd6f6b76f5468e4ef43b72edb2ac8009bcea08f86d24fc3a6084d055bc643ecb36954065a7acc5b4c0b4b56fd0b9367005217",
          "sha256": "b3c658c9e5cb8df7bb9f6d4ba7cb13da5babb58197c48d3731165d215530ba22",
          "sha1": "4a424366efa936744c133945b910cb9ae9c9d565",
          "md5": "00117745939339c9d7dba799d21bea6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.13-javadoc.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.13-javadoc.jar",
          "size": 597269,
          "sha512": "8e7ba1ee06e9d63975f6044d5e76926cc8c0a907034f815507f8e1f1f940492e0895c8d0aff3806b1a1b63e40a894940e6af976b553554afc8b0e63145ba2a84",
          "sha256": "dabd2ead1e714f89e826561f260a4f92f0124da9a9212b52b2b98492e7d358b2",
          "sha1": "f286f12f59bdcd886d1bf4e625e176016eb8d28a",
          "md5": "42a21c59675f98a3f428f57c70743c1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-core-24.1.9-SNAPSHOT.13-sources.jar",
          "url": "vectorx-core-24.1.9-SNAPSHOT.13-sources.jar",
          "size": 113586,
          "sha512": "24cb0b7c81b1cb0a482a29a9bb259da365a2a0e371c36d37801459c3c8d052460488ffed935ea2376b43e897e2cae26c1a5a7c261286ef47729e51dbc2e5b6fc",
          "sha256": "d2afc11fdd55b0cabb434c26d58449808c487c3e31ae1d638ac6917918c33a58",
          "sha1": "bb8d4f21a02546b066d42523e01ed8ad7dcde23b",
          "md5": "87b16c1ef77aaffb89c96e3fcd586dc4"
        }
      ]
    }
  ]
}
