{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-security",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.1.jar",
          "url": "vectorx-security-24.1.1.jar",
          "size": 107160,
          "sha512": "ab7e5e7a90dfe4acda8731fc417f67bd82971beba3f7be5600066be7a919a000dfb45bd6d38e86ba388281549fe5940982976159c9edffa8e0ed4cf62c19c2cf",
          "sha256": "435ebe86dc17de2f600a980990420dfa65ce673f66058f49d666beca9d2d70c4",
          "sha1": "8951961b2aaf17744533531b19b1b0bf8c2642aa",
          "md5": "1dbc961810109e73c457ec7d3eb9a5f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-socket",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-security-24.1.1.jar",
          "url": "vectorx-security-24.1.1.jar",
          "size": 107160,
          "sha512": "ab7e5e7a90dfe4acda8731fc417f67bd82971beba3f7be5600066be7a919a000dfb45bd6d38e86ba388281549fe5940982976159c9edffa8e0ed4cf62c19c2cf",
          "sha256": "435ebe86dc17de2f600a980990420dfa65ce673f66058f49d666beca9d2d70c4",
          "sha1": "8951961b2aaf17744533531b19b1b0bf8c2642aa",
          "md5": "1dbc961810109e73c457ec7d3eb9a5f2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.1-javadoc.jar",
          "url": "vectorx-security-24.1.1-javadoc.jar",
          "size": 411970,
          "sha512": "8369b0fdaabbff671d05b0f1b179db1d2ac71cb7addd14ccb3120643aeeabb4bb4c9497d5706a198917e32e04f650f5d718373a8133b9e0af2d170fe69c5590e",
          "sha256": "ac8de20bcd73385b47aa3b54c10aed62f8cf35a031301580f8cdfed592ff09bc",
          "sha1": "3e9e2d19cb38ae92d23704a8d1fb0ed857d95c1b",
          "md5": "0fef98e4b9881b8bd6681b36ffb923dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-security-24.1.1-sources.jar",
          "url": "vectorx-security-24.1.1-sources.jar",
          "size": 65616,
          "sha512": "2c3859d3915b8a3cd489b85464805c4cf9d19844ece3af7331b1070cb42ea6eefabd942759465e14feccf7b9367879db39201903d913b60ecd06e993081a8c30",
          "sha256": "647f3ddaadd99eebb598dff3d143a92e3a58a8b10a6376fba792d474698386a2",
          "sha1": "9e405386c2e836e679e7f9ab49435ab9cd1f28ec",
          "md5": "2bd467def5f1e863e2171c2533eebaef"
        }
      ]
    }
  ]
}
