{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.1.jar",
          "url": "vectorx-web-servlet-24.1.1.jar",
          "size": 99308,
          "sha512": "87603ac1b98420109cfec4e382ec97f4030765a284505d5282365334908131c2da396002248168066b26990f1fc8e3c6eb6e84a89837d6c87502f35c1df9353c",
          "sha256": "604d94d1fbb9eecd1c4ed40907de460e35af1ec8135fbbfcb53716f6587ddb4c",
          "sha1": "ae1de0636c6b4accf3712643fac913adb682087a",
          "md5": "23068facaa9060e1f0e6f0e1e8fb93ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.1.jar",
          "url": "vectorx-web-servlet-24.1.1.jar",
          "size": 99308,
          "sha512": "87603ac1b98420109cfec4e382ec97f4030765a284505d5282365334908131c2da396002248168066b26990f1fc8e3c6eb6e84a89837d6c87502f35c1df9353c",
          "sha256": "604d94d1fbb9eecd1c4ed40907de460e35af1ec8135fbbfcb53716f6587ddb4c",
          "sha1": "ae1de0636c6b4accf3712643fac913adb682087a",
          "md5": "23068facaa9060e1f0e6f0e1e8fb93ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.1-javadoc.jar",
          "url": "vectorx-web-servlet-24.1.1-javadoc.jar",
          "size": 297842,
          "sha512": "ad73675f1de31239e527a65815e293bf578c58fbec8551d6a04c294bfca9ed7de1dc4311aa185feab34cc3fddb531ce62b24d492f144aed9ca5c708cb4dfd6d5",
          "sha256": "d9b8e1efa5db0f3502e414f307fbd5d2f97a71a1bf696037cbfe471ac68c41a6",
          "sha1": "fdf755752df0b6259e013a135ce248e885f4a8e1",
          "md5": "04758accd86241853924dc4b42f4ccb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-24.1.1-sources.jar",
          "url": "vectorx-web-servlet-24.1.1-sources.jar",
          "size": 50810,
          "sha512": "0c5a70f48799df0923cde26a7a217a24b41bb6038d50fb9442ee99dc5453f7bda6bc8717c4eed5d34d5810ffefefb04de86d51c318c47e29165d9a8d4cab3e5a",
          "sha256": "5bc15c320db70b5d611280b9308fc90014ba3db19511c7430215b41602e5db17",
          "sha1": "b9eed073e4d23bf022d02bfd4ed8b56a6f183b49",
          "md5": "7891c139061e8dadc5144aa2420a3dce"
        }
      ]
    }
  ]
}
