{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-manager",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.7.jar",
          "url": "vectorx-batch-manager-24.1.7.jar",
          "size": 45153,
          "sha512": "5ed772a8d5d3d9f3699af61633a3388a3c49ac99df25e76acb11db9bb92b3825ea1c8c7636b9da042721198066a7ff5afc93867a6863b259f12cc4f8810364ed",
          "sha256": "e658c14dc7b5ffdb6b019e8f5f203c04066ce09f8e75679851704e8d601cbc41",
          "sha1": "e5bb59b681258522fcd21f09e4542005242fe524",
          "md5": "a40b68ebd272dc4e7e59dd8e2eacfb56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.7.jar",
          "url": "vectorx-batch-manager-24.1.7.jar",
          "size": 45153,
          "sha512": "5ed772a8d5d3d9f3699af61633a3388a3c49ac99df25e76acb11db9bb92b3825ea1c8c7636b9da042721198066a7ff5afc93867a6863b259f12cc4f8810364ed",
          "sha256": "e658c14dc7b5ffdb6b019e8f5f203c04066ce09f8e75679851704e8d601cbc41",
          "sha1": "e5bb59b681258522fcd21f09e4542005242fe524",
          "md5": "a40b68ebd272dc4e7e59dd8e2eacfb56"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.7-javadoc.jar",
          "url": "vectorx-batch-manager-24.1.7-javadoc.jar",
          "size": 139217,
          "sha512": "455fa8c81376d9fa4eda61b0f2570a37dcfb8511909b57529814365cc7b7614ca8cbd3532063ceb30700b2ea7cc7be4dec83f2dbfbd1e2a5528b388fdf566efb",
          "sha256": "b6207d3ee1a82c9e41024f4f92ce0077db457c19117c312d015d1f6f56685720",
          "sha1": "0475f8c439a024761da36d939a0d4ac3b9d8142c",
          "md5": "e632dd4b8c5722ac9f81028f3c8c4e08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.7-sources.jar",
          "url": "vectorx-batch-manager-24.1.7-sources.jar",
          "size": 20387,
          "sha512": "85bc683ac40414c3c6d2b4f36a7653291aa655aa4311b6a2c60d2d30e88de0b89be8aaa150314d502d3b4c353ed38ff71910b14f6fab1cf8fe19a114a0362a64",
          "sha256": "c4d46a8e30a79c7e337fe47716bb66427051fdd0aee994fecf96fcac0c34e9d4",
          "sha1": "ad71dec93a16c847f5140b9af58107ffcb5329d5",
          "md5": "f4e4d8eada3dad23316942efc2c6d020"
        }
      ]
    }
  ]
}
