{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-redis",
    "version": "24.1.9-SNAPSHOT.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.1.jar",
          "size": 9739,
          "sha512": "2e76b61dd09774cbc681da7af74c9632d01cb55f1794da96557f5db90ae48819facc7633cb3921fbbe89cb745ba6e70238c340f400c241498eee2c3f46f15d95",
          "sha256": "4be08d356bab1f07f30e69ad98869d6bb319056ccbb3c35c2e1f99572cde4428",
          "sha1": "d10c1e76ef8e4a0e854826aa98e89911c442e301",
          "md5": "28f39ed06521bf1c67b2113cf957fb45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.1.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.1.jar",
          "size": 9739,
          "sha512": "2e76b61dd09774cbc681da7af74c9632d01cb55f1794da96557f5db90ae48819facc7633cb3921fbbe89cb745ba6e70238c340f400c241498eee2c3f46f15d95",
          "sha256": "4be08d356bab1f07f30e69ad98869d6bb319056ccbb3c35c2e1f99572cde4428",
          "sha1": "d10c1e76ef8e4a0e854826aa98e89911c442e301",
          "md5": "28f39ed06521bf1c67b2113cf957fb45"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.1-javadoc.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.1-javadoc.jar",
          "size": 93716,
          "sha512": "1ba2f538173b172f8ffb94f1c404504905eb4f93eaf3861b04176d8117ffc1f7b7446d02fc905f0b13a44ed292b592bc0dc6014d3db2473c781e2b354e62a325",
          "sha256": "9320cb7103693f2b2b2cbdde09dadb28b1c34ed8bb70febafa7047bea5a9b603",
          "sha1": "d108912c224a4cbed181041b31129bd8baeee5ab",
          "md5": "14c9a146261fbecc3d87b080bbabad1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-redis-24.1.9-SNAPSHOT.1-sources.jar",
          "url": "vectorx-data-redis-24.1.9-SNAPSHOT.1-sources.jar",
          "size": 3360,
          "sha512": "ec744bda9bddd013d9a7ae14bd1447bf4c28828b000d4d2e37b66dece204b71885c7d4be151489af91c99c71f22b9123fcc44e235234ba55a6f40bd2f6806368",
          "sha256": "b2b620132680d2c3acba8337263b442aab966cfc3e6eb22346776e28eda8463f",
          "sha1": "bf7208d784ec74953dd7d0bd68daf52961677d57",
          "md5": "6304aaedda90d1c8abf83ee682172a4b"
        }
      ]
    }
  ]
}
