{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.5.jar",
          "size": 2715,
          "sha512": "2fbad5e423ff8e78872a4ebb58c41966055c41991f35e054edb8dfa5d7c2fd95710a7955b03961a46c7245b5eb8555c68d18c1d05de0debec56addd55eb00a66",
          "sha256": "0d4fd6e87a3e48525dea2b7a85681f002fda50fff0072de15283f5e525dd2abd",
          "sha1": "a59301841f9f87bafc58f9a44c5f1edc4fa76822",
          "md5": "74ca8d4a17dbd78b2834b697fbe425cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.5.jar",
          "size": 2715,
          "sha512": "2fbad5e423ff8e78872a4ebb58c41966055c41991f35e054edb8dfa5d7c2fd95710a7955b03961a46c7245b5eb8555c68d18c1d05de0debec56addd55eb00a66",
          "sha256": "0d4fd6e87a3e48525dea2b7a85681f002fda50fff0072de15283f5e525dd2abd",
          "sha1": "a59301841f9f87bafc58f9a44c5f1edc4fa76822",
          "md5": "74ca8d4a17dbd78b2834b697fbe425cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 74154,
          "sha512": "225564235057f6bde811f90784a7c5d00fc67a7c26b1ecd760401dcc149019cfe23a28cb81f97547870f6917cc3d41d8d7ee5a9f3722e46184d2e6fa2c630354",
          "sha256": "a087c41861bb9466ef96561b6823056073f8cc354f9cae9d69fc1a2a41218017",
          "sha1": "db4f79e061213a73d471d8b4262a47b2fba89fb0",
          "md5": "e57e7bdd0f20ac5bed5ccbd0c33489df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-cloud-core-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 1182,
          "sha512": "0340de94859b9ef31dfa2e6f587a4ce85b31b8ad311049bf5cd2edbe073a9fc29bb086203d32ccb71184744569f68d62669038daef3910a83368c90cf8140777",
          "sha256": "895181185d2fd1d50887f551361cd45bbb4e89ec30cf20082ed4977b16f6f449",
          "sha1": "d0006f35f78cb7d92c93d2d8310cf65b25f77acf",
          "md5": "7f38ea192983ea151b471dbdb295fbfe"
        }
      ]
    }
  ]
}
