{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-mybatis",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.4.jar",
          "url": "vectorx-data-mybatis-24.1.4.jar",
          "size": 106462,
          "sha512": "194044871d301df59a746dc01d4623e74c1b194c6fcec4f3dc4cd831ef9b9a70ad0be82d6525d8ca82a24db22d94d6b39f9eaa9e0a768fa6e0dac59fe05b7eb7",
          "sha256": "79465ca608eed441d9b109196f8cab90a0426ac35e7405bba968a1166e619bcb",
          "sha1": "fe97278b3b7dbd30c7ca2543465d3ba188e82d3f",
          "md5": "c4f1f1799256e3aa0ebdd2988861838d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.mybatis",
          "module": "mybatis-typehandlers-jsr310",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.github.jsqlparser",
          "module": "jsqlparser",
          "version": {
            "requires": "4.3"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.4.jar",
          "url": "vectorx-data-mybatis-24.1.4.jar",
          "size": 106462,
          "sha512": "194044871d301df59a746dc01d4623e74c1b194c6fcec4f3dc4cd831ef9b9a70ad0be82d6525d8ca82a24db22d94d6b39f9eaa9e0a768fa6e0dac59fe05b7eb7",
          "sha256": "79465ca608eed441d9b109196f8cab90a0426ac35e7405bba968a1166e619bcb",
          "sha1": "fe97278b3b7dbd30c7ca2543465d3ba188e82d3f",
          "md5": "c4f1f1799256e3aa0ebdd2988861838d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.4-javadoc.jar",
          "url": "vectorx-data-mybatis-24.1.4-javadoc.jar",
          "size": 298614,
          "sha512": "9b1b98c47f60754fdfe8e35cf1a8147e83aedf0aada4df82a291f057702422e172dfd611b3653ac84798f1673fb255ed222bc8fa8421749185bf14d108302d66",
          "sha256": "d707555276ddc674035f014d85288973c1b452ba93baf4253e71b65792980b65",
          "sha1": "a8b6fe4baa06d0217f4c2f0b6eb7114b14252fa4",
          "md5": "faa8ddec467658ca4dac2b2320dcc126"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-mybatis-24.1.4-sources.jar",
          "url": "vectorx-data-mybatis-24.1.4-sources.jar",
          "size": 68934,
          "sha512": "9cfe4d86597601aff195d6c9ec4324000db543b20750aa31c80d1da3ff2119f8262ab4d53e49c9eaa58096b4825c60a8d72d856c566e3e448a64207b3d0b4215",
          "sha256": "bb7963b7508de95a77277292be25023bd67febee7ec923fcc4731dba0c8f467b",
          "sha1": "0e059250ffa8d7a27db8577e916c11fe3cd5beb2",
          "md5": "3fdcc0bb5af4f5b700b24a5e013a981a"
        }
      ]
    }
  ]
}
