{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-bo",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.1.jar",
          "url": "vectorx-management-bo-24.1.1.jar",
          "size": 145411,
          "sha512": "1a495c4dd88066b7c3f5b1e1cec0f6cbbe4628bbaee4ff594fe31ad6966ecade246031538847ef8583e62b259c0352efe6ec602e2a639225d0627a2eb64f0481",
          "sha256": "0139ddd307cea8d5ffa1906b21843016d7cb37e65bf49118573c3a17cd336f7c",
          "sha1": "e0e0c10b80ab48ff55f9b2df594a62a2ec56fe78",
          "md5": "4950c4976c8075547f269c0bdb9925ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-bo-24.1.1.jar",
          "url": "vectorx-management-bo-24.1.1.jar",
          "size": 145411,
          "sha512": "1a495c4dd88066b7c3f5b1e1cec0f6cbbe4628bbaee4ff594fe31ad6966ecade246031538847ef8583e62b259c0352efe6ec602e2a639225d0627a2eb64f0481",
          "sha256": "0139ddd307cea8d5ffa1906b21843016d7cb37e65bf49118573c3a17cd336f7c",
          "sha1": "e0e0c10b80ab48ff55f9b2df594a62a2ec56fe78",
          "md5": "4950c4976c8075547f269c0bdb9925ec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.1-javadoc.jar",
          "url": "vectorx-management-bo-24.1.1-javadoc.jar",
          "size": 305797,
          "sha512": "357fe20bc289624f0334fe92c77e3409d7ac73ae1d87c64ee5d27bcff274c7e2d67a430afb7100a69ad1f1d3c4cf00fc04c9099cf8235403d19c7a3113b83c49",
          "sha256": "8fcec3672338f5a1fe975ab52391a82c7ca75d4bdc30d959598725f13acbc224",
          "sha1": "bf7c01ef7567728fc1c82946a93bb3a8de157d06",
          "md5": "f0d85bd45e47e8b9453d98e0290012ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-bo-24.1.1-sources.jar",
          "url": "vectorx-management-bo-24.1.1-sources.jar",
          "size": 59264,
          "sha512": "45a351f378f203dae3d4f5958f29a77d9ae2bc981269e8309ce61731a8e3b1bd56b18f9439b0706946e7b606f19e0b52082215f6ec8e093bf5aa73da39f33ca5",
          "sha256": "85ce54cffb09ccda4ea0bd51ff131cf3204f368d268526256420cb1858ab4f1f",
          "sha1": "a8e2a2c9c1c990c7c4a6424e2539bb1a8e1c4447",
          "md5": "83b0feee9c750c61aab45f13644625ca"
        }
      ]
    }
  ]
}
