{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-web-servlet-tobe-nexacro",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-bo",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.7.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.7.jar",
          "size": 38548,
          "sha512": "5a75a1a58e7669548785d46b292d28944eccf003a984bf55a6ae5236a0765169a7fa9e1066c5747a0a6ae74e011a0144e13592f08e76d23647442a267167be13",
          "sha256": "42ce1953c8ad7bdc5767a5c381077f674df3d6340539d8248d44f1617358f84c",
          "sha1": "ce0ef2792f53bd9c835ce2a9948dcf605dadf891",
          "md5": "4b883d6475faeaada6380ba6cfe9747e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-tobe",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-management-bo",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "jstl",
          "module": "jstl",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.7.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.7.jar",
          "size": 38548,
          "sha512": "5a75a1a58e7669548785d46b292d28944eccf003a984bf55a6ae5236a0765169a7fa9e1066c5747a0a6ae74e011a0144e13592f08e76d23647442a267167be13",
          "sha256": "42ce1953c8ad7bdc5767a5c381077f674df3d6340539d8248d44f1617358f84c",
          "sha1": "ce0ef2792f53bd9c835ce2a9948dcf605dadf891",
          "md5": "4b883d6475faeaada6380ba6cfe9747e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.7-javadoc.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.7-javadoc.jar",
          "size": 150382,
          "sha512": "ba5898b3684d132f04cfde3d9a3fe2a57c4972ad69717192f017cabf6fc606fef068b3222f85cf5227c8ca159716717925d82d108f5e0d8a74cbb599b67ae672",
          "sha256": "4b9e27e71ef0ac08e9f1cbaa9980bf0ac9661f4f8c66443c8aba318294543d86",
          "sha1": "33b2aada7fcf517bf06a640ab46830f7643780c5",
          "md5": "d259769eb3888e73aae4fc9e08da64b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-web-servlet-tobe-nexacro-24.1.7-sources.jar",
          "url": "vectorx-web-servlet-tobe-nexacro-24.1.7-sources.jar",
          "size": 21316,
          "sha512": "726c64bb1b81b0acf9b0662619edb3fbf053e76ab6992a8d2f1d27a13062b490399be18e24fd942304fb4e7295acb3faf052d16d0218f9f0b4196992817e8628",
          "sha256": "2baa77a57ab28b81b54aef5e45efe2ff3426a794593405a624cfa7203dcf7199",
          "sha1": "11aacecf7ee3ae057375e5fc40b81cb9911261df",
          "md5": "685a75bb618a3ec8331a18efa6eca138"
        }
      ]
    }
  ]
}
