{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-data-jpa",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.4.jar",
          "url": "vectorx-data-jpa-24.1.4.jar",
          "size": 2691,
          "sha512": "6d048d85f41b7cdb03b9dcc8def5061bc3f22c3622963ff2d85e84e5123452e37240866bbd78c10b40b87a5fd7088db4ab93fa4f7e0e24ca1be2c917474d04ab",
          "sha256": "c8fdd21011b97ad76198218b1ec386628135b49c104e2e0a3591f4826990add2",
          "sha1": "3cea71bebf0eabaaec10aa783874c4232e076c1f",
          "md5": "2be74c0f2b59ad6084c723e1d0f4bf66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.4.jar",
          "url": "vectorx-data-jpa-24.1.4.jar",
          "size": 2691,
          "sha512": "6d048d85f41b7cdb03b9dcc8def5061bc3f22c3622963ff2d85e84e5123452e37240866bbd78c10b40b87a5fd7088db4ab93fa4f7e0e24ca1be2c917474d04ab",
          "sha256": "c8fdd21011b97ad76198218b1ec386628135b49c104e2e0a3591f4826990add2",
          "sha1": "3cea71bebf0eabaaec10aa783874c4232e076c1f",
          "md5": "2be74c0f2b59ad6084c723e1d0f4bf66"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.4-javadoc.jar",
          "url": "vectorx-data-jpa-24.1.4-javadoc.jar",
          "size": 70340,
          "sha512": "e49df46bc94e44425e6794656bcd86a37d467724c965e868ed261d8d06c7385db7d91fcb26e09f9bc0f7fc534043988b0bb80677154696361bb337633cbe4639",
          "sha256": "5a6176b4357ca5069844446df1c09ba01e276d761fd50d4c73fc152473ab5036",
          "sha1": "0ca9e4ab46960b785f364c7926edcdba1a7ed24e",
          "md5": "787bf4436774baddf36466be65f468af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-data-jpa-24.1.4-sources.jar",
          "url": "vectorx-data-jpa-24.1.4-sources.jar",
          "size": 1184,
          "sha512": "8385be022546cc97650274950f2551cc40de0b940026f72ece7367a721ebb639ff66f2e4cc36f472c13a26d36ebed7fb62ab9edbe20488a758c23a7bd23ff508",
          "sha256": "cc7bfc1df594de2a91f8d946b21c50e7975b48b62936f00920bbc4f3aa65c764",
          "sha1": "60783f71fadbfdd1ae89fc0371826f4eb52871a9",
          "md5": "d5ab7b12d9a7ebeb0c9d4d9a61b574d0"
        }
      ]
    }
  ]
}
