{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-manager",
    "version": "24.1.9-SNAPSHOT.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-batch-manager-24.1.9-SNAPSHOT.4.jar",
          "size": 45172,
          "sha512": "e0602d8f858128e2dbc47ce29623f056784c55f7b598a4dc32eba5d70156c9cff684e998ba31859b8c306f36d5c3941982938d1908761f0fe83c46ffb70c48ba",
          "sha256": "5c4ca3dc5ddc4d588697bcf5408152d386b637bd1797bf7416343dffc1f4b9c5",
          "sha1": "613f92b90e03565a8816f50899a109c29e6ddaff",
          "md5": "d9e62a323bb325e7c4663db948f57efc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.9-SNAPSHOT.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.9-SNAPSHOT.4.jar",
          "url": "vectorx-batch-manager-24.1.9-SNAPSHOT.4.jar",
          "size": 45172,
          "sha512": "e0602d8f858128e2dbc47ce29623f056784c55f7b598a4dc32eba5d70156c9cff684e998ba31859b8c306f36d5c3941982938d1908761f0fe83c46ffb70c48ba",
          "sha256": "5c4ca3dc5ddc4d588697bcf5408152d386b637bd1797bf7416343dffc1f4b9c5",
          "sha1": "613f92b90e03565a8816f50899a109c29e6ddaff",
          "md5": "d9e62a323bb325e7c4663db948f57efc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.9-SNAPSHOT.4-javadoc.jar",
          "url": "vectorx-batch-manager-24.1.9-SNAPSHOT.4-javadoc.jar",
          "size": 143008,
          "sha512": "38968985d26aeb2cd62f0b0e4ec02345312027abbc43683624158358ac336e84e1f6c5bcab42ec7b34402aad8f9ffb63a4afaedf1b6d1b9b2c3841f3940d69d7",
          "sha256": "fe5c5af5d770aba2ba1f63fb039c06fae799475d3e8d01041fa5e4a0de348e97",
          "sha1": "e1958637a2d8d86a8383a9f9ce733bb8565b2958",
          "md5": "8bac8af8900a9d7f8b5e47a3f6faab8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.9-SNAPSHOT.4-sources.jar",
          "url": "vectorx-batch-manager-24.1.9-SNAPSHOT.4-sources.jar",
          "size": 20251,
          "sha512": "b51e885572ee1e1480c955ed5ef936c8f3159b3fcbb78b228bbe724b67fe4dd40cc5c6805ac85695ff570446946fd1702746cea8576a812771abe633091aa3a9",
          "sha256": "79a9d2e802ec100a872faab79fc70f06f5823d6ff345ff913a1e7e4252d93853",
          "sha1": "ffe01dd598af95979db2f22a9b21a7d8c01853c8",
          "md5": "90d83f6570540b39b0f8bf81e6811c91"
        }
      ]
    }
  ]
}
