{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-gateway",
    "version": "24.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-eureka-client",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.7.jar",
          "url": "vectorx-cloud-gateway-24.1.7.jar",
          "size": 46815,
          "sha512": "32d7f31dc12d9d635454e3262df7f4358e3a2ef1fc0aac52dac732b6a2cd218f06f0c840f05f9473a5e1056578d8c4dd583bdc6f96fa53826e06c0451ac1fc73",
          "sha256": "8028098b178a791a0f7538796d3bf592dd3ab9b69bc65f31dbf4c55f8b83444c",
          "sha1": "7926322767083973f78cf1ae9a5123614f7ccb81",
          "md5": "a8bff5695ce3aece5104dc3681a1cba8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-core",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-cloud-eureka-client",
          "version": {
            "requires": "24.1.7"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            },
            {
              "group": "com.github.vlsi.compactmap",
              "module": "compactmap"
            },
            {
              "group": "com.sun.jersey.contribs",
              "module": "jersey-apache-client4"
            },
            {
              "group": "javax.servlet",
              "module": "servlet-api"
            },
            {
              "group": "com.netflix.archaius",
              "module": "archaius-core"
            },
            {
              "group": "com.github.andrewoma.dexx",
              "module": "dexx-collections"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-client"
            },
            {
              "group": "com.sun.jersey",
              "module": "jersey-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.7.jar",
          "url": "vectorx-cloud-gateway-24.1.7.jar",
          "size": 46815,
          "sha512": "32d7f31dc12d9d635454e3262df7f4358e3a2ef1fc0aac52dac732b6a2cd218f06f0c840f05f9473a5e1056578d8c4dd583bdc6f96fa53826e06c0451ac1fc73",
          "sha256": "8028098b178a791a0f7538796d3bf592dd3ab9b69bc65f31dbf4c55f8b83444c",
          "sha1": "7926322767083973f78cf1ae9a5123614f7ccb81",
          "md5": "a8bff5695ce3aece5104dc3681a1cba8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.7-javadoc.jar",
          "url": "vectorx-cloud-gateway-24.1.7-javadoc.jar",
          "size": 162601,
          "sha512": "47c0d12a325c5b02291a35e9c7571ca65cf40773eeb7750a24b712925a6d113170e214ce48f1ffb9440893b568f13f07eebcb5a9256a5a8d74a30da29e283b75",
          "sha256": "2b5a9a67a51780387ec23c89caf310032a9836a2a466477c5e9a4e4425046254",
          "sha1": "296a1830db85b32730057b372749f219483da1bd",
          "md5": "3e8babd7014943bf7f6878c2bc147cf3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-gateway-24.1.7-sources.jar",
          "url": "vectorx-cloud-gateway-24.1.7-sources.jar",
          "size": 15249,
          "sha512": "08dd1dd6cdd7342a7438306d11a048819af7021c814273e43ed55f99e51980422401c3778eadb68cae5e98b9ad4a433af93f718184472cb0a576a14451526d41",
          "sha256": "3f6464b759fdd0747a6b71a2d1c642a2dc0b86843d424a771739da6a1f732b7f",
          "sha1": "432cfde7707f0eee81f71ab0523e4df8f687b25a",
          "md5": "9f7060a572d41883eaa18389033a83ba"
        }
      ]
    }
  ]
}
