{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-management-core",
    "version": "24.1.9-SNAPSHOT.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.5.jar",
          "size": 926517,
          "sha512": "c7381f86523f50ade1f59365bfe2efca27186526267c4fa2c36e05fdc3328479a145ba0e5d207e315253361fd2cd772b24ca4c75b04e3c61f0142ba82a135b81",
          "sha256": "820d5d5ad14849199efc9ed6edb17918c54d335ee8bd9e327b0238f47b39d87f",
          "sha1": "d88ee80b375153b4d61365ff2fa3df89e8417912",
          "md5": "fdce326825f28a3b2292ac6951db6567"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-view",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security-jwt",
          "version": {
            "requires": "24.1.9-SNAPSHOT.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.5.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.5.jar",
          "size": 926517,
          "sha512": "c7381f86523f50ade1f59365bfe2efca27186526267c4fa2c36e05fdc3328479a145ba0e5d207e315253361fd2cd772b24ca4c75b04e3c61f0142ba82a135b81",
          "sha256": "820d5d5ad14849199efc9ed6edb17918c54d335ee8bd9e327b0238f47b39d87f",
          "sha1": "d88ee80b375153b4d61365ff2fa3df89e8417912",
          "md5": "fdce326825f28a3b2292ac6951db6567"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.5-javadoc.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.5-javadoc.jar",
          "size": 1350615,
          "sha512": "c4b979b0cbc8ebda3ef7f1495ba200654989acf06a348a9b63e9aecbd974e3054afb3a1c49008aa83a284ccc552cfa6e48f439db3c98d0711e180fc2dc3920c0",
          "sha256": "5cea405563ba6bf873db881b55949d66e5cdf34e334b1b74929bdf2664d33e1d",
          "sha1": "b8d4c185426472e86c0e721cf6fa1b9c339ab95f",
          "md5": "5151e72bfc5998334fca5266974b34ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-management-core-24.1.9-SNAPSHOT.5-sources.jar",
          "url": "vectorx-management-core-24.1.9-SNAPSHOT.5-sources.jar",
          "size": 328688,
          "sha512": "87c5f642e9f6eaaedf47e213b0482175e1b544388f60235047ae65f6cc6126422525fecce1a95c27c831de4b70ecd72955db20dc92aa7391a4dcbed0629338d6",
          "sha256": "b63d569bac78baac805324d1b266d891433ac9939cf042e1c4f878fd4fd74d1b",
          "sha1": "e87268ce5f3894e81ae82c18eebd394c8a20128b",
          "md5": "e8f80333863402f792be178f5f829925"
        }
      ]
    }
  ]
}
