{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring.starter",
    "module": "vectorx-starter-restapi",
    "version": "24.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-restapi-24.1.4.jar",
          "url": "vectorx-starter-restapi-24.1.4.jar",
          "size": 261,
          "sha512": "235bb2772218a86a631af4061a7960151b90f0b7798ed5c3c4a3cf56cc16f7bae99124b5bd6c99cb3ce511a27352a8f001fe0c330bcb82d19401f8dba68ba319",
          "sha256": "2621082bcf47d37ac51771fad7405ddf9f9db2faa3c76b1e63d6c920bfecef76",
          "sha1": "f68ade8dfe4e813c8b5e40febb95e7938b99b190",
          "md5": "7db47620fbaf5cdc403cb05d3e3aa503"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-autoconfigure",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-test",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.4"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-security",
          "version": {
            "requires": "24.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "vectorx-starter-restapi-24.1.4.jar",
          "url": "vectorx-starter-restapi-24.1.4.jar",
          "size": 261,
          "sha512": "235bb2772218a86a631af4061a7960151b90f0b7798ed5c3c4a3cf56cc16f7bae99124b5bd6c99cb3ce511a27352a8f001fe0c330bcb82d19401f8dba68ba319",
          "sha256": "2621082bcf47d37ac51771fad7405ddf9f9db2faa3c76b1e63d6c920bfecef76",
          "sha1": "f68ade8dfe4e813c8b5e40febb95e7938b99b190",
          "md5": "7db47620fbaf5cdc403cb05d3e3aa503"
        }
      ]
    }
  ]
}
