{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-test",
    "version": "24.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.2.jar",
          "url": "vectorx-test-24.1.2.jar",
          "size": 31765,
          "sha512": "6c0d45d7b6b1b031703cd89dc04a6c3aa94e7457bf594978c09e2daa96ad86e4b06ebf6dcd1af63304752f8f61529b72c3bcc75c7f3bac4dbb63c5b0cf403147",
          "sha256": "173de1267f66037fabccfabd96f6848bbb1eef826cf0144a7c0308c112d8efcf",
          "sha1": "bc172c6bcfb39465d3ec69906e0234cca58aeaa6",
          "md5": "5e79419961c150bf0627bcf94aa44376"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        }
      ],
      "files": [
        {
          "name": "vectorx-test-24.1.2.jar",
          "url": "vectorx-test-24.1.2.jar",
          "size": 31765,
          "sha512": "6c0d45d7b6b1b031703cd89dc04a6c3aa94e7457bf594978c09e2daa96ad86e4b06ebf6dcd1af63304752f8f61529b72c3bcc75c7f3bac4dbb63c5b0cf403147",
          "sha256": "173de1267f66037fabccfabd96f6848bbb1eef826cf0144a7c0308c112d8efcf",
          "sha1": "bc172c6bcfb39465d3ec69906e0234cca58aeaa6",
          "md5": "5e79419961c150bf0627bcf94aa44376"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.2-javadoc.jar",
          "url": "vectorx-test-24.1.2-javadoc.jar",
          "size": 125838,
          "sha512": "38f46905a6e17ffcf1b288f72164572365e9051c93ece29c6a23cef0e6cfd48845bd4d3f6a346021389ba3b1b713e57543d435e7fd9acac47e3beb608c6d2a54",
          "sha256": "58afc04b8ef92aa9c23ef96ba5f2b01cf98a281e2138a89aa7629392b1fb4fed",
          "sha1": "cad59275252fe47f080b7c1a57f0227ab5af62d5",
          "md5": "fb7496dba37a7aeaa90c58a7f0c10a64"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-test-24.1.2-sources.jar",
          "url": "vectorx-test-24.1.2-sources.jar",
          "size": 11947,
          "sha512": "6c673d4329348829f7c8d317619295449fd701b20149e58124edfd06152209494941f4b846f20d3f0d030d1c0c711e8dc0fbea2846911434ce3597d700bebfaf",
          "sha256": "389211ff755812385928c6ce93134476a3c648b8bb7b92466effdaacd34da4af",
          "sha1": "af67bd0b7360b595b25fe6748a73387b6c5c0f49",
          "md5": "243bcbe91421d5a11e787e0b582ba208"
        }
      ]
    }
  ]
}
