{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-batch-manager",
    "version": "24.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.5.jar",
          "url": "vectorx-batch-manager-24.1.5.jar",
          "size": 45153,
          "sha512": "28aa20f9a454502853a434fa0e8b698da975f085c99141c2f0ef09c108b044aec4872fd3c4b0286425fe39ef995c51d667786865ae74de38076ae0663777e5a5",
          "sha256": "f3a194458ce9f32306b268a1a751183e455dbc5d02c7aa943751ae1dbf4e80e2",
          "sha1": "21832f621cb8c6026b274bc91cc343343e4c2f63",
          "md5": "c44d5a771d3fe3d33c334cf8ed3b1dd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-core",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-data-mybatis",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-servlet-rest",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-batch",
          "version": {
            "requires": "24.1.5"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.4"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        },
        {
          "group": "com.cronutils",
          "module": "cron-utils",
          "version": {
            "requires": "9.2.0"
          },
          "excludes": [
            {
              "group": "ognl",
              "module": "ognl"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.5.jar",
          "url": "vectorx-batch-manager-24.1.5.jar",
          "size": 45153,
          "sha512": "28aa20f9a454502853a434fa0e8b698da975f085c99141c2f0ef09c108b044aec4872fd3c4b0286425fe39ef995c51d667786865ae74de38076ae0663777e5a5",
          "sha256": "f3a194458ce9f32306b268a1a751183e455dbc5d02c7aa943751ae1dbf4e80e2",
          "sha1": "21832f621cb8c6026b274bc91cc343343e4c2f63",
          "md5": "c44d5a771d3fe3d33c334cf8ed3b1dd5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.5-javadoc.jar",
          "url": "vectorx-batch-manager-24.1.5-javadoc.jar",
          "size": 139221,
          "sha512": "31987bed034a53f3f67214373021193eb48c9bc9932fd868a787fc51a5d9e8470e47f9ad5b20a9c608695c1c487bf6d8a273b25393910f9f16264eb2238f3af4",
          "sha256": "bed1c37bbe30e80af33a956e453baaf594c781aaedb91f15ab27b0fea8c0acea",
          "sha1": "cdbeee6964e355db4bb2e651727c0c02ade3763b",
          "md5": "5cf94125e52657d3c1b8deea857bcfd0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-batch-manager-24.1.5-sources.jar",
          "url": "vectorx-batch-manager-24.1.5-sources.jar",
          "size": 20387,
          "sha512": "125095a2a25e0ee22a8db4b9a3e874348aee625e0b7bf9af91a01a58fea2a4e0ad45461b7badc782e3d7e8146ac1bee91231907c8a9ccaf0e7f0c8b9984b363c",
          "sha256": "982e3989f58f7f16467044def49f30de7863e8d69362718a1afc50a375398ed7",
          "sha1": "c4028aeadf994f4c188a55fbf23e8663b4581998",
          "md5": "4d43833dffb14ebf17f87b9aaa9e5797"
        }
      ]
    }
  ]
}
