{
  "formatVersion": "1.1",
  "component": {
    "group": "me.vectorx.spring",
    "module": "vectorx-cloud-core",
    "version": "24.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.1"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.1.jar",
          "url": "vectorx-cloud-core-24.1.1.jar",
          "size": 2694,
          "sha512": "53545175f01811b92e1775124f8fe447eee50ac0cce2556067ad1f685462cd13a2fa5edceb9632dd5f2080f61a3de80dd7c08f5d92cf1eeeaa68030460d9119d",
          "sha256": "6c4fe0cc57729c6e796b9b5ff8878f61e69353ee3750633df6b711bf48340123",
          "sha1": "7ef0b6984d05989463ed86513f3ea573ec3ed6dd",
          "md5": "560a72505dd13e5bcf1c9e17db8ebbab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "me.vectorx.spring",
          "module": "vectorx-web-core",
          "version": {
            "requires": "24.1.1"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter"
        }
      ],
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.1.jar",
          "url": "vectorx-cloud-core-24.1.1.jar",
          "size": 2694,
          "sha512": "53545175f01811b92e1775124f8fe447eee50ac0cce2556067ad1f685462cd13a2fa5edceb9632dd5f2080f61a3de80dd7c08f5d92cf1eeeaa68030460d9119d",
          "sha256": "6c4fe0cc57729c6e796b9b5ff8878f61e69353ee3750633df6b711bf48340123",
          "sha1": "7ef0b6984d05989463ed86513f3ea573ec3ed6dd",
          "md5": "560a72505dd13e5bcf1c9e17db8ebbab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.1-javadoc.jar",
          "url": "vectorx-cloud-core-24.1.1-javadoc.jar",
          "size": 70381,
          "sha512": "ad44dc206f4206d59cd575f0cb959358ac010d85d9c3b2e686601cf27853c5b9ba37683cefaa4cbf61e4d35cd2fceba249e235dd366d36ecf2ea1ecfe81cd947",
          "sha256": "a510a64cb17ae4fa2cd910b5330d3427efe65052ade85f6ed04502c62373024b",
          "sha1": "6bbe9c9d35d550c7ddbe341e5f7e668cc49af6d9",
          "md5": "eae5b09e02c5519243254a6797d3a0d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectorx-cloud-core-24.1.1-sources.jar",
          "url": "vectorx-cloud-core-24.1.1-sources.jar",
          "size": 1186,
          "sha512": "2165290b2a1739c3703c650d97028cd22e227a76b6593cb67b01ba02611d64a1f9d993517aab8560a89a2115c8ba9acf8d0a391880c1e78433ee1858c09efac9",
          "sha256": "f50600efb642174bab8c760fef303b948a5fb4435b63c8671288635f71b37f1b",
          "sha1": "9814508078cc16c08a1908a40de59699a2d8856c",
          "md5": "bae0dbe70ac11d7be2e51c601371ca9f"
        }
      ]
    }
  ]
}
